// OPA.c
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:43:09 2026

#include "OPA.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void OPA$InstrDesc$init$(OPA$InstrDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$InstrDesc$class$;
    }
}

struct OPA$InstrDesc$Class$ OPA$InstrDesc$class$ = { 
    0,
};

void OPA$Operand$init$(OPA$Operand* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$Operand$class$;
    }
}

struct OPA$Operand$Class$ OPA$Operand$class$ = { 
    0,
};

void OPA$ObjDesc$init$(OPA$ObjDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$ObjDesc$class$;
    }
}

struct OPA$ObjDesc$Class$ OPA$ObjDesc$class$ = { 
    0,
};

void OPA$FixPntDesc$init$(OPA$FixPntDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$FixPntDesc$class$;
    }
}

struct OPA$FixPntDesc$Class$ OPA$FixPntDesc$class$ = { 
    0,
};

OPA$Object OPA$root = NULL;

void OPA$_$0$init$(OPA$_$0* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        OPA$InstrDesc$init$(obj, 256);
    }
}

OPA$_$0 OPA$InstrTab = {0};

OPA$_$1 OPA$InstrHash = {0};

int16_t OPA$nofInstr = 0;

OPA$_$2 OPA$SizeTab = {0};

uint8_t OPA$export = 0;

uint8_t OPA$inline_ = 0;

uint8_t OPA$FirstTime = 0;

int32_t OPA$Target = 0;

int32_t OPA$pc = 0;

int32_t OPA$sym = 0;

OPA$Name OPA$ident = {0};

int32_t OPA$val = 0;

OPA$_$3 OPA$str = {0};

int32_t OPA$errpos = 0;

OPT$Node OPA$first = NULL;

OPT$Node OPA$last = NULL;

OPT$Node OPA$fixlist = NULL;

int8_t OPA$condCode = 0;

int32_t OPA$AND(int32_t a, int32_t b) {
    return (a & b);
}

int32_t OPA$ORL(int32_t a, int32_t b) {
    return (a | b);
}

void OPA$insert(MIC$AP name, OPA$Object* obj) {
    OPA$Object ob0 = NULL;
    OPA$Object ob1 = NULL;
    int32_t d = 0;
    ob0 = OPA$root;
    ob1 = (*ob0).right;
    d = 1;
    while(1) {
        if( (ob1 == NULL) ) { 
            ob1 = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); ob1->class$ = &OPA$ObjDesc$class$;
            strcpy((char*)(*ob1).name.$, (const char*)name.$);
            (*ob1).typ = 1;
            (*ob1).left = NULL;
            (*ob1).right = NULL;
            (*ob1).fix = NULL;
            (*ob1).obj = NULL;
            (*ob1).next = (*OPA$root).next;
            (*OPA$root).next = ob1;
            (*ob1).val = OPM$errpos;
            if( (d < 0) ) { 
                (*ob0).left = ob1;
            } else { 
                (*ob0).right = ob1;
            }
            goto __227;
        } else if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) < 0) ) { 
            d = (-1);
            ob0 = ob1;
            ob1 = (*ob1).left;
        } else if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) > 0) ) { 
            d = 1;
            ob0 = ob1;
            ob1 = (*ob1).right;
        } else { 
            goto __227;
        }
    }    __227:

    (*obj) = ob1;
}

OPA$Object OPA$ConvertObj(OPT$Object ob) {
    OPA$Object obj = NULL;
    if( (ob != NULL) ) { 
        obj = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); obj->class$ = &OPA$ObjDesc$class$;
        switch( (*ob).mode ) { 
        case 1:
            (*obj).val = 1;
            (*obj).size = ((int8_t*)OPA$SizeTab.$)[(*(*ob).typ).form];
            if( ((*ob).mnolev <= 0) ) { 
                (*obj).typ = 7;
            } else { 
                (*obj).typ = 5;
            }
            break;
        case 2:
            (*obj).typ = 6;
            (*obj).val = 1;
            (*obj).size = 4;
            break;
        case 3:
            (*obj).typ = 3;
            (*obj).val = (*(*ob).conval).intval;
            if( (((*(*ob).typ).form > 6) || ((*(*ob).typ).form == 2)) ) { 
                OPM$err(51);
            }
            break;
        case 5:
            (*obj).typ = 4;
            (*obj).size = ((int8_t*)OPA$SizeTab.$)[(*(*ob).typ).form];
            OPM$err(514);
            break;
        case 11:
            (*obj).typ = 11;
            break;
        default:
            (*obj).typ = 3;
            (*obj).val = 0;
            OPM$err(514);
            break;
        }
        (*obj).obj = ob;
    }
    return obj;
}

void OPA$find(MIC$AP name, OPA$Object* obj) {
    OPA$Object ob0 = NULL;
    OPT$Object ob = NULL;
    ob0 = (*OPA$root).right;
    while( ((ob0 != NULL) && (strcmp((const char*)(*ob0).name.$, (const char*)name.$) != 0)) ) {
        if( (strcmp((const char*)name.$, (const char*)(*ob0).name.$) < 0) ) { 
            ob0 = (*ob0).left;
        } else { 
            ob0 = (*ob0).right;
        }
    }
    (*obj) = ob0;
    if( ((*obj) == NULL) ) { 
        strcpy((char*)OPS$name.$, (const char*)name.$);
        OPT$Find(&ob);
        if( (ob != NULL) ) { 
            (*obj) = OPA$ConvertObj(ob);
        } else { 
            OPA$insert(name, &(*obj));
        }
    }
}

int32_t OPA$HashInstr(MIC$AP name) {
    int32_t i = 0;
    int32_t k = 0;
    i = 0;
    k = 0;
    while( (((uint8_t*)name.$)[i] != 0) ) {
        k = OBERON$MOD(((k * 31) + (int32_t)(uint8_t)(((uint8_t*)name.$)[i])), 512);
        i++;
    }
    return k;
}

void OPA$AddInstr(MIC$AP name, int8_t cat, int32_t op, int32_t flags) {
    int32_t h = 0;
    int32_t n = 0;
    if(!(OPA$nofInstr < 256)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    strcpy((char*)((OPA$InstrDesc*)OPA$InstrTab.$)[OPA$nofInstr].name.$, (const char*)name.$);
    ((OPA$InstrDesc*)OPA$InstrTab.$)[OPA$nofInstr].cat = cat;
    ((OPA$InstrDesc*)OPA$InstrTab.$)[OPA$nofInstr].op = op;
    ((OPA$InstrDesc*)OPA$InstrTab.$)[OPA$nofInstr].flags = flags;
    h = OPA$HashInstr(name);
    while( (((int16_t*)OPA$InstrHash.$)[h] >= 0) ) {
        h = OBERON$MOD((h + 1), 512);
    }
    ((int16_t*)OPA$InstrHash.$)[h] = OPA$nofInstr;
    OPA$nofInstr++;
}

void OPA$FindInstruction(MIC$AP name, int32_t* inx) {
    int32_t h = 0;
    int32_t n = 0;
    h = OPA$HashInstr(name);
    n = 0;
    while( ((n < 512) && (((int16_t*)OPA$InstrHash.$)[h] >= 0)) ) {
        if( (strcmp((const char*)((OPA$InstrDesc*)OPA$InstrTab.$)[((int16_t*)OPA$InstrHash.$)[h]].name.$, (const char*)name.$) == 0) ) { 
            (*inx) = ((int16_t*)OPA$InstrHash.$)[h];
            return;
        }
        h = OBERON$MOD((h + 1), 512);
        n++;
    }
    (*inx) = (-1);
}

void OPA$BuildInstrTable() {
    OPA$nofInstr = 0;
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){65,78,68,0}) + 1,(const uint8_t[]){65,78,68,0}}, 0, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){69,79,82,0}) + 1,(const uint8_t[]){69,79,82,0}}, 0, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,85,66,0}) + 1,(const uint8_t[]){83,85,66,0}}, 0, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){82,83,66,0}) + 1,(const uint8_t[]){82,83,66,0}}, 0, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){65,68,68,0}) + 1,(const uint8_t[]){65,68,68,0}}, 0, 4, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){65,68,67,0}) + 1,(const uint8_t[]){65,68,67,0}}, 0, 5, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,66,67,0}) + 1,(const uint8_t[]){83,66,67,0}}, 0, 6, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){82,83,67,0}) + 1,(const uint8_t[]){82,83,67,0}}, 0, 7, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){84,83,84,0}) + 1,(const uint8_t[]){84,83,84,0}}, 0, 8, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){84,69,81,0}) + 1,(const uint8_t[]){84,69,81,0}}, 0, 9, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){67,77,80,0}) + 1,(const uint8_t[]){67,77,80,0}}, 0, 10, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){67,77,78,0}) + 1,(const uint8_t[]){67,77,78,0}}, 0, 11, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){79,82,82,0}) + 1,(const uint8_t[]){79,82,82,0}}, 0, 12, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,79,86,0}) + 1,(const uint8_t[]){77,79,86,0}}, 0, 13, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,73,67,0}) + 1,(const uint8_t[]){66,73,67,0}}, 0, 14, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,86,78,0}) + 1,(const uint8_t[]){77,86,78,0}}, 0, 15, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,83,76,0}) + 1,(const uint8_t[]){76,83,76,0}}, 22, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,83,82,0}) + 1,(const uint8_t[]){76,83,82,0}}, 22, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){65,83,82,0}) + 1,(const uint8_t[]){65,83,82,0}}, 22, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){82,79,82,0}) + 1,(const uint8_t[]){82,79,82,0}}, 22, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,85,76,0}) + 1,(const uint8_t[]){77,85,76,0}}, 1, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,76,65,0}) + 1,(const uint8_t[]){77,76,65,0}}, 1, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){85,77,85,76,76,0}) + 1,(const uint8_t[]){85,77,85,76,76,0}}, 1, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){85,77,76,65,76,0}) + 1,(const uint8_t[]){85,77,76,65,76,0}}, 1, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,77,85,76,76,0}) + 1,(const uint8_t[]){83,77,85,76,76,0}}, 1, 4, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,77,76,65,76,0}) + 1,(const uint8_t[]){83,77,76,65,76,0}}, 1, 5, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,68,73,86,0}) + 1,(const uint8_t[]){83,68,73,86,0}}, 2, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){85,68,73,86,0}) + 1,(const uint8_t[]){85,68,73,86,0}}, 2, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,68,82,0}) + 1,(const uint8_t[]){76,68,82,0}}, 3, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,68,82,66,0}) + 1,(const uint8_t[]){76,68,82,66,0}}, 3, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,84,82,0}) + 1,(const uint8_t[]){83,84,82,0}}, 3, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,84,82,66,0}) + 1,(const uint8_t[]){83,84,82,66,0}}, 3, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,68,82,72,0}) + 1,(const uint8_t[]){76,68,82,72,0}}, 4, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,68,82,83,72,0}) + 1,(const uint8_t[]){76,68,82,83,72,0}}, 4, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){76,68,82,83,66,0}) + 1,(const uint8_t[]){76,68,82,83,66,0}}, 4, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,84,82,72,0}) + 1,(const uint8_t[]){83,84,82,72,0}}, 4, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,0}) + 1,(const uint8_t[]){66,0}}, 5, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,76,0}) + 1,(const uint8_t[]){66,76,0}}, 5, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,88,0}) + 1,(const uint8_t[]){66,88,0}}, 6, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,76,88,0}) + 1,(const uint8_t[]){66,76,88,0}}, 6, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){80,85,83,72,0}) + 1,(const uint8_t[]){80,85,83,72,0}}, 11, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){80,79,80,0}) + 1,(const uint8_t[]){80,79,80,0}}, 11, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,79,86,87,0}) + 1,(const uint8_t[]){77,79,86,87,0}}, 12, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,79,86,84,0}) + 1,(const uint8_t[]){77,79,86,84,0}}, 12, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){67,76,90,0}) + 1,(const uint8_t[]){67,76,90,0}}, 13, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){82,66,73,84,0}) + 1,(const uint8_t[]){82,66,73,84,0}}, 13, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){82,69,86,0}) + 1,(const uint8_t[]){82,69,86,0}}, 13, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){78,79,80,0}) + 1,(const uint8_t[]){78,79,80,0}}, 14, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){68,77,66,0}) + 1,(const uint8_t[]){68,77,66,0}}, 14, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){68,83,66,0}) + 1,(const uint8_t[]){68,83,66,0}}, 14, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){73,83,66,0}) + 1,(const uint8_t[]){73,83,66,0}}, 14, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){66,75,80,84,0}) + 1,(const uint8_t[]){66,75,80,84,0}}, 14, 4, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){83,86,67,0}) + 1,(const uint8_t[]){83,86,67,0}}, 14, 5, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){67,80,83,73,69,0}) + 1,(const uint8_t[]){67,80,83,73,69,0}}, 15, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){67,80,83,73,68,0}) + 1,(const uint8_t[]){67,80,83,73,68,0}}, 15, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,67,82,0}) + 1,(const uint8_t[]){77,67,82,0}}, 16, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,82,67,0}) + 1,(const uint8_t[]){77,82,67,0}}, 16, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,83,82,0}) + 1,(const uint8_t[]){77,83,82,0}}, 17, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){77,82,83,0}) + 1,(const uint8_t[]){77,82,83,0}}, 17, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,65,68,68,0}) + 1,(const uint8_t[]){86,65,68,68,0}}, 8, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,83,85,66,0}) + 1,(const uint8_t[]){86,83,85,66,0}}, 8, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,77,85,76,0}) + 1,(const uint8_t[]){86,77,85,76,0}}, 8, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,68,73,86,0}) + 1,(const uint8_t[]){86,68,73,86,0}}, 8, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,65,66,83,0}) + 1,(const uint8_t[]){86,65,66,83,0}}, 7, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,78,69,71,0}) + 1,(const uint8_t[]){86,78,69,71,0}}, 7, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,67,77,80,0}) + 1,(const uint8_t[]){86,67,77,80,0}}, 7, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,83,81,82,84,0}) + 1,(const uint8_t[]){86,83,81,82,84,0}}, 7, 3, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,76,68,82,0}) + 1,(const uint8_t[]){86,76,68,82,0}}, 9, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,83,84,82,0}) + 1,(const uint8_t[]){86,83,84,82,0}}, 9, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,77,79,86,0}) + 1,(const uint8_t[]){86,77,79,86,0}}, 19, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,77,82,83,0}) + 1,(const uint8_t[]){86,77,82,83,0}}, 20, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,77,83,82,0}) + 1,(const uint8_t[]){86,77,83,82,0}}, 20, 1, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){86,67,86,84,0}) + 1,(const uint8_t[]){86,67,86,84,0}}, 21, 0, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){68,67,68,0}) + 1,(const uint8_t[]){68,67,68,0}}, 18, 4, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){68,67,87,0}) + 1,(const uint8_t[]){68,67,87,0}}, 18, 2, (0));
    OPA$AddInstr((MIC$AP){strlen((const uint8_t[]){68,67,66,0}) + 1,(const uint8_t[]){68,67,66,0}}, 18, 1, (0));
}

void OPA$skipBlanks() {
    while( ((OPS$ch == 32) || (OPS$ch == 9)) ) {
        OPM$Get(&OPS$ch);
    }
    if( (OPS$ch == 59) ) { 
        while( ((OPS$ch != 13) && (OPS$ch != 10)) ) {
            OPM$Get(&OPS$ch);
        }
    }
}

void OPA$GetIdent(MIC$AP name) {
    int32_t i = 0;
    i = 0;
    OPM$errpos = (OPM$curpos - 1);
    do {
        if( (i < (32 - 1)) ) { 
            ((uint8_t*)name.$)[i] = OPS$ch;
            i++;
        }
        OPM$Get(&OPS$ch);
    } while( !(!(((((65 <= (uint8_t)toupper((uint8_t)OPS$ch)) && ((uint8_t)toupper((uint8_t)OPS$ch) <= 90)) || ((48 <= OPS$ch) && (OPS$ch <= 57))) || (OPS$ch == 46)) || (OPS$ch == 95))) );
    ((uint8_t*)name.$)[i] = 0;
}

void OPA$Get$Comment() {
    OPM$Get(&OPS$ch);
    while(1) {
        while(1) {
            while( (OPS$ch == 40) ) {
                OPM$Get(&OPS$ch);
                if( (OPS$ch == 42) ) { 
                    OPA$Get$Comment();
                }
            }
            if( (OPS$ch == 42) ) { 
                OPM$Get(&OPS$ch);
                goto __492;
            }
            if( (OPS$ch == 0) ) { 
                goto __492;
            }
            OPM$Get(&OPS$ch);
        }        __492:

        if( (OPS$ch == 41) ) { 
            OPM$Get(&OPS$ch);
            goto __491;
        }
        if( (OPS$ch == 0) ) { 
            OPM$Mark(5, OPM$errpos);
            goto __491;
        }
    }    __491:

}

void OPA$Get$Str() {
    uint8_t och = 0;
    int32_t i = 0;
    och = OPS$ch;
    i = 0;
    while(1) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == och) ) { 
            goto __509;
        } else if( (OPS$ch < 32) ) { 
            OPM$err(3);
            goto __509;
        } else if( (i == (256 - 1)) ) { 
            OPM$err(241);
            goto __509;
        }
        ((uint8_t*)OPA$str.$)[i] = OPS$ch;
        i++;
    }    __509:

    OPM$Get(&OPS$ch);
    ((uint8_t*)OPA$str.$)[i] = 0;
    OPA$val = i;
}

void OPA$Get(int32_t* sym) {
    OPA$skipBlanks();
    OPM$errpos = OPM$curpos;
    if( (OPS$ch >= 65 && OPS$ch <= 90) || (OPS$ch >= 97 && OPS$ch <= 122) ) {
        OPA$GetIdent((MIC$AP){32, OPA$ident.$});
        if( (OPS$ch == 58) ) { 
            OPM$Get(&OPS$ch);
            (*sym) = 11;
        } else if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){69,78,68,0}) == 0) ) { 
            (*sym) = 10;
        } else { 
            (*sym) = 1;
        }
    } else if( (OPS$ch >= 48 && OPS$ch <= 57) ) {
        OPA$val = 0;
        (*sym) = 4;
        OPS$Number();
        if(!(OPS$numtyp <= 2)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
        OPA$val = OPS$intval;
    } else if( (OPS$ch == 59) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 2;
    } else if( (OPS$ch == 64) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 3;
    } else if( (OPS$ch == 44) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 5;
    } else if( (OPS$ch == 91) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 6;
    } else if( (OPS$ch == 93) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 7;
    } else if( (OPS$ch == 123) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 20;
    } else if( (OPS$ch == 125) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 21;
    } else if( (OPS$ch == 13) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 8;
    } else if( (OPS$ch == 10) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 8;
    } else if( (OPS$ch == 42) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 9;
    } else if( (OPS$ch == 47) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 15;
    } else if( (OPS$ch == 43) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 13;
    } else if( (OPS$ch == 45) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 14;
    } else if( (OPS$ch == 40) ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == 42) ) { 
            OPA$Get$Comment();
            OPA$Get(&(*sym));
        } else { 
            (*sym) = 16;
        }
    } else if( (OPS$ch == 41) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 17;
    } else if( (OPS$ch == 58) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 12;
    } else if( (OPS$ch == 46) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 19;
    } else if( (OPS$ch == 35) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 22;
    } else if( (OPS$ch == 33) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 23;
    } else if( (OPS$ch == 34) || (OPS$ch == 39) ) {
        OPA$Get$Str();
        (*sym) = 18;
    } else {
        (*sym) = 0;
        OPM$Get(&OPS$ch);
    }

}

void OPA$Check(int32_t s) {
    if( (OPA$sym != s) ) { 
        OPM$err((int16_t)(s));
    }
    OPA$Get(&OPA$sym);
}

void OPA$Expression$Factor(int32_t* x) {
    if( (OPA$sym == 4) ) { 
        (*x) = OPA$val;
        OPA$Get(&OPA$sym);
    } else if( (OPA$sym == 16) ) { 
        OPA$Get(&OPA$sym);
        OPA$Expression(&(*x));
        OPA$Check(17);
    } else { 
        OPM$err(601);
        (*x) = 0;
    }
}

void OPA$Expression$Term(int32_t* x) {
    int32_t y = 0;
    int32_t op = 0;
    OPA$Expression$Factor(&(*x));
    while( ((OPA$sym == 9) || (OPA$sym == 15)) ) {
        op = OPA$sym;
        OPA$Get(&OPA$sym);
        OPA$Expression$Factor(&y);
        if( (op == 9) ) { 
            (*x) = ((*x) * y);
        } else { 
            (*x) = OBERON$DIV((*x), y);
        }
    }
}

void OPA$Expression(int32_t* x) {
    int32_t y = 0;
    int32_t op = 0;
    if( (OPA$sym == 14) ) { 
        OPA$Get(&OPA$sym);
        OPA$Expression$Term(&(*x));
        (*x) = (-(*x));
    } else { 
        OPA$Expression$Term(&(*x));
    }
    while( ((OPA$sym == 13) || (OPA$sym == 14)) ) {
        op = OPA$sym;
        OPA$Get(&OPA$sym);
        OPA$Expression$Term(&y);
        if( (op == 13) ) { 
            (*x) = ((*x) + y);
        } else { 
            (*x) = ((*x) - y);
        }
    }
}

void OPA$ParseCondition(MIC$AP name, int8_t* cond, int32_t* nameLen) {
    int32_t len = 0;
    len = 0;
    while( (((uint8_t*)name.$)[len] != 0) ) {
        len++;
    }
    (*cond) = 14;
    (*nameLen) = len;
    if( (len >= 3) ) { 
        if( ((((uint8_t*)name.$)[(len - 2)] == 69) && (((uint8_t*)name.$)[(len - 1)] == 81)) ) { 
            (*cond) = 0;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 78) && (((uint8_t*)name.$)[(len - 1)] == 69)) ) { 
            (*cond) = 1;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 67) && (((uint8_t*)name.$)[(len - 1)] == 83)) ) { 
            (*cond) = 2;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 72) && (((uint8_t*)name.$)[(len - 1)] == 83)) ) { 
            (*cond) = 2;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 67) && (((uint8_t*)name.$)[(len - 1)] == 67)) ) { 
            (*cond) = 3;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 76) && (((uint8_t*)name.$)[(len - 1)] == 79)) ) { 
            (*cond) = 3;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 77) && (((uint8_t*)name.$)[(len - 1)] == 73)) ) { 
            (*cond) = 4;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 80) && (((uint8_t*)name.$)[(len - 1)] == 76)) ) { 
            (*cond) = 5;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 86) && (((uint8_t*)name.$)[(len - 1)] == 83)) ) { 
            (*cond) = 6;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 86) && (((uint8_t*)name.$)[(len - 1)] == 67)) ) { 
            (*cond) = 7;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 72) && (((uint8_t*)name.$)[(len - 1)] == 73)) ) { 
            (*cond) = 8;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 76) && (((uint8_t*)name.$)[(len - 1)] == 83)) ) { 
            (*cond) = 9;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 71) && (((uint8_t*)name.$)[(len - 1)] == 69)) ) { 
            (*cond) = 10;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 76) && (((uint8_t*)name.$)[(len - 1)] == 84)) ) { 
            (*cond) = 11;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 71) && (((uint8_t*)name.$)[(len - 1)] == 84)) ) { 
            (*cond) = 12;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 76) && (((uint8_t*)name.$)[(len - 1)] == 69)) ) { 
            (*cond) = 13;
            (*nameLen) = (len - 2);
        } else if( ((((uint8_t*)name.$)[(len - 2)] == 65) && (((uint8_t*)name.$)[(len - 1)] == 76)) ) { 
            (*cond) = 14;
            (*nameLen) = (len - 2);
        }
    }
}

uint8_t OPA$ParseRegister(MIC$AP name, int16_t* reg, int32_t* mode) {
    (*mode) = 8;
    if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,48,0}) == 0) ) { 
        (*reg) = 0;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,0}) == 0) ) { 
        (*reg) = 1;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,50,0}) == 0) ) { 
        (*reg) = 2;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,51,0}) == 0) ) { 
        (*reg) = 3;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,52,0}) == 0) ) { 
        (*reg) = 4;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,53,0}) == 0) ) { 
        (*reg) = 5;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,54,0}) == 0) ) { 
        (*reg) = 6;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,55,0}) == 0) ) { 
        (*reg) = 7;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,56,0}) == 0) ) { 
        (*reg) = 8;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,57,0}) == 0) ) { 
        (*reg) = 9;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,48,0}) == 0) ) { 
        (*reg) = 10;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,49,0}) == 0) ) { 
        (*reg) = 11;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,50,0}) == 0) ) { 
        (*reg) = 12;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,51,0}) == 0) ) { 
        (*reg) = 13;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,52,0}) == 0) ) { 
        (*reg) = 14;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){82,49,53,0}) == 0) ) { 
        (*reg) = 15;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){70,80,0}) == 0) ) { 
        (*reg) = 11;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){73,80,0}) == 0) ) { 
        (*reg) = 12;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,80,0}) == 0) ) { 
        (*reg) = 13;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){76,82,0}) == 0) ) { 
        (*reg) = 14;
        return 1;
    } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){80,67,0}) == 0) ) { 
        (*reg) = 15;
        return 1;
    } else if( (((uint8_t*)name.$)[0] == 83) ) { 
        (*mode) = 16;
        if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,48,0}) == 0) ) { 
            (*reg) = 0;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,0}) == 0) ) { 
            (*reg) = 1;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,0}) == 0) ) { 
            (*reg) = 2;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,51,0}) == 0) ) { 
            (*reg) = 3;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,52,0}) == 0) ) { 
            (*reg) = 4;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,53,0}) == 0) ) { 
            (*reg) = 5;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,54,0}) == 0) ) { 
            (*reg) = 6;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,55,0}) == 0) ) { 
            (*reg) = 7;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,56,0}) == 0) ) { 
            (*reg) = 8;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,57,0}) == 0) ) { 
            (*reg) = 9;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,48,0}) == 0) ) { 
            (*reg) = 10;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,49,0}) == 0) ) { 
            (*reg) = 11;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,50,0}) == 0) ) { 
            (*reg) = 12;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,51,0}) == 0) ) { 
            (*reg) = 13;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,52,0}) == 0) ) { 
            (*reg) = 14;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,53,0}) == 0) ) { 
            (*reg) = 15;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,54,0}) == 0) ) { 
            (*reg) = 16;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,55,0}) == 0) ) { 
            (*reg) = 17;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,56,0}) == 0) ) { 
            (*reg) = 18;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,49,57,0}) == 0) ) { 
            (*reg) = 19;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,48,0}) == 0) ) { 
            (*reg) = 20;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,49,0}) == 0) ) { 
            (*reg) = 21;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,50,0}) == 0) ) { 
            (*reg) = 22;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,51,0}) == 0) ) { 
            (*reg) = 23;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,52,0}) == 0) ) { 
            (*reg) = 24;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,53,0}) == 0) ) { 
            (*reg) = 25;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,54,0}) == 0) ) { 
            (*reg) = 26;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,55,0}) == 0) ) { 
            (*reg) = 27;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,56,0}) == 0) ) { 
            (*reg) = 28;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,50,57,0}) == 0) ) { 
            (*reg) = 29;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,51,48,0}) == 0) ) { 
            (*reg) = 30;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){83,51,49,0}) == 0) ) { 
            (*reg) = 31;
            return 1;
        } else { 
            (*mode) = 8;
            return 0;
        }
    } else if( (((uint8_t*)name.$)[0] == 68) ) { 
        (*mode) = 24;
        if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,48,0}) == 0) ) { 
            (*reg) = 0;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,0}) == 0) ) { 
            (*reg) = 1;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,0}) == 0) ) { 
            (*reg) = 2;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,51,0}) == 0) ) { 
            (*reg) = 3;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,52,0}) == 0) ) { 
            (*reg) = 4;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,53,0}) == 0) ) { 
            (*reg) = 5;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,54,0}) == 0) ) { 
            (*reg) = 6;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,55,0}) == 0) ) { 
            (*reg) = 7;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,56,0}) == 0) ) { 
            (*reg) = 8;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,57,0}) == 0) ) { 
            (*reg) = 9;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,48,0}) == 0) ) { 
            (*reg) = 10;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,49,0}) == 0) ) { 
            (*reg) = 11;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,50,0}) == 0) ) { 
            (*reg) = 12;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,51,0}) == 0) ) { 
            (*reg) = 13;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,52,0}) == 0) ) { 
            (*reg) = 14;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,53,0}) == 0) ) { 
            (*reg) = 15;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,54,0}) == 0) ) { 
            (*reg) = 16;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,55,0}) == 0) ) { 
            (*reg) = 17;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,56,0}) == 0) ) { 
            (*reg) = 18;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,49,57,0}) == 0) ) { 
            (*reg) = 19;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,48,0}) == 0) ) { 
            (*reg) = 20;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,49,0}) == 0) ) { 
            (*reg) = 21;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,50,0}) == 0) ) { 
            (*reg) = 22;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,51,0}) == 0) ) { 
            (*reg) = 23;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,52,0}) == 0) ) { 
            (*reg) = 24;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,53,0}) == 0) ) { 
            (*reg) = 25;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,54,0}) == 0) ) { 
            (*reg) = 26;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,55,0}) == 0) ) { 
            (*reg) = 27;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,56,0}) == 0) ) { 
            (*reg) = 28;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,50,57,0}) == 0) ) { 
            (*reg) = 29;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,51,48,0}) == 0) ) { 
            (*reg) = 30;
            return 1;
        } else if( (strcmp((const char*)name.$, (const char*)(const uint8_t[]){68,51,49,0}) == 0) ) { 
            (*reg) = 31;
            return 1;
        } else { 
            (*mode) = 8;
            return 0;
        }
    } else { 
        return 0;
    }
}

void OPA$ParseRegList(int32_t* regList) {
    int16_t reg = 0;
    int16_t reg2 = 0;
    int32_t mode = 0;
    OPA$Name name = {0};
    (*regList) = (0);
    do {
        if( (OPA$sym == 1) ) { 
            strcpy((char*)name.$, (const char*)OPA$ident.$);
            if( (OPA$ParseRegister((MIC$AP){32, name.$}, &reg, &mode) && (mode == 8)) ) { 
                OPA$Get(&OPA$sym);
                if( (OPA$sym == 14) ) { 
                    OPA$Get(&OPA$sym);
                    if( (OPA$sym == 1) ) { 
                        strcpy((char*)name.$, (const char*)OPA$ident.$);
                        if( (OPA$ParseRegister((MIC$AP){32, name.$}, &reg2, &mode) && (mode == 8)) ) { 
                            OPA$Get(&OPA$sym);
                            while( (reg <= reg2) ) {
                                (*regList) |= (1u << reg);
                                reg++;
                            }
                        } else { 
                            OPM$err(506);
                        }
                    } else { 
                        OPM$err(506);
                    }
                } else { 
                    (*regList) |= (1u << reg);
                }
            } else { 
                OPM$err(506);
            }
        } else { 
            OPM$err(506);
        }
        if( (OPA$sym == 5) ) { 
            OPA$Get(&OPA$sym);
        }
    } while( !(OPA$sym == 21) );
    OPA$Get(&OPA$sym);
}

void OPA$GetOperand(OPA$Operand* o) {
    OPA$Object obj = NULL;
    OPA$Name name = {0};
    int16_t reg = 0;
    int32_t mode = 0;
    (*o).mode = (-1);
    (*o).reg = (-1);
    (*o).imm = 0;
    (*o).disp = 0;
    (*o).base = (-1);
    (*o).index = (-1);
    (*o).shift = (-1);
    (*o).shiftAmt = 0;
    (*o).regList = (0);
    (*o).obj = NULL;
    (*o).writeback = 0;
    (*o).preIndex = 0;
    (*o).dbl = 0;
    if( (OPA$sym == 22) ) { 
        OPA$Get(&OPA$sym);
        OPA$Expression(&(*o).imm);
        (*o).mode = 32;
    } else if( (OPA$sym == 6) ) { 
        OPA$Get(&OPA$sym);
        (*o).mode = 40;
        (*o).preIndex = 1;
        if( (OPA$sym == 1) ) { 
            strcpy((char*)name.$, (const char*)OPA$ident.$);
            if( (OPA$ParseRegister((MIC$AP){32, name.$}, &reg, &mode) && (mode == 8)) ) { 
                (*o).base = reg;
                OPA$Get(&OPA$sym);
                if( (OPA$sym == 5) ) { 
                    OPA$Get(&OPA$sym);
                    if( (OPA$sym == 22) ) { 
                        OPA$Get(&OPA$sym);
                        OPA$Expression(&(*o).disp);
                    } else if( (OPA$sym == 1) ) { 
                        strcpy((char*)name.$, (const char*)OPA$ident.$);
                        if( (OPA$ParseRegister((MIC$AP){32, name.$}, &reg, &mode) && (mode == 8)) ) { 
                            (*o).index = reg;
                            OPA$Get(&OPA$sym);
                            if( (OPA$sym == 5) ) { 
                                OPA$Get(&OPA$sym);
                                if( (OPA$sym == 1) ) { 
                                    if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){76,83,76,0}) == 0) ) { 
                                        (*o).shift = 0;
                                    } else if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){76,83,82,0}) == 0) ) { 
                                        (*o).shift = 1;
                                    } else if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){65,83,82,0}) == 0) ) { 
                                        (*o).shift = 2;
                                    } else if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){82,79,82,0}) == 0) ) { 
                                        (*o).shift = 3;
                                    } else { 
                                        OPM$err(506);
                                    }
                                    OPA$Get(&OPA$sym);
                                    if( (OPA$sym == 22) ) { 
                                        OPA$Get(&OPA$sym);
                                        OPA$Expression(&(*o).imm);
                                        (*o).shiftAmt = (int16_t)((*o).imm);
                                    } else { 
                                        OPM$err(506);
                                    }
                                }
                            }
                        } else { 
                            OPM$err(506);
                        }
                    } else if( (OPA$sym == 14) ) { 
                        OPA$Get(&OPA$sym);
                        if( (OPA$sym == 22) ) { 
                            OPA$Get(&OPA$sym);
                            OPA$Expression(&(*o).disp);
                            (*o).disp = (-(*o).disp);
                        } else if( (OPA$sym == 1) ) { 
                            strcpy((char*)name.$, (const char*)OPA$ident.$);
                            if( (OPA$ParseRegister((MIC$AP){32, name.$}, &reg, &mode) && (mode == 8)) ) { 
                                (*o).index = reg;
                                (*o).shift = (-1);
                                OPA$Get(&OPA$sym);
                            } else { 
                                OPM$err(506);
                            }
                        } else { 
                            OPM$err(506);
                        }
                    }
                }
                if( (OPA$sym == 7) ) { 
                    OPA$Get(&OPA$sym);
                } else { 
                    OPM$err(507);
                }
                if( (OPA$sym == 23) ) { 
                    (*o).writeback = 1;
                    OPA$Get(&OPA$sym);
                }
            } else { 
                OPM$err(506);
            }
        } else { 
            OPM$err(506);
        }
    } else if( (OPA$sym == 20) ) { 
        OPA$Get(&OPA$sym);
        OPA$ParseRegList(&(*o).regList);
        (*o).mode = 64;
    } else if( (OPA$sym == 1) ) { 
        strcpy((char*)name.$, (const char*)OPA$ident.$);
        if( OPA$ParseRegister((MIC$AP){32, name.$}, &reg, &mode) ) { 
            (*o).mode = mode;
            (*o).reg = reg;
            OPA$Get(&OPA$sym);
        } else { 
            OPA$find((MIC$AP){32, name.$}, &obj);
            if( ((obj != NULL) && ((*obj).typ == 0)) ) { 
                (*o).mode = 48;
                (*o).imm = (*obj).val;
                OPA$Get(&OPA$sym);
            } else if( ((obj != NULL) && ((*obj).typ == 1)) ) { 
                (*o).mode = 49;
                (*o).obj = obj;
                OPA$Get(&OPA$sym);
            } else if( ((obj != NULL) && ((*obj).typ == 3)) ) { 
                (*o).mode = 32;
                (*o).imm = (*obj).val;
                OPA$Get(&OPA$sym);
            } else { 
                (*o).mode = 32;
                (*o).imm = 0;
                OPM$err(500);
            }
        }
    } else if( (OPA$sym == 4) ) { 
        (*o).mode = 32;
        OPA$Expression(&(*o).imm);
    } else if( (OPA$sym == 14) ) { 
        (*o).mode = 32;
        OPA$Expression(&(*o).imm);
    } else { 
        (*o).mode = (-1);
    }
}

void OPA$CheckLabels() {
    OPA$Object obj = NULL;
    OPA$Object obj1 = NULL;
    OPA$Object obj2 = NULL;
    obj1 = (*OPA$root).next;
    obj = NULL;
    while( (obj1 != NULL) ) {
        obj2 = (*obj1).next;
        (*obj1).next = obj;
        obj = obj1;
        obj1 = obj2;
    }
    while( (obj != NULL) ) {
        if( ((*obj).typ == 1) ) { 
            OPM$Mark(128, (*obj).val);
        }
        obj = (*obj).next;
    }
}

void OPA$InsertFix(OPA$Object* obj, int32_t pc) {
    OPA$FixPnt fix = NULL;
    OPT$Node x = NULL;
    switch( (*(*obj)).typ ) { 
    case 1:
        fix = (OPA$FixPntDesc*)GC_MALLOC(sizeof(OPA$FixPntDesc)); fix->class$ = &OPA$FixPntDesc$class$;
        (*fix).pc = pc;
        (*fix).node = OPA$last;
        (*fix).pos = ((int32_t)(uint8_t)((*(*OPA$last).conval).ext[0]) - 3);
        (*fix).next = (*(*obj)).fix;
        (*(*obj)).fix = fix;
        break;
    case 5:
    case 6:
    case 7:
        if( (OPA$export && OPA$inline_) ) { 
            OPM$err(517);
        }
        x = OPT$NewNode(31);
        (*x).obj = (*(*obj)).obj;
        (*x).conval = OPT$NewConst();
        (*(*x).conval).intval = pc;
        (*(*x).conval).intval2 = OPM$errpos;
        (*x).link = OPA$fixlist;
        OPA$fixlist = x;
        break;
    default:
        OPM$err(607);
        break;
    }
}

void OPA$FixDisp(OPA$FixPnt* fix) {
    int32_t pos = 0;
    int32_t disp = 0;
    int32_t i = 0;
    disp = (OPA$pc - (*(*fix)).pc);
    int _temp0 = 3; i = 0; 
    while( i <= _temp0 ) {
        (*(*(*(*fix)).node).conval).ext[((*(*fix)).pos + i)] = (uint8_t)(OBERON$MOD(disp, 256));
        disp = OBERON$DIV(disp, 256);
        i++;
    }
}

void OPA$NewNode() {
    OPT$Node x = NULL;
    x = OPT$NewNode(30);
    (*x).conval = OPT$NewConst();
    (*(*x).conval).ext = OPT$NewExt();
    (*(*x).conval).ext[0] = 0;
    (*(*x).conval).intval = OPM$errpos;
    OPB$Link(&OPA$first, &OPA$last, x);
}

void OPA$PutByte(int32_t b) {
    int32_t pos = 0;
    pos = ((int32_t)(uint8_t)((*(*OPA$last).conval).ext[0]) + 1);
    if( (pos > 255) ) { 
        OPA$NewNode();
        pos = 1;
    }
    (*(*OPA$last).conval).ext[pos] = (uint8_t)(b);
    (*(*OPA$last).conval).ext[0] = (uint8_t)(pos);
    OPA$pc++;
}

void OPA$PutWord(int32_t w) {
    OPA$PutByte(OPA$AND(w, 255));
    OPA$PutByte(OPA$AND(OBERON$DIV(w, 256), 255));
    OPA$PutByte(OPA$AND(OBERON$DIV(w, 65536), 255));
    OPA$PutByte(OPA$AND(OBERON$DIV(w, 16777216), 255));
}

uint8_t OPA$CanEncodeImm(int32_t imm, int32_t* encoding) {
    int32_t rot = 0;
    int32_t val = 0;
    if( ((imm >= 0) && (imm < 256)) ) { 
        (*encoding) = imm;
        return 1;
    }
    rot = 0;
    while( (rot < 16) ) {
        val = OPA$ORL(OPA$AND(imm, ((int32_t)4294967295U)), 0);
        if( (rot > 0) ) { 
            val = OPA$ORL(OPA$AND(ASH$(imm, (rot * 2)), ((int32_t)4294967295U)), OPA$AND(ASH$(imm, (-(32 - (rot * 2)))), ((int32_t)4294967295U)));
        }
        if( ((val >= 0) && (val < 256)) ) { 
            (*encoding) = ((rot * 256) + val);
            return 1;
        }
        rot++;
    }
    return 0;
}

void OPA$GenDataProc(int8_t cond, int32_t op, uint8_t S, int16_t Rd, int16_t Rn, OPA$Operand* op2) {
    int32_t w = 0;
    int32_t encoding = 0;
    int32_t sbit = 0;
    if( S ) { 
        sbit = 1048576;
    } else { 
        sbit = 0;
    }
    if( ((*op2).mode == 32) ) { 
        if( OPA$CanEncodeImm((*op2).imm, &encoding) ) { 
            w = (((((((cond * 268435456) + 33554432) + (op * 2097152)) + sbit) + (Rn * 65536)) + (Rd * 4096)) + encoding);
            OPA$PutWord(w);
        } else { 
            OPM$err(501);
        }
    } else if( ((*op2).mode == 8) ) { 
        w = (((((cond * 268435456) + (op * 2097152)) + sbit) + (Rn * 65536)) + (Rd * 4096));
        if( ((*op2).shift >= 0) ) { 
            w = (((w + ((*op2).shiftAmt * 128)) + ((*op2).shift * 32)) + (*op2).reg);
        } else { 
            w = (w + (*op2).reg);
        }
        OPA$PutWord(w);
    } else { 
        OPM$err(501);
    }
}

void OPA$GenShiftInstr(int8_t cond, int32_t shiftType, int16_t Rd, int16_t Rm, OPA$Operand* op2) {
    int32_t w = 0;
    if( ((*op2).mode == 32) ) { 
        w = ((((((cond * 268435456) + (13 * 2097152)) + (Rd * 4096)) + ((*op2).imm * 128)) + (shiftType * 32)) + Rm);
        OPA$PutWord(w);
    } else if( ((*op2).mode == 8) ) { 
        w = (((((((cond * 268435456) + (13 * 2097152)) + (Rd * 4096)) + ((*op2).reg * 256)) + (shiftType * 32)) + 16) + Rm);
        OPA$PutWord(w);
    } else { 
        OPM$err(501);
    }
}

void OPA$GenMultiply(int8_t cond, int32_t op, int16_t Rd, int16_t Rm, int16_t Rs, int16_t Rn) {
    int32_t w = 0;
    switch( op ) { 
    case 0:
        w = (((((cond * 268435456) + (Rd * 65536)) + (Rs * 256)) + 144) + Rm);
        break;
    case 1:
        w = (((((((cond * 268435456) + 2097152) + (Rd * 65536)) + (Rn * 4096)) + (Rs * 256)) + 144) + Rm);
        break;
    case 2:
        w = (((((((cond * 268435456) + 8388608) + (Rd * 65536)) + (Rn * 4096)) + (Rs * 256)) + 144) + Rm);
        break;
    case 3:
        w = (((((((cond * 268435456) + 10485760) + (Rd * 65536)) + (Rn * 4096)) + (Rs * 256)) + 144) + Rm);
        break;
    case 4:
        w = (((((((cond * 268435456) + 12582912) + (Rd * 65536)) + (Rn * 4096)) + (Rs * 256)) + 144) + Rm);
        break;
    case 5:
        w = (((((((cond * 268435456) + 14680064) + (Rd * 65536)) + (Rn * 4096)) + (Rs * 256)) + 144) + Rm);
        break;
    }
    OPA$PutWord(w);
}

void OPA$GenDivide(int8_t cond, int32_t op, int16_t Rd, int16_t Rn, int16_t Rm) {
    int32_t w = 0;
    if( (op == 0) ) { 
        w = (((((((cond * 268435456) + 7405568) + (Rd * 65536)) + 3840) + (Rm * 16)) + 1) + Rn);
    } else { 
        w = (((((((cond * 268435456) + 7536640) + (Rd * 65536)) + 3840) + (Rm * 16)) + 1) + Rn);
    }
    OPA$PutWord(w);
}

void OPA$GenLdSt(int8_t cond, int32_t op, int16_t Rt, OPA$Operand* mem) {
    int32_t w = 0;
    int32_t U = 0;
    int32_t P = 0;
    int32_t W = 0;
    int32_t L = 0;
    int32_t B = 0;
    L = 0;
    B = 0;
    if( ((op == 0) || (op == 1)) ) { 
        L = 1048576;
    }
    if( ((op == 1) || (op == 3)) ) { 
        B = 4194304;
    }
    P = 16777216;
    U = 8388608;
    W = 0;
    if( (*mem).writeback ) { 
        W = 2097152;
    }
    if( ((*mem).disp < 0) ) { 
        U = 0;
        (*mem).disp = (-(*mem).disp);
    }
    if( ((*mem).index >= 0) ) { 
        w = ((((((((((cond * 268435456) + 100663296) + P) + U) + B) + W) + L) + ((*mem).base * 65536)) + (Rt * 4096)) + (*mem).index);
        if( ((*mem).shift >= 0) ) { 
            w = ((w + ((*mem).shiftAmt * 128)) + ((*mem).shift * 32));
        }
    } else { 
        if( ((*mem).disp > 4095) ) { 
            OPM$err(501);
        }
        w = ((((((((((cond * 268435456) + 67108864) + P) + U) + B) + W) + L) + ((*mem).base * 65536)) + (Rt * 4096)) + OPA$AND((*mem).disp, 4095));
    }
    OPA$PutWord(w);
}

void OPA$GenLdStH(int8_t cond, int32_t op, int16_t Rt, OPA$Operand* mem) {
    int32_t w = 0;
    int32_t U = 0;
    int32_t P = 0;
    int32_t W = 0;
    int32_t L = 0;
    int32_t S = 0;
    int32_t H = 0;
    P = 16777216;
    U = 8388608;
    W = 0;
    if( (*mem).writeback ) { 
        W = 2097152;
    }
    if( ((*mem).disp < 0) ) { 
        U = 0;
        (*mem).disp = (-(*mem).disp);
    }
    switch( op ) { 
    case 0:
        L = 1048576;
        S = 0;
        H = 32;
        break;
    case 1:
        L = 1048576;
        S = 64;
        H = 32;
        break;
    case 2:
        L = 1048576;
        S = 64;
        H = 0;
        break;
    case 3:
        L = 0;
        S = 0;
        H = 32;
        break;
    }
    if( ((*mem).index >= 0) ) { 
        w = (((((((((((cond * 268435456) + P) + U) + W) + L) + ((*mem).base * 65536)) + (Rt * 4096)) + S) + H) + 144) + (*mem).index);
    } else { 
        if( ((*mem).disp > 255) ) { 
            OPM$err(501);
        }
        w = (((((((((((((cond * 268435456) + P) + U) + 4194304) + W) + L) + ((*mem).base * 65536)) + (Rt * 4096)) + (OBERON$DIV((*mem).disp, 16) * 256)) + S) + H) + 144) + OBERON$MOD((*mem).disp, 16));
    }
    OPA$PutWord(w);
}

void OPA$GenBranch(int8_t cond, uint8_t link, OPA$Operand* target) {
    int32_t w = 0;
    int32_t offset = 0;
    if( link ) { 
        w = ((cond * 268435456) + 184549376);
    } else { 
        w = ((cond * 268435456) + 167772160);
    }
    if( ((*target).mode == 48) ) { 
        offset = OBERON$DIV(((*target).imm - (OPA$pc + 8)), 4);
        w = (w + OPA$AND(offset, 16777215));
        OPA$PutWord(w);
    } else if( ((*target).mode == 49) ) { 
        OPA$PutWord(w);
        if( ((*target).obj != NULL) ) { 
            OPA$InsertFix(&(*target).obj, (OPA$pc - 4));
        }
    } else if( ((*target).mode == 32) ) { 
        offset = OBERON$DIV(((*target).imm - (OPA$pc + 8)), 4);
        w = (w + OPA$AND(offset, 16777215));
        OPA$PutWord(w);
    } else { 
        OPM$err(501);
    }
}

void OPA$GenBX(int8_t cond, uint8_t link, int16_t Rm) {
    int32_t w = 0;
    if( link ) { 
        w = (((cond * 268435456) + 19922736) + Rm);
    } else { 
        w = (((cond * 268435456) + 19922704) + Rm);
    }
    OPA$PutWord(w);
}

void OPA$GenPushPop(int8_t cond, uint8_t pop, int32_t regList) {
    int32_t w = 0;
    if( pop ) { 
        w = (((cond * 268435456) + 146604032) + regList);
    } else { 
        w = (((cond * 268435456) + 153944064) + regList);
    }
    OPA$PutWord(w);
}

void OPA$GenMOVWT(int8_t cond, uint8_t top, int16_t Rd, int32_t imm16) {
    int32_t w = 0;
    if( top ) { 
        w = ((cond * 268435456) + 54525952);
    } else { 
        w = ((cond * 268435456) + 50331648);
    }
    w = (((w + (OBERON$DIV(imm16, 4096) * 65536)) + (Rd * 4096)) + OBERON$MOD(imm16, 4096));
    OPA$PutWord(w);
}

void OPA$GenCLZetc(int8_t cond, int32_t op, int16_t Rd, int16_t Rm) {
    int32_t w = 0;
    switch( op ) { 
    case 0:
        w = ((((cond * 268435456) + 24055568) + (Rd * 4096)) + Rm);
        break;
    case 1:
        w = ((((cond * 268435456) + 117378864) + (Rd * 4096)) + Rm);
        break;
    case 2:
        w = ((((cond * 268435456) + 113184560) + (Rd * 4096)) + Rm);
        break;
    }
    OPA$PutWord(w);
}

void OPA$GenNOPBarrier(int32_t op, int32_t imm) {
    switch( op ) { 
    case 0:
        OPA$PutWord(((int32_t)3810586624U));
        break;
    case 1:
        OPA$PutWord(((int32_t)4118802522U));
        break;
    case 2:
        OPA$PutWord(((int32_t)4118802506U));
        break;
    case 3:
        OPA$PutWord(((int32_t)4118802543U));
        break;
    case 4:
        OPA$PutWord(((((int32_t)3776970864U) + (OBERON$DIV(imm, 16) * 256)) + OBERON$MOD(imm, 16)));
        break;
    case 5:
        OPA$PutWord((((int32_t)4009754624U) + OPA$AND(imm, 16777215)));
        break;
    }
}

void OPA$GenCPS(int32_t op) {
    if( (op == 0) ) { 
        OPA$PutWord(((int32_t)4043833472U));
    } else { 
        OPA$PutWord(((int32_t)4044095616U));
    }
}

void OPA$GenVFP3op(int8_t cond, int32_t op, uint8_t dbl, int16_t Vd, int16_t Vn, int16_t Vm) {
    int32_t w = 0;
    int32_t sz = 0;
    int32_t opc = 0;
    if( dbl ) { 
        sz = 256;
    } else { 
        sz = 0;
    }
    switch( op ) { 
    case 0:
        opc = 238029312;
        break;
    case 1:
        opc = 238029376;
        break;
    case 2:
        opc = 236980736;
        break;
    case 3:
        opc = 243272192;
        break;
    }
    w = (((cond * 268435456) + opc) + sz);
    if( dbl ) { 
        w = ((((((w + (OBERON$DIV(Vd, 16) * 4194304)) + (OBERON$MOD(Vd, 16) * 4096)) + (OBERON$DIV(Vn, 16) * 128)) + (OBERON$MOD(Vn, 16) * 65536)) + (OBERON$DIV(Vm, 16) * 32)) + OBERON$MOD(Vm, 16));
    } else { 
        w = ((((((w + (OBERON$MOD(Vd, 2) * 4194304)) + (OBERON$DIV(Vd, 2) * 4096)) + (OBERON$MOD(Vn, 2) * 128)) + (OBERON$DIV(Vn, 2) * 65536)) + (OBERON$MOD(Vm, 2) * 32)) + OBERON$DIV(Vm, 2));
    }
    OPA$PutWord(w);
}

void OPA$GenVFP2op(int8_t cond, int32_t op, uint8_t dbl, int16_t Vd, int16_t Vm) {
    int32_t w = 0;
    int32_t sz = 0;
    int32_t opc = 0;
    if( dbl ) { 
        sz = 256;
    } else { 
        sz = 0;
    }
    switch( op ) { 
    case 0:
        opc = 246418112;
        break;
    case 1:
        opc = 246483520;
        break;
    case 2:
        opc = 246680128;
        break;
    case 3:
        opc = 246483648;
        break;
    }
    w = (((cond * 268435456) + opc) + sz);
    if( dbl ) { 
        w = ((((w + (OBERON$DIV(Vd, 16) * 4194304)) + (OBERON$MOD(Vd, 16) * 4096)) + (OBERON$DIV(Vm, 16) * 32)) + OBERON$MOD(Vm, 16));
    } else { 
        w = ((((w + (OBERON$MOD(Vd, 2) * 4194304)) + (OBERON$DIV(Vd, 2) * 4096)) + (OBERON$MOD(Vm, 2) * 32)) + OBERON$DIV(Vm, 2));
    }
    OPA$PutWord(w);
}

void OPA$GenVLdSt(int8_t cond, uint8_t store, uint8_t dbl, int16_t Vd, int16_t Rn, int32_t offset) {
    int32_t w = 0;
    int32_t U = 0;
    U = 8388608;
    if( (offset < 0) ) { 
        U = 0;
        offset = (-offset);
    }
    if( (OBERON$MOD(offset, 4) != 0) ) { 
        OPM$err(501);
    }
    offset = OBERON$DIV(offset, 4);
    if( (offset > 255) ) { 
        OPM$err(501);
    }
    if( store ) { 
        w = ((cond * 268435456) + 218106368);
    } else { 
        w = ((cond * 268435456) + 219154944);
    }
    if( dbl ) { 
        w = (w + 256);
    }
    w = (((w + U) + (Rn * 65536)) + OPA$AND(offset, 255));
    if( dbl ) { 
        w = ((w + (OBERON$DIV(Vd, 16) * 4194304)) + (OBERON$MOD(Vd, 16) * 4096));
    } else { 
        w = ((w + (OBERON$MOD(Vd, 2) * 4194304)) + (OBERON$DIV(Vd, 2) * 4096));
    }
    OPA$PutWord(w);
}

void OPA$GenVMOV(int8_t cond, uint8_t toVFP, int16_t Rt, int16_t Vn) {
    int32_t w = 0;
    if( toVFP ) { 
        w = (((((cond * 268435456) + 234883600) + (OBERON$DIV(Vn, 2) * 65536)) + (OBERON$MOD(Vn, 2) * 128)) + (Rt * 4096));
    } else { 
        w = (((((cond * 268435456) + 235932176) + (OBERON$DIV(Vn, 2) * 65536)) + (OBERON$MOD(Vn, 2) * 128)) + (Rt * 4096));
    }
    OPA$PutWord(w);
}

void OPA$GenVMRS(int8_t cond, uint8_t toAPSR) {
    if( toAPSR ) { 
        OPA$PutWord(((cond * 268435456) + 250739216));
    } else { 
        OPA$PutWord(((cond * 268435456) + 249629200));
    }
}

void OPA$GenCopro(int8_t cond, uint8_t mrc, int16_t coproc, int16_t opc1, int16_t Rt, int16_t CRn, int16_t CRm, int16_t opc2) {
    int32_t w = 0;
    if( mrc ) { 
        w = ((cond * 268435456) + 235929616);
    } else { 
        w = ((cond * 268435456) + 234881040);
    }
    w = ((((((w + (opc1 * 2097152)) + (CRn * 65536)) + (Rt * 4096)) + (coproc * 256)) + (opc2 * 32)) + CRm);
    OPA$PutWord(w);
}

void OPA$ParseInstruction() {
    int32_t ind = 0;
    int32_t nameLen = 0;
    OPA$Mnemo baseName = {0};
void OPA$_$9$init$(OPA$_$9* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        OPA$Operand$init$(obj, 5);
    }
}

    OPA$_$9 op = {0};
    int32_t i = 0;
    int8_t cond = 0;
    uint8_t setFlags = 0;
    int8_t cat = 0;
    int32_t opcode = 0;
    OPA$errpos = OPM$errpos;
    if( (((strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){68,67,68,0}) == 0) || (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){68,67,87,0}) == 0)) || (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){68,67,66,0}) == 0)) ) { 
        ind = 0;
        if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){68,67,68,0}) == 0) ) { 
            ind = 4;
        } else if( (strcmp((const char*)OPA$ident.$, (const char*)(const uint8_t[]){68,67,87,0}) == 0) ) { 
            ind = 2;
        } else { 
            ind = 1;
        }
        OPA$Get(&OPA$sym);
        while( (((OPA$sym == 4) || (OPA$sym == 18)) || (OPA$sym == 22)) ) {
            if( (OPA$sym == 22) ) { 
                OPA$Get(&OPA$sym);
            }
            if( ((OPA$sym == 18) && (OPA$val == 1)) ) { 
                i = 0;
                while( (i < ind) ) {
                    OPA$PutByte((int32_t)(uint8_t)(((uint8_t*)OPA$str.$)[0]));
                    i++;
                }
            } else if( (OPA$sym == 4) ) { 
                i = 0;
                while( (i < ind) ) {
                    OPA$PutByte(OPA$AND(OPA$val, 255));
                    OPA$val = OBERON$DIV(OPA$val, 256);
                    i++;
                }
            } else { 
                OPA$Expression(&OPA$val);
                i = 0;
                while( (i < ind) ) {
                    OPA$PutByte(OPA$AND(OPA$val, 255));
                    OPA$val = OBERON$DIV(OPA$val, 256);
                    i++;
                }
            }
            OPA$Get(&OPA$sym);
            if( (OPA$sym == 5) ) { 
                OPA$Get(&OPA$sym);
            } else { 
                return;
            }
        }
        return;
    }
    strcpy((char*)baseName.$, (const char*)OPA$ident.$);
    OPA$FindInstruction((MIC$AP){12, baseName.$}, &ind);
    if( (ind >= 0) ) { 
        cond = 14;
        setFlags = 0;
    } else { 
        strcpy((char*)baseName.$, (const char*)OPA$ident.$);
        OPA$ParseCondition((MIC$AP){12, baseName.$}, &cond, &nameLen);
        setFlags = 0;
        if( ((nameLen > 1) && (((uint8_t*)baseName.$)[(nameLen - 1)] == 83)) ) { 
            ((uint8_t*)baseName.$)[(nameLen - 1)] = 0;
            setFlags = 1;
            nameLen--;
        } else { 
            ((uint8_t*)baseName.$)[nameLen] = 0;
        }
        OPA$FindInstruction((MIC$AP){12, baseName.$}, &ind);
        if( (ind < 0) ) { 
            strcpy((char*)baseName.$, (const char*)OPA$ident.$);
            OPA$ParseCondition((MIC$AP){12, baseName.$}, &cond, &nameLen);
            ((uint8_t*)baseName.$)[nameLen] = 0;
            setFlags = 0;
            OPA$FindInstruction((MIC$AP){12, baseName.$}, &ind);
            if( (ind < 0) ) { 
                OPM$err(502);
                return;
            }
        }
    }
    cat = ((OPA$InstrDesc*)OPA$InstrTab.$)[ind].cat;
    opcode = ((OPA$InstrDesc*)OPA$InstrTab.$)[ind].op;
    OPA$Get(&OPA$sym);
    int _temp1 = 4; i = 0; 
    while( i <= _temp1 ) {
        ((OPA$Operand*)op.$)[i].mode = (-1);
        ((OPA$Operand*)op.$)[i].reg = (-1);
        ((OPA$Operand*)op.$)[i].imm = 0;
        ((OPA$Operand*)op.$)[i].disp = 0;
        ((OPA$Operand*)op.$)[i].base = (-1);
        ((OPA$Operand*)op.$)[i].index = (-1);
        ((OPA$Operand*)op.$)[i].shift = (-1);
        ((OPA$Operand*)op.$)[i].shiftAmt = 0;
        ((OPA$Operand*)op.$)[i].regList = (0);
        ((OPA$Operand*)op.$)[i].obj = NULL;
        ((OPA$Operand*)op.$)[i].writeback = 0;
        ((OPA$Operand*)op.$)[i].preIndex = 0;
        ((OPA$Operand*)op.$)[i].dbl = 0;
        i++;
    }
    if( (OPA$sym != 8) ) { 
        i = 0;
        while(1) {
            OPA$GetOperand(&((OPA$Operand*)op.$)[i]);
            i++;
            if( (OPA$sym != 5) ) { 
                goto __1456;
            }
            OPA$Get(&OPA$sym);
            if( (i >= 5) ) { 
                OPM$err(501);
                goto __1456;
            }
        }        __1456:

    }
    switch( cat ) { 
    case 0:
        if( ((opcode == 13) || (opcode == 15)) ) { 
            if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
                OPA$GenDataProc(cond, opcode, setFlags, ((OPA$Operand*)op.$)[0].reg, 0, &((OPA$Operand*)op.$)[1]);
            } else { 
                OPM$err(501);
            }
        } else if( ((((opcode == 10) || (opcode == 11)) || (opcode == 8)) || (opcode == 9)) ) { 
            if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
                OPA$GenDataProc(cond, opcode, 1, 0, ((OPA$Operand*)op.$)[0].reg, &((OPA$Operand*)op.$)[1]);
            } else { 
                OPM$err(501);
            }
        } else { 
            if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 8)) ) { 
                OPA$GenDataProc(cond, opcode, setFlags, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, &((OPA$Operand*)op.$)[2]);
            } else { 
                OPM$err(501);
            }
        }
        break;
    case 22:
        if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 8)) ) { 
            OPA$GenShiftInstr(cond, opcode, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, &((OPA$Operand*)op.$)[2]);
        } else { 
            OPM$err(501);
        }
        break;
    case 1:
        if( (opcode <= 1) ) { 
            if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
                if( (opcode == 0) ) { 
                    OPA$GenMultiply(cond, opcode, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[2].reg, 0);
                } else { 
                    OPA$GenMultiply(cond, opcode, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[2].reg, ((OPA$Operand*)op.$)[3].reg);
                }
            } else { 
                OPM$err(501);
            }
        } else { 
            if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
                OPA$GenMultiply(cond, opcode, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[3].reg, ((OPA$Operand*)op.$)[2].reg);
            } else { 
                OPM$err(501);
            }
        }
        break;
    case 2:
        if( (((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 8)) && (((OPA$Operand*)op.$)[2].mode == 8)) ) { 
            OPA$GenDivide(cond, opcode, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[2].reg);
        } else { 
            OPM$err(501);
        }
        break;
    case 3:
        if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 40)) ) { 
            OPA$GenLdSt(cond, opcode, ((OPA$Operand*)op.$)[0].reg, &((OPA$Operand*)op.$)[1]);
        } else { 
            OPM$err(501);
        }
        break;
    case 4:
        if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 40)) ) { 
            OPA$GenLdStH(cond, opcode, ((OPA$Operand*)op.$)[0].reg, &((OPA$Operand*)op.$)[1]);
        } else { 
            OPM$err(501);
        }
        break;
    case 5:
        OPA$GenBranch(cond, (opcode == 1), &((OPA$Operand*)op.$)[0]);
        break;
    case 6:
        if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
            OPA$GenBX(cond, (opcode == 1), ((OPA$Operand*)op.$)[0].reg);
        } else { 
            OPM$err(501);
        }
        break;
    case 11:
        if( (((OPA$Operand*)op.$)[0].mode == 64) ) { 
            OPA$GenPushPop(cond, (opcode == 1), ((OPA$Operand*)op.$)[0].regList);
        } else { 
            OPM$err(501);
        }
        break;
    case 12:
        if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 32)) ) { 
            OPA$GenMOVWT(cond, (opcode == 1), ((OPA$Operand*)op.$)[0].reg, OPA$AND(((OPA$Operand*)op.$)[1].imm, 65535));
        } else { 
            OPM$err(501);
        }
        break;
    case 13:
        if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 8)) ) { 
            OPA$GenCLZetc(cond, opcode, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg);
        } else { 
            OPM$err(501);
        }
        break;
    case 14:
        if( (opcode <= 3) ) { 
            OPA$GenNOPBarrier(opcode, 0);
        } else if( (opcode == 4) ) { 
            if( (((OPA$Operand*)op.$)[0].mode == 32) ) { 
                OPA$GenNOPBarrier(opcode, ((OPA$Operand*)op.$)[0].imm);
            } else { 
                OPA$GenNOPBarrier(opcode, 0);
            }
        } else { 
            if( (((OPA$Operand*)op.$)[0].mode == 32) ) { 
                OPA$GenNOPBarrier(opcode, ((OPA$Operand*)op.$)[0].imm);
            } else { 
                OPA$GenNOPBarrier(opcode, 0);
            }
        }
        break;
    case 15:
        OPA$GenCPS(opcode);
        break;
    case 16:
        if( (((OPA$Operand*)op.$)[2].mode == 8) ) { 
            OPA$GenCopro(cond, (opcode == 1), (int16_t)(((OPA$Operand*)op.$)[0].imm), (int16_t)(((OPA$Operand*)op.$)[1].imm), ((OPA$Operand*)op.$)[2].reg, (int16_t)(((OPA$Operand*)op.$)[3].imm), (int16_t)(((OPA$Operand*)op.$)[4].imm), 0);
        } else { 
            OPM$err(501);
        }
        break;
    case 17:
        if( (opcode == 0) ) { 
            if( (((OPA$Operand*)op.$)[1].mode == 8) ) { 
                OPA$PutWord((((cond * 268435456) + 18935808) + ((OPA$Operand*)op.$)[1].reg));
            } else { 
                OPM$err(501);
            }
        } else { 
            if( (((OPA$Operand*)op.$)[0].mode == 8) ) { 
                OPA$PutWord((((cond * 268435456) + 17760256) + (((OPA$Operand*)op.$)[0].reg * 4096)));
            } else { 
                OPM$err(501);
            }
        }
        break;
    case 8:
        if( (((OPA$Operand*)op.$)[0].mode == 24) ) { 
            OPA$GenVFP3op(cond, opcode, 1, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[2].reg);
        } else if( (((OPA$Operand*)op.$)[0].mode == 16) ) { 
            OPA$GenVFP3op(cond, opcode, 0, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[2].reg);
        } else { 
            OPM$err(501);
        }
        break;
    case 7:
        if( (((OPA$Operand*)op.$)[0].mode == 24) ) { 
            OPA$GenVFP2op(cond, opcode, 1, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg);
        } else if( (((OPA$Operand*)op.$)[0].mode == 16) ) { 
            OPA$GenVFP2op(cond, opcode, 0, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg);
        } else { 
            OPM$err(501);
        }
        break;
    case 9:
        if( ((((OPA$Operand*)op.$)[0].mode == 24) && (((OPA$Operand*)op.$)[1].mode == 40)) ) { 
            OPA$GenVLdSt(cond, (opcode == 1), 1, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].base, ((OPA$Operand*)op.$)[1].disp);
        } else if( ((((OPA$Operand*)op.$)[0].mode == 16) && (((OPA$Operand*)op.$)[1].mode == 40)) ) { 
            OPA$GenVLdSt(cond, (opcode == 1), 0, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].base, ((OPA$Operand*)op.$)[1].disp);
        } else { 
            OPM$err(501);
        }
        break;
    case 19:
        if( ((((OPA$Operand*)op.$)[0].mode == 16) && (((OPA$Operand*)op.$)[1].mode == 8)) ) { 
            OPA$GenVMOV(cond, 1, ((OPA$Operand*)op.$)[1].reg, ((OPA$Operand*)op.$)[0].reg);
        } else if( ((((OPA$Operand*)op.$)[0].mode == 8) && (((OPA$Operand*)op.$)[1].mode == 16)) ) { 
            OPA$GenVMOV(cond, 0, ((OPA$Operand*)op.$)[0].reg, ((OPA$Operand*)op.$)[1].reg);
        } else if( ((((OPA$Operand*)op.$)[0].mode == 16) && (((OPA$Operand*)op.$)[1].mode == 16)) ) { 
            OPA$PutWord(((((((cond * 268435456) + 246417984) + (OBERON$MOD(((OPA$Operand*)op.$)[0].reg, 2) * 4194304)) + (OBERON$DIV(((OPA$Operand*)op.$)[0].reg, 2) * 4096)) + (OBERON$MOD(((OPA$Operand*)op.$)[1].reg, 2) * 32)) + OBERON$DIV(((OPA$Operand*)op.$)[1].reg, 2)));
        } else if( ((((OPA$Operand*)op.$)[0].mode == 24) && (((OPA$Operand*)op.$)[1].mode == 24)) ) { 
            OPA$PutWord(((((((cond * 268435456) + 246418240) + (OBERON$DIV(((OPA$Operand*)op.$)[0].reg, 16) * 4194304)) + (OBERON$MOD(((OPA$Operand*)op.$)[0].reg, 16) * 4096)) + (OBERON$DIV(((OPA$Operand*)op.$)[1].reg, 16) * 32)) + OBERON$MOD(((OPA$Operand*)op.$)[1].reg, 16)));
        } else { 
            OPM$err(501);
        }
        break;
    case 20:
        if( (opcode == 0) ) { 
            OPA$GenVMRS(cond, 1);
        } else { 
            OPA$GenVMRS(cond, 0);
        }
        break;
    case 21:
        OPM$err(501);
        break;
    default:
        OPM$err(502);
        break;
    }
}

void OPA$ParseLabel() {
    OPA$Object obj = NULL;
    OPA$FixPnt fix = NULL;
    if(!(OPA$sym == 11)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    OPA$insert((MIC$AP){32, OPA$ident.$}, &obj);
    if( ((*obj).typ == 1) ) { 
        fix = (*obj).fix;
        while( (fix != NULL) ) {
            OPA$FixDisp(&fix);
            fix = (*fix).next;
        }
        (*obj).typ = 0;
        (*obj).val = OPA$pc;
    } else { 
        OPM$err(512);
    }
    OPA$Get(&OPA$sym);
}

void OPA$Init() {
    (*OPA$root).next = NULL;
    (*OPA$root).left = NULL;
    (*OPA$root).right = NULL;
    OPA$pc = 0;
    OPA$Target = (0 | 1u << 0);
}

void OPA$Close() {
    (*OPA$root).right = NULL;
}

void OPA$BodyInit() {
    int32_t i = 0;
    OPM$LogWLn();
    OPM$LogWStr((MIC$AP){strlen((const uint8_t[]){32,32,117,115,105,110,103,32,79,80,50,45,65,83,77,32,65,82,77,51,50,32,97,100,100,45,111,110,0}) + 1,(const uint8_t[]){32,32,117,115,105,110,103,32,79,80,50,45,65,83,77,32,65,82,77,51,50,32,97,100,100,45,111,110,0}});
    OPA$root = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); OPA$root->class$ = &OPA$ObjDesc$class$;
    (*OPA$root).left = NULL;
    (*OPA$root).right = NULL;
    (*OPA$root).next = NULL;
    int _temp2 = (512 - 1); i = 0; 
    while( i <= _temp2 ) {
        ((int16_t*)OPA$InstrHash.$)[i] = (-1);
        i++;
    }
    OPA$BuildInstrTable();
    ((int8_t*)OPA$SizeTab.$)[0] = 0;
    ((int8_t*)OPA$SizeTab.$)[1] = 1;
    ((int8_t*)OPA$SizeTab.$)[2] = 1;
    ((int8_t*)OPA$SizeTab.$)[3] = 1;
    ((int8_t*)OPA$SizeTab.$)[4] = 1;
    ((int8_t*)OPA$SizeTab.$)[5] = 2;
    ((int8_t*)OPA$SizeTab.$)[6] = 4;
    ((int8_t*)OPA$SizeTab.$)[7] = 4;
    ((int8_t*)OPA$SizeTab.$)[8] = 8;
    ((int8_t*)OPA$SizeTab.$)[9] = 4;
    ((int8_t*)OPA$SizeTab.$)[10] = 4;
    ((int8_t*)OPA$SizeTab.$)[11] = 4;
    ((int8_t*)OPA$SizeTab.$)[12] = 0;
    ((int8_t*)OPA$SizeTab.$)[13] = 4;
    ((int8_t*)OPA$SizeTab.$)[14] = 4;
    ((int8_t*)OPA$SizeTab.$)[15] = 0;
    ((int8_t*)OPA$SizeTab.$)[16] = 8;
}

/* public */ void OPA$Assemble(OPT$Node* x, uint8_t exported, uint8_t inlined) {
    OPA$export = exported;
    OPA$inline_ = inlined;
    if( OPA$FirstTime ) { 
        OPA$BodyInit();
        OPA$FirstTime = 0;
    }
    OPA$Init();
    OPA$first = NULL;
    OPA$last = NULL;
    OPA$NewNode();
    OPA$fixlist = NULL;
    OPA$Get(&OPA$sym);
    if( (OPA$sym == 20) ) { 
        while( (((OPA$sym != 21) && (OPA$sym != 8)) && (OPA$sym != 10)) ) {
            OPA$Get(&OPA$sym);
        }
        if( (OPA$sym == 21) ) { 
            OPA$Get(&OPA$sym);
        }
    } else { 
        OPA$Get(&OPA$sym);
    }
    while( ((OPA$sym != 10) && (OPA$sym != 0)) ) {
        if( (OPA$sym == 11) ) { 
            OPA$ParseLabel();
        }
        if( (OPA$sym == 1) ) { 
            OPA$ParseInstruction();
        }
        while( ((OPA$sym != 10) && (OPA$sym != 8)) ) {
            OPA$Get(&OPA$sym);
            OPM$err(510);
        }
        OPA$Get(&OPA$sym);
    }
    if( OPM$noerr ) { 
        OPA$CheckLabels();
    }
    OPA$Close();
    OPB$Construct(29, &OPA$first, OPA$fixlist);
    (*x) = OPA$first;
    (*(*x)).conval = NULL;
}

void OPA$BEGIN$() {
    OPA$FirstTime = 1;
}

static int OPA$initialized = 0;
void OPA$init$(void) {
    if( OPA$initialized ) return;
    OPA$initialized = 1;
    OPM$init$();
    OPS$init$();
    OPT$init$();
    OPB$init$();
    OPA$BEGIN$();
}

