#ifndef __OPA_INCLUDED__
#define __OPA_INCLUDED__

// OPA.h
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:43:09 2026

#include <stdint.h>
#include "OPM.h"
#include "OPS.h"
#include "OPT.h"
#include "OPB.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPA$none (-1)
#define OPA$ARMv7A 0
#define OPA$Nassembler 29
#define OPA$Ncode 30
#define OPA$Nfixup 31
#define OPA$StLabel 0
#define OPA$StFwdLabel 1
#define OPA$StConst 3
#define OPA$StType 4
#define OPA$StVar 5
#define OPA$StVarPar 6
#define OPA$StGlobal 7
#define OPA$StMod 11
#define OPA$RegMode 8
#define OPA$SRegMode 16
#define OPA$DRegMode 24
#define OPA$ImmMode 32
#define OPA$MemMode 40
#define OPA$LabelMode 48
#define OPA$FwdLabelMode 49
#define OPA$ShiftMode 56
#define OPA$RegListMode 64
#define OPA$CondMode 72
#define OPA$CondEQ 0
#define OPA$CondNE 1
#define OPA$CondCS 2
#define OPA$CondCC 3
#define OPA$CondMI 4
#define OPA$CondPL 5
#define OPA$CondVS 6
#define OPA$CondVC 7
#define OPA$CondHI 8
#define OPA$CondLS 9
#define OPA$CondGE 10
#define OPA$CondLT 11
#define OPA$CondGT 12
#define OPA$CondLE 13
#define OPA$CondAL 14
#define OPA$ShLSL 0
#define OPA$ShLSR 1
#define OPA$ShASR 2
#define OPA$ShROR 3
#define OPA$CatDP 0
#define OPA$CatMul 1
#define OPA$CatDiv 2
#define OPA$CatLdSt 3
#define OPA$CatLdStH 4
#define OPA$CatBranch 5
#define OPA$CatBX 6
#define OPA$CatVFP2 7
#define OPA$CatVFP3 8
#define OPA$CatVLdSt 9
#define OPA$CatSys 10
#define OPA$CatPushPop 11
#define OPA$CatMOVW 12
#define OPA$CatCLZ 13
#define OPA$CatNOP 14
#define OPA$CatCPS 15
#define OPA$CatCopro 16
#define OPA$CatMSR 17
#define OPA$CatData 18
#define OPA$CatVMOV 19
#define OPA$CatVMRS 20
#define OPA$CatVCVT 21
#define OPA$CatShift 22
#define OPA$TAB 9
#define OPA$CR 13
#define OPA$LF 10
#define OPA$SPACE 32
#define OPA$ScUndef 0
#define OPA$ScIdent 1
#define OPA$ScSemicolon 2
#define OPA$ScAt 3
#define OPA$ScNumber 4
#define OPA$ScComma 5
#define OPA$ScLBrak 6
#define OPA$ScRBrak 7
#define OPA$ScCR 8
#define OPA$ScMult 9
#define OPA$ScEnd 10
#define OPA$ScLabel 11
#define OPA$ScColon 12
#define OPA$ScPlus 13
#define OPA$ScMinus 14
#define OPA$ScDiv 15
#define OPA$ScLPar 16
#define OPA$ScRPar 17
#define OPA$ScString 18
#define OPA$ScPoint 19
#define OPA$ScLBrace 20
#define OPA$ScRBrace 21
#define OPA$ScHash 22
#define OPA$ScExcl 23
#define OPA$NameLen 32
#define OPA$MaxStrLen 256
#define OPA$MnemoLen 12
#define OPA$MaxInstr 256
#define OPA$InstrHashSize 512
#define OPA$dpAND 0
#define OPA$dpEOR 1
#define OPA$dpSUB 2
#define OPA$dpRSB 3
#define OPA$dpADD 4
#define OPA$dpADC 5
#define OPA$dpSBC 6
#define OPA$dpRSC 7
#define OPA$dpTST 8
#define OPA$dpTEQ 9
#define OPA$dpCMP 10
#define OPA$dpCMN 11
#define OPA$dpORR 12
#define OPA$dpMOV 13
#define OPA$dpBIC 14
#define OPA$dpMVN 15
typedef OPS$Name OPA$Name;
typedef struct OPA$Mnemo { uint8_t $[12]; } OPA$Mnemo;
typedef struct OPA$ObjDesc* OPA$Object;
typedef struct OPA$FixPntDesc* OPA$FixPnt;
typedef struct OPA$InstrDesc {
    struct OPA$InstrDesc$Class$* class$;
    OPA$Mnemo name;
    int8_t cat;
    int32_t op;
    int32_t flags;
} OPA$InstrDesc;
void OPA$InstrDesc$init$(OPA$InstrDesc* obj, unsigned int n);
struct OPA$InstrDesc$Class$ {
    void* super$;
};
extern struct OPA$InstrDesc$Class$ OPA$InstrDesc$class$;
typedef struct OPA$Operand {
    struct OPA$Operand$Class$* class$;
    int32_t mode;
    int16_t reg;
    int32_t imm;
    int32_t disp;
    int16_t base;
    int16_t index;
    int16_t shift;
    int16_t shiftAmt;
    int32_t regList;
    OPA$Object obj;
    uint8_t writeback;
    uint8_t preIndex;
    uint8_t dbl;
} OPA$Operand;
void OPA$Operand$init$(OPA$Operand* obj, unsigned int n);
struct OPA$Operand$Class$ {
    void* super$;
};
extern struct OPA$Operand$Class$ OPA$Operand$class$;
typedef struct OPA$ObjDesc {
    struct OPA$ObjDesc$Class$* class$;
    int32_t typ;
    int32_t val;
    int32_t size;
    OPA$Name name;
    OPA$Object left;
    OPA$Object right;
    OPA$Object next;
    OPA$FixPnt fix;
    OPT$Object obj;
} OPA$ObjDesc;
void OPA$ObjDesc$init$(OPA$ObjDesc* obj, unsigned int n);
struct OPA$ObjDesc$Class$ {
    void* super$;
};
extern struct OPA$ObjDesc$Class$ OPA$ObjDesc$class$;
typedef struct OPA$FixPntDesc {
    struct OPA$FixPntDesc$Class$* class$;
    int32_t pc;
    OPT$Node node;
    int32_t pos;
    OPA$FixPnt next;
} OPA$FixPntDesc;
void OPA$FixPntDesc$init$(OPA$FixPntDesc* obj, unsigned int n);
struct OPA$FixPntDesc$Class$ {
    void* super$;
};
extern struct OPA$FixPntDesc$Class$ OPA$FixPntDesc$class$;
extern OPA$Object OPA$root;
typedef struct OPA$_$0 { OPA$InstrDesc $[256]; } OPA$_$0;
void OPA$_$0$init$(OPA$_$0* obj, unsigned int n);
extern OPA$_$0 OPA$InstrTab;
typedef struct OPA$_$1 { int16_t $[512]; } OPA$_$1;
extern OPA$_$1 OPA$InstrHash;
extern int16_t OPA$nofInstr;
typedef struct OPA$_$2 { int8_t $[17]; } OPA$_$2;
extern OPA$_$2 OPA$SizeTab;
extern uint8_t OPA$export;
extern uint8_t OPA$inline_;
extern uint8_t OPA$FirstTime;
extern int32_t OPA$Target;
extern int32_t OPA$pc;
extern int32_t OPA$sym;
extern OPA$Name OPA$ident;
extern int32_t OPA$val;
typedef struct OPA$_$3 { uint8_t $[256]; } OPA$_$3;
extern OPA$_$3 OPA$str;
extern int32_t OPA$errpos;
extern OPT$Node OPA$first;
extern OPT$Node OPA$last;
extern OPT$Node OPA$fixlist;
extern int8_t OPA$condCode;
extern int32_t OPA$AND(int32_t a, int32_t b);
extern int32_t OPA$ORL(int32_t a, int32_t b);
// no typedef for open array OPA$_$4 (uint8_t*)
extern void OPA$insert(MIC$AP name, OPA$Object* obj);
extern OPA$Object OPA$ConvertObj(OPT$Object ob);
extern void OPA$find(MIC$AP name, OPA$Object* obj);
// no typedef for open array OPA$_$5 (uint8_t*)
extern int32_t OPA$HashInstr(MIC$AP name);
// no typedef for open array OPA$_$6 (uint8_t*)
extern void OPA$AddInstr(MIC$AP name, int8_t cat, int32_t op, int32_t flags);
// no typedef for open array OPA$_$7 (uint8_t*)
extern void OPA$FindInstruction(MIC$AP name, int32_t* inx);
extern void OPA$BuildInstrTable();
extern void OPA$skipBlanks();
extern void OPA$GetIdent(MIC$AP name);
extern void OPA$Get(int32_t* sym);
extern void OPA$Check(int32_t s);
extern void OPA$Expression(int32_t* x);
// no typedef for open array OPA$_$8 (uint8_t*)
extern void OPA$ParseCondition(MIC$AP name, int8_t* cond, int32_t* nameLen);
extern uint8_t OPA$ParseRegister(MIC$AP name, int16_t* reg, int32_t* mode);
extern void OPA$ParseRegList(int32_t* regList);
extern void OPA$GetOperand(OPA$Operand* o);
extern void OPA$CheckLabels();
extern void OPA$InsertFix(OPA$Object* obj, int32_t pc);
extern void OPA$FixDisp(OPA$FixPnt* fix);
extern void OPA$NewNode();
extern void OPA$PutByte(int32_t b);
extern void OPA$PutWord(int32_t w);
extern uint8_t OPA$CanEncodeImm(int32_t imm, int32_t* encoding);
extern void OPA$GenDataProc(int8_t cond, int32_t op, uint8_t S, int16_t Rd, int16_t Rn, OPA$Operand* op2);
extern void OPA$GenShiftInstr(int8_t cond, int32_t shiftType, int16_t Rd, int16_t Rm, OPA$Operand* op2);
extern void OPA$GenMultiply(int8_t cond, int32_t op, int16_t Rd, int16_t Rm, int16_t Rs, int16_t Rn);
extern void OPA$GenDivide(int8_t cond, int32_t op, int16_t Rd, int16_t Rn, int16_t Rm);
extern void OPA$GenLdSt(int8_t cond, int32_t op, int16_t Rt, OPA$Operand* mem);
extern void OPA$GenLdStH(int8_t cond, int32_t op, int16_t Rt, OPA$Operand* mem);
extern void OPA$GenBranch(int8_t cond, uint8_t link, OPA$Operand* target);
extern void OPA$GenBX(int8_t cond, uint8_t link, int16_t Rm);
extern void OPA$GenPushPop(int8_t cond, uint8_t pop, int32_t regList);
extern void OPA$GenMOVWT(int8_t cond, uint8_t top, int16_t Rd, int32_t imm16);
extern void OPA$GenCLZetc(int8_t cond, int32_t op, int16_t Rd, int16_t Rm);
extern void OPA$GenNOPBarrier(int32_t op, int32_t imm);
extern void OPA$GenCPS(int32_t op);
extern void OPA$GenVFP3op(int8_t cond, int32_t op, uint8_t dbl, int16_t Vd, int16_t Vn, int16_t Vm);
extern void OPA$GenVFP2op(int8_t cond, int32_t op, uint8_t dbl, int16_t Vd, int16_t Vm);
extern void OPA$GenVLdSt(int8_t cond, uint8_t store, uint8_t dbl, int16_t Vd, int16_t Rn, int32_t offset);
extern void OPA$GenVMOV(int8_t cond, uint8_t toVFP, int16_t Rt, int16_t Vn);
extern void OPA$GenVMRS(int8_t cond, uint8_t toAPSR);
extern void OPA$GenCopro(int8_t cond, uint8_t mrc, int16_t coproc, int16_t opc1, int16_t Rt, int16_t CRn, int16_t CRm, int16_t opc2);
extern void OPA$ParseInstruction();
typedef struct OPA$_$9 { OPA$Operand $[5]; } OPA$_$9;
void OPA$_$9$init$(OPA$_$9* obj, unsigned int n);
extern void OPA$ParseLabel();
extern void OPA$Init();
extern void OPA$Close();
extern void OPA$BodyInit();
/* public */ extern void OPA$Assemble(OPT$Node* x, uint8_t exported, uint8_t inlined);
extern void OPA$BEGIN$();
extern void OPA$init$(void);

#endif // __OPA_INCLUDED__