#ifndef __OPO_INCLUDED__
#define __OPO_INCLUDED__

// OPO.h
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:43:09 2026

#include <stdint.h>
#include "OPT.h"
#include "OPM.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPO$Reg 15
#define OPO$Abs 16
#define OPO$RegRel 17
#define OPO$Coc 18
#define OPO$noScale 0
#define OPO$Scale1 0
#define OPO$Scale2 1
#define OPO$Scale4 2
#define OPO$Scale8 3
#define OPO$RegReg 0
#define OPO$RegMem 1
#define OPO$MemReg 2
#define OPO$ImmReg 3
#define OPO$ImmMem 4
#define OPO$Regs 0
#define OPO$Mem 2
#define OPO$Imme 3
#define OPO$CodeLength 65000
#define OPO$MaxConstLength (64 * 1024)
#define OPO$R0 0
#define OPO$R1 1
#define OPO$R2 2
#define OPO$R3 3
#define OPO$R4 4
#define OPO$R5 5
#define OPO$R6 6
#define OPO$R7 7
#define OPO$R8 8
#define OPO$R9 9
#define OPO$R10 10
#define OPO$FP 11
#define OPO$R11 11
#define OPO$IP 12
#define OPO$R12 12
#define OPO$SP 13
#define OPO$R13 13
#define OPO$LR 14
#define OPO$R14 14
#define OPO$PC 15
#define OPO$R15 15
#define OPO$Bit8 1
#define OPO$Bit16 2
#define OPO$Bit32 0
#define OPO$Bit64 5
#define OPO$noDisp 0
#define OPO$none (-1)
#define OPO$noBase (-1)
#define OPO$noInx (-1)
#define OPO$noImm 0
#define OPO$BUG 42
#define OPO$CondEQ 0
#define OPO$CondNE 1
#define OPO$CondCS 2
#define OPO$CondHS 2
#define OPO$CondCC 3
#define OPO$CondLO 3
#define OPO$CondMI 4
#define OPO$CondPL 5
#define OPO$CondVS 6
#define OPO$CondVC 7
#define OPO$CondHI 8
#define OPO$CondLS 9
#define OPO$CondGE 10
#define OPO$CondLT 11
#define OPO$CondGT 12
#define OPO$CondLE 13
#define OPO$CondAL 14
#define OPO$dpAND 0
#define OPO$dpEOR 1
#define OPO$dpSUB 2
#define OPO$dpRSB 3
#define OPO$dpADD 4
#define OPO$dpADC 5
#define OPO$dpSBC 6
#define OPO$dpRSC 7
#define OPO$dpTST 8
#define OPO$dpTEQ 9
#define OPO$dpCMP 10
#define OPO$dpCMN 11
#define OPO$dpORR 12
#define OPO$dpMOV 13
#define OPO$dpBIC 14
#define OPO$dpMVN 15
#define OPO$ShiftLSL 0
#define OPO$ShiftLSR 1
#define OPO$ShiftASR 2
#define OPO$ShiftROR 3
/* public */ // no typedef for pointer to array OPO$ConstArray (using MIC$DA instead)
// no typedef for open array OPO$_$0 (uint8_t*)
/* public */ extern int32_t OPO$pc;
/* public */ extern int32_t OPO$dsize;
/* public */ extern int32_t OPO$csize;
/* public */ extern int8_t OPO$lastImmSize;
/* public */ extern uint8_t* OPO$constant;
typedef struct OPO$_$1 { uint8_t $[65000]; } OPO$_$1;
/* public */ extern OPO$_$1 OPO$code;
/* public */ extern uint8_t OPO$CodeErr;
/* public */ extern void OPO$PutByte(int32_t b);
/* public */ extern void OPO$PutWord(int32_t w);
/* public */ extern void OPO$PutWordAt(int32_t pos, int32_t w);
/* public */ extern void OPO$GetWord(int32_t pos, int32_t* w);
/* public */ extern void OPO$PutByteAt(int32_t pos, int16_t b);
/* public */ extern void OPO$PutDWord(int32_t w);
/* public */ extern void OPO$PutDWordAt(int32_t pos, int32_t w);
/* public */ extern void OPO$GetDWord(int32_t pos, int32_t* w);
/* public */ extern void OPO$PutConsDWord(int32_t pos, int32_t val);
/* public */ extern void OPO$GetConsDWord(int32_t pos, int32_t* val);
/* public */ extern uint8_t OPO$CanEncodeImm(int32_t imm, int32_t* encoding);
/* public */ extern int32_t OPO$EncodeImm12(int32_t imm);
/* public */ extern void OPO$GenDataProcImm(int32_t cond, int32_t op, int32_t S, int32_t Rd, int32_t Rn, int32_t imm12);
/* public */ extern void OPO$GenDataProcReg(int32_t cond, int32_t op, int32_t S, int32_t Rd, int32_t Rn, int32_t Rm, int32_t shiftType, int32_t shiftAmt);
/* public */ extern void OPO$GenDataProcRegShiftReg(int32_t cond, int32_t op, int32_t S, int32_t Rd, int32_t Rn, int32_t Rm, int32_t shiftType, int32_t Rs);
/* public */ extern void OPO$GenMOVImm(int32_t cond, int32_t Rd, int32_t imm);
/* public */ extern void OPO$GenMOVReg(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenMVNImm(int32_t cond, int32_t Rd, int32_t imm);
/* public */ extern void OPO$GenADD(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenADDImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenSUB(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenSUBImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenRSB(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenRSBImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenANDReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenANDImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenORRReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenORRImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenEORReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenEORImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenBICReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenBICImm(int32_t cond, int32_t Rd, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenCMPReg(int32_t cond, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenCMPImm(int32_t cond, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenTSTReg(int32_t cond, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenTSTImm(int32_t cond, int32_t Rn, int32_t imm);
/* public */ extern void OPO$GenShiftImm(int32_t cond, int32_t Rd, int32_t Rm, int32_t shiftType, int32_t shiftAmt);
/* public */ extern void OPO$GenShiftReg(int32_t cond, int32_t Rd, int32_t Rm, int32_t shiftType, int32_t Rs);
/* public */ extern void OPO$GenMUL(int32_t cond, int32_t Rd, int32_t Rm, int32_t Rs);
/* public */ extern void OPO$GenMLA(int32_t cond, int32_t Rd, int32_t Rm, int32_t Rs, int32_t Rn);
/* public */ extern void OPO$GenSDIV(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenUDIV(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm);
/* public */ extern void OPO$GenMOVW(int32_t cond, int32_t Rd, int32_t imm16);
/* public */ extern void OPO$GenMOVT(int32_t cond, int32_t Rd, int32_t imm16);
/* public */ extern void OPO$LoadImm32(int32_t cond, int32_t Rd, int32_t imm);
/* public */ extern void OPO$GenLDR(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRB(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRH(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRSB(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRSH(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTR(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTRB(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTRH(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm, int32_t shiftType, int32_t shiftAmt);
/* public */ extern void OPO$GenSTRReg(int32_t cond, int32_t Rd, int32_t Rn, int32_t Rm, int32_t shiftType, int32_t shiftAmt);
/* public */ extern void OPO$GenSTRPre(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRPre(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTRPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRBPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTRBPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenLDRHPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenSTRHPost(int32_t cond, int32_t Rd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenPushReg(int32_t cond, int32_t Rd);
/* public */ extern void OPO$GenPopReg(int32_t cond, int32_t Rd);
/* public */ extern void OPO$GenPUSH(int32_t cond, int32_t regList);
/* public */ extern void OPO$GenPOP(int32_t cond, int32_t regList);
/* public */ extern void OPO$GenB(int32_t cond, int32_t offset);
/* public */ extern void OPO$GenBL(int32_t cond, int32_t offset);
/* public */ extern void OPO$GenBX(int32_t cond, int32_t Rm);
/* public */ extern void OPO$GenBLX(int32_t cond, int32_t Rm);
/* public */ extern void OPO$GenVLDR(int32_t cond, int32_t single, int32_t Vd, int32_t Rn, int32_t offset);
/* public */ extern void OPO$GenVSTR(int32_t cond, int32_t single, int32_t Vd, int32_t Rn, int32_t offset);
extern void OPO$EncodeVFPReg(int32_t reg, int32_t single, int32_t* hiNib, int32_t* loBit);
/* public */ extern void OPO$GenVFPDataProc(int32_t cond, int32_t single, int32_t opc1, int32_t opc2, int32_t Vd, int32_t Vn, int32_t Vm);
/* public */ extern void OPO$GenVADD(int32_t cond, int32_t single, int32_t Vd, int32_t Vn, int32_t Vm);
/* public */ extern void OPO$GenVSUB(int32_t cond, int32_t single, int32_t Vd, int32_t Vn, int32_t Vm);
/* public */ extern void OPO$GenVMUL(int32_t cond, int32_t single, int32_t Vd, int32_t Vn, int32_t Vm);
/* public */ extern void OPO$GenVDIV(int32_t cond, int32_t single, int32_t Vd, int32_t Vn, int32_t Vm);
/* public */ extern void OPO$GenVABS(int32_t cond, int32_t single, int32_t Vd, int32_t Vm);
/* public */ extern void OPO$GenVNEG(int32_t cond, int32_t single, int32_t Vd, int32_t Vm);
/* public */ extern void OPO$GenVCMP(int32_t cond, int32_t single, int32_t Vd, int32_t Vm);
/* public */ extern void OPO$GenVMRS(int32_t cond);
/* public */ extern void OPO$GenVMOVGPRtoS(int32_t cond, int32_t Sn, int32_t Rt);
/* public */ extern void OPO$GenVMOVStoGPR(int32_t cond, int32_t Rt, int32_t Sn);
/* public */ extern void OPO$GenVCVTF32S32(int32_t cond, int32_t Sd, int32_t Sm);
/* public */ extern void OPO$GenVCVTF64S32(int32_t cond, int32_t Dd, int32_t Sm);
/* public */ extern void OPO$GenVCVTF64F32(int32_t cond, int32_t Dd, int32_t Sm);
/* public */ extern void OPO$GenVCVTF32F64(int32_t cond, int32_t Sd, int32_t Dm);
/* public */ extern void OPO$GenVCVTMS32F32(int32_t cond, int32_t Sd, int32_t Sm);
/* public */ extern void OPO$GenVCVTMS32F64(int32_t cond, int32_t Sd, int32_t Dm);
/* public */ extern void OPO$GenVCVTS32F32(int32_t cond, int32_t Sd, int32_t Sm);
/* public */ extern void OPO$GenVCVTS32F64(int32_t cond, int32_t Sd, int32_t Dm);
/* public */ extern void OPO$GenVMOVF(int32_t cond, int32_t single, int32_t Vd, int32_t Vm);
/* public */ extern void OPO$GenVPUSHS(int32_t cond, int32_t Sd, int32_t count);
/* public */ extern void OPO$GenVPUSHD(int32_t cond, int32_t Dd, int32_t count);
/* public */ extern void OPO$GenVPOPS(int32_t cond, int32_t Sd, int32_t count);
/* public */ extern void OPO$GenVPOPD(int32_t cond, int32_t Dd, int32_t count);
/* public */ extern void OPO$GenVSTMDBS(int32_t cond, int32_t Rn, int32_t Sd);
/* public */ extern void OPO$GenVSTMDBD(int32_t cond, int32_t Rn, int32_t Dd);
/* public */ extern void OPO$GenVLDMIAS(int32_t cond, int32_t Rn, int32_t Sd);
/* public */ extern void OPO$GenVLDMIAD(int32_t cond, int32_t Rn, int32_t Dd);
/* public */ extern void OPO$GenDMBISH();
/* public */ extern void OPO$GenSXTB(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenSXTH(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenUXTB(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenUXTH(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenCLZ(int32_t cond, int32_t Rd, int32_t Rm);
/* public */ extern void OPO$GenNOP(int32_t cond);
// no typedef for open array OPO$_$2 (uint8_t*)
/* public */ extern void OPO$InlineCode(MIC$AP asmCode, int16_t parSize);
extern void OPO$BEGIN$();
extern void OPO$init$(void);

#endif // __OPO_INCLUDED__