#ifndef __OPA_INCLUDED__
#define __OPA_INCLUDED__

// OPA.h
// this file was generated by o2c  on Sat May 16 12:21:55 2026

#include <stdint.h>
#include "OPM.h"
#include "OPS.h"
#include "OPT.h"
#include "OPB.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPA$none (-1)
#define OPA$RV32IMAF 0
#define OPA$Nassembler 29
#define OPA$Ncode 30
#define OPA$Nfixup 31
#define OPA$StLabel 0
#define OPA$StFwdLabel 1
#define OPA$StConst 3
#define OPA$StType 4
#define OPA$StVar 5
#define OPA$StVarPar 6
#define OPA$StGlobal 7
#define OPA$StMod 11
#define OPA$RegMode 8
#define OPA$FRegMode 16
#define OPA$ImmMode 32
#define OPA$MemMode 40
#define OPA$LabelMode 48
#define OPA$FwdLabelMode 49
#define OPA$TAB 9
#define OPA$CR 13
#define OPA$LF 10
#define OPA$SPACE 32
#define OPA$ScUndef 0
#define OPA$ScIdent 1
#define OPA$ScSemicolon 2
#define OPA$ScAt 3
#define OPA$ScNumber 4
#define OPA$ScComma 5
#define OPA$ScLBrak 6
#define OPA$ScRBrak 7
#define OPA$ScCR 8
#define OPA$ScMult 9
#define OPA$ScEnd 10
#define OPA$ScLabel 11
#define OPA$ScColon 12
#define OPA$ScPlus 13
#define OPA$ScMinus 14
#define OPA$ScDiv 15
#define OPA$ScLPar 16
#define OPA$ScRPar 17
#define OPA$ScString 18
#define OPA$ScPoint 19
#define OPA$ScLBrace 20
#define OPA$ScRBrace 21
#define OPA$ScHash 22
#define OPA$ScExcl 23
#define OPA$NameLen 32
#define OPA$MaxStrLen 256
#define OPA$MnemoLen 12
#define OPA$MaxInstr 256
#define OPA$InstrHashSize 512
#define OPA$CatRType 0
#define OPA$CatIType 1
#define OPA$CatSType 2
#define OPA$CatBType 3
#define OPA$CatUType 4
#define OPA$CatJType 5
#define OPA$CatJALR 6
#define OPA$CatLoad 7
#define OPA$CatStore 8
#define OPA$CatFLoad 9
#define OPA$CatFStore 10
#define OPA$CatFR3 11
#define OPA$CatFR2 12
#define OPA$CatFCmp 13
#define OPA$CatFCvtF2I 14
#define OPA$CatFCvtI2F 15
#define OPA$CatFMvF2X 16
#define OPA$CatFMvX2F 17
#define OPA$CatSys 18
#define OPA$CatData 19
#define OPA$CatPseudo 20
#define OPA$CatShiftI 21
#define OPA$opLUI 55
#define OPA$opAUIPC 23
#define OPA$opJAL 111
#define OPA$opJALR 103
#define OPA$opBRANCH 99
#define OPA$opLOAD 3
#define OPA$opSTORE 35
#define OPA$opOPIMM 19
#define OPA$opOP 51
#define OPA$opFLOAT 7
#define OPA$opFSTORE 39
#define OPA$opFOP 83
#define OPA$opSYSTEM 115
#define OPA$opFENCE 15
#define OPA$psNOP 0
#define OPA$psMV 1
#define OPA$psLI 2
#define OPA$psRET 3
#define OPA$psNEG 4
#define OPA$psNOT 5
#define OPA$psSEQZ 6
#define OPA$psSNEZ 7
#define OPA$psJ 8
#define OPA$psCALL 9
typedef OPS$Name OPA$Name;
typedef struct OPA$Mnemo { uint8_t $[12]; } OPA$Mnemo;
typedef struct OPA$ObjDesc* OPA$Object;
typedef struct OPA$FixPntDesc* OPA$FixPnt;
typedef struct OPA$InstrDesc {
    struct OPA$InstrDesc$Class$* class$;
    OPA$Mnemo name;
    int8_t cat;
    int32_t op;
    int32_t flags;
} OPA$InstrDesc;
void OPA$InstrDesc$init$(OPA$InstrDesc* obj, unsigned int n);
struct OPA$InstrDesc$Class$ {
    void* super$;
};
extern struct OPA$InstrDesc$Class$ OPA$InstrDesc$class$;
typedef struct OPA$Operand {
    struct OPA$Operand$Class$* class$;
    int32_t mode;
    int16_t reg;
    int32_t imm;
    int32_t disp;
    int16_t base;
    OPA$Object obj;
} OPA$Operand;
void OPA$Operand$init$(OPA$Operand* obj, unsigned int n);
struct OPA$Operand$Class$ {
    void* super$;
};
extern struct OPA$Operand$Class$ OPA$Operand$class$;
typedef struct OPA$ObjDesc {
    struct OPA$ObjDesc$Class$* class$;
    int32_t typ;
    int32_t val;
    int32_t size;
    OPA$Name name;
    OPA$Object left;
    OPA$Object right;
    OPA$Object next;
    OPA$FixPnt fix;
    OPT$Object obj;
} OPA$ObjDesc;
void OPA$ObjDesc$init$(OPA$ObjDesc* obj, unsigned int n);
struct OPA$ObjDesc$Class$ {
    void* super$;
};
extern struct OPA$ObjDesc$Class$ OPA$ObjDesc$class$;
typedef struct OPA$FixPntDesc {
    struct OPA$FixPntDesc$Class$* class$;
    int32_t pc;
    OPT$Node node;
    int32_t pos;
    OPA$FixPnt next;
} OPA$FixPntDesc;
void OPA$FixPntDesc$init$(OPA$FixPntDesc* obj, unsigned int n);
struct OPA$FixPntDesc$Class$ {
    void* super$;
};
extern struct OPA$FixPntDesc$Class$ OPA$FixPntDesc$class$;
extern OPA$Object OPA$root;
typedef struct OPA$_$0 { OPA$InstrDesc $[256]; } OPA$_$0;
void OPA$_$0$init$(OPA$_$0* obj, unsigned int n);
extern OPA$_$0 OPA$InstrTab;
typedef struct OPA$_$1 { int16_t $[512]; } OPA$_$1;
extern OPA$_$1 OPA$InstrHash;
extern int16_t OPA$nofInstr;
typedef struct OPA$_$2 { int8_t $[17]; } OPA$_$2;
extern OPA$_$2 OPA$SizeTab;
extern uint8_t OPA$export;
extern uint8_t OPA$inline_;
extern uint8_t OPA$FirstTime;
extern int32_t OPA$Target;
extern int32_t OPA$pc;
extern int32_t OPA$sym;
extern OPA$Name OPA$ident;
extern int32_t OPA$val;
typedef struct OPA$_$3 { uint8_t $[256]; } OPA$_$3;
extern OPA$_$3 OPA$str;
extern int32_t OPA$errpos;
extern OPT$Node OPA$first;
extern OPT$Node OPA$last;
extern OPT$Node OPA$fixlist;
extern int32_t OPA$AND(int32_t a, int32_t b);
extern int32_t OPA$ORL(int32_t a, int32_t b);
// no typedef for open array OPA$_$4 (uint8_t*)
extern void OPA$insert(MIC$AP name, OPA$Object* obj);
extern OPA$Object OPA$ConvertObj(OPT$Object ob);
extern void OPA$find(MIC$AP name, OPA$Object* obj);
// no typedef for open array OPA$_$5 (uint8_t*)
extern int32_t OPA$HashInstr(MIC$AP name);
// no typedef for open array OPA$_$6 (uint8_t*)
extern void OPA$AddInstr(MIC$AP name, int8_t cat, int32_t op, int32_t flags);
// no typedef for open array OPA$_$7 (uint8_t*)
extern void OPA$FindInstruction(MIC$AP name, int32_t* inx);
extern void OPA$BuildInstrTable();
extern void OPA$skipBlanks();
extern void OPA$GetIdent(MIC$AP name);
extern void OPA$Get(int32_t* sym);
extern void OPA$Check(int32_t s);
extern void OPA$Expression(int32_t* x);
extern uint8_t OPA$ParseRegister(MIC$AP name, int16_t* reg, int32_t* mode);
extern void OPA$GetOperand(OPA$Operand* o);
extern void OPA$GetMemOperand(OPA$Operand* o);
extern void OPA$CheckLabels();
extern void OPA$InsertFix(OPA$Object* obj, int32_t pc);
extern void OPA$FixDisp(OPA$FixPnt* fix);
extern void OPA$NewNode();
extern void OPA$PutByte(int32_t b);
extern void OPA$PutWord(int32_t w);
extern void OPA$EncRType(int32_t funct7, int32_t rs2, int32_t rs1, int32_t funct3, int32_t rd, int32_t opcode);
extern void OPA$EncIType(int32_t imm12, int32_t rs1, int32_t funct3, int32_t rd, int32_t opcode);
extern void OPA$EncSType(int32_t imm12, int32_t rs2, int32_t rs1, int32_t funct3, int32_t opcode);
extern void OPA$EncBType(int32_t imm13, int32_t rs2, int32_t rs1, int32_t funct3, int32_t opcode);
extern void OPA$EncUType(int32_t imm20, int32_t rd, int32_t opcode);
extern void OPA$EncJType(int32_t imm21, int32_t rd, int32_t opcode);
extern void OPA$LoadImm32(int32_t rd, int32_t imm);
extern void OPA$ParseInstruction();
typedef struct OPA$_$8 { OPA$Operand $[4]; } OPA$_$8;
void OPA$_$8$init$(OPA$_$8* obj, unsigned int n);
extern void OPA$ParseLabel();
extern void OPA$Init();
extern void OPA$Close();
extern void OPA$BodyInit();
/* public */ extern void OPA$Assemble(OPT$Node* x, uint8_t exported, uint8_t inlined);
extern void OPA$BEGIN$();
extern void OPA$init$(void);

#endif // __OPA_INCLUDED__