#ifndef __OPO_INCLUDED__
#define __OPO_INCLUDED__

// OPO.h
// this file was generated by o2c  on Sat May 16 12:21:55 2026

#include <stdint.h>
#include "OPT.h"
#include "OPM.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPO$Reg 15
#define OPO$Abs 16
#define OPO$RegRel 17
#define OPO$Coc 18
#define OPO$noScale 0
#define OPO$Scale1 0
#define OPO$Scale2 1
#define OPO$Scale4 2
#define OPO$Scale8 3
#define OPO$RegReg 0
#define OPO$RegMem 1
#define OPO$MemReg 2
#define OPO$ImmReg 3
#define OPO$ImmMem 4
#define OPO$Regs 0
#define OPO$Mem 2
#define OPO$Imme 3
#define OPO$CodeLength 65000
#define OPO$MaxConstLength (64 * 1024)
#define OPO$X0 0
#define OPO$X1 1
#define OPO$RA 1
#define OPO$X2 2
#define OPO$SP 2
#define OPO$X3 3
#define OPO$GP 3
#define OPO$X4 4
#define OPO$TP 4
#define OPO$X5 5
#define OPO$T0 5
#define OPO$X6 6
#define OPO$T1 6
#define OPO$X7 7
#define OPO$T2 7
#define OPO$X8 8
#define OPO$S0 8
#define OPO$FP 8
#define OPO$X9 9
#define OPO$S1 9
#define OPO$X10 10
#define OPO$A0 10
#define OPO$X11 11
#define OPO$A1 11
#define OPO$X12 12
#define OPO$A2 12
#define OPO$X13 13
#define OPO$A3 13
#define OPO$X14 14
#define OPO$A4 14
#define OPO$X15 15
#define OPO$A5 15
#define OPO$X16 16
#define OPO$A6 16
#define OPO$X17 17
#define OPO$A7 17
#define OPO$X18 18
#define OPO$S2 18
#define OPO$X19 19
#define OPO$S3 19
#define OPO$X20 20
#define OPO$S4 20
#define OPO$X21 21
#define OPO$S5 21
#define OPO$X22 22
#define OPO$S6 22
#define OPO$X23 23
#define OPO$S7 23
#define OPO$X24 24
#define OPO$S8 24
#define OPO$X25 25
#define OPO$S9 25
#define OPO$X26 26
#define OPO$S10 26
#define OPO$X27 27
#define OPO$S11 27
#define OPO$X28 28
#define OPO$T3 28
#define OPO$X29 29
#define OPO$T4 29
#define OPO$X30 30
#define OPO$T5 30
#define OPO$X31 31
#define OPO$T6 31
#define OPO$Bit8 1
#define OPO$Bit16 2
#define OPO$Bit32 0
#define OPO$Bit64 5
#define OPO$noDisp 0
#define OPO$none (-1)
#define OPO$noBase (-1)
#define OPO$noInx (-1)
#define OPO$noImm 0
#define OPO$BUG 42
#define OPO$opLUI 55
#define OPO$opAUIPC 23
#define OPO$opJAL 111
#define OPO$opJALR 103
#define OPO$opBRANCH 99
#define OPO$opLOAD 3
#define OPO$opSTORE 35
#define OPO$opOPIMM 19
#define OPO$opOP 51
#define OPO$opFLOAT 7
#define OPO$opFSTORE 39
#define OPO$opFMADD 67
#define OPO$opFOP 83
#define OPO$opSYSTEM 115
#define OPO$opFENCE 15
#define OPO$opAMO 47
#define OPO$fBEQ 0
#define OPO$fBNE 1
#define OPO$fBLT 4
#define OPO$fBGE 5
#define OPO$fBLTU 6
#define OPO$fBGEU 7
#define OPO$fLB 0
#define OPO$fLH 1
#define OPO$fLW 2
#define OPO$fLBU 4
#define OPO$fLHU 5
#define OPO$fSB 0
#define OPO$fSH 1
#define OPO$fSW 2
#define OPO$fADD 0
#define OPO$fSLL 1
#define OPO$fSLT 2
#define OPO$fSLTU 3
#define OPO$fXOR 4
#define OPO$fSRL 5
#define OPO$fOR 6
#define OPO$fAND 7
#define OPO$f7ZERO 0
#define OPO$f7SUB 32
#define OPO$f7MUL 1
#define OPO$fMUL 0
#define OPO$fMULH 1
#define OPO$fMULHSU 2
#define OPO$fMULHU 3
#define OPO$fDIV 4
#define OPO$fDIVU 5
#define OPO$fREM 6
#define OPO$fREMU 7
#define OPO$f7FADDS 0
#define OPO$f7FSUBS 4
#define OPO$f7FMULS 8
#define OPO$f7FDIVS 12
#define OPO$f7FSQRTS 44
#define OPO$f7FSGN 16
#define OPO$f7FMINMAX 20
#define OPO$f7FCVTWS 96
#define OPO$f7FMVXW 112
#define OPO$f7FCMPS 80
#define OPO$f7FCVTSW 104
#define OPO$f7FMVWX 120
#define OPO$rmRNE 0
#define OPO$rmRTZ 1
#define OPO$rmRDN 2
#define OPO$rmRUP 3
#define OPO$rmRMM 4
#define OPO$rmDYN 7
#define OPO$ccEQ 0
#define OPO$ccNE 1
#define OPO$ccLT 2
#define OPO$ccGE 3
#define OPO$ccGT 4
#define OPO$ccLE 5
#define OPO$ccHI 6
#define OPO$ccHS 7
#define OPO$ccLO 8
#define OPO$ccLS 9
#define OPO$ccCS 10
#define OPO$ccCC 11
#define OPO$ccAL 255
/* public */ // no typedef for pointer to array OPO$ConstArray (using MIC$DA instead)
// no typedef for open array OPO$_$0 (uint8_t*)
/* public */ extern int32_t OPO$pc;
/* public */ extern int32_t OPO$dsize;
/* public */ extern int32_t OPO$csize;
/* public */ extern int8_t OPO$lastImmSize;
/* public */ extern uint8_t* OPO$constant;
typedef struct OPO$_$1 { uint8_t $[65000]; } OPO$_$1;
/* public */ extern OPO$_$1 OPO$code;
/* public */ extern uint8_t OPO$CodeErr;
/* public */ extern void OPO$PutByte(int32_t b);
/* public */ extern void OPO$PutWord(int32_t w);
/* public */ extern void OPO$PutWordAt(int32_t pos, int32_t w);
/* public */ extern void OPO$GetWord(int32_t pos, int32_t* w);
/* public */ extern void OPO$PutByteAt(int32_t pos, int16_t b);
/* public */ extern void OPO$PutDWord(int32_t w);
/* public */ extern void OPO$PutDWordAt(int32_t pos, int32_t w);
/* public */ extern void OPO$GetDWord(int32_t pos, int32_t* w);
/* public */ extern void OPO$PutConsDWord(int32_t pos, int32_t val);
/* public */ extern void OPO$GetConsDWord(int32_t pos, int32_t* val);
/* public */ extern void OPO$GenRType(int32_t opcode, int32_t rd, int32_t funct3, int32_t rs1, int32_t rs2, int32_t funct7);
/* public */ extern void OPO$GenIType(int32_t opcode, int32_t rd, int32_t funct3, int32_t rs1, int32_t imm12);
/* public */ extern void OPO$GenSType(int32_t opcode, int32_t funct3, int32_t rs1, int32_t rs2, int32_t imm12);
/* public */ extern void OPO$GenBType(int32_t opcode, int32_t funct3, int32_t rs1, int32_t rs2, int32_t imm13);
/* public */ extern void OPO$GenUType(int32_t opcode, int32_t rd, int32_t imm20);
/* public */ extern void OPO$GenJType(int32_t opcode, int32_t rd, int32_t imm21);
/* public */ extern void OPO$GenADD(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSUB(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenAND(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenOR(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenXOR(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSLL(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSRL(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSRA(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSLT(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenSLTU(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenADDI(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenANDI(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenORI(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenXORI(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenSLTI(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenSLTIU(int32_t rd, int32_t rs1, int32_t imm);
/* public */ extern void OPO$GenSLLI(int32_t rd, int32_t rs1, int32_t shamt);
/* public */ extern void OPO$GenSRLI(int32_t rd, int32_t rs1, int32_t shamt);
/* public */ extern void OPO$GenSRAI(int32_t rd, int32_t rs1, int32_t shamt);
/* public */ extern void OPO$GenLUI(int32_t rd, int32_t imm20);
/* public */ extern void OPO$GenAUIPC(int32_t rd, int32_t imm20);
/* public */ extern void OPO$GenJAL(int32_t rd, int32_t offset);
/* public */ extern void OPO$GenJALR(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenBEQ(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenBNE(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenBLT(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenBGE(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenBLTU(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenBGEU(int32_t rs1, int32_t rs2, int32_t offset);
/* public */ extern void OPO$GenLW(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenLH(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenLHU(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenLB(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenLBU(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenSW(int32_t rs2, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenSH(int32_t rs2, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenSB(int32_t rs2, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenMUL(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenMULH(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenDIV(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenDIVU(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenREM(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenREMU(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFLW(int32_t rd, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenFSW(int32_t rs2, int32_t rs1, int32_t offset);
/* public */ extern void OPO$GenFADDS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFSUBS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFMULS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFDIVS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFSGNJS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFSGNJNS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFSGNJXS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFEQS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFLTS(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFLES(int32_t rd, int32_t rs1, int32_t rs2);
/* public */ extern void OPO$GenFCVTWS(int32_t rd, int32_t rs1, int32_t rm);
/* public */ extern void OPO$GenFCVTSW(int32_t rd, int32_t rs1, int32_t rm);
/* public */ extern void OPO$GenFMVXW(int32_t rd, int32_t rs1);
/* public */ extern void OPO$GenFMVWX(int32_t rd, int32_t rs1);
/* public */ extern void OPO$GenECALL();
/* public */ extern void OPO$GenEBREAK();
/* public */ extern void OPO$GenFENCE();
/* public */ extern void OPO$GenWFI();
/* public */ extern void OPO$GenNOP();
/* public */ extern void OPO$GenMOV(int32_t rd, int32_t rs);
/* public */ extern void OPO$LoadImm32(int32_t rd, int32_t imm);
/* public */ extern void OPO$EmitAbsLoad(int32_t rd, int32_t disp, int32_t* slotOffset);
/* public */ extern void OPO$EmitCondBranch(int32_t cc, int32_t offset);
/* public */ extern int32_t OPO$InvertCC(int32_t cc);
/* public */ extern void OPO$EmitCondBranchAt(int32_t pos, int32_t cc, int32_t offset);
/* public */ extern void OPO$ExtractJImm(int32_t pos, int32_t* imm);
/* public */ extern void OPO$EmitJALAt(int32_t pos, int32_t rd, int32_t offset);
/* public */ extern void OPO$EmitChainJAL(int32_t rd, int32_t chainVal);
/* public */ extern void OPO$EmitChainJALAt(int32_t pos, int32_t rd, int32_t chainVal);
/* public */ extern void OPO$ExtractChainVal(int32_t pos, int32_t* val);
/* public */ extern void OPO$EmitNOPAt(int32_t pos);
// no typedef for open array OPO$_$2 (uint8_t*)
/* public */ extern void OPO$InlineCode(MIC$AP asmCode, int16_t parSize);
extern void OPO$BEGIN$();
extern void OPO$init$(void);

#endif // __OPO_INCLUDED__