// OPTR.c
// this file was generated by o2c  on Sat May 16 12:21:55 2026

#include "OPTR.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

/* public */ int8_t OPTR$Target = 0;

/* public */ int32_t OPTR$MinRegNr = 0;

/* public */ int32_t OPTR$MaxRegNr = 0;

/* public */ uint8_t OPTR$ValidRegType(int32_t regNr, int8_t typeForm) {
    if( ((1 <= regNr) && (regNr <= 31)) ) { 
        return (((1 << typeForm) & (0 | (uint32_t)((((uint64_t)1 << (7 - 0 + 1)) - 1) << 0) | 1u << 9 | 1u << 11 | 1u << 13 | 1u << 14)) != 0);
    } else { 
        return 0;
    }
}

/* public */ int32_t OPTR$RegIndex(int32_t regNr) {
    return regNr;
}

/* public */ uint8_t OPTR$IsLegacyReg(int32_t regNr) {
    return ((1 <= regNr) && (regNr <= 31));
}

/* public */ void OPTR$EnterRegisters(OPTR$EnterConstProc enter) {
    enter((MIC$AP){strlen((const uint8_t[]){122,101,114,111,0}) + 1,(const uint8_t[]){122,101,114,111,0}}, 0);
    enter((MIC$AP){strlen((const uint8_t[]){114,97,0}) + 1,(const uint8_t[]){114,97,0}}, 1);
    enter((MIC$AP){strlen((const uint8_t[]){115,112,0}) + 1,(const uint8_t[]){115,112,0}}, 2);
    enter((MIC$AP){strlen((const uint8_t[]){103,112,0}) + 1,(const uint8_t[]){103,112,0}}, 3);
    enter((MIC$AP){strlen((const uint8_t[]){116,112,0}) + 1,(const uint8_t[]){116,112,0}}, 4);
    enter((MIC$AP){strlen((const uint8_t[]){116,48,0}) + 1,(const uint8_t[]){116,48,0}}, 5);
    enter((MIC$AP){strlen((const uint8_t[]){116,49,0}) + 1,(const uint8_t[]){116,49,0}}, 6);
    enter((MIC$AP){strlen((const uint8_t[]){116,50,0}) + 1,(const uint8_t[]){116,50,0}}, 7);
    enter((MIC$AP){strlen((const uint8_t[]){115,48,0}) + 1,(const uint8_t[]){115,48,0}}, 8);
    enter((MIC$AP){strlen((const uint8_t[]){70,80,0}) + 1,(const uint8_t[]){70,80,0}}, 8);
    enter((MIC$AP){strlen((const uint8_t[]){115,49,0}) + 1,(const uint8_t[]){115,49,0}}, 9);
    enter((MIC$AP){strlen((const uint8_t[]){97,48,0}) + 1,(const uint8_t[]){97,48,0}}, 10);
    enter((MIC$AP){strlen((const uint8_t[]){97,49,0}) + 1,(const uint8_t[]){97,49,0}}, 11);
    enter((MIC$AP){strlen((const uint8_t[]){97,50,0}) + 1,(const uint8_t[]){97,50,0}}, 12);
    enter((MIC$AP){strlen((const uint8_t[]){97,51,0}) + 1,(const uint8_t[]){97,51,0}}, 13);
    enter((MIC$AP){strlen((const uint8_t[]){97,52,0}) + 1,(const uint8_t[]){97,52,0}}, 14);
    enter((MIC$AP){strlen((const uint8_t[]){97,53,0}) + 1,(const uint8_t[]){97,53,0}}, 15);
    enter((MIC$AP){strlen((const uint8_t[]){97,54,0}) + 1,(const uint8_t[]){97,54,0}}, 16);
    enter((MIC$AP){strlen((const uint8_t[]){97,55,0}) + 1,(const uint8_t[]){97,55,0}}, 17);
    enter((MIC$AP){strlen((const uint8_t[]){115,50,0}) + 1,(const uint8_t[]){115,50,0}}, 18);
    enter((MIC$AP){strlen((const uint8_t[]){115,51,0}) + 1,(const uint8_t[]){115,51,0}}, 19);
    enter((MIC$AP){strlen((const uint8_t[]){115,52,0}) + 1,(const uint8_t[]){115,52,0}}, 20);
    enter((MIC$AP){strlen((const uint8_t[]){115,53,0}) + 1,(const uint8_t[]){115,53,0}}, 21);
    enter((MIC$AP){strlen((const uint8_t[]){115,54,0}) + 1,(const uint8_t[]){115,54,0}}, 22);
    enter((MIC$AP){strlen((const uint8_t[]){115,55,0}) + 1,(const uint8_t[]){115,55,0}}, 23);
    enter((MIC$AP){strlen((const uint8_t[]){115,56,0}) + 1,(const uint8_t[]){115,56,0}}, 24);
    enter((MIC$AP){strlen((const uint8_t[]){115,57,0}) + 1,(const uint8_t[]){115,57,0}}, 25);
    enter((MIC$AP){strlen((const uint8_t[]){115,49,48,0}) + 1,(const uint8_t[]){115,49,48,0}}, 26);
    enter((MIC$AP){strlen((const uint8_t[]){115,49,49,0}) + 1,(const uint8_t[]){115,49,49,0}}, 27);
    enter((MIC$AP){strlen((const uint8_t[]){116,51,0}) + 1,(const uint8_t[]){116,51,0}}, 28);
    enter((MIC$AP){strlen((const uint8_t[]){116,52,0}) + 1,(const uint8_t[]){116,52,0}}, 29);
    enter((MIC$AP){strlen((const uint8_t[]){116,53,0}) + 1,(const uint8_t[]){116,53,0}}, 30);
    enter((MIC$AP){strlen((const uint8_t[]){116,54,0}) + 1,(const uint8_t[]){116,54,0}}, 31);
    enter((MIC$AP){strlen((const uint8_t[]){120,48,0}) + 1,(const uint8_t[]){120,48,0}}, 0);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,0}) + 1,(const uint8_t[]){120,49,0}}, 1);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,0}) + 1,(const uint8_t[]){120,50,0}}, 2);
    enter((MIC$AP){strlen((const uint8_t[]){120,51,0}) + 1,(const uint8_t[]){120,51,0}}, 3);
    enter((MIC$AP){strlen((const uint8_t[]){120,52,0}) + 1,(const uint8_t[]){120,52,0}}, 4);
    enter((MIC$AP){strlen((const uint8_t[]){120,53,0}) + 1,(const uint8_t[]){120,53,0}}, 5);
    enter((MIC$AP){strlen((const uint8_t[]){120,54,0}) + 1,(const uint8_t[]){120,54,0}}, 6);
    enter((MIC$AP){strlen((const uint8_t[]){120,55,0}) + 1,(const uint8_t[]){120,55,0}}, 7);
    enter((MIC$AP){strlen((const uint8_t[]){120,56,0}) + 1,(const uint8_t[]){120,56,0}}, 8);
    enter((MIC$AP){strlen((const uint8_t[]){120,57,0}) + 1,(const uint8_t[]){120,57,0}}, 9);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,48,0}) + 1,(const uint8_t[]){120,49,48,0}}, 10);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,49,0}) + 1,(const uint8_t[]){120,49,49,0}}, 11);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,50,0}) + 1,(const uint8_t[]){120,49,50,0}}, 12);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,51,0}) + 1,(const uint8_t[]){120,49,51,0}}, 13);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,52,0}) + 1,(const uint8_t[]){120,49,52,0}}, 14);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,53,0}) + 1,(const uint8_t[]){120,49,53,0}}, 15);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,54,0}) + 1,(const uint8_t[]){120,49,54,0}}, 16);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,55,0}) + 1,(const uint8_t[]){120,49,55,0}}, 17);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,56,0}) + 1,(const uint8_t[]){120,49,56,0}}, 18);
    enter((MIC$AP){strlen((const uint8_t[]){120,49,57,0}) + 1,(const uint8_t[]){120,49,57,0}}, 19);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,48,0}) + 1,(const uint8_t[]){120,50,48,0}}, 20);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,49,0}) + 1,(const uint8_t[]){120,50,49,0}}, 21);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,50,0}) + 1,(const uint8_t[]){120,50,50,0}}, 22);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,51,0}) + 1,(const uint8_t[]){120,50,51,0}}, 23);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,52,0}) + 1,(const uint8_t[]){120,50,52,0}}, 24);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,53,0}) + 1,(const uint8_t[]){120,50,53,0}}, 25);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,54,0}) + 1,(const uint8_t[]){120,50,54,0}}, 26);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,55,0}) + 1,(const uint8_t[]){120,50,55,0}}, 27);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,56,0}) + 1,(const uint8_t[]){120,50,56,0}}, 28);
    enter((MIC$AP){strlen((const uint8_t[]){120,50,57,0}) + 1,(const uint8_t[]){120,50,57,0}}, 29);
    enter((MIC$AP){strlen((const uint8_t[]){120,51,48,0}) + 1,(const uint8_t[]){120,51,48,0}}, 30);
    enter((MIC$AP){strlen((const uint8_t[]){120,51,49,0}) + 1,(const uint8_t[]){120,51,49,0}}, 31);
    enter((MIC$AP){strlen((const uint8_t[]){83,80,0}) + 1,(const uint8_t[]){83,80,0}}, 2);
    enter((MIC$AP){strlen((const uint8_t[]){82,65,0}) + 1,(const uint8_t[]){82,65,0}}, 1);
}

void OPTR$BEGIN$() {
    OPTR$Target = 2;
    OPTR$MinRegNr = 0;
    OPTR$MaxRegNr = 31;
}

static int OPTR$initialized = 0;
void OPTR$init$(void) {
    if( OPTR$initialized ) return;
    OPTR$initialized = 1;
    OPM$init$();
    OPTR$BEGIN$();
}

