// OPTR.c
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:41:45 2026

#include "OPTR.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

/* public */ uint8_t OPTR$RequireAlignment = 0;

/* public */ uint8_t OPTR$LittleEndian = 0;

/* public */ OPTR$_$1 OPTR$Target = {0};

/* public */ int32_t OPTR$MinRegNr = 0;

/* public */ int32_t OPTR$MaxRegNr = 0;

/* public */ uint8_t OPTR$ValidRegType(int32_t regNr, int8_t typeForm) {
    if( ((0 <= regNr) && (regNr < 8)) ) { 
        return (((1 << typeForm) & (0 | (uint32_t)((((uint64_t)1 << (7 - 0 + 1)) - 1) << 0) | 1u << 9 | 1u << 11 | 1u << 13 | 1u << 14)) != 0);
    } else if( ((8 <= regNr) && (regNr < 16)) ) { 
        return (((1 << typeForm) & (0 | 1u << 6 | 1u << 7 | 1u << 9 | 1u << 13 | 1u << 14)) != 0);
    } else if( ((16 <= regNr) && (regNr < 24)) ) { 
        return (((1 << typeForm) & (0 | 1u << 5)) != 0);
    } else if( ((24 <= regNr) && (regNr < 32)) ) { 
        return (((1 << typeForm) & (0 | 1u << 1 | 1u << 2 | 1u << 3 | 1u << 4)) != 0);
    } else { 
        return 0;
    }
}

/* public */ int32_t OPTR$RegIndex(int32_t regNr) {
    return OBERON$MOD(regNr, 8);
}

/* public */ uint8_t OPTR$IsLegacyReg(int32_t regNr) {
    return ((0 <= regNr) && (regNr < 8));
}

/* public */ void OPTR$EnterRegisters(OPTR$EnterConstProc enter) {
    enter((MIC$AP){strlen((const uint8_t[]){69,65,88,0}) + 1,(const uint8_t[]){69,65,88,0}}, 8);
    enter((MIC$AP){strlen((const uint8_t[]){69,67,88,0}) + 1,(const uint8_t[]){69,67,88,0}}, 9);
    enter((MIC$AP){strlen((const uint8_t[]){69,68,88,0}) + 1,(const uint8_t[]){69,68,88,0}}, 10);
    enter((MIC$AP){strlen((const uint8_t[]){69,66,88,0}) + 1,(const uint8_t[]){69,66,88,0}}, 11);
    enter((MIC$AP){strlen((const uint8_t[]){69,83,80,0}) + 1,(const uint8_t[]){69,83,80,0}}, 12);
    enter((MIC$AP){strlen((const uint8_t[]){69,66,80,0}) + 1,(const uint8_t[]){69,66,80,0}}, 13);
    enter((MIC$AP){strlen((const uint8_t[]){69,83,73,0}) + 1,(const uint8_t[]){69,83,73,0}}, 14);
    enter((MIC$AP){strlen((const uint8_t[]){69,68,73,0}) + 1,(const uint8_t[]){69,68,73,0}}, 15);
    enter((MIC$AP){strlen((const uint8_t[]){65,88,0}) + 1,(const uint8_t[]){65,88,0}}, 16);
    enter((MIC$AP){strlen((const uint8_t[]){67,88,0}) + 1,(const uint8_t[]){67,88,0}}, 17);
    enter((MIC$AP){strlen((const uint8_t[]){68,88,0}) + 1,(const uint8_t[]){68,88,0}}, 18);
    enter((MIC$AP){strlen((const uint8_t[]){66,88,0}) + 1,(const uint8_t[]){66,88,0}}, 19);
    enter((MIC$AP){strlen((const uint8_t[]){83,80,0}) + 1,(const uint8_t[]){83,80,0}}, 20);
    enter((MIC$AP){strlen((const uint8_t[]){66,80,0}) + 1,(const uint8_t[]){66,80,0}}, 21);
    enter((MIC$AP){strlen((const uint8_t[]){83,73,0}) + 1,(const uint8_t[]){83,73,0}}, 22);
    enter((MIC$AP){strlen((const uint8_t[]){68,73,0}) + 1,(const uint8_t[]){68,73,0}}, 23);
    enter((MIC$AP){strlen((const uint8_t[]){65,76,0}) + 1,(const uint8_t[]){65,76,0}}, 24);
    enter((MIC$AP){strlen((const uint8_t[]){67,76,0}) + 1,(const uint8_t[]){67,76,0}}, 25);
    enter((MIC$AP){strlen((const uint8_t[]){68,76,0}) + 1,(const uint8_t[]){68,76,0}}, 26);
    enter((MIC$AP){strlen((const uint8_t[]){66,76,0}) + 1,(const uint8_t[]){66,76,0}}, 27);
    enter((MIC$AP){strlen((const uint8_t[]){65,72,0}) + 1,(const uint8_t[]){65,72,0}}, 28);
    enter((MIC$AP){strlen((const uint8_t[]){67,72,0}) + 1,(const uint8_t[]){67,72,0}}, 29);
    enter((MIC$AP){strlen((const uint8_t[]){68,72,0}) + 1,(const uint8_t[]){68,72,0}}, 30);
    enter((MIC$AP){strlen((const uint8_t[]){66,72,0}) + 1,(const uint8_t[]){66,72,0}}, 31);
}

void OPTR$BEGIN$() {
    OPTR$RequireAlignment = 0;
    OPTR$LittleEndian = 1;
    strcpy((char*)OPTR$Target.$, (const char*)(const uint8_t[]){105,51,56,54,0});
    OPTR$MinRegNr = 0;
    OPTR$MaxRegNr = 31;
}

static int OPTR$initialized = 0;
void OPTR$init$(void) {
    if( OPTR$initialized ) return;
    OPTR$initialized = 1;
    OPTR$BEGIN$();
}

