// Files.c
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include "Files.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void Files$_$0$init$(Files$_$0* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Files$_$0$class$;
    }
}

struct Files$_$0$Class$ Files$_$0$class$ = { 
    0,
};

void Files$Rider$init$(Files$Rider* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Files$Rider$class$;
    }
}

struct Files$Rider$Class$ Files$Rider$class$ = { 
    0,
};

/* public */ void Files$WriteLInt(Files$Rider* R, int32_t x) {
    Files$WriteBytes(&(*R), (MIC$AP){ sizeof(int32_t), &x}, 4);
}

/* public */ void Files$WriteInt(Files$Rider* R, int16_t x) {
    Files$Write(&(*R), (uint8_t)(x));
    Files$Write(&(*R), (uint8_t)(OBERON$DIV(x, 256)));
}

/* public */ void Files$WriteSet(Files$Rider* R, int32_t x) {
    Files$WriteBytes(&(*R), (MIC$AP){ sizeof(int32_t), &x}, 4);
}

/* public */ void Files$WriteReal(Files$Rider* R, float x) {
    Files$WriteBytes(&(*R), (MIC$AP){ sizeof(float), &x}, 4);
}

/* public */ void Files$WriteLReal(Files$Rider* R, double x) {
    Files$WriteBytes(&(*R), (MIC$AP){ sizeof(double), &x}, 8);
}

/* public */ void Files$WriteNum(Files$Rider* R, int32_t x) {
    while( ((x < (-64)) || (x > 63)) ) {
        Files$Write(&(*R), (uint8_t)((OBERON$MOD(x, 128) + 128)));
        x = OBERON$DIV(x, 128);
    }
    Files$Write(&(*R), (uint8_t)(OBERON$MOD(x, 128)));
}

/* public */ void Files$ReadInt(Files$Rider* R, int16_t* x) {
    int8_t x0;
    int8_t x1;
    Files$Read(&(*R), &x0);
    Files$Read(&(*R), &x1);
    (*x) = (((int16_t)(x1) * 256) + OBERON$MOD((int16_t)(x0), 256));
}

/* public */ void Files$ReadString(Files$Rider* R, MIC$AP x) {
    int16_t i;
    uint8_t ch;
    i = 0;
    while(1) {
        Files$Read(&(*R), &ch);
        ((uint8_t*)x.$)[i] = ch;
        i++;
        if( (ch == 0) ) { 
            goto __67;
        }
        if( (i == x.$1) ) { 
            ((uint8_t*)x.$)[(i - 1)] = 0;
            do {
                Files$Read(&(*R), &ch);
            } while( !(ch == 0) );
            goto __67;
        }
    }    __67:

}

/* public */ void Files$ReadReal(Files$Rider* R, float* x) {
    Files$ReadBytes(&(*R), (MIC$AP){ sizeof(float), &(*x)}, 4);
}

/* public */ void Files$ReadSet(Files$Rider* R, int32_t* x) {
    Files$ReadBytes(&(*R), (MIC$AP){ sizeof(int32_t), &(*x)}, 4);
}

/* public */ void Files$ReadLReal(Files$Rider* R, double* x) {
    Files$ReadBytes(&(*R), (MIC$AP){ sizeof(double), &(*x)}, 8);
}

static int Files$initialized = 0;
void Files$init$(void) {
    if( Files$initialized ) return;
    Files$initialized = 1;
}

