#ifndef __FONTS_INCLUDED__
#define __FONTS_INCLUDED__

// Fonts.h
// this file was generated by AoCodeNavigator 0.6.10 on So. Feb. 22 16:24:39 2026

#include <stdint.h>

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
/* public */ typedef struct Fonts$_$0* Fonts$Font;
typedef struct Fonts$_$0 {
    struct Fonts$_$0$Class$* class$;
} Fonts$_$0;
void Fonts$_$0$init$(Fonts$_$0* obj, unsigned int n);
struct Fonts$_$0$Class$ {
    void* super$;
};
extern struct Fonts$_$0$Class$ Fonts$_$0$class$;
extern void Fonts$init$(void);

#endif // __FONTS_INCLUDED__