#ifndef __OBERON_INCLUDED__
#define __OBERON_INCLUDED__

// Oberon.h
// this file was generated by AoCodeNavigator 0.6.10 on So. Feb. 22 22:43:43 2026

#include <stdint.h>
#include "Texts.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
/* public */ typedef struct Oberon$_$0* Oberon$ParList;
typedef struct Oberon$_$0 {
    struct Oberon$_$0$Class$* class$;
} Oberon$_$0;
void Oberon$_$0$init$(Oberon$_$0* obj, unsigned int n);
struct Oberon$_$0$Class$ {
    void* super$;
};
extern struct Oberon$_$0$Class$ Oberon$_$0$class$;
/* public */ extern Texts$Text Oberon$Log;
/* public */ extern Oberon$ParList Oberon$Par;
/* public */ extern void Oberon$Collect();
// no typedef for open array Oberon$_$1 (uint8_t*)
/* public */ extern void Oberon$Call(MIC$AP name, Oberon$ParList par, uint8_t new, int16_t* res);
extern void Oberon$init$(void);

#endif // __OBERON_INCLUDED__