// OP2.c
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:32:16 2026

#include "OP2.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void OP2$SignOn() {
    Out$String((MIC$AP){strlen((const uint8_t[]){79,98,101,114,111,110,32,80,111,114,116,97,98,108,101,32,67,111,109,112,105,108,101,114,32,47,32,110,119,44,32,114,99,44,32,110,109,44,32,116,107,44,32,112,114,107,32,47,32,0}) + 1,(const uint8_t[]){79,98,101,114,111,110,32,80,111,114,116,97,98,108,101,32,67,111,109,112,105,108,101,114,32,47,32,110,119,44,32,114,99,44,32,110,109,44,32,116,107,44,32,112,114,107,32,47,32,0}});
    Out$String((MIC$AP){8, OPTR$Target.$});
    Out$String((MIC$AP){strlen((const uint8_t[]){32,116,97,114,103,101,116,0}) + 1,(const uint8_t[]){32,116,97,114,103,101,116,0}});
    Out$Ln();
    Out$String((MIC$AP){strlen((const uint8_t[]){67,57,57,32,118,101,114,115,105,111,110,32,97,110,100,32,65,82,77,118,55,32,98,97,99,107,101,110,100,32,98,121,32,109,101,64,114,111,99,104,117,115,45,107,101,108,108,101,114,46,99,104,0}) + 1,(const uint8_t[]){67,57,57,32,118,101,114,115,105,111,110,32,97,110,100,32,65,82,77,118,55,32,98,97,99,107,101,110,100,32,98,121,32,109,101,64,114,111,99,104,117,115,45,107,101,108,108,101,114,46,99,104,0}});
    Out$Ln();
}

void OP2$ParseOptions(MIC$AP name, MIC$AP options, MIC$AP path, MIC$AP pref, MIC$AP extension, int32_t* codeOpt, int32_t* parserOpt) {
    int32_t i = 0;
    int32_t j = 0;
    int32_t k = 0;
    uint8_t ch = 0;
    (*codeOpt) = (0 | 1u << 0 | 1u << 3 | 1u << 5 | 1u << 20 | 1u << 6);
    (*parserOpt) = (0);
    i = 0;
    ((uint8_t*)path.$)[0] = 0;
    ((uint8_t*)pref.$)[0] = 0;
    strcpy((char*)extension.$, (const char*)(const uint8_t[]){46,77,111,100,0});
    while(1) {
        ch = ((uint8_t*)options.$)[i];
        i++;
        if( (ch == 0) ) { 
            goto __25;
        } else if( (ch == 120) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 0));
        } else if( (ch == 118) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 1));
        } else if( (ch == 116) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 3));
        } else if( (ch == 112) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 5));
        } else if( (ch == 97) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 6));
        } else if( (ch == 122) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 20));
        } else if( (ch == 113) ) { 
            (*codeOpt) = ((*codeOpt) ^ (0 | 1u << 22));
        } else if( (ch == 115) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 10));
        } else if( (ch == 83) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 8));
        } else if( (ch == 110) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 9));
        } else if( (ch == 101) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 11));
        } else if( (ch == 102) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 7));
        } else if( (ch == 119) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 12));
        } else if( (ch == 88) ) { 
            (*parserOpt) = ((*parserOpt) | (0 | 1u << 18));
        } else if( (ch == 50) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 19));
        } else if( (ch == 49) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 21));
        } else if( (ch == 84) ) { 
            (*parserOpt) = ((*parserOpt) ^ (0 | 1u << 24));
        } else if( (ch == 46) ) { 
            j = 0;
            while( ((ch != 0) && (ch != 32)) ) {
                ((uint8_t*)extension.$)[j] = ch;
                ch = ((uint8_t*)options.$)[i];
                j++;
                i++;
            }
            ((uint8_t*)extension.$)[j] = 0;
        } else if( (ch == 80) ) { 
            ch = ((uint8_t*)options.$)[i];
            i++;
            k = 0;
            while( ((ch != 0) && (ch != 32)) ) {
                ((uint8_t*)path.$)[k] = ch;
                k++;
                ch = ((uint8_t*)options.$)[i];
                i++;
            }
            ((uint8_t*)path.$)[k] = 0;
        } else if( (ch == 79) ) { 
            ch = ((uint8_t*)options.$)[i];
            i++;
            k = 0;
            while( ((ch != 0) && (ch != 32)) ) {
                ((uint8_t*)pref.$)[k] = ch;
                k++;
                ch = ((uint8_t*)options.$)[i];
                i++;
            }
            ((uint8_t*)pref.$)[k] = 0;
        }
    }    __25:

    if( (((1 << 18) & (*parserOpt)) != 0) ) { 
        i = (-1);
        do {
            i++;
            ((uint8_t*)pref.$)[i] = ((uint8_t*)name.$)[i];
        } while( !((((uint8_t*)name.$)[i] == 0) || (((uint8_t*)name.$)[i] == 46)) );
        if( (((uint8_t*)name.$)[i] != 46) ) { 
            i = 0;
        } else { 
            i++;
        }
        ((uint8_t*)pref.$)[i] = 0;
    }
}

void OP2$WriteMsg(Texts$Reader source) {
    int8_t sym = 0;
    Out$String((MIC$AP){strlen((const uint8_t[]){32,99,111,109,112,105,108,105,110,103,32,0}) + 1,(const uint8_t[]){32,99,111,109,112,105,108,105,110,103,32,0}});
    OPM$Init((0), (0), source, Oberon$Log);
    OPS$Get(&sym);
    if( (sym == 67) ) { 
        OPS$Get(&sym);
        if( (sym == 40) ) { 
            Out$String((MIC$AP){32, OPM$outputPath.$});
            Out$String((MIC$AP){32, OPM$outputPrefix.$});
            OPS$Get(&sym);
            Out$String((MIC$AP){32, OPS$name.$});
            while( (sym == 18) ) {
                Out$String((MIC$AP){strlen((const uint8_t[]){46,0}) + 1,(const uint8_t[]){46,0}});
                OPS$Get(&sym);
                if( (sym == 40) ) { 
                    Out$String((MIC$AP){32, OPS$name.$});
                    OPS$Get(&sym);
                }
            }
            Out$String((MIC$AP){8, OPM$extension.$});
        }
    }
}

void OP2$Module(Texts$Reader source, MIC$AP name, MIC$AP options, int32_t breakpc, uint8_t* error) {
    int32_t codeOpt = 0;
    int32_t parserOpt = 0;
    uint8_t extSF = 0;
    uint8_t newSF = 0;
    OPT$Node p = NULL;
    OPS$Name modName = {0};
    OP2$ParseOptions(name, options, (MIC$AP){32, OPM$outputPath.$}, (MIC$AP){32, OPM$outputPrefix.$}, (MIC$AP){8, OPM$extension.$}, &codeOpt, &parserOpt);
    OP2$WriteMsg(source);
    OPM$Init(codeOpt, parserOpt, source, Oberon$Log);
    OPS$ch = 32;
    OPB$typSize = OPV$TypSize;
    OPV$Init(breakpc);
    newSF = (((1 << 10) & parserOpt) != 0);
    extSF = (((1 << 11) & parserOpt) != 0);
    OPP$Module(&p, (MIC$AP){32, modName.$});
    if( OPM$noerr ) { 
        OPL$Init();
        OPM$errpos = 0;
        OPM$Begin((MIC$AP){32, modName.$});
        if( OPM$noerr ) { 
            OPT$Export((MIC$AP){32, modName.$}, &newSF, &extSF);
            OPV$AdrAndSize(OPT$topScope);
            if( newSF ) { 
                OPM$LogWStr((MIC$AP){strlen((const uint8_t[]){32,110,101,119,32,115,121,109,98,111,108,32,102,105,108,101,0}) + 1,(const uint8_t[]){32,110,101,119,32,115,121,109,98,111,108,32,102,105,108,101,0}});
            } else if( extSF ) { 
                OPM$LogWStr((MIC$AP){strlen((const uint8_t[]){32,101,120,116,101,110,100,101,100,32,115,121,109,98,111,108,32,102,105,108,101,0}) + 1,(const uint8_t[]){32,101,120,116,101,110,100,101,100,32,115,121,109,98,111,108,32,102,105,108,101,0}});
            }
            if( OPM$noerr ) { 
                OPM$errpos = 0;
                OPC$Init();
                OPV$Module(p);
                if( OPM$noerr ) { 
                    OPL$OutCode((MIC$AP){32, modName.$});
                    if( OPM$noerr ) { 
                        OPM$LogWStr((MIC$AP){strlen((const uint8_t[]){32,32,32,0}) + 1,(const uint8_t[]){32,32,32,0}});
                        OPM$LogWNum(OPO$pc, 1);
                    }
                }
            }
            OPL$Close();
        }
    }
    OPT$CloseScope();
    OPT$Close();
    OPM$LogWLn();
    (*error) = (!OPM$noerr);
    strcpy((char*)OPM$outputPath.$, (const char*)(const uint8_t[]){33,0});
    strcpy((char*)OPM$outputPrefix.$, (const char*)(const uint8_t[]){33,0});
}

/* public */ void OP2$CompileFile(MIC$AP name, MIC$AP opt, uint8_t* error) {
    Texts$Reader r = {0};
    int32_t pc = 0;
    if( Texts$OpenReader(&r, name) ) { 
        Out$String(name);
        OPS$Init();
        OP2$Module(r, name, opt, pc, &(*error));
    } else { 
        Out$String(name);
        Out$String((MIC$AP){strlen((const uint8_t[]){32,110,111,116,32,102,111,117,110,100,0}) + 1,(const uint8_t[]){32,110,111,116,32,102,111,117,110,100,0}});
        Out$Ln();
        (*error) = 1;
    }
}

void OP2$BEGIN$() {
    OP2$SignOn();
}

static int OP2$initialized = 0;
void OP2$init$(void) {
    if( OP2$initialized ) return;
    OP2$initialized = 1;
    OPP$init$();
    OPB$init$();
    OPV$init$();
    OPT$init$();
    OPS$init$();
    OPC$init$();
    OPL$init$();
    OPO$init$();
    OPM$init$();
    OPTR$init$();
    Texts$init$();
    Oberon$init$();
    OP2$BEGIN$();
}

