// OPA.c
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include "OPA.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void OPA$InstrDesc$init$(OPA$InstrDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$InstrDesc$class$;
    }
}

struct OPA$InstrDesc$Class$ OPA$InstrDesc$class$ = { 
    0,
};

void OPA$OpCode$init$(OPA$OpCode* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$OpCode$class$;
    }
}

struct OPA$OpCode$Class$ OPA$OpCode$class$ = { 
    0,
};

void OPA$Operand$init$(OPA$Operand* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$Operand$class$;
    }
}

struct OPA$Operand$Class$ OPA$Operand$class$ = { 
    0,
};

void OPA$ObjDesc$init$(OPA$ObjDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$ObjDesc$class$;
    }
}

struct OPA$ObjDesc$Class$ OPA$ObjDesc$class$ = { 
    0,
};

void OPA$FixPntDesc$init$(OPA$FixPntDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$FixPntDesc$class$;
    }
}

struct OPA$FixPntDesc$Class$ OPA$FixPntDesc$class$ = { 
    0,
};

OPA$Object OPA$root = NULL;

OPA$OpCode* OPA$OpTab = NULL;

int32_t OPA$OpTabLen;

OPA$InstrDesc* OPA$InstrTab = NULL;

int32_t OPA$InstrTabLen;

OPA$_$5 OPA$SizeTab;

void OPA$_$7$init$(OPA$_$7* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPA$_$7$class$;
    }
}

struct OPA$_$7$Class$ OPA$_$7$class$ = { 
    0,
};

void OPA$_$6$init$(OPA$_$6* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        OPA$_$7$init$(obj, 32);
    }
}

OPA$_$6 OPA$TargetTab;

int32_t OPA$TargetCount;

uint8_t OPA$export;

uint8_t OPA$inline_;

uint8_t OPA$FirstTime;

int32_t OPA$Target;

int32_t OPA$pc;

int32_t OPA$sym;

OPA$Name OPA$ident;

int32_t OPA$val;

OPA$_$8 OPA$str;

int32_t OPA$errpos;

OPT$Node OPA$first = NULL;

OPT$Node OPA$last = NULL;

OPT$Node OPA$fixlist = NULL;

int32_t OPA$AND(int32_t a, int32_t b) {
    return (a & b);
}

int32_t OPA$ModeSize(int32_t mode) {
    switch( mode ) { 
    case 48:
    case 51:
    case 52:
    case 96:
    case 9:
    case 19:
    case 8:
    case 65:
    case 73:
    case 53:
        return 1;
        break;
    case 49:
    case 97:
    case 17:
    case 18:
    case 16:
    case 66:
    case 74:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 86:
        return 2;
        break;
    case 50:
    case 98:
    case 99:
    case 33:
    case 32:
    case 67:
    case 75:
    case 69:
        return 4;
        break;
    case 76:
    case 40:
    case 70:
        return 8;
        break;
    case 77:
        return 10;
        break;
    case 64:
    case 68:
        return 0;
        break;
    default:
        return 0;
        break;
    }
}

int16_t OPA$ConstSize(int32_t i, uint8_t signed_) {
    if( (((-128 <= i) && (127 >= i)) || ((!signed_) && (OPA$AND(i, ((int32_t)4294967040U)) == 0))) ) { 
        return 1;
    } else if( (((-32768 <= i) && (32767 >= i)) || ((!signed_) && (OPA$AND(i, ((int32_t)4294901760U)) == 0))) ) { 
        return 2;
    } else { 
        return 4;
    }
}

uint8_t OPA$IsRegMode(int32_t m, uint8_t strict) {
    return ((((m == 8) || (m == 16)) || (m == 32)) || ((!strict) && ((((m == 9) || (m == 17)) || (m == 33)) || (m == 18))));
}

uint8_t OPA$IsSRegMode(int32_t m, uint8_t strict) {
    return ((m == 80) || (((((((!strict) && (m == 81)) || (m == 82)) || (m == 83)) || (m == 84)) || (m == 85)) || (m == 86)));
}

uint8_t OPA$IsSpecRegMode(int32_t m) {
    return (((m == 112) || (m == 113)) || (m == 114));
}

uint8_t OPA$IsMMode(int32_t m) {
    return ((((((m == 72) || (m == 73)) || (m == 74)) || (m == 75)) || (m == 76)) || (m == 77));
}

uint8_t OPA$IsRMMode(int32_t m) {
    return ((((m == 64) || (m == 65)) || (m == 66)) || (m == 67));
}

uint8_t OPA$IsMMMode(int32_t m) {
    return (((m == 68) || (m == 69)) || (m == 70));
}

uint8_t OPA$IsFRegMode(int32_t m, uint8_t strict) {
    return ((m == 128) || ((!strict) && (m == 129)));
}

uint8_t OPA$IsRegister(int32_t mode) {
    return (((OPA$IsRegMode(mode, 1) || OPA$IsSRegMode(mode, 0)) || OPA$IsSpecRegMode(mode)) || (mode == 40));
}

uint8_t OPA$NeedModRM(int32_t mode, int32_t regpos) {
    return (((OPA$IsRMMode(mode) || OPA$IsMMode(mode)) || OPA$IsMMMode(mode)) || ((((regpos == 1) || (regpos == 4)) || (regpos == 3)) && OPA$IsRegister(mode)));
}

uint8_t OPA$IsImmMode(int32_t m) {
    return (((((m == 48) || (m == 49)) || (m == 50)) || (m == 53)) || (m == 54));
}

uint8_t OPA$IsRelMode(int32_t m) {
    return (((m == 96) || (m == 97)) || (m == 98));
}

int32_t OPA$Evaluate(OPA$Operand* op, int32_t mode) {
    if( (mode == (*op).mode) ) { 
        return 4;
    } else if( OPA$IsRMMode(mode) ) { 
        if( OPA$IsMMode((*op).mode) ) { 
            if( (OPA$ModeSize((*op).mode) == OPA$ModeSize(mode)) ) { 
                return 4;
            } else if( (((*op).mode == 64) || ((*op).mode == 72)) ) { 
                return 1;
            }
        } else if( (OPA$IsRegMode((*op).mode, 0) && (OPA$ModeSize((*op).mode) == OPA$ModeSize(mode))) ) { 
            return 2;
        }
    } else if( OPA$IsRegMode(mode, 1) ) { 
        if( (OPA$ModeSize((*op).mode) == OPA$ModeSize(mode)) ) { 
            if( OPA$IsRegMode((*op).mode, 1) ) { 
                return 4;
            } else if( OPA$IsRegMode((*op).mode, 0) ) { 
                return 2;
            }
        }
    } else if( (mode == 18) ) { 
        if( (((*op).mode == 16) && ((*op).reg == 2)) ) { 
            return 4;
        }
    } else if( (mode == 19) ) { 
        if( (((*op).mode == 8) && ((*op).reg == 1)) ) { 
            return 4;
        }
    } else if( OPA$IsRegMode(mode, 0) ) { 
        return 0;
    } else if( OPA$IsImmMode(mode) ) { 
        if( ((*op).mode == 54) ) { 
            if( (OPA$ModeSize(mode) > OPA$ConstSize((*op).imm, (mode == 53))) ) { 
                return 3;
            } else if( (OPA$ModeSize(mode) == OPA$ConstSize((*op).imm, (mode == 53))) ) { 
                return 4;
            }
        } else if( OPA$IsImmMode((*op).mode) ) { 
            if( (OPA$ModeSize(mode) > OPA$ModeSize((*op).mode)) ) { 
                return 3;
            } else if( (OPA$ModeSize(mode) == OPA$ModeSize((*op).mode)) ) { 
                return 4;
            }
        }
    } else if( (mode == 51) ) { 
        if( (OPA$IsImmMode((*op).mode) && ((*op).imm == 1)) ) { 
            return 4;
        }
    } else if( (mode == 52) ) { 
        if( (OPA$IsImmMode((*op).mode) && ((*op).imm == 3)) ) { 
            return 4;
        }
    } else if( OPA$IsMMode(mode) ) { 
        if( OPA$IsMMode((*op).mode) ) { 
            if( (OPA$ModeSize((*op).mode) == OPA$ModeSize(mode)) ) { 
                return 4;
            } else if( (((*op).mode == 72) || (mode == 72)) ) { 
                return 1;
            }
        }
    } else if( (mode == 80) ) { 
        if( OPA$IsSRegMode((*op).mode, 0) ) { 
            return 4;
        }
    } else if( OPA$IsRelMode(mode) ) { 
        if( ((mode == 98) && ((*op).mode == 99)) ) { 
            return 4;
        } else if( OPA$IsImmMode((*op).mode) ) { 
            if( (OPA$ModeSize(mode) == OPA$ConstSize((*op).imm, 1)) ) { 
                return 4;
            } else if( (OPA$ModeSize(mode) > OPA$ConstSize((*op).imm, 1)) ) { 
                return 3;
            }
        }
    } else if( (mode == 128) ) { 
        if( OPA$IsFRegMode((*op).mode, 1) ) { 
            return 4;
        } else if( OPA$IsFRegMode((*op).mode, 0) ) { 
            return 2;
        }
    } else if( (mode == 70) ) { 
        if( (((*op).mode == 40) || ((*op).mode == 76)) ) { 
            return 4;
        } else if( ((*op).mode == 72) ) { 
            return 2;
        }
    } else if( (mode == 69) ) { 
        if( (((*op).mode == 40) || ((*op).mode == 75)) ) { 
            return 4;
        } else if( ((*op).mode == 72) ) { 
            return 2;
        }
    }
    return 0;
}

int32_t OPA$Match(int32_t ind, MIC$AP op) {
    int32_t start;
    int32_t end;
    int32_t i;
    int32_t j;
    int32_t k;
    int32_t best;
    start = OPA$InstrTab[ind].start;
    end = OPA$InstrTab[ind].end;
    ind = (-1);
    best = 0;
    while( (start < end) ) {
        i = OPA$Evaluate(&((OPA$Operand*)op.$)[0], ((int16_t*)OPA$OpTab[start].op.$)[0]);
        if( (i == 0) ) { 
        } else { 
            j = OPA$Evaluate(&((OPA$Operand*)op.$)[1], ((int16_t*)OPA$OpTab[start].op.$)[1]);
            if( (j == 0) ) { 
                i = 0;
            } else { 
                k = OPA$Evaluate(&((OPA$Operand*)op.$)[2], ((int16_t*)OPA$OpTab[start].op.$)[2]);
                if( ((i < j) && (i < k)) ) { 
                } else if( (j < k) ) { 
                    i = j;
                } else { 
                    i = k;
                }
            }
        }
        if( (i != 0) ) { 
            if( (i == 4) ) { 
                ind = start;
                return ind;
            } else if( (i > best) ) { 
                ind = start;
                best = i;
            } else if( ((i == best) && (i == 1)) ) { 
                OPM$Mark(512, OPA$errpos);
                ind = (-1);
                return ind;
            }
        }
        start++;
    }
    if( (ind == (-1)) ) { 
        OPM$Mark(501, OPA$errpos);
    }
    return ind;
}

void OPA$insert(MIC$AP name, OPA$Object* obj) {
    OPA$Object ob0 = NULL;
    OPA$Object ob1 = NULL;
    int32_t d;
    ob0 = OPA$root;
    ob1 = (*ob0).right;
    d = 1;
    while(1) {
        if( (ob1 == NULL) ) { 
            ob1 = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); ob1->class$ = &OPA$ObjDesc$class$;
            strcpy((char*)(*ob1).name.$, (const char*)name.$);
            (*ob1).typ = 1;
            (*ob1).left = NULL;
            (*ob1).right = NULL;
            (*ob1).fix = NULL;
            (*ob1).obj = NULL;
            (*ob1).next = (*OPA$root).next;
            (*OPA$root).next = ob1;
            (*ob1).val = OPM$errpos;
            if( (d < 0) ) { 
                (*ob0).left = ob1;
            } else { 
                (*ob0).right = ob1;
            }
        } else if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) < 0) ) { 
            d = (-1);
            ob0 = ob1;
            ob1 = (*ob1).left;
        } else if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) > 0) ) { 
            d = 1;
            ob0 = ob1;
            ob1 = (*ob1).right;
        } else { 
            goto __396;
        }
    }    __396:

    (*obj) = ob1;
}

OPA$Object OPA$ConvertObj(OPT$Object ob) {
    OPA$Object obj = NULL;
    if( (ob != NULL) ) { 
        obj = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); obj->class$ = &OPA$ObjDesc$class$;
        switch( (*ob).mode ) { 
        case 1:
            (*obj).val = 1;
            (*obj).size = ((int8_t*)OPA$SizeTab.$)[(*(*ob).typ).form];
            if( ((*ob).mnolev <= 0) ) { 
                (*obj).typ = 7;
            } else { 
                (*obj).typ = 5;
            }
            break;
        case 2:
            (*obj).typ = 6;
            (*obj).val = 1;
            (*obj).size = 4;
            break;
        case 3:
            (*obj).typ = 3;
            (*obj).val = (*(*ob).conval).intval;
            if( (((*(*ob).typ).form > 6) || ((*(*ob).typ).form == 2)) ) { 
                OPM$err(51);
            }
            break;
        case 5:
            (*obj).typ = 4;
            (*obj).size = ((int8_t*)OPA$SizeTab.$)[(*(*ob).typ).form];
            OPM$err(514);
            break;
        case 11:
            (*obj).typ = 11;
            break;
        default:
            (*obj).typ = 3;
            (*obj).val = 0;
            OPM$err(514);
            break;
        }
        (*obj).obj = ob;
    }
    return obj;
}

void OPA$find(MIC$AP name, OPA$Object* obj) {
    OPA$Object ob0 = NULL;
    OPT$Object ob = NULL;
    ob0 = (*OPA$root).right;
    while( ((ob0 != NULL) && (strcmp((const char*)(*ob0).name.$, (const char*)name.$) != 0)) ) {
        if( (strcmp((const char*)name.$, (const char*)(*ob0).name.$) < 0) ) { 
            ob0 = (*ob0).left;
        } else { 
            ob0 = (*ob0).right;
        }
    }
    (*obj) = ob0;
    if( ((*obj) == NULL) ) { 
        strcpy((char*)OPS$name.$, (const char*)name.$);
        OPT$Find(&ob);
        if( (ob != NULL) ) { 
            (*obj) = OPA$ConvertObj(ob);
        } else { 
            OPA$insert(name, &(*obj));
        }
    }
}

void OPA$HashFn(MIC$AP name, int32_t* k, int32_t* n) {
    int32_t i;
    if( ((*n) == 0) ) { 
        i = 0;
        (*k) = 0;
        while( (((uint8_t*)name.$)[i] != 0) ) {
            (*k) = OBERON$MOD((((*k) * 16) + (int32_t)(uint8_t)(((uint8_t*)name.$)[i])), OPA$InstrTabLen);
            i++;
        }
        (*n) = 1;
    } else { 
        (*k) = OBERON$MOD(((*k) + (*n)), OPA$InstrTabLen);
        (*n) += 1;
    }
}

void OPA$FindInstruction(MIC$AP name, int32_t* inx) {
    int32_t n;
    n = 0;
    do {
        OPA$HashFn(name, &(*inx), &n);
    } while( !(((strcmp((const char*)name.$, (const char*)OPA$InstrTab[(*inx)].name.$) == 0) || (((uint8_t*)OPA$InstrTab[(*inx)].name.$)[0] == 0)) || (n > OPA$InstrTabLen)) );
    if( ((((uint8_t*)OPA$InstrTab[(*inx)].name.$)[0] == 0) || (n > OPA$InstrTabLen)) ) { 
        (*inx) = (-1);
    } else if( ((OPA$InstrTab[(*inx)].target | OPA$Target) != OPA$Target) ) { 
        OPM$err(515);
    }
}

void OPA$skipBlanks() {
    while( ((OPS$ch == ' ') || (OPS$ch == 9)) ) {
        OPM$Get(&OPS$ch);
    }
    if( (OPS$ch == ';') ) { 
        while( ((OPS$ch != 13) && (OPS$ch != 10)) ) {
            OPM$Get(&OPS$ch);
        }
    }
}

void OPA$GetIdent(MIC$AP name) {
    int32_t i;
    i = 0;
    OPM$errpos = (OPM$curpos - 1);
    do {
        if( (i < (32 - 1)) ) { 
            ((uint8_t*)name.$)[i] = OPS$ch;
            i++;
        }
        OPM$Get(&OPS$ch);
    } while( !(!((('A' <= (uint8_t)toupper((uint8_t)OPS$ch)) && ((uint8_t)toupper((uint8_t)OPS$ch) <= 'Z')) || (('0' <= OPS$ch) && (OPS$ch <= '9')))) );
    ((uint8_t*)name.$)[i] = 0;
}

void OPA$Get$Comment() {
    OPM$Get(&OPS$ch);
    while(1) {
        while(1) {
            while( (OPS$ch == '(') ) {
                OPM$Get(&OPS$ch);
                if( (OPS$ch == '*') ) { 
                    OPA$Get$Comment();
                }
            }
            if( (OPS$ch == '*') ) { 
                OPM$Get(&OPS$ch);
                goto __512;
            }
            if( (OPS$ch == 0) ) { 
                goto __512;
            }
            OPM$Get(&OPS$ch);
        }        __512:

        if( (OPS$ch == ')') ) { 
            OPM$Get(&OPS$ch);
            goto __511;
        }
        if( (OPS$ch == 0) ) { 
            OPM$Mark(5, OPM$errpos);
            goto __511;
        }
    }    __511:

}

void OPA$Get$Str() {
    uint8_t och;
    int32_t i;
    och = OPS$ch;
    i = 0;
    while(1) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == och) ) { 
            goto __529;
        } else if( (OPS$ch < ' ') ) { 
            OPM$err(3);
            goto __529;
        } else if( (i == (256 - 1)) ) { 
            OPM$err(241);
            goto __529;
        }
        ((uint8_t*)OPA$str.$)[i] = OPS$ch;
        i++;
    }    __529:

    OPM$Get(&OPS$ch);
    ((uint8_t*)OPA$str.$)[i] = 0;
    OPA$val = i;
}

void OPA$Get(int32_t* sym) {
    OPA$skipBlanks();
    OPM$errpos = OPM$curpos;
    if( (OPS$ch >= 'A' && OPS$ch <= 'Z') || (OPS$ch >= 'a' && OPS$ch <= 'z') ) {
        OPA$GetIdent((MIC$AP){32, OPA$ident.$});
        if( (OPS$ch == ':') ) { 
            OPM$Get(&OPS$ch);
            (*sym) = 11;
        } else if( (strcmp((const char*)OPA$ident.$, (const char*)"END") == 0) ) { 
            (*sym) = 10;
        } else { 
            (*sym) = 1;
        }
    } else if( (OPS$ch >= '0' && OPS$ch <= '9') ) {
        OPA$val = 0;
        (*sym) = 4;
        OPS$Number();
        if(!(OPS$numtyp <= 2)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
        OPA$val = OPS$intval;
    } else if( (OPS$ch == ';') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 2;
    } else if( (OPS$ch == '@') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 3;
    } else if( (OPS$ch == ',') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 5;
    } else if( (OPS$ch == '[') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 6;
    } else if( (OPS$ch == ']') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 7;
    } else if( (OPS$ch == '{') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 20;
    } else if( (OPS$ch == '}') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 21;
    } else if( (OPS$ch == 13) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 8;
    } else if( (OPS$ch == 10) ) {
        OPM$Get(&OPS$ch);
        (*sym) = 8;
    } else if( (OPS$ch == '*') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 9;
    } else if( (OPS$ch == '/') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 15;
    } else if( (OPS$ch == '+') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 13;
    } else if( (OPS$ch == '-') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 14;
    } else if( (OPS$ch == '(') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '*') ) { 
            OPA$Get$Comment();
            OPA$Get(&(*sym));
        } else { 
            (*sym) = 16;
        }
    } else if( (OPS$ch == ')') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 17;
    } else if( (OPS$ch == ':') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 12;
    } else if( (OPS$ch == '.') ) {
        OPM$Get(&OPS$ch);
        (*sym) = 19;
    } else if( (OPS$ch == '"') || (OPS$ch == 39) ) {
        OPA$Get$Str();
        (*sym) = 18;
    } else {
        (*sym) = 0;
        OPM$Get(&OPS$ch);
    }

}

void OPA$Check(int32_t s) {
    if( (OPA$sym != s) ) { 
        OPM$err((int16_t)(s));
    }
    OPA$Get(&OPA$sym);
}

void OPA$Qualident(OPA$Object* obj) {
    int32_t i;
    OPT$Object o = NULL;
    (*obj) = NULL;
    if( (OPA$sym == 1) ) { 
        if( (strcmp((const char*)OPA$ident.$, (const char*)"SYSTEM") == 0) ) { 
            if( (!OPT$SYSimported) ) { 
                OPM$err(135);
            }
            strcpy((char*)OPS$name.$, "SYSTEM");
            OPT$Find(&o);
            if( (o != NULL) ) { 
                (*o).flag |= (1u << 1);
            }
            OPA$Get(&OPA$sym);
            if( (OPA$sym == 19) ) { 
                OPA$Get(&OPA$sym);
                if( (OPA$sym == 1) ) { 
                    i = 0;
                    while( ((i < OPA$TargetCount) && (strcmp((const char*)((OPA$_$7*)OPA$TargetTab.$)[i].name.$, (const char*)OPA$ident.$) != 0)) ) {
                        i++;
                    }
                    if( (i == OPA$TargetCount) ) { 
                        OPM$err(0);
                    } else { 
                        (*obj) = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); (*obj)->class$ = &OPA$ObjDesc$class$;
                        (*(*obj)).typ = 3;
                        (*(*obj)).val = i;
                    }
                } else { 
                    OPM$err(0);
                }
                OPA$Get(&OPA$sym);
            } else { 
                OPM$err(18);
            }
        } else { 
            OPA$Get(&OPA$sym);
            OPA$find((MIC$AP){32, OPA$ident.$}, &(*obj));
            if( ((((*obj) != NULL) && (OPA$sym == 19)) && ((*(*obj)).typ == 11)) ) { 
                OPA$Get(&OPA$sym);
                memcpy(OPS$name.$, OPA$ident.$,32 * sizeof(uint8_t));
                OPT$FindImport((*(*obj)).obj, &(*(*obj)).obj);
                (*obj) = OPA$ConvertObj((*(*obj)).obj);
            }
            if( ((*obj) == NULL) ) { 
                OPM$err(0);
            }
        }
    } else { 
        OPM$err(40);
    }
}

void OPA$Expression$Factor(int32_t* x) {
    if( (OPA$sym == 4) ) { 
        (*x) = OPA$val;
        OPA$Get(&OPA$sym);
    } else if( (OPA$sym == 16) ) { 
        OPA$Get(&OPA$sym);
        OPA$Expression(&(*x));
        OPA$Check(17);
    } else { 
        OPM$err(601);
    }
}

void OPA$Expression$Term(int32_t* x) {
    int32_t y;
    int32_t op;
    OPA$Expression$Factor(&(*x));
    while( ((OPA$sym == 9) || (OPA$sym == 15)) ) {
        op = OPA$sym;
        OPA$Get(&OPA$sym);
        OPA$Expression$Factor(&y);
        if( (op == 9) ) { 
            (*x) = ((*x) * y);
        } else { 
            (*x) = OBERON$DIV((*x), y);
        }
    }
}

void OPA$Expression(int32_t* x) {
    int32_t y;
    int32_t op;
    if( (OPA$sym == 14) ) { 
        op = OPA$sym;
        OPA$Get(&OPA$sym);
        OPA$Expression$Term(&(*x));
        (*x) = (-(*x));
    } else { 
        OPA$Expression$Term(&(*x));
    }
    while( ((OPA$sym == 13) || (OPA$sym == 14)) ) {
        op = OPA$sym;
        OPA$Get(&OPA$sym);
        OPA$Expression$Term(&y);
        if( (op == 13) ) { 
            (*x) = ((*x) + y);
        } else { 
            (*x) = ((*x) - y);
        }
    }
}

void OPA$GetBaseIndex(OPA$Operand* o, int32_t size) {
    OPA$Object obj = NULL;
    switch( size ) { 
    case 0:
        (*o).mode = 72;
        break;
    case 1:
        (*o).mode = 73;
        break;
    case 2:
        (*o).mode = 74;
        break;
    case 4:
        (*o).mode = 75;
        break;
    case 8:
        (*o).mode = 76;
        break;
    case 10:
        (*o).mode = 77;
        break;
    }
    (*o).disp = (*o).imm;
    (*o).imm = 0;
    while( ((OPA$sym == 6) || (OPA$sym == 13)) ) {
        OPA$Get(&OPA$sym);
        if( (OPA$sym == 1) ) { 
            OPA$find((MIC$AP){32, OPA$ident.$}, &obj);
        } else { 
            obj = NULL;
        }
        if( (((obj == NULL) || (!OPA$IsRegMode((*obj).typ, 0))) || (OPA$ModeSize((*obj).typ) != 4)) ) { 
            OPM$err(506);
            return;
        }
        OPA$Get(&OPA$sym);
        if( (OPA$sym == 9) ) { 
            if( ((*o).index != (-1)) ) { 
                OPM$err(509);
                return;
            }
            (*o).index = (int16_t)((*obj).val);
            OPA$Get(&OPA$sym);
            if( ((OPA$sym != 4) || ((((OPA$val != 1) && (OPA$val != 2)) && (OPA$val != 4)) && (OPA$val != 8))) ) { 
                OPM$err(508);
                return;
            }
            (*o).scale = (int16_t)(OPA$val);
            OPA$Get(&OPA$sym);
        } else if( ((OPA$sym == 7) || (OPA$sym == 13)) ) { 
            if( ((*o).base == (-1)) ) { 
                (*o).base = (int16_t)((*obj).val);
            } else if( ((*o).index == (-1)) ) { 
                (*o).index = (int16_t)((*obj).val);
            } else { 
                OPM$err(509);
            }
        } else { 
            OPM$err(510);
            return;
        }
        if( (OPA$sym == 7) ) { 
            OPA$Get(&OPA$sym);
        }
    }
}

void OPA$GetOperand(OPA$Operand* o) {
    OPA$Object obj = NULL;
    int32_t size;
    (*o).reg = (-1);
    (*o).disp = 0;
    (*o).base = (-1);
    (*o).index = (-1);
    (*o).imm = 0;
    (*o).seg = (-1);
    (*o).scale = (-1);
    (*o).obj = NULL;
    size = 0;
    if( (OPA$sym == 1) ) { 
        OPA$find((MIC$AP){32, OPA$ident.$}, &obj);
        if( ((obj != NULL) && ((*obj).typ == 80)) ) { 
            (*o).seg = (int16_t)((*obj).val);
            OPA$Get(&OPA$sym);
            OPA$Check(12);
            if( (OPA$sym == 1) ) { 
                OPA$find((MIC$AP){32, OPA$ident.$}, &obj);
            }
        }
    }
    if( (((OPA$sym == 1) && (obj != NULL)) && ((*obj).typ == 4)) ) { 
        size = (int16_t)((*obj).size);
        OPA$Get(&OPA$sym);
        if( ((OPA$sym != 1) || (strcmp((const char*)OPA$ident.$, (const char*)"PTR") != 0)) ) { 
        } else { 
            OPA$Get(&OPA$sym);
        }
        if( (OPA$sym == 1) ) { 
            OPA$find((MIC$AP){32, OPA$ident.$}, &obj);
        }
    }
    switch( OPA$sym ) { 
    case 3:
        OPA$Get(&OPA$sym);
        if( (OPA$sym != 4) ) { 
            OPM$err((-601));
        }
        (*o).disp = OPA$val;
        (*o).mode = 72;
        OPA$Get(&OPA$sym);
        break;
    case 6:
        OPA$GetBaseIndex(&(*o), size);
        break;
    case 1:
    case 4:
    case 14:
        if( (OPA$sym == 1) ) { 
            if( (obj == NULL) ) { 
                OPM$err(500);
                return;
            }
            if( (size == 0) ) { 
                size = (*obj).size;
            }
            if( OPA$IsRegMode((*obj).typ, 0) ) { 
                (*o).mode = (*obj).typ;
                (*o).reg = (int16_t)((*obj).val);
                OPA$Get(&OPA$sym);
                return;
            } else if( OPA$IsSRegMode((*obj).typ, 0) ) { 
                (*o).mode = (*obj).typ;
                (*o).reg = (int16_t)((*obj).val);
                OPA$Get(&OPA$sym);
                return;
            } else if( OPA$IsSpecRegMode((*obj).typ) ) { 
                if( (!(((1 << 17) & OPA$Target) != 0)) ) { 
                    OPM$err(515);
                }
                if( (((!(((1 << 2) & OPA$Target) != 0)) && ((*obj).typ == 112)) && ((*obj).val == 4)) ) { 
                    OPM$err(515);
                }
                (*o).mode = (*obj).typ;
                (*o).reg = (int16_t)((*obj).val);
                OPA$Get(&OPA$sym);
                return;
            } else if( ((*obj).typ == 40) ) { 
                if( (!(((1 << 18) & OPA$Target) != 0)) ) { 
                    OPM$err(515);
                }
                (*o).mode = (*obj).typ;
                (*o).reg = (int16_t)((*obj).val);
                OPA$Get(&OPA$sym);
                return;
            } else if( OPA$IsFRegMode((*obj).typ, 0) ) { 
                (*o).mode = (*obj).typ;
                OPA$Get(&OPA$sym);
                if( (OPA$sym == 16) ) { 
                    OPA$Expression(&size);
                    (*o).reg = (int16_t)(size);
                } else { 
                    (*o).reg = 0;
                    (*o).mode = 129;
                }
                return;
            } else if( ((*obj).typ == 0) ) { 
                (*o).imm = (*obj).val;
                (*o).mode = 96;
                OPA$Get(&OPA$sym);
                return;
            } else if( ((*obj).typ == 1) ) { 
                (*o).obj = obj;
                (*o).mode = 99;
                OPA$Get(&OPA$sym);
                return;
            } else if( ((*obj).typ == 3) ) { 
                (*o).imm = (*obj).val;
                OPA$Get(&OPA$sym);
            } else if( (((*obj).typ == 5) || ((*obj).typ == 6)) ) { 
                if( OPA$inline_ ) { 
                    OPM$err(518);
                }
                (*o).imm = (*obj).val;
                (*o).obj = obj;
                OPA$Get(&OPA$sym);
            } else if( ((*obj).typ == 7) ) { 
                (*o).disp = 305419896;
                (*o).obj = obj;
                switch( size ) { 
                case 1:
                    (*o).mode = 73;
                    break;
                case 2:
                    (*o).mode = 74;
                    break;
                case 4:
                    (*o).mode = 75;
                    break;
                case 8:
                    (*o).mode = 76;
                    break;
                case 10:
                    (*o).mode = 77;
                    break;
                default:
                    (*o).mode = 75;
                    break;
                }
                OPA$Get(&OPA$sym);
                return;
            } else { 
                OPM$err(600);
                return;
            }
        } else { 
            OPA$Expression(&(*o).imm);
        }
        switch( size ) { 
        case 1:
            (*o).mode = 48;
            break;
        case 2:
            (*o).mode = 49;
            break;
        case 4:
            (*o).mode = 50;
            break;
        default:
            (*o).mode = 54;
            break;
        }
        if( (OPA$sym == 6) ) { 
            OPA$GetBaseIndex(&(*o), size);
        }
        break;
    default:
        (*o).mode = (-1);
        OPM$err(511);
        break;
    }
}

void OPA$CheckLabels() {
    OPA$Object obj = NULL;
    OPA$Object obj1 = NULL;
    OPA$Object obj2 = NULL;
    obj1 = (*OPA$root).next;
    obj = NULL;
    while( (obj1 != NULL) ) {
        obj2 = (*obj1).next;
        (*obj1).next = obj;
        obj = obj1;
        obj1 = obj2;
    }
    while( (obj != NULL) ) {
        if( ((*obj).typ == 1) ) { 
            OPM$Mark(128, (*obj).val);
        }
        obj = (*obj).next;
    }
}

void OPA$InsertFix(OPA$Object* obj, int32_t pc) {
    OPA$FixPnt fix = NULL;
    OPT$Node x = NULL;
    switch( (*(*obj)).typ ) { 
    case 1:
        fix = (OPA$FixPntDesc*)GC_MALLOC(sizeof(OPA$FixPntDesc)); fix->class$ = &OPA$FixPntDesc$class$;
        (*fix).pc = pc;
        (*fix).node = OPA$last;
        (*fix).pos = ((int32_t)(uint8_t)((*(*OPA$last).conval).ext[0]) - 3);
        (*fix).next = (*(*obj)).fix;
        (*(*obj)).fix = fix;
        break;
    case 5:
    case 6:
    case 7:
        if( (OPA$export && OPA$inline_) ) { 
            OPM$err(517);
        }
        x = OPT$NewNode(31);
        (*x).obj = (*(*obj)).obj;
        (*x).conval = OPT$NewConst();
        (*(*x).conval).intval = pc;
        (*(*x).conval).intval2 = OPM$errpos;
        (*x).link = OPA$fixlist;
        OPA$fixlist = x;
        break;
    default:
        OPM$err(607);
        break;
    }
}

void OPA$FixDisp(OPA$FixPnt* fix) {
    int32_t pos;
    int32_t disp;
    disp = (OPA$pc - (*(*fix)).pc);
    int _temp0 = ((*(*fix)).pos + 3); pos = (*(*fix)).pos; 
    while( pos <= _temp0 ) {
        (*(*(*(*fix)).node).conval).ext[pos] = (uint8_t)(disp);
        disp = OBERON$DIV(disp, 256);
        pos++;
    }
}

void OPA$NewNode() {
    OPT$Node x = NULL;
    x = OPT$NewNode(30);
    (*x).conval = OPT$NewConst();
    (*(*x).conval).ext = OPT$NewExt();
    (*(*x).conval).ext[0] = 0;
    (*(*x).conval).intval = OPM$errpos;
    OPB$Link(&OPA$first, &OPA$last, x);
}

void OPA$PutByte(int32_t b) {
    int32_t pos;
    pos = ((int32_t)(uint8_t)((*(*OPA$last).conval).ext[0]) + 1);
    if( (pos > 255) ) { 
        OPA$NewNode();
        pos = 1;
    }
    (*(*OPA$last).conval).ext[pos] = (uint8_t)(b);
    (*(*OPA$last).conval).ext[0] = (uint8_t)(pos);
    OPA$pc++;
}

void OPA$PutBytes(int32_t b, int32_t size) {
    int32_t pos;
    pos = (int32_t)(uint8_t)((*(*OPA$last).conval).ext[0]);
    if( (pos > (255 - size)) ) { 
        OPA$NewNode();
        pos = 0;
    }
    while( (size > 0) ) {
        pos++;
        (*(*OPA$last).conval).ext[pos] = (uint8_t)(b);
        b = OBERON$DIV(b, 256);
        OPA$pc++;
        size--;
    }
    (*(*OPA$last).conval).ext[0] = (uint8_t)(pos);
}

void OPA$ModRM(int32_t* modrm, OPA$Operand* op, int32_t mode, int32_t regpos, uint8_t UseSpecReg) {
    int32_t mod;
    if( ((((OPA$IsRegMode(mode, 1) && (!UseSpecReg)) || OPA$IsSRegMode(mode, 0)) || OPA$IsSpecRegMode(mode)) || (mode == 40)) ) { 
        if(!((*op).reg != (-1))){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
        if( (regpos == 4) ) { 
            if(!((*modrm) == 0)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
            (*modrm) = ((3 * 64) + (*op).reg);
        } else if( (regpos == 3) ) { 
            if(!((*modrm) == 0)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
            (*modrm) = ((3 * 64) + ((*op).reg * 9));
        } else { 
            (*modrm) = ((*modrm) + ((*op).reg * 8));
        }
    } else if( (OPA$NeedModRM(mode, (-1)) || (OPA$IsRegMode(mode, 1) && UseSpecReg)) ) { 
        if( ((*op).reg != (-1)) ) { 
            (*modrm) = (((*modrm) + (*op).reg) + 192);
        } else { 
            if( (((*op).disp == 0) && (!(((*op).base == 5) && ((*op).index == (-1))))) ) { 
                mod = 0;
            } else if( (OPA$ConstSize((*op).disp, 1) == 1) ) { 
                mod = 1;
            } else if( (((*op).base == (-1)) && ((*op).index == (-1))) ) { 
                mod = 0;
            } else { 
                mod = 2;
            }
            (*modrm) = ((*modrm) + (mod * 64));
            if( ((*op).index != (-1)) ) { 
                (*modrm) = ((*modrm) + 4);
            } else if( ((*op).base != (-1)) ) { 
                (*modrm) = ((*modrm) + (*op).base);
            } else { 
                (*modrm) = ((*modrm) + 5);
            }
        }
    } else { 
        OPM$err(1000);
    }
}

int8_t OPA$SIB(OPA$Operand op) {
    int32_t val;
    if( (op.index == 4) ) { 
        OPM$err(501);
    } else if( (op.index != (-1)) ) { 
        val = (op.base + (op.index * 8));
        switch( op.scale ) { 
        case (-1):
        case 1:
            break;
        case 2:
            val = (val + (1 * 64));
            break;
        case 4:
            val = (val + (2 * 64));
            break;
        case 8:
            val = (val + (3 * 64));
            break;
        }
    } else { 
        val = (op.base + (4 * 8));
    }
    return (uint8_t)((int16_t)(val));
}

void OPA$GenCode(int32_t ind, MIC$AP op) {
    int32_t i;
    int32_t instr;
    int32_t opi;
    OPA$Mnemo name;
    OPA$Object fixobj = NULL;
    uint8_t UseRM;
    uint8_t UseImm;
    uint8_t UseSpecReg;
    uint8_t UseSegReg;
    uint8_t UseDisp;
    int32_t seg;
    int32_t reg;
    int32_t modrm;
    int32_t sib;
    int32_t imm;
    int32_t immSize;
    int32_t disp;
    disp = 0;
    if( OPA$IsRelMode(((OPA$Operand*)op.$)[0].mode) ) { 
        switch( OPA$ConstSize(((((OPA$Operand*)op.$)[0].imm - 2) - OPA$pc), 1) ) { 
        case 1:
            ((OPA$Operand*)op.$)[0].mode = 96;
            break;
        case 2:
        case 4:
            ((OPA$Operand*)op.$)[0].mode = 98;
            break;
        }
    }
    strcpy((char*)name.$, (const char*)OPA$InstrTab[ind].name.$);
    instr = OPA$Match(ind, op);
    if( (instr < 0) ) { 
        return;
    }
    UseSpecReg = (OPA$IsSpecRegMode(((int16_t*)OPA$OpTab[instr].op.$)[0]) || OPA$IsSpecRegMode(((int16_t*)OPA$OpTab[instr].op.$)[1]));
    UseSegReg = (OPA$IsSRegMode(((int16_t*)OPA$OpTab[instr].op.$)[0], 0) || OPA$IsSRegMode(((int16_t*)OPA$OpTab[instr].op.$)[1], 0));
    if( ((((!UseSpecReg) && (!UseSegReg)) && (((uint8_t*)name.$)[0] != 'F')) && (((strcmp((const char*)name.$, (const char*)"OUT") == 0) && (OPA$ModeSize(((int16_t*)OPA$OpTab[instr].op.$)[1]) == 2)) || ((strcmp((const char*)name.$, (const char*)"OUT") != 0) && (OPA$ModeSize(((int16_t*)OPA$OpTab[instr].op.$)[0]) == 2)))) ) { 
        if( ((((int16_t*)OPA$OpTab[instr].op.$)[0] == 97) || (((strcmp((const char*)name.$, (const char*)"LEA") == 0) || (strcmp((const char*)name.$, (const char*)"OUTS") == 0)) && (((int16_t*)OPA$OpTab[instr].op.$)[1] == 66))) ) { 
            OPA$PutByte(103);
        } else if( (((strcmp((const char*)name.$, (const char*)"RET") != 0) && (strcmp((const char*)name.$, (const char*)"ARPL") != 0)) && (strcmp((const char*)name.$, (const char*)"STR") != 0)) ) { 
            OPA$PutByte(102);
        }
    }
    if( (((1 << 18) & OPA$InstrTab[ind].target) != 0) ) { 
        OPA$PutByte(15);
    }
    seg = (-1);
    reg = (-1);
    modrm = 0;
    UseRM = 0;
    sib = (-1);
    UseImm = 0;
    fixobj = NULL;
    UseDisp = 0;
    i = 0;
    while( ((i < 3) && (((int16_t*)OPA$OpTab[instr].op.$)[i] != (-1))) ) {
        opi = ((int16_t*)OPA$OpTab[instr].op.$)[i];
        if( (((OPA$Operand*)op.$)[i].seg != (-1)) ) { 
            if( (seg != (-1)) ) { 
                OPM$err(504);
            } else { 
                seg = ((OPA$Operand*)op.$)[i].seg;
            }
        }
        if( ((OPA$OpTab[instr].reg == 2) && (OPA$IsRegMode(opi, 1) || OPA$IsFRegMode(opi, 1))) ) { 
            reg = ((OPA$Operand*)op.$)[i].reg;
        }
        if( OPA$NeedModRM(opi, OPA$OpTab[instr].reg) ) { 
            OPA$ModRM(&modrm, &((OPA$Operand*)op.$)[i], opi, OPA$OpTab[instr].reg, UseSpecReg);
            UseRM = 1;
            if( OPA$NeedModRM(opi, (-1)) ) { 
                disp = ((OPA$Operand*)op.$)[i].disp;
                fixobj = ((OPA$Operand*)op.$)[i].obj;
                UseDisp = ((disp != 0) || ((((OPA$Operand*)op.$)[i].base == 5) && (((OPA$Operand*)op.$)[i].index == (-1))));
            }
        }
        if( ((((OPA$Operand*)op.$)[i].index != (-1)) || (((OPA$Operand*)op.$)[i].base == 4)) ) { 
            if(!(sib == (-1))){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
            sib = OPA$SIB(((OPA$Operand*)op.$)[i]);
        }
        if( (OPA$IsImmMode(opi) || (OPA$IsRelMode(opi) && OPA$IsImmMode(((OPA$Operand*)op.$)[i].mode))) ) { 
            if(!(!UseImm)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
            UseImm = 1;
            imm = ((OPA$Operand*)op.$)[i].imm;
            immSize = OPA$ModeSize(opi);
        }
        i++;
    }
    if( (seg != (-1)) ) { 
        OPA$PutByte(seg);
    }
    if( (reg == (-1)) ) { 
        reg = 0;
    }
    if( (OPA$OpTab[instr].op1 != (-1)) ) { 
        OPA$PutByte(OPA$OpTab[instr].op0);
        OPA$PutByte((OPA$OpTab[instr].op1 + reg));
    } else { 
        OPA$PutByte((OPA$OpTab[instr].op0 + reg));
    }
    if( (OPA$OpTab[instr].opc != (-1)) ) { 
        if(!(OPA$AND(modrm, 56) == 0)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
        modrm = (modrm + (OPA$OpTab[instr].opc * 8));
        UseRM = 1;
    }
    if( UseRM ) { 
        OPA$PutByte(modrm);
    }
    if( (sib != (-1)) ) { 
        OPA$PutByte(sib);
    }
    if( UseDisp ) { 
        if( (fixobj != NULL) ) { 
            OPA$InsertFix(&fixobj, OPA$pc);
        }
        if( (OPA$ConstSize(disp, 1) == 1) ) { 
            OPA$PutByte(disp);
        } else { 
            OPA$PutBytes(disp, 4);
        }
    }
    if( (OPA$IsRelMode(((int16_t*)OPA$OpTab[instr].op.$)[0]) && (!OPA$IsImmMode(((OPA$Operand*)op.$)[0].mode))) ) { 
        OPA$PutBytes(((((OPA$Operand*)op.$)[0].imm - OPA$pc) - OPA$ModeSize(((int16_t*)OPA$OpTab[instr].op.$)[0])), OPA$ModeSize(((int16_t*)OPA$OpTab[instr].op.$)[0]));
        if( (((OPA$Operand*)op.$)[0].mode == 99) ) { 
            OPA$InsertFix(&((OPA$Operand*)op.$)[0].obj, OPA$pc);
        }
    }
    if( UseImm ) { 
        OPA$PutBytes(imm, immSize);
    }
}

void OPA$ParseLabel() {
    OPA$Object obj = NULL;
    OPA$FixPnt fix = NULL;
    if(!(OPA$sym == 11)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    OPA$insert((MIC$AP){32, OPA$ident.$}, &obj);
    if( ((*obj).typ == 1) ) { 
        fix = (*obj).fix;
        while( (fix != NULL) ) {
            OPA$FixDisp(&fix);
            fix = (*fix).next;
        }
        (*obj).typ = 0;
        (*obj).val = OPA$pc;
    } else { 
        OPM$err(512);
    }
    OPA$Get(&OPA$sym);
}

void OPA$ParseInstruction() {
    int32_t ind;
    int32_t size;
    int32_t i;
void OPA$_$14$init$(OPA$_$14* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        OPA$Operand$init$(obj, 3);
    }
}

    OPA$_$14 op;
    OPA$Name name;
    if( (((strcmp((const char*)OPA$ident.$, (const char*)"DB") == 0) || (strcmp((const char*)OPA$ident.$, (const char*)"DW") == 0)) || (strcmp((const char*)OPA$ident.$, (const char*)"DD") == 0)) ) { 
        switch( ((uint8_t*)OPA$ident.$)[1] ) { 
        case 'B':
            size = 1;
            break;
        case 'W':
            size = 2;
            break;
        case 'D':
            size = 4;
            break;
        }
        OPA$Get(&OPA$sym);
        while( ((OPA$sym == 4) || (OPA$sym == 18)) ) {
            if( ((OPA$sym == 18) && (OPA$val == 1)) ) { 
                OPA$PutBytes((int32_t)(uint8_t)(((uint8_t*)OPA$str.$)[0]), size);
            } else if( ((OPA$sym == 4) && (OPA$ConstSize(OPA$val, 0) <= size)) ) { 
                OPA$PutBytes(OPA$val, size);
            } else { 
                OPM$err(203);
            }
            OPA$Get(&OPA$sym);
            if( (OPA$sym == 5) ) { 
                OPA$Get(&OPA$sym);
            } else { 
                return;
            }
        }
    } else if( (strcmp((const char*)OPA$ident.$, (const char*)"DS") == 0) ) { 
        OPA$Get(&OPA$sym);
        if( (OPA$sym == 18) ) { 
            int _temp1 = OPA$val; i = 0; 
            while( i <= _temp1 ) {
                OPA$PutBytes((int32_t)(uint8_t)(((uint8_t*)OPA$str.$)[i]), 1);
                i++;
            }
            OPA$Get(&OPA$sym);
        } else { 
            OPM$err(513);
        }
    } else { 
        int _temp2 = 2; i = 0; 
        while( i <= _temp2 ) {
            ((OPA$Operand*)op.$)[i].mode = (-1);
            i++;
        }
        OPA$FindInstruction((MIC$AP){32, OPA$ident.$}, &ind);
        strcpy((char*)name.$, (const char*)OPA$ident.$);
        OPA$errpos = OPM$errpos;
        OPA$Get(&OPA$sym);
        if( (ind < 0) ) { 
            OPM$err(502);
            return;
        }
        ((uint8_t*)name.$)[3] = 0;
        if( (strcmp((const char*)name.$, (const char*)"REP") == 0) ) { 
            OPA$GenCode(ind, (MIC$AP){3, op.$});
            if( (OPA$sym == 8) ) { 
                OPA$Get(&OPA$sym);
            }
            OPA$FindInstruction((MIC$AP){32, OPA$ident.$}, &ind);
            OPA$errpos = OPM$errpos;
            OPA$Get(&OPA$sym);
            if( (ind < 0) ) { 
                OPM$err(502);
                return;
            }
        }
        i = 0;
        if( (OPA$sym != 8) ) { 
            while(1) {
                OPA$GetOperand(&((OPA$Operand*)op.$)[i]);
                i++;
                if( (OPA$sym != 5) ) { 
                    goto __1110;
                }
                OPA$Get(&OPA$sym);
            }            __1110:

        }
        OPA$GenCode(ind, (MIC$AP){3, op.$});
    }
}

void OPA$ParseTarget() {
    OPA$Object obj = NULL;
    while(1) {
        if( (OPA$sym == 1) ) { 
            OPA$Qualident(&obj);
            if( (obj == NULL) ) { 
                OPM$err(0);
            } else if( ((*obj).typ == 3) ) { 
                OPA$Target = (OPA$Target | ((OPA$_$7*)OPA$TargetTab.$)[(*obj).val].flag);
            } else { 
                OPM$err(0);
            }
        } else { 
            OPM$err(40);
        }
        if( (OPA$sym == 21) ) { 
            OPA$Get(&OPA$sym);
            goto __1124;
        } else if( (OPA$sym == 5) ) { 
            OPA$Get(&OPA$sym);
        } else if( (OPA$sym != 1) ) { 
            OPM$err(24);
            goto __1124;
        } else { 
            OPM$err(19);
        }
    }    __1124:

}

void OPA$InsertReg(MIC$AP name, int32_t t, int32_t v) {
    OPA$Object obj = NULL;
    OPA$insert(name, &obj);
    (*obj).typ = t;
    (*obj).val = v;
    (*obj).size = 0;
}

void OPA$InsertType(MIC$AP name, int32_t s) {
    OPA$Object obj = NULL;
    OPA$insert(name, &obj);
    (*obj).typ = 4;
    (*obj).val = (-1);
    (*obj).size = s;
}

void OPA$Init() {
    (*OPA$root).next = NULL;
    (*OPA$root).left = NULL;
    (*OPA$root).right = NULL;
    OPA$InsertReg((MIC$AP){strlen("AL") + 1,"AL"}, 9, 0);
    OPA$InsertReg((MIC$AP){strlen("AH") + 1,"AH"}, 8, 4);
    OPA$InsertReg((MIC$AP){strlen("AX") + 1,"AX"}, 17, 0);
    OPA$InsertReg((MIC$AP){strlen("EAX") + 1,"EAX"}, 33, 0);
    OPA$InsertReg((MIC$AP){strlen("BL") + 1,"BL"}, 8, 3);
    OPA$InsertReg((MIC$AP){strlen("BH") + 1,"BH"}, 8, 7);
    OPA$InsertReg((MIC$AP){strlen("BX") + 1,"BX"}, 16, 3);
    OPA$InsertReg((MIC$AP){strlen("EBX") + 1,"EBX"}, 32, 3);
    OPA$InsertReg((MIC$AP){strlen("CL") + 1,"CL"}, 8, 1);
    OPA$InsertReg((MIC$AP){strlen("CH") + 1,"CH"}, 8, 5);
    OPA$InsertReg((MIC$AP){strlen("CX") + 1,"CX"}, 16, 1);
    OPA$InsertReg((MIC$AP){strlen("ECX") + 1,"ECX"}, 32, 1);
    OPA$InsertReg((MIC$AP){strlen("DL") + 1,"DL"}, 8, 2);
    OPA$InsertReg((MIC$AP){strlen("DH") + 1,"DH"}, 8, 6);
    OPA$InsertReg((MIC$AP){strlen("DX") + 1,"DX"}, 16, 2);
    OPA$InsertReg((MIC$AP){strlen("EDX") + 1,"EDX"}, 32, 2);
    OPA$InsertReg((MIC$AP){strlen("SP") + 1,"SP"}, 16, 4);
    OPA$InsertReg((MIC$AP){strlen("ESP") + 1,"ESP"}, 32, 4);
    OPA$InsertReg((MIC$AP){strlen("BP") + 1,"BP"}, 16, 5);
    OPA$InsertReg((MIC$AP){strlen("EBP") + 1,"EBP"}, 32, 5);
    OPA$InsertReg((MIC$AP){strlen("SI") + 1,"SI"}, 16, 6);
    OPA$InsertReg((MIC$AP){strlen("ESI") + 1,"ESI"}, 32, 6);
    OPA$InsertReg((MIC$AP){strlen("DI") + 1,"DI"}, 16, 7);
    OPA$InsertReg((MIC$AP){strlen("EDI") + 1,"EDI"}, 32, 7);
    OPA$InsertReg((MIC$AP){strlen("MM0") + 1,"MM0"}, 40, 0);
    OPA$InsertReg((MIC$AP){strlen("MM1") + 1,"MM1"}, 40, 1);
    OPA$InsertReg((MIC$AP){strlen("MM2") + 1,"MM2"}, 40, 2);
    OPA$InsertReg((MIC$AP){strlen("MM3") + 1,"MM3"}, 40, 3);
    OPA$InsertReg((MIC$AP){strlen("MM4") + 1,"MM4"}, 40, 4);
    OPA$InsertReg((MIC$AP){strlen("MM5") + 1,"MM5"}, 40, 5);
    OPA$InsertReg((MIC$AP){strlen("MM6") + 1,"MM6"}, 40, 6);
    OPA$InsertReg((MIC$AP){strlen("MM7") + 1,"MM7"}, 40, 7);
    OPA$InsertReg((MIC$AP){strlen("CS") + 1,"CS"}, 81, 1);
    OPA$InsertReg((MIC$AP){strlen("SS") + 1,"SS"}, 86, 2);
    OPA$InsertReg((MIC$AP){strlen("DS") + 1,"DS"}, 82, 3);
    OPA$InsertReg((MIC$AP){strlen("ES") + 1,"ES"}, 83, 0);
    OPA$InsertReg((MIC$AP){strlen("FS") + 1,"FS"}, 84, 4);
    OPA$InsertReg((MIC$AP){strlen("GS") + 1,"GS"}, 85, 5);
    OPA$InsertReg((MIC$AP){strlen("CR0") + 1,"CR0"}, 112, 0);
    OPA$InsertReg((MIC$AP){strlen("CR2") + 1,"CR2"}, 112, 2);
    OPA$InsertReg((MIC$AP){strlen("CR3") + 1,"CR3"}, 112, 3);
    OPA$InsertReg((MIC$AP){strlen("CR4") + 1,"CR4"}, 112, 4);
    OPA$InsertReg((MIC$AP){strlen("DR0") + 1,"DR0"}, 113, 0);
    OPA$InsertReg((MIC$AP){strlen("DR1") + 1,"DR1"}, 113, 1);
    OPA$InsertReg((MIC$AP){strlen("DR2") + 1,"DR2"}, 113, 2);
    OPA$InsertReg((MIC$AP){strlen("DR3") + 1,"DR3"}, 113, 3);
    OPA$InsertReg((MIC$AP){strlen("DR6") + 1,"DR6"}, 113, 6);
    OPA$InsertReg((MIC$AP){strlen("DR7") + 1,"DR7"}, 113, 7);
    OPA$InsertReg((MIC$AP){strlen("ST") + 1,"ST"}, 128, 0);
    OPA$InsertType((MIC$AP){strlen("BYTE") + 1,"BYTE"}, 1);
    OPA$InsertType((MIC$AP){strlen("WORD") + 1,"WORD"}, 2);
    OPA$InsertType((MIC$AP){strlen("DWORD") + 1,"DWORD"}, 4);
    OPA$InsertType((MIC$AP){strlen("QWORD") + 1,"QWORD"}, 8);
    OPA$InsertType((MIC$AP){strlen("TBYTE") + 1,"TBYTE"}, 10);
    OPA$pc = 0;
    OPA$Target = (0);
}

void OPA$Close() {
    (*OPA$root).right = NULL;
}

void OPA$InsertTarget(MIC$AP name, int32_t flag) {
    strcpy((char*)((OPA$_$7*)OPA$TargetTab.$)[OPA$TargetCount].name.$, (const char*)name.$);
    ((OPA$_$7*)OPA$TargetTab.$)[OPA$TargetCount].flag = flag;
    OPA$TargetCount++;
}

void OPA$BodyInit() {
    int16_t s;
    int32_t i;
    Files$File f = NULL;
    Files$Rider r;
    OPM$LogWLn();
    OPM$LogWStr((MIC$AP){strlen("  using OP2-ASM add-on / prk") + 1,"  using OP2-ASM add-on / prk"});
    OPA$root = (OPA$ObjDesc*)GC_MALLOC(sizeof(OPA$ObjDesc)); OPA$root->class$ = &OPA$ObjDesc$class$;
    (*OPA$root).left = NULL;
    (*OPA$root).right = NULL;
    (*OPA$root).next = NULL;
    f = Files$Old((MIC$AP){strlen("OPA.Data") + 1,"OPA.Data"});
    if( (f != NULL) ) { 
        Files$Set(&r, f, 0);
        Files$ReadInt(&r, &s);
        OPA$InstrTabLen = s;
        OPA$InstrTab = (OPA$InstrDesc*)$allocda(OPA$InstrTabLen, sizeof(OPA$InstrDesc));
        int _temp3 = (OPA$InstrTabLen - 1); i = 0; 
        while( i <= _temp3 ) {
            Files$ReadString(&r, (MIC$AP){12, OPA$InstrTab[i].name.$});
            if( (strcmp((const char*)OPA$InstrTab[i].name.$, (const char*)"") != 0) ) { 
                Files$ReadInt(&r, &OPA$InstrTab[i].start);
                Files$ReadInt(&r, &OPA$InstrTab[i].end);
                Files$ReadSet(&r, &OPA$InstrTab[i].target);
            }
            i++;
        }
        Files$ReadInt(&r, &s);
        OPA$OpTabLen = s;
        OPA$OpTab = (OPA$OpCode*)$allocda(OPA$OpTabLen, sizeof(OPA$OpCode));
        int _temp4 = (OPA$OpTabLen - 1); i = 0; 
        while( i <= _temp4 ) {
            Files$ReadInt(&r, &((int16_t*)OPA$OpTab[i].op.$)[0]);
            Files$ReadInt(&r, &((int16_t*)OPA$OpTab[i].op.$)[1]);
            Files$ReadInt(&r, &((int16_t*)OPA$OpTab[i].op.$)[2]);
            Files$ReadInt(&r, &OPA$OpTab[i].op0);
            Files$ReadInt(&r, &OPA$OpTab[i].op1);
            Files$ReadInt(&r, &OPA$OpTab[i].opc);
            Files$ReadInt(&r, &OPA$OpTab[i].reg);
            i++;
        }
        Files$Close(f);
    } else { 
        OPM$LogWLn();
        OPM$LogWStr((MIC$AP){strlen("OPA.Data") + 1,"OPA.Data"});
        OPM$LogWStr((MIC$AP){strlen(" not found, ASM not ready") + 1," not found, ASM not ready"});
    }
    ((int8_t*)OPA$SizeTab.$)[0] = 0;
    ((int8_t*)OPA$SizeTab.$)[1] = 1;
    ((int8_t*)OPA$SizeTab.$)[2] = 1;
    ((int8_t*)OPA$SizeTab.$)[3] = 1;
    ((int8_t*)OPA$SizeTab.$)[4] = 1;
    ((int8_t*)OPA$SizeTab.$)[5] = 2;
    ((int8_t*)OPA$SizeTab.$)[6] = 4;
    ((int8_t*)OPA$SizeTab.$)[7] = 4;
    ((int8_t*)OPA$SizeTab.$)[8] = 8;
    ((int8_t*)OPA$SizeTab.$)[9] = 4;
    ((int8_t*)OPA$SizeTab.$)[10] = 4;
    ((int8_t*)OPA$SizeTab.$)[11] = 4;
    ((int8_t*)OPA$SizeTab.$)[12] = 0;
    ((int8_t*)OPA$SizeTab.$)[13] = 4;
    ((int8_t*)OPA$SizeTab.$)[14] = 4;
    ((int8_t*)OPA$SizeTab.$)[15] = 0;
    ((int8_t*)OPA$SizeTab.$)[16] = 8;
    OPA$TargetCount = 0;
    OPA$InsertTarget((MIC$AP){strlen("i386") + 1,"i386"}, (0 | 1u << 0));
    OPA$InsertTarget((MIC$AP){strlen("i486") + 1,"i486"}, (0 | 1u << 0 | 1u << 1));
    OPA$InsertTarget((MIC$AP){strlen("Pentium") + 1,"Pentium"}, (0 | 1u << 0 | 1u << 1 | 1u << 2));
    OPA$InsertTarget((MIC$AP){strlen("PentiumPro") + 1,"PentiumPro"}, (0 | 1u << 0 | 1u << 1 | 1u << 2 | 1u << 3));
    OPA$InsertTarget((MIC$AP){strlen("FPU") + 1,"FPU"}, (0 | 1u << 16));
    OPA$InsertTarget((MIC$AP){strlen("Privileged") + 1,"Privileged"}, (0 | 1u << 17));
    OPA$InsertTarget((MIC$AP){strlen("MMX") + 1,"MMX"}, (0 | 1u << 18));
}

/* public */ void OPA$Assemble(OPT$Node* x, uint8_t exported, uint8_t inlined) {
    OPA$export = exported;
    OPA$inline_ = inlined;
    if( OPA$FirstTime ) { 
        OPA$BodyInit();
        OPA$FirstTime = 0;
    }
    OPA$Init();
    OPA$first = NULL;
    OPA$last = NULL;
    OPA$NewNode();
    OPA$fixlist = NULL;
    OPA$Get(&OPA$sym);
    if( (OPA$sym == 20) ) { 
        OPA$Get(&OPA$sym);
        OPA$ParseTarget();
    } else { 
        OPA$Get(&OPA$sym);
        OPA$Target = (0);
    }
    if( (OPA$Target == (0)) ) { 
        OPM$err(516);
        OPA$Target = (0 | (uint32_t)((((uint64_t)1 << (31 - 0 + 1)) - 1) << 0));
    }
    while( ((OPA$sym != 10) && (OPA$sym != 0)) ) {
        if( (OPA$sym == 11) ) { 
            OPA$ParseLabel();
        }
        if( (OPA$sym == 1) ) { 
            OPA$ParseInstruction();
        }
        while( ((OPA$sym != 10) && (OPA$sym != 8)) ) {
            OPA$Get(&OPA$sym);
            OPM$err(510);
        }
        OPA$Get(&OPA$sym);
    }
    if( OPM$noerr ) { 
        OPA$CheckLabels();
    }
    OPA$Close();
    OPB$Construct(29, &OPA$first, OPA$fixlist);
    (*x) = OPA$first;
    (*(*x)).conval = NULL;
}

void OPA$BEGIN$() {
    OPA$FirstTime = 1;
}

static int OPA$initialized = 0;
void OPA$init$(void) {
    if( OPA$initialized ) return;
    OPA$initialized = 1;
    Files$init$();
    OPM$init$();
    OPS$init$();
    OPT$init$();
    OPB$init$();
    OPA$BEGIN$();
}

