#ifndef __OPA_INCLUDED__
#define __OPA_INCLUDED__

// OPA.h
// this file was generated by AoCodeNavigator 0.6.10 on Mo. Feb. 23 23:59:33 2026

#include <stdint.h>
#include "Files.h"
#include "OPM.h"
#include "OPS.h"
#include "OPT.h"
#include "OPB.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPA$FileName "OPA.Data"
#define OPA$none (-1)
#define OPA$i386 0
#define OPA$i486 1
#define OPA$Pentium 2
#define OPA$PentiumPro 3
#define OPA$FPU 16
#define OPA$Privileged 17
#define OPA$MMX 18
#define OPA$Nassembler 29
#define OPA$Ncode 30
#define OPA$Nfixup 31
#define OPA$StLabel 0
#define OPA$StFwdLabel 1
#define OPA$StConst 3
#define OPA$StType 4
#define OPA$StVar 5
#define OPA$StVarPar 6
#define OPA$StGlobal 7
#define OPA$StMod 11
#define OPA$Reg8 8
#define OPA$Reg16 16
#define OPA$Reg32 32
#define OPA$MReg 40
#define OPA$RegAL 9
#define OPA$RegAX 17
#define OPA$RegEAX 33
#define OPA$RegDX 18
#define OPA$RegCL 19
#define OPA$Imm8 48
#define OPA$Imm16 49
#define OPA$Imm32 50
#define OPA$SImm8 53
#define OPA$Imm 54
#define OPA$Const1 51
#define OPA$Const3 52
#define OPA$RM 64
#define OPA$RM8 65
#define OPA$RM16 66
#define OPA$RM32 67
#define OPA$MM 68
#define OPA$MM32 69
#define OPA$MM64 70
#define OPA$M 72
#define OPA$M8 73
#define OPA$M16 74
#define OPA$M32 75
#define OPA$M64 76
#define OPA$M80 77
#define OPA$SReg 80
#define OPA$RegCS 81
#define OPA$RegDS 82
#define OPA$RegES 83
#define OPA$RegFS 84
#define OPA$RegGS 85
#define OPA$RegSS 86
#define OPA$Rel8 96
#define OPA$Rel16 97
#define OPA$Rel32 98
#define OPA$FwdJmp 99
#define OPA$CRReg 112
#define OPA$DRReg 113
#define OPA$TRReg 114
#define OPA$FReg 128
#define OPA$FRegST 129
#define OPA$TAB 9
#define OPA$CR 13
#define OPA$LF 10
#define OPA$SPACE ' '
#define OPA$ScUndef 0
#define OPA$ScIdent 1
#define OPA$ScSemicolon 2
#define OPA$ScAt 3
#define OPA$ScNumber 4
#define OPA$ScComma 5
#define OPA$ScLBrak 6
#define OPA$ScRBrak 7
#define OPA$ScCR 8
#define OPA$ScMult 9
#define OPA$ScEnd 10
#define OPA$ScLabel 11
#define OPA$ScColon 12
#define OPA$ScPlus 13
#define OPA$ScMinus 14
#define OPA$ScDiv 15
#define OPA$ScLPar 16
#define OPA$ScRPar 17
#define OPA$ScString 18
#define OPA$ScPoint 19
#define OPA$ScLBrace 20
#define OPA$ScRBrace 21
#define OPA$NameLen 32
#define OPA$MaxStrLen 256
#define OPA$MnemoLen 12
#define OPA$OmReg 1
#define OPA$OmOp 2
#define OPA$OmRMReg 3
#define OPA$OmRM 4
#define OPA$NoMatch 0
#define OPA$SizeCast 1
#define OPA$TypeCast 2
#define OPA$ConstCast 3
#define OPA$Hit 4
typedef OPS$Name OPA$Name;
typedef struct OPA$Mnemo { uint8_t $[12]; } OPA$Mnemo;
typedef struct OPA$ObjDesc* OPA$Object;
typedef struct OPA$FixPntDesc* OPA$FixPnt;
typedef struct OPA$InstrDesc {
    struct OPA$InstrDesc$Class$* class$;
    OPA$Mnemo name;
    int16_t start;
    int16_t end;
    int32_t target;
} OPA$InstrDesc;
void OPA$InstrDesc$init$(OPA$InstrDesc* obj, unsigned int n);
struct OPA$InstrDesc$Class$ {
    void* super$;
};
extern struct OPA$InstrDesc$Class$ OPA$InstrDesc$class$;
typedef struct OPA$_$0 { int16_t $[3]; } OPA$_$0;
typedef struct OPA$OpCode {
    struct OPA$OpCode$Class$* class$;
    OPA$_$0 op;
    int16_t op0;
    int16_t op1;
    int16_t opc;
    int16_t reg;
} OPA$OpCode;
void OPA$OpCode$init$(OPA$OpCode* obj, unsigned int n);
struct OPA$OpCode$Class$ {
    void* super$;
};
extern struct OPA$OpCode$Class$ OPA$OpCode$class$;
typedef struct OPA$Operand {
    struct OPA$Operand$Class$* class$;
    int32_t mode;
    int32_t imm;
    int32_t disp;
    int16_t index;
    int16_t base;
    int16_t reg;
    int16_t seg;
    int16_t scale;
    OPA$Object obj;
} OPA$Operand;
void OPA$Operand$init$(OPA$Operand* obj, unsigned int n);
struct OPA$Operand$Class$ {
    void* super$;
};
extern struct OPA$Operand$Class$ OPA$Operand$class$;
typedef struct OPA$ObjDesc {
    struct OPA$ObjDesc$Class$* class$;
    int32_t typ;
    int32_t val;
    int32_t size;
    OPA$Name name;
    OPA$Object left;
    OPA$Object right;
    OPA$Object next;
    OPA$FixPnt fix;
    OPT$Object obj;
} OPA$ObjDesc;
void OPA$ObjDesc$init$(OPA$ObjDesc* obj, unsigned int n);
struct OPA$ObjDesc$Class$ {
    void* super$;
};
extern struct OPA$ObjDesc$Class$ OPA$ObjDesc$class$;
typedef struct OPA$FixPntDesc {
    struct OPA$FixPntDesc$Class$* class$;
    int32_t pc;
    OPT$Node node;
    int32_t pos;
    OPA$FixPnt next;
} OPA$FixPntDesc;
void OPA$FixPntDesc$init$(OPA$FixPntDesc* obj, unsigned int n);
struct OPA$FixPntDesc$Class$ {
    void* super$;
};
extern struct OPA$FixPntDesc$Class$ OPA$FixPntDesc$class$;
extern OPA$Object OPA$root;
// no typedef for open array OPA$_$2 (OPA$OpCode*)
// no typedef for pointer to array OPA$_$1 (using MIC$DA instead)
extern OPA$OpCode* OPA$OpTab;
extern int32_t OPA$OpTabLen;
// no typedef for open array OPA$_$4 (OPA$InstrDesc*)
// no typedef for pointer to array OPA$_$3 (using MIC$DA instead)
extern OPA$InstrDesc* OPA$InstrTab;
extern int32_t OPA$InstrTabLen;
typedef struct OPA$_$5 { int8_t $[17]; } OPA$_$5;
extern OPA$_$5 OPA$SizeTab;
typedef struct OPA$_$7 {
    struct OPA$_$7$Class$* class$;
    OPA$Name name;
    int32_t flag;
} OPA$_$7;
void OPA$_$7$init$(OPA$_$7* obj, unsigned int n);
struct OPA$_$7$Class$ {
    void* super$;
};
extern struct OPA$_$7$Class$ OPA$_$7$class$;
typedef struct OPA$_$6 { OPA$_$7 $[32]; } OPA$_$6;
void OPA$_$6$init$(OPA$_$6* obj, unsigned int n);
extern OPA$_$6 OPA$TargetTab;
extern int32_t OPA$TargetCount;
extern uint8_t OPA$export;
extern uint8_t OPA$inline_;
extern uint8_t OPA$FirstTime;
extern int32_t OPA$Target;
extern int32_t OPA$pc;
extern int32_t OPA$sym;
extern OPA$Name OPA$ident;
extern int32_t OPA$val;
typedef struct OPA$_$8 { uint8_t $[256]; } OPA$_$8;
extern OPA$_$8 OPA$str;
extern int32_t OPA$errpos;
extern OPT$Node OPA$first;
extern OPT$Node OPA$last;
extern OPT$Node OPA$fixlist;
extern int32_t OPA$AND(int32_t a, int32_t b);
extern int32_t OPA$ModeSize(int32_t mode);
extern int16_t OPA$ConstSize(int32_t i, uint8_t signed_);
extern uint8_t OPA$IsRegMode(int32_t m, uint8_t strict);
extern uint8_t OPA$IsSRegMode(int32_t m, uint8_t strict);
extern uint8_t OPA$IsSpecRegMode(int32_t m);
extern uint8_t OPA$IsMMode(int32_t m);
extern uint8_t OPA$IsRMMode(int32_t m);
extern uint8_t OPA$IsMMMode(int32_t m);
extern uint8_t OPA$IsFRegMode(int32_t m, uint8_t strict);
extern uint8_t OPA$IsRegister(int32_t mode);
extern uint8_t OPA$NeedModRM(int32_t mode, int32_t regpos);
extern uint8_t OPA$IsImmMode(int32_t m);
extern uint8_t OPA$IsRelMode(int32_t m);
extern int32_t OPA$Evaluate(OPA$Operand* op, int32_t mode);
// no typedef for open array OPA$_$9 (OPA$Operand*)
extern int32_t OPA$Match(int32_t ind, MIC$AP op);
// no typedef for open array OPA$_$10 (uint8_t*)
extern void OPA$insert(MIC$AP name, OPA$Object* obj);
extern OPA$Object OPA$ConvertObj(OPT$Object ob);
extern void OPA$find(MIC$AP name, OPA$Object* obj);
// no typedef for open array OPA$_$11 (uint8_t*)
extern void OPA$HashFn(MIC$AP name, int32_t* k, int32_t* n);
// no typedef for open array OPA$_$12 (uint8_t*)
extern void OPA$FindInstruction(MIC$AP name, int32_t* inx);
extern void OPA$skipBlanks();
extern void OPA$GetIdent(MIC$AP name);
extern void OPA$Get(int32_t* sym);
extern void OPA$Check(int32_t s);
extern void OPA$Qualident(OPA$Object* obj);
extern void OPA$Expression(int32_t* x);
extern void OPA$GetBaseIndex(OPA$Operand* o, int32_t size);
extern void OPA$GetOperand(OPA$Operand* o);
extern void OPA$CheckLabels();
extern void OPA$InsertFix(OPA$Object* obj, int32_t pc);
extern void OPA$FixDisp(OPA$FixPnt* fix);
extern void OPA$NewNode();
extern void OPA$PutByte(int32_t b);
extern void OPA$PutBytes(int32_t b, int32_t size);
extern void OPA$ModRM(int32_t* modrm, OPA$Operand* op, int32_t mode, int32_t regpos, uint8_t UseSpecReg);
extern int8_t OPA$SIB(OPA$Operand op);
// no typedef for open array OPA$_$13 (OPA$Operand*)
extern void OPA$GenCode(int32_t ind, MIC$AP op);
extern void OPA$ParseLabel();
extern void OPA$ParseInstruction();
typedef struct OPA$_$14 { OPA$Operand $[3]; } OPA$_$14;
void OPA$_$14$init$(OPA$_$14* obj, unsigned int n);
extern void OPA$ParseTarget();
// no typedef for open array OPA$_$15 (uint8_t*)
extern void OPA$InsertReg(MIC$AP name, int32_t t, int32_t v);
// no typedef for open array OPA$_$16 (uint8_t*)
extern void OPA$InsertType(MIC$AP name, int32_t s);
extern void OPA$Init();
extern void OPA$Close();
// no typedef for open array OPA$_$17 (uint8_t*)
extern void OPA$InsertTarget(MIC$AP name, int32_t flag);
extern void OPA$BodyInit();
/* public */ extern void OPA$Assemble(OPT$Node* x, uint8_t exported, uint8_t inlined);
extern void OPA$BEGIN$();
extern void OPA$init$(void);

#endif // __OPA_INCLUDED__