#ifndef __OPB_INCLUDED__
#define __OPB_INCLUDED__

// OPB.h
// this file was generated by AoCodeNavigator 0.6.10 on Mo. Feb. 23 23:59:33 2026

#include <stdint.h>
#include "OPT.h"
#include "OPS.h"
#include "OPM.h"
#include "OPTR.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPB$AwaitIF 1
#define OPB$times 1
#define OPB$slash 2
#define OPB$div 3
#define OPB$mod 4
#define OPB$and 5
#define OPB$plus 6
#define OPB$minus 7
#define OPB$or 8
#define OPB$eql 9
#define OPB$neq 10
#define OPB$lss 11
#define OPB$leq 12
#define OPB$gtr 13
#define OPB$geq 14
#define OPB$in 15
#define OPB$is 16
#define OPB$ash 17
#define OPB$msk 18
#define OPB$len 19
#define OPB$conv 20
#define OPB$abs 21
#define OPB$cap 22
#define OPB$odd 23
#define OPB$not 33
#define OPB$adr 24
#define OPB$cc 25
#define OPB$bit 26
#define OPB$lsh 27
#define OPB$rot 28
#define OPB$val 29
#define OPB$get8 30
#define OPB$get16 31
#define OPB$get32 32
#define OPB$type 34
#define OPB$Var 1
#define OPB$VarPar 2
#define OPB$Con 3
#define OPB$Fld 4
#define OPB$Typ 5
#define OPB$LProc 6
#define OPB$XProc 7
#define OPB$SProc 8
#define OPB$CProc 9
#define OPB$IProc 10
#define OPB$Mod 11
#define OPB$Head 12
#define OPB$TProc 13
#define OPB$Undef 0
#define OPB$Byte 1
#define OPB$Bool 2
#define OPB$Char 3
#define OPB$SInt 4
#define OPB$Int 5
#define OPB$LInt 6
#define OPB$Real 7
#define OPB$LReal 8
#define OPB$Set 9
#define OPB$String 10
#define OPB$NilTyp 11
#define OPB$NoTyp 12
#define OPB$Pointer 13
#define OPB$ProcTyp 14
#define OPB$Comp 15
#define OPB$HInt 16
#define OPB$intSet (0 | (uint32_t)((((uint64_t)1 << (6 - 4 + 1)) - 1) << 4))
#define OPB$realSet (0 | 1u << 7 | 1u << 8)
#define OPB$Basic 1
#define OPB$StaticArr 2
#define OPB$SDynArr 3
#define OPB$DynArr 4
#define OPB$OpenArr 5
#define OPB$Record 6
#define OPB$ArraySet (0 | 1u << 2 | 1u << 3 | 1u << 4 | 1u << 5)
#define OPB$Nvar 0
#define OPB$Nvarpar 1
#define OPB$Nfield 2
#define OPB$Nderef 3
#define OPB$Nindex 4
#define OPB$Nguard 5
#define OPB$Neguard 6
#define OPB$Nconst 7
#define OPB$Ntype 8
#define OPB$Nproc 9
#define OPB$Nupto 10
#define OPB$Nmop 11
#define OPB$Ndop 12
#define OPB$Ncall 13
#define OPB$Ninittd 14
#define OPB$Nif 15
#define OPB$Ncaselse 16
#define OPB$Ncasedo 17
#define OPB$Nenter 18
#define OPB$Nassign 19
#define OPB$Nifelse 20
#define OPB$Ncase 21
#define OPB$Nwhile 22
#define OPB$Nrepeat 23
#define OPB$Nloop 24
#define OPB$Nexit 25
#define OPB$Nreturn 26
#define OPB$Nwith 27
#define OPB$Ntrap 28
#define OPB$Nfixup 31
#define OPB$assign 0
#define OPB$haltfn 0
#define OPB$newfn 1
#define OPB$absfn 2
#define OPB$capfn 3
#define OPB$ordfn 4
#define OPB$entierfn 5
#define OPB$oddfn 6
#define OPB$minfn 7
#define OPB$maxfn 8
#define OPB$chrfn 9
#define OPB$shortfn 10
#define OPB$longfn 11
#define OPB$sizefn 12
#define OPB$incfn 13
#define OPB$decfn 14
#define OPB$inclfn 15
#define OPB$exclfn 16
#define OPB$lenfn 17
#define OPB$copyfn 18
#define OPB$ashfn 19
#define OPB$assertfn 32
#define OPB$awaitfn 64
#define OPB$lockfn 66
#define OPB$adrfn 20
#define OPB$ccfn 21
#define OPB$lshfn 22
#define OPB$rotfn 23
#define OPB$getfn 24
#define OPB$putfn 25
#define OPB$getrfn 26
#define OPB$putrfn 27
#define OPB$bitfn 28
#define OPB$valfn 29
#define OPB$sysnewfn 30
#define OPB$movefn 31
#define OPB$stifn 33
#define OPB$clifn 34
#define OPB$poutfn 35
#define OPB$pinfn 36
#define OPB$shalt 37
#define OPB$get8fn 38
#define OPB$get16fn 39
#define OPB$get32fn 40
#define OPB$put8fn 41
#define OPB$put16fn 42
#define OPB$put32fn 43
#define OPB$typefn 44
#define OPB$internal 0
#define OPB$external 1
#define OPB$externalR 2
#define OPB$hasBody 1
#define OPB$isRedef 2
#define OPB$slNeeded 3
#define OPB$ovflchk 1
#define OPB$AssertTrap 8
#define OPB$notag 1
#define OPB$stdcall 2
#define OPB$cdecl 3
#define OPB$delegate 5
typedef void (*OPB$_$0)(OPT$Struct typ, uint8_t allocDesc); 
/* public */ extern OPB$_$0 OPB$typSize;
typedef void (*OPB$_$1)(OPT$Object* obj); 
/* public */ extern OPB$_$1 OPB$verify;
extern int16_t OPB$exp;
extern int32_t OPB$maxExp;
extern OPT$Object OPB$InitPar;
extern void OPB$err(int16_t n);
/* public */ extern void OPB$InitInsert(OPT$Node* stat);
/* public */ extern void OPB$CodeInsert(OPT$Node* stat);
extern void OPB$InitAppend(OPT$Node* x);
/* public */ extern OPT$Node OPB$NewLeaf(OPT$Object obj);
/* public */ extern void OPB$Construct(int8_t class, OPT$Node* x, OPT$Node y);
/* public */ extern void OPB$Link(OPT$Node* x, OPT$Node* last, OPT$Node y);
extern int32_t OPB$BoolToInt(uint8_t b);
extern uint8_t OPB$IntToBool(int32_t i);
/* public */ extern OPT$Node OPB$NewBoolConst(uint8_t boolval);
/* public */ extern void OPB$OptIf(OPT$Node* x);
/* public */ extern OPT$Node OPB$Nil();
/* public */ extern OPT$Node OPB$BoolConst(int16_t value);
/* public */ extern OPT$Node OPB$EmptySet();
extern void OPB$SetIntType(OPT$Node node);
/* public */ extern OPT$Node OPB$NewIntConst(int32_t intval);
/* public */ extern OPT$Node OPB$NewRealConst(double realval, OPT$Struct typ);
/* public */ extern OPT$Node OPB$NewString(MIC$AP str, int32_t len);
extern void OPB$CharToString(OPT$Node n);
extern void OPB$BindNodes(int8_t class, OPT$Struct typ, OPT$Node* x, OPT$Node y);
extern uint8_t OPB$NotVar(OPT$Node x);
/* public */ extern void OPB$DeRef(OPT$Node* x);
/* public */ extern void OPB$Index(OPT$Node* x, OPT$Node y);
/* public */ extern void OPB$Field(OPT$Node* x, OPT$Object y);
/* public */ extern void OPB$TypTest(OPT$Node* x, OPT$Object obj, uint8_t guard);
/* public */ extern void OPB$In(OPT$Node* x, OPT$Node y);
extern int32_t OPB$log(int32_t x);
extern void OPB$CheckRealType(int16_t f, int16_t nr, OPT$Const x);
/* public */ extern void OPB$MOp(int8_t op, OPT$Node* x);
extern void OPB$CheckPtr(OPT$Node* x, OPT$Node* y);
/* public */ extern void OPB$CheckParameters(OPT$Object fp, OPT$Object ap, uint8_t checkNames);
extern void OPB$CheckProc(OPT$Struct x, OPT$Object y);
extern void OPB$ConstOp(int16_t op, OPT$Node x, OPT$Node y);
extern void OPB$Convert(OPT$Node* x, OPT$Struct typ);
extern void OPB$Val(OPT$Node* x, OPT$Struct typ);
/* public */ extern void OPB$Op(int8_t op, OPT$Node* x, OPT$Node y);
/* public */ extern void OPB$SetRange(OPT$Node* x, OPT$Node y);
/* public */ extern void OPB$SetElem(OPT$Node* x);
extern void OPB$CheckAssign(OPT$Struct x, OPT$Node ynode);
extern void OPB$CheckLeaf(OPT$Node x, uint8_t dynArrToo);
/* public */ extern void OPB$StPar0(OPT$Node* par0, int16_t fctno);
/* public */ extern void OPB$StPar1(OPT$Node* par0, OPT$Node x, int8_t fctno);
/* public */ extern void OPB$StParN(OPT$Node* par0, OPT$Node x, int16_t fctno, int16_t n);
/* public */ extern void OPB$StFct(OPT$Node* par0, int8_t fctno, int16_t parno);
extern void OPB$OpenArrParCheck(OPT$Struct ftyp, OPT$Struct atyp, uint8_t fvarpar);
extern void OPB$CheckReceiver(OPT$Node* x, OPT$Object fp);
/* public */ extern void OPB$PrepCall(OPT$Node* x, OPT$Object* fpar);
/* public */ extern void OPB$Param(OPT$Node* ap, OPT$Object fp);
/* public */ extern void OPB$StaticLink(int8_t dlev);
/* public */ extern void OPB$Call(OPT$Node* x, OPT$Node apar, OPT$Object fp);
/* public */ extern void OPB$CopyAndSubst(OPT$Node* new, OPT$Node old);
/* public */ extern void OPB$Lock(OPT$Node* x, OPT$Object self, uint8_t excl);
/* public */ extern void OPB$Enter(OPT$Node* procdec, OPT$Node stat, OPT$Object proc);
/* public */ extern void OPB$Return(OPT$Node* x, OPT$Object proc);
/* public */ extern void OPB$Assign(OPT$Node* x, OPT$Node y);
/* public */ extern void OPB$Inittd(OPT$Node* inittd, OPT$Node* last, OPT$Struct typ);
extern void OPB$BEGIN$();
extern void OPB$init$(void);

#endif // __OPB_INCLUDED__