#ifndef __OPIR_INCLUDED__
#define __OPIR_INCLUDED__

// OPIR.h
// this file was generated by AoCodeNavigator 0.6.12 on Mi. März 4 17:25:17 2026

#include <stdint.h>
#include "OPT.h"
#include "OPM.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPIR$ld 32
#define OPIR$ldbdw 64
#define OPIR$ldwdw 96
#define OPIR$ldbw 128
#define OPIR$ldbdwu 160
#define OPIR$ldwdwu 196
#define OPIR$ldbwu 224
#define OPIR$getReg 256
#define OPIR$putReg 288
#define OPIR$ldProc 320
#define OPIR$ldXProc 352
#define OPIR$lea 384
#define OPIR$store 416
#define OPIR$push 448
#define OPIR$pop 480
#define OPIR$add 512
#define OPIR$sub 544
#define OPIR$mul 576
#define OPIR$div 608
#define OPIR$mod 640
#define OPIR$neg 960
#define OPIR$abs 992
#define OPIR$cmp 1056
#define OPIR$je 1504
#define OPIR$jne 1536
#define OPIR$jl 1568
#define OPIR$jle 1600
#define OPIR$jg 1632
#define OPIR$jge 1664
#define OPIR$ja 1696
#define OPIR$jae 1728
#define OPIR$jb 1760
#define OPIR$jbe 1792
#define OPIR$jc 1824
#define OPIR$jnc 1856
#define OPIR$jmp 1888
#define OPIR$jmpReg 1920
#define OPIR$sete 1120
#define OPIR$setne 1152
#define OPIR$setl 1184
#define OPIR$setle 1216
#define OPIR$setg 1248
#define OPIR$setge 1280
#define OPIR$seta 1312
#define OPIR$setae 1344
#define OPIR$setb 1376
#define OPIR$setbe 1408
#define OPIR$setc 1440
#define OPIR$setnc 1472
#define OPIR$te 1952
#define OPIR$tne 1984
#define OPIR$tle 2944
#define OPIR$ta 2016
#define OPIR$tae 2880
#define OPIR$to 2912
#define OPIR$trap 2048
#define OPIR$or 672
#define OPIR$xor 704
#define OPIR$and 736
#define OPIR$not 1024
#define OPIR$bt 1088
#define OPIR$btr 768
#define OPIR$bts 800
#define OPIR$test 3424
#define OPIR$call 2080
#define OPIR$callReg 2112
#define OPIR$xcall 2144
#define OPIR$ret 2176
#define OPIR$enter 2208
#define OPIR$leave 2240
#define OPIR$sal 832
#define OPIR$sar 864
#define OPIR$shr 896
#define OPIR$rol 928
#define OPIR$cld 2272
#define OPIR$repMovs 2304
#define OPIR$cmpString 2336
#define OPIR$pushReg 2368
#define OPIR$popReg 2400
#define OPIR$case_ 2432
#define OPIR$short_ 2976
#define OPIR$phi 2464
#define OPIR$label 2496
#define OPIR$entier 3104
#define OPIR$cli 3168
#define OPIR$sti 3200
#define OPIR$in 3232
#define OPIR$out 3264
#define OPIR$assembler 3296
#define OPIR$clear 3328
#define OPIR$std 3392
#define OPIR$dmb 3456
#define OPIR$fload 2528
#define OPIR$fstore 2560
#define OPIR$fist 2592
#define OPIR$fild 2624
#define OPIR$fadd 2656
#define OPIR$fsub 2688
#define OPIR$fmul 2720
#define OPIR$fdiv 2752
#define OPIR$fabs 2784
#define OPIR$fchs 2816
#define OPIR$fcmp 2848
#define OPIR$newStat 3136
#define OPIR$none (-1)
#define OPIR$FP (-2)
#define OPIR$SP (-3)
#define OPIR$noHint (-1)
#define OPIR$useReg0 0
#define OPIR$useReg1 1
#define OPIR$useReg2 2
#define OPIR$useReg3 3
#define OPIR$useReg4 4
#define OPIR$useReg5 5
#define OPIR$useReg6 6
#define OPIR$useReg7 7
#define OPIR$useFReg 8
#define OPIR$tryReg0 16
#define OPIR$tryReg1 17
#define OPIR$tryReg2 18
#define OPIR$tryReg3 19
#define OPIR$tryReg6 22
#define OPIR$tryReg7 23
#define OPIR$Reg 15
#define OPIR$Abs 16
#define OPIR$RegRel 17
#define OPIR$Coc 18
#define OPIR$RegReg 0
#define OPIR$RegMem 1
#define OPIR$MemReg 2
#define OPIR$ImmReg 3
#define OPIR$ImmMem 4
#define OPIR$noScale 0
#define OPIR$Scale1 0
#define OPIR$Scale2 1
#define OPIR$Scale4 2
#define OPIR$Scale8 3
#define OPIR$Bit8 16
#define OPIR$Bit16 8
#define OPIR$Bit32 0
#define OPIR$Bit64 40
#define OPIR$WithTrap 1
#define OPIR$CaseTrap 2
#define OPIR$FuncTrap 3
#define OPIR$OverflowTrap 4
#define OPIR$EqualGuardTrap 5
#define OPIR$GuardTrap 6
#define OPIR$RangeTrap 7
#define OPIR$DimTrap 9
#define OPIR$NewLinkIndex 2
#define OPIR$NewEntryNr 253
#define OPIR$NewSysLinkIndex 3
#define OPIR$NewSysEntryNr 252
#define OPIR$NewArrayLinkIndex 4
#define OPIR$NewArrayEntryNr 251
#define OPIR$StartIndex 5
#define OPIR$StartEntryNr 250
#define OPIR$AwaitIndex 6
#define OPIR$AwaitEntryNr 249
#define OPIR$LockIndex 7
#define OPIR$LockEntryNr 247
#define OPIR$UnlockIndex 8
#define OPIR$UnlockEntryNr 246
#define OPIR$DivModLinkIndex 9
#define OPIR$DivModEntryNr 245
#define OPIR$F64AddLinkIndex 10
#define OPIR$F64AddEntryNr 244
#define OPIR$F64SubLinkIndex 11
#define OPIR$F64SubEntryNr 243
#define OPIR$F64MulLinkIndex 12
#define OPIR$F64MulEntryNr 242
#define OPIR$F64DivLinkIndex 13
#define OPIR$F64DivEntryNr 241
#define OPIR$F64CmpLinkIndex 14
#define OPIR$F64CmpEntryNr 240
#define OPIR$F64CvtIFLinkIndex 15
#define OPIR$F64CvtIFEntryNr 239
#define OPIR$F64CvtFILinkIndex 16
#define OPIR$F64CvtFIEntryNr 238
#define OPIR$F64NegLinkIndex 17
#define OPIR$F64NegEntryNr 237
#define OPIR$F64AbsLinkIndex 18
#define OPIR$F64AbsEntryNr 236
#define OPIR$Nil (-1)
/* public */ typedef struct OPIR$Instruction {
    struct OPIR$Instruction$Class$* class$;
    int8_t scale;
    int8_t reg;
    int16_t op;
    int32_t dest;
    int32_t src1;
    int32_t src2;
    int32_t inx;
    int32_t pc;
    int32_t hint;
    int16_t link;
    int16_t used;
    OPT$Node node;
    uint8_t abs;
} OPIR$Instruction;
void OPIR$Instruction$init$(OPIR$Instruction* obj, unsigned int n);
struct OPIR$Instruction$Class$ {
    void* super$;
};
extern struct OPIR$Instruction$Class$ OPIR$Instruction$class$;
/* public */ // no typedef for pointer to array OPIR$InstructionTable (using MIC$DA instead)
// no typedef for open array OPIR$_$0 (OPIR$Instruction*)
/* public */ // no typedef for pointer to array OPIR$Map (using MIC$DA instead)
typedef struct OPIR$_$1 {
    struct OPIR$_$1$Class$* class$;
    int32_t pos;
    int32_t pc;
} OPIR$_$1;
void OPIR$_$1$init$(OPIR$_$1* obj, unsigned int n);
struct OPIR$_$1$Class$ {
    void* super$;
};
extern struct OPIR$_$1$Class$ OPIR$_$1$class$;
/* public */ // no typedef for open array OPIR$MapDesc (OPIR$_$1*)
/* public */ extern OPIR$Instruction* OPIR$Instr;
/* public */ extern int32_t OPIR$mapSize;
/* public */ extern OPIR$_$1* OPIR$map;
extern void OPIR$BEGIN$();
extern void OPIR$init$(void);

#endif // __OPIR_INCLUDED__