#ifndef __OPL_INCLUDED__
#define __OPL_INCLUDED__

// OPL.h
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include <stdint.h>
#include "OPT.h"
#include "OPO.h"
#include "OPM.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPL$NewRef 1
#define OPL$Experimental 1
#define OPL$Reg 15
#define OPL$Abs 16
#define OPL$RegRel 17
#define OPL$Coc 18
#define OPL$ld 32
#define OPL$ldbdw 64
#define OPL$ldwdw 96
#define OPL$ldbw 128
#define OPL$ldbdwu 160
#define OPL$ldwdwu 196
#define OPL$ldbwu 224
#define OPL$getReg 256
#define OPL$putReg 288
#define OPL$ldProc 320
#define OPL$ldXProc 352
#define OPL$lea 384
#define OPL$store 416
#define OPL$push 448
#define OPL$pop 480
#define OPL$add 512
#define OPL$sub 544
#define OPL$mul 576
#define OPL$div 608
#define OPL$mod 640
#define OPL$neg 960
#define OPL$abs 992
#define OPL$cmp 1056
#define OPL$je 1504
#define OPL$jne 1536
#define OPL$jl 1568
#define OPL$jle 1600
#define OPL$jg 1632
#define OPL$jge 1664
#define OPL$ja 1696
#define OPL$jae 1728
#define OPL$jb 1760
#define OPL$jbe 1792
#define OPL$jc 1824
#define OPL$jnc 1856
#define OPL$jmp 1888
#define OPL$jmpReg 1920
#define OPL$sete 1120
#define OPL$setne 1152
#define OPL$setl 1184
#define OPL$setle 1216
#define OPL$setg 1248
#define OPL$setge 1280
#define OPL$seta 1312
#define OPL$setae 1344
#define OPL$setb 1376
#define OPL$setbe 1408
#define OPL$setc 1440
#define OPL$setnc 1472
#define OPL$te 1952
#define OPL$tne 1984
#define OPL$tle 2944
#define OPL$ta 2016
#define OPL$tae 2880
#define OPL$to 2912
#define OPL$trap 2048
#define OPL$or 672
#define OPL$xor 704
#define OPL$and 736
#define OPL$not 1024
#define OPL$bt 1088
#define OPL$btr 768
#define OPL$bts 800
#define OPL$test 3424
#define OPL$call 2080
#define OPL$callReg 2112
#define OPL$xcall 2144
#define OPL$ret 2176
#define OPL$enter 2208
#define OPL$leave 2240
#define OPL$sal 832
#define OPL$sar 864
#define OPL$shr 896
#define OPL$rol 928
#define OPL$cld 2272
#define OPL$repMovs 2304
#define OPL$cmpString 2336
#define OPL$pushReg 2368
#define OPL$popReg 2400
#define OPL$case_ 2432
#define OPL$short_ 2976
#define OPL$phi 2464
#define OPL$label 2496
#define OPL$entier 3104
#define OPL$cli 3168
#define OPL$sti 3200
#define OPL$in 3232
#define OPL$out 3264
#define OPL$assembler 3296
#define OPL$clear 3328
#define OPL$std 3392
#define OPL$fload 2528
#define OPL$fstore 2560
#define OPL$fist 2592
#define OPL$fild 2624
#define OPL$fadd 2656
#define OPL$fsub 2688
#define OPL$fmul 2720
#define OPL$fdiv 2752
#define OPL$fabs 2784
#define OPL$fchs 2816
#define OPL$fcmp 2848
#define OPL$newStat 3136
#define OPL$Ld DIV$(32, 32)
#define OPL$Ldbdw DIV$(64, 32)
#define OPL$Ldwdw DIV$(96, 32)
#define OPL$Ldbw DIV$(128, 32)
#define OPL$Ldbdwu DIV$(160, 32)
#define OPL$Ldwdwu DIV$(196, 32)
#define OPL$Ldbwu DIV$(224, 32)
#define OPL$GETreg DIV$(256, 32)
#define OPL$PUTreg DIV$(288, 32)
#define OPL$LdProc DIV$(320, 32)
#define OPL$LdXProc DIV$(352, 32)
#define OPL$Lea DIV$(384, 32)
#define OPL$Sto DIV$(416, 32)
#define OPL$Push DIV$(448, 32)
#define OPL$Pop DIV$(480, 32)
#define OPL$Add DIV$(512, 32)
#define OPL$Sub DIV$(544, 32)
#define OPL$Mul DIV$(576, 32)
#define OPL$Div DIV$(608, 32)
#define OPL$Mod DIV$(640, 32)
#define OPL$Neg DIV$(960, 32)
#define OPL$Abso DIV$(992, 32)
#define OPL$Cmp DIV$(1056, 32)
#define OPL$Je DIV$(1504, 32)
#define OPL$Jne DIV$(1536, 32)
#define OPL$Jl DIV$(1568, 32)
#define OPL$Jle DIV$(1600, 32)
#define OPL$Jg DIV$(1632, 32)
#define OPL$Jge DIV$(1664, 32)
#define OPL$Ja DIV$(1696, 32)
#define OPL$Jae DIV$(1728, 32)
#define OPL$Jb DIV$(1760, 32)
#define OPL$Jbe DIV$(1792, 32)
#define OPL$Jc DIV$(1824, 32)
#define OPL$Jnc DIV$(1856, 32)
#define OPL$Jmp DIV$(1888, 32)
#define OPL$JmpReg DIV$(1920, 32)
#define OPL$Sete DIV$(1120, 32)
#define OPL$Setne DIV$(1152, 32)
#define OPL$Setl DIV$(1184, 32)
#define OPL$Setle DIV$(1216, 32)
#define OPL$Setg DIV$(1248, 32)
#define OPL$Setge DIV$(1280, 32)
#define OPL$Seta DIV$(1312, 32)
#define OPL$Setae DIV$(1344, 32)
#define OPL$Setb DIV$(1376, 32)
#define OPL$Setbe DIV$(1408, 32)
#define OPL$Setc DIV$(1440, 32)
#define OPL$Setnc DIV$(1472, 32)
#define OPL$Te DIV$(1952, 32)
#define OPL$Tne DIV$(1984, 32)
#define OPL$Tle DIV$(2944, 32)
#define OPL$Ta DIV$(2016, 32)
#define OPL$Tae DIV$(2880, 32)
#define OPL$To DIV$(2912, 32)
#define OPL$Trap DIV$(2048, 32)
#define OPL$oR DIV$(672, 32)
#define OPL$Xor DIV$(704, 32)
#define OPL$And DIV$(736, 32)
#define OPL$Not DIV$(1024, 32)
#define OPL$Bt DIV$(1088, 32)
#define OPL$Btr DIV$(768, 32)
#define OPL$Bts DIV$(800, 32)
#define OPL$Test DIV$(3424, 32)
#define OPL$Call DIV$(2080, 32)
#define OPL$CallReg DIV$(2112, 32)
#define OPL$Xcall DIV$(2144, 32)
#define OPL$Ret DIV$(2176, 32)
#define OPL$Enter DIV$(2208, 32)
#define OPL$Leave DIV$(2240, 32)
#define OPL$Sal DIV$(832, 32)
#define OPL$Sar DIV$(864, 32)
#define OPL$Shr DIV$(896, 32)
#define OPL$Rol DIV$(928, 32)
#define OPL$Cld DIV$(2272, 32)
#define OPL$RepMovs DIV$(2304, 32)
#define OPL$CmpString DIV$(2336, 32)
#define OPL$PushReg DIV$(2368, 32)
#define OPL$PopReg DIV$(2400, 32)
#define OPL$Case DIV$(2432, 32)
#define OPL$Short DIV$(2976, 32)
#define OPL$Phi DIV$(2464, 32)
#define OPL$Label DIV$(2496, 32)
#define OPL$Entier DIV$(3104, 32)
#define OPL$Cli DIV$(3168, 32)
#define OPL$Sti DIV$(3200, 32)
#define OPL$In DIV$(3232, 32)
#define OPL$Out DIV$(3264, 32)
#define OPL$Assembler DIV$(3296, 32)
#define OPL$Clear DIV$(3328, 32)
#define OPL$Std DIV$(3392, 32)
#define OPL$FLoad DIV$(2528, 32)
#define OPL$FStore DIV$(2560, 32)
#define OPL$Fist DIV$(2592, 32)
#define OPL$Fild DIV$(2624, 32)
#define OPL$Fadd DIV$(2656, 32)
#define OPL$Fsub DIV$(2688, 32)
#define OPL$Fmul DIV$(2720, 32)
#define OPL$Fdiv DIV$(2752, 32)
#define OPL$Fabs DIV$(2784, 32)
#define OPL$Fchs DIV$(2816, 32)
#define OPL$Fcmp DIV$(2848, 32)
#define OPL$NewStat DIV$(3136, 32)
#define OPL$VarEntryTag 140
#define OPL$EntryTag 130
#define OPL$commandTag 131
#define OPL$pointerTag 132
#define OPL$importTag 133
#define OPL$VarConsLinkTag 141
#define OPL$LinkTag 134
#define OPL$DataTag 135
#define OPL$ExportTag 136
#define OPL$CodeTag 137
#define OPL$UseTag 138
#define OPL$TypeTag 139
#define OPL$RefTag 140
#define OPL$noHint (-1)
#define OPL$useEAX 0
#define OPL$useECX 1
#define OPL$useEDX 2
#define OPL$useEBX 3
#define OPL$useESP 4
#define OPL$useEBP 5
#define OPL$useESI 6
#define OPL$useEDI 7
#define OPL$useST 8
#define OPL$tryEAX 16
#define OPL$tryECX 17
#define OPL$tryEDX 18
#define OPL$tryEBX 19
#define OPL$tryESI 22
#define OPL$tryEDI 23
#define OPL$useReg (0 | 1u << 0 | 1u << 1 | 1u << 2 | 1u << 3 | 1u << 4 | 1u << 5 | 1u << 6 | 1u << 7)
#define OPL$tryReg (0 | 1u << 16 | 1u << 17 | 1u << 18 | 1u << 19 | 1u << 22 | 1u << 23)
#define OPL$none (-1)
#define OPL$RiscFP (-2)
#define OPL$RiscESP (-3)
#define OPL$noScale 0
#define OPL$Scale1 0
#define OPL$Scale2 1
#define OPL$Scale4 2
#define OPL$RegReg 0
#define OPL$RegMem 1
#define OPL$MemReg 2
#define OPL$ImmReg 3
#define OPL$ImmMem 4
#define OPL$Nil (-1)
#define OPL$WithTrap 1
#define OPL$CaseTrap 2
#define OPL$FuncTrap 3
#define OPL$EqualGuardTrap 5
#define OPL$GuardTrap 6
#define OPL$OverflowTrap 4
#define OPL$RangeTrap 7
#define OPL$DimTrap 9
#define OPL$nofTrapFixups 10
#define OPL$PtrInit 5
#define OPL$CaseTabelIndex 0
#define OPL$CaseTableEntryNr 255
#define OPL$LocProcAssIndex 1
#define OPL$LocProcAssEntryNr 254
#define OPL$NewLinkIndex 2
#define OPL$NewEntryNr 253
#define OPL$NewSysLinkIndex 3
#define OPL$NewSysEntryNr 252
#define OPL$NewArrayLinkIndex 4
#define OPL$NewArrayEntryNr 251
#define OPL$StartIndex 5
#define OPL$StartEntryNr 250
#define OPL$AwaitIndex 6
#define OPL$AwaitEntryNr 249
#define OPL$LockIndex 7
#define OPL$LockEntryNr 247
#define OPL$UnlockIndex 8
#define OPL$UnlockEntryNr 246
#define OPL$InitLinks 9
/* public */ typedef struct OPL$Instruction {
    struct OPL$Instruction$Class$* class$;
    int8_t scale;
    int8_t reg;
    int16_t op;
    int32_t dest;
    int32_t src1;
    int32_t src2;
    int32_t inx;
    int32_t pc;
    int32_t hint;
    int16_t link;
    int16_t used;
    OPT$Node node;
    uint8_t abs;
} OPL$Instruction;
void OPL$Instruction$init$(OPL$Instruction* obj, unsigned int n);
struct OPL$Instruction$Class$ {
    void* super$;
};
extern struct OPL$Instruction$Class$ OPL$Instruction$class$;
/* public */ // no typedef for pointer to array OPL$InstructionTable (using MIC$DA instead)
// no typedef for open array OPL$_$0 (OPL$Instruction*)
/* public */ // no typedef for pointer to array OPL$Map (using MIC$DA instead)
typedef struct OPL$_$1 {
    struct OPL$_$1$Class$* class$;
    int32_t pos;
    int32_t pc;
} OPL$_$1;
void OPL$_$1$init$(OPL$_$1* obj, unsigned int n);
struct OPL$_$1$Class$ {
    void* super$;
};
extern struct OPL$_$1$Class$ OPL$_$1$class$;
/* public */ // no typedef for open array OPL$MapDesc (OPL$_$1*)
/* public */ extern OPL$Instruction* OPL$Instr;
/* public */ extern int32_t OPL$mapSize;
/* public */ extern OPL$_$1* OPL$map;
#define OPL$MaxCommands 128
#define OPL$MaxNewMethods 16
#define OPL$MaxExtensions 15
#define OPL$MaxEntry 128
#define OPL$LinkLength 512
#define OPL$MaxSaveLevel 32
#define OPL$Var 1
#define OPL$VarPar 2
#define OPL$Con 3
#define OPL$Fld 4
#define OPL$Typ 5
#define OPL$LProc 6
#define OPL$XProc 7
#define OPL$CProc 9
#define OPL$IProc 10
#define OPL$Module 11
#define OPL$TProc 13
#define OPL$Undef 0
#define OPL$Byte 1
#define OPL$Bool 2
#define OPL$Char 3
#define OPL$SInt 4
#define OPL$Int 5
#define OPL$LInt 6
#define OPL$Real 7
#define OPL$LReal 8
#define OPL$Set 9
#define OPL$String 10
#define OPL$NilTyp 11
#define OPL$NoTyp 12
#define OPL$Pointer 13
#define OPL$ProcTyp 14
#define OPL$Comp 15
#define OPL$HInt 16
#define OPL$Basic 1
#define OPL$StaticArr 2
#define OPL$SDynArr 3
#define OPL$DynArr 4
#define OPL$OpenArr 5
#define OPL$Record 6
#define OPL$internal 0
#define OPL$external 1
#define OPL$externalR 2
#define OPL$hasBody 1
#define OPL$slNeeded 3
#define OPL$activeObj 5
#define OPL$false 0
#define OPL$true 1
#define OPL$noEntry (-1)
#define OPL$BUG 41
#define OPL$EAX 0
#define OPL$ECX 1
#define OPL$EDX 2
#define OPL$EBX 3
#define OPL$ESP 4
#define OPL$EBP 5
#define OPL$ESI 6
#define OPL$EDI 7
#define OPL$AX 8
#define OPL$CX 9
#define OPL$DX 10
#define OPL$BX 11
#define OPL$SP 12
#define OPL$BP 13
#define OPL$SI 14
#define OPL$DI 15
#define OPL$AL 16
#define OPL$CL 17
#define OPL$DL 18
#define OPL$BL 19
#define OPL$AH 20
#define OPL$CH 21
#define OPL$DH 22
#define OPL$BH 23
#define OPL$SplittableReg (0 | 1u << 0 | 1u << 1 | 1u << 2 | 1u << 3 | 1u << 8 | 1u << 9 | 1u << 10 | 1u << 11)
#define OPL$noDisp 0
#define OPL$Disp8 1
#define OPL$Disp32 2
#define OPL$RegSt 5
#define OPL$StReg 6
#define OPL$StRegP 7
#define OPL$MemSt 8
#define OPL$Regs 0
#define OPL$Mem 2
#define OPL$Imme 3
#define OPL$Bit8 16
#define OPL$Bit16 8
#define OPL$Bit32 0
#define OPL$Bit64 40
#define OPL$sReal 0
#define OPL$lReal 2
#define OPL$eReal 4
#define OPL$sInt 1
#define OPL$noBase (-1)
#define OPL$noInx (-1)
#define OPL$noImm 0
#define OPL$free (-1)
#define OPL$Occupied -32768
#define OPL$Splitted (-32768 + 1)
#define OPL$ROR 1
#define OPL$ROL 0
#define OPL$RCL 2
#define OPL$RCR 3
#define OPL$SHL 4
#define OPL$SAL 4
#define OPL$SHR 5
#define OPL$SAR 7
#define OPL$CMPS 83
#define OPL$INS 54
#define OPL$LODS 86
#define OPL$MOVS 82
#define OPL$OUTS 55
#define OPL$SCAS 87
#define OPL$STOS 85
#define OPL$JO 0
#define OPL$JNO 1
#define OPL$JB 2
#define OPL$JC 2
#define OPL$JNAE 2
#define OPL$JNB 3
#define OPL$JNC 3
#define OPL$JAE 3
#define OPL$JE 4
#define OPL$JZ 4
#define OPL$JNE 5
#define OPL$JNZ 5
#define OPL$JBE 6
#define OPL$JNA 6
#define OPL$JNBE 7
#define OPL$JA 7
#define OPL$JS 8
#define OPL$JNS 9
#define OPL$JP 10
#define OPL$JPE 10
#define OPL$JNP 11
#define OPL$JPO 11
#define OPL$JL 12
#define OPL$JNGE 12
#define OPL$JNL 13
#define OPL$JGE 13
#define OPL$JLE 14
#define OPL$JNG 14
#define OPL$JNLE 15
#define OPL$JG 15
#define OPL$SETO 0
#define OPL$SETNO 1
#define OPL$SETB 2
#define OPL$SETNAE 2
#define OPL$SETAE 3
#define OPL$SETNB 3
#define OPL$SETE 4
#define OPL$SETZ 4
#define OPL$SETNE 5
#define OPL$SETNZ 5
#define OPL$SETBE 6
#define OPL$SETNA 6
#define OPL$SETNBE 7
#define OPL$SETA 7
#define OPL$SETS 8
#define OPL$SETNS 9
#define OPL$SETP 10
#define OPL$SETPE 10
#define OPL$SETNP 11
#define OPL$SETPO 11
#define OPL$SETL 12
#define OPL$SETNGE 12
#define OPL$SETNL 13
#define OPL$SETGE 13
#define OPL$SETLE 14
#define OPL$SETNG 14
#define OPL$SETNLE 15
#define OPL$SETG 15
#define OPL$ADD 0
#define OPL$ADC 16
#define OPL$SUB 40
#define OPL$SBB 24
#define OPL$CMP 56
#define OPL$AND 32
#define OPL$Or 8
#define OPL$XOR 48
#define OPL$FCOMPP 0
#define OPL$FTST 1
#define OPL$FLDZ 2
#define OPL$FLD1 3
#define OPL$FABS 4
#define OPL$FCHS 5
#define OPL$FSTSW 6
#define OPL$FINCSTP 7
#define OPL$FDECSTP 8
#define OPL$SAHF 158
#define OPL$CLD 252
#define OPL$STD 253
#define OPL$CBW 152
#define OPL$CWD 153
#define OPL$CLI 250
#define OPL$STI 251
#define OPL$EUEnd 0
#define OPL$EURecord 1
#define OPL$EUProcFlag ((int32_t)2147483648U)
#define OPL$notag 1
#define OPL$stdcall 2
#define OPL$cdecl 3
#define OPL$untraced 4
#define OPL$delegate 5
typedef struct OPL$LinkRec {
    struct OPL$LinkRec$Class$* class$;
    int16_t offset;
    int16_t mod;
    int16_t entry;
} OPL$LinkRec;
void OPL$LinkRec$init$(OPL$LinkRec* obj, unsigned int n);
struct OPL$LinkRec$Class$ {
    void* super$;
};
extern struct OPL$LinkRec$Class$ OPL$LinkRec$class$;
typedef struct OPL$VarConsRec {
    struct OPL$VarConsRec$Class$* class$;
    int16_t mod;
    int16_t entry;
    int16_t noflinks;
    int16_t index;
} OPL$VarConsRec;
void OPL$VarConsRec$init$(OPL$VarConsRec* obj, unsigned int n);
struct OPL$VarConsRec$Class$ {
    void* super$;
};
extern struct OPL$VarConsRec$Class$ OPL$VarConsRec$class$;
// no typedef for pointer to array OPL$VarConsTable (using MIC$DA instead)
// no typedef for open array OPL$_$2 (OPL$VarConsRec*)
typedef struct OPL$VarConsLinkRec {
    struct OPL$VarConsLinkRec$Class$* class$;
    int16_t offset;
    int16_t next;
} OPL$VarConsLinkRec;
void OPL$VarConsLinkRec$init$(OPL$VarConsLinkRec* obj, unsigned int n);
struct OPL$VarConsLinkRec$Class$ {
    void* super$;
};
extern struct OPL$VarConsLinkRec$Class$ OPL$VarConsLinkRec$class$;
// no typedef for pointer to array OPL$VarConsLinkTable (using MIC$DA instead)
// no typedef for open array OPL$_$3 (OPL$VarConsLinkRec*)
typedef struct OPL$_$4 { int16_t $[8]; } OPL$_$4;
typedef struct OPL$SavedRegRec {
    struct OPL$SavedRegRec$Class$* class$;
    OPL$_$4 reg;
    OPL$_$4 sreg;
    OPL$_$4 freg;
} OPL$SavedRegRec;
void OPL$SavedRegRec$init$(OPL$SavedRegRec* obj, unsigned int n);
struct OPL$SavedRegRec$Class$ {
    void* super$;
};
extern struct OPL$SavedRegRec$Class$ OPL$SavedRegRec$class$;
// no typedef for pointer to array OPL$PtrTable (using MIC$DA instead)
// no typedef for open array OPL$_$5 (int32_t*)
// no typedef for pointer to array OPL$RecTable (using MIC$DA instead)
// no typedef for open array OPL$_$6 (OPT$Struct*)
// no typedef for pointer to array OPL$EntryTable (using MIC$DA instead)
// no typedef for open array OPL$_$7 (int16_t*)
// no typedef for pointer to array OPL$ExpTable (using MIC$DA instead)
// no typedef for open array OPL$_$8 (int32_t*)
extern int32_t* OPL$ptrTab;
extern OPT$Struct* OPL$recTab;
extern int16_t* OPL$entry;
extern OPL$VarConsRec* OPL$varConsLink;
typedef struct OPL$_$9 { OPL$LinkRec $[512]; } OPL$_$9;
void OPL$_$9$init$(OPL$_$9* obj, unsigned int n);
extern OPL$_$9 OPL$link;
extern OPL$VarConsLinkRec* OPL$varConsTab;
extern int16_t OPL$nofVarCons;
extern int16_t OPL$noVarEntries;
extern int16_t OPL$nofEntries;
extern int16_t OPL$nofVarConsLinks;
extern int16_t OPL$nofLinks;
extern int16_t OPL$nofrecs;
extern int32_t OPL$nofptrs;
extern uint8_t OPL$ConstErr;
extern uint8_t OPL$RegErr;
extern uint8_t OPL$VarEntryErr;
extern uint8_t OPL$LinkErr;
typedef struct OPL$_$10 { int32_t $[8]; } OPL$_$10;
extern OPL$_$10 OPL$regTab;
extern OPL$_$10 OPL$sregTab;
extern OPL$_$10 OPL$fregTab;
typedef struct OPL$_$11 { OPL$SavedRegRec $[32]; } OPL$_$11;
void OPL$_$11$init$(OPL$_$11* obj, unsigned int n);
extern OPL$_$11 OPL$savedRegs;
extern int16_t OPL$nofSavedLevel;
extern int8_t OPL$ftop;
typedef struct OPL$_$12 { int32_t $[10]; } OPL$_$12;
extern OPL$_$12 OPL$trapFixupTab;
typedef struct OPL$_$13 { int8_t $[((DIV$(1856, 32) - DIV$(1504, 32)) + 1)]; } OPL$_$13;
extern OPL$_$13 OPL$JmpConvert;
typedef struct OPL$_$14 { int8_t $[((DIV$(1472, 32) - DIV$(1120, 32)) + 1)]; } OPL$_$14;
extern OPL$_$14 OPL$SetccConvert;
extern int8_t OPL$FreeRegDisp;
extern int16_t OPL$nofStr;
/* public */ extern int32_t OPL$linkTable;
/* public */ extern int32_t OPL$gVarLink;
extern int32_t* OPL$explist;
extern int32_t OPL$exppos;
/* public */ extern void OPL$Init();
extern void OPL$GetReg8(int8_t* reg);
extern void OPL$GetThisReg8(int8_t this);
extern void OPL$GetSplittableReg(int8_t* reg);
extern void OPL$GetReg(int8_t* reg);
extern void OPL$GetThisReg(int8_t this);
extern void OPL$AssignNewReg(int32_t pReg);
extern void OPL$AssignThisReg(int32_t pReg, int8_t this);
extern void OPL$AssignReg(int32_t pReg, int8_t* reg, int8_t* base, int8_t* inx);
extern void OPL$FreeReg(int8_t reg);
extern void OPL$DecReg(int8_t reg);
extern void OPL$DecCheckReg(int32_t pReg, int8_t src, int8_t base, int8_t inx);
extern uint8_t OPL$loaded(int32_t pReg);
extern void OPL$FindReg(int32_t pReg, int8_t* reg);
extern void OPL$FindLoadReg(int32_t pReg, int8_t* reg);
extern uint8_t OPL$LastUse(int8_t reg);
extern void OPL$FindMemReg(OPL$Instruction* instr, int8_t* mode, int8_t* scale, int8_t* size, int8_t* base, int8_t* inx, int32_t* disp);
extern void OPL$Load(OPL$Instruction* instr);
extern void OPL$LoadProc(OPL$Instruction* instr);
extern void OPL$Store(OPL$Instruction* instr);
extern void OPL$GenPortIO(OPL$Instruction* instr);
extern void OPL$GenPush(OPL$Instruction* instr);
extern void OPL$GenPop(OPL$Instruction* instr);
extern void OPL$Gen1(OPL$Instruction* instr, int32_t RiscPC);
extern void OPL$Gen2(OPL$Instruction* instr);
extern void OPL$Gen3(OPL$Instruction* instr);
extern void OPL$Flags(OPL$Instruction* instr);
extern void OPL$GenAbs(OPL$Instruction* instr);
extern void OPL$GenDivMod(OPL$Instruction* instr);
extern void OPL$GenMul(OPL$Instruction* instr);
extern void OPL$GenRepMovs(OPL$Instruction* instr);
extern void OPL$GenCmpString(OPL$Instruction* instr);
extern void OPL$Setcc(OPL$Instruction* instr);
extern void OPL$GenTrap(int32_t trapNr);
extern void OPL$GenIntpt(OPL$Instruction Instr);
extern void OPL$GenTrapCC(OPL$Instruction* instr);
extern void OPL$FixupAndGenTrap();
extern void OPL$GenShort(OPL$Instruction* instr);
extern void OPL$GenPhi(OPL$Instruction* instr);
extern void OPL$GetFreg(int8_t* freg);
extern void OPL$FreeFreg(int8_t freg);
extern void OPL$ReleaseFreg(int8_t freg);
extern void OPL$AssignFreg(int32_t pReg);
extern void OPL$TakeFreg(int32_t pReg, int8_t freg);
extern void OPL$FindFreg(int32_t pReg, int8_t* freg);
extern uint8_t OPL$LastUseF(int8_t freg);
extern void OPL$DecCheckFreg(int8_t freg);
extern void OPL$Fload(OPL$Instruction* instr);
extern void OPL$Fstore(OPL$Instruction* instr);
extern void OPL$FloatGen1(OPL$Instruction* instr);
extern void OPL$FloatGen3(OPL$Instruction* instr);
extern void OPL$FloatCmp(OPL$Instruction* instr);
extern void OPL$GenEntier(OPL$Instruction* instr);
extern void OPL$ClearSDynArr(OPL$Instruction* instr);
extern void OPL$GenEnter(int32_t locSize, OPT$Object locals, int8_t sysflag);
extern void OPL$GenLeave(int8_t sysflag);
extern void OPL$PushRegs();
extern void OPL$PopRegs(OPL$Instruction* instr);
extern void OPL$FixupJcc(int32_t label);
extern void OPL$FixupCaseTab(OPL$Instruction* instr);
extern void OPL$EncodeFixup(int32_t i);
extern void OPL$GenAsm(OPL$Instruction instr);
/* public */ extern void OPL$GenCode(int16_t pSize);
/* public */ extern void OPL$FixupLocalProcCall(OPT$Object proc);
/* public */ extern void OPL$NewVarCons(int16_t mod, int16_t entry, int32_t* index);
extern void OPL$VarConsLink(int32_t index, int32_t offset);
extern void OPL$AbsAccess(OPT$Node node, int32_t offset);
/* public */ extern void OPL$NewEntry(int32_t* entryNr);
/* public */ extern void OPL$NewLink(int32_t mod, int32_t entry, int32_t* index);
extern void OPL$AddLink(int32_t index, int32_t offset);
// no typedef for open array OPL$_$15 (uint8_t*)
/* public */ extern void OPL$AllocConst(MIC$AP s, int32_t len, int32_t align, int32_t* adr);
/* public */ extern void OPL$AllocCaseTab(int32_t low, int32_t high, int32_t* tab);
/* public */ extern void OPL$AllocTypDesc(OPT$Struct typ);
/* public */ extern void OPL$CaseJump(int32_t Label, int32_t tab, int32_t from, int32_t to);
/* public */ extern void OPL$OutRefPoint(OPT$Object proc);
// no typedef for open array OPL$_$16 (uint8_t*)
/* public */ extern void OPL$OutRefName(MIC$AP name);
/* public */ extern void OPL$OutRefs(OPT$Object obj);
extern int32_t OPL$LSW(int32_t x);
extern void OPL$Export(OPT$Object obj, int16_t* nofExp);
typedef struct OPL$_$17 { uint8_t $[32]; } OPL$_$17;
extern void OPL$Use(OPT$Object obj);
// no typedef for open array OPL$_$18 (uint8_t*)
/* public */ extern void OPL$OutCode(MIC$AP modName);
typedef struct OPL$_$19 { OPT$Object $[128]; } OPL$_$19;
typedef struct OPL$_$20 { OPT$Object $[128]; } OPL$_$20;
typedef struct OPL$_$21 { int8_t $[128]; } OPL$_$21;
/* public */ extern void OPL$Close();
extern void OPL$BEGIN$();
extern void OPL$init$(void);

#endif // __OPL_INCLUDED__