#ifndef __OPM_INCLUDED__
#define __OPM_INCLUDED__

// OPM.h
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include <stdint.h>
#include "Fonts.h"
#include "Texts.h"
#include "Oberon.h"
#include "Files.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPM$ByteSize 1
#define OPM$CharSize 1
#define OPM$BoolSize 1
#define OPM$SetSize 4
#define OPM$SIntSize 1
#define OPM$IntSize 2
#define OPM$LIntSize 4
#define OPM$HIntSize 8
#define OPM$RealSize 4
#define OPM$LRealSize 8
#define OPM$ProcSize 4
#define OPM$PointerSize 4
#define OPM$nilval 0
#define OPM$MinSInt (-128)
#define OPM$MinInt (-32768)
#define OPM$MinLInt ((int32_t)2147483648U)
#define OPM$MinRealPat ((int32_t)4286578687U)
#define OPM$MinLRealPatL ((int32_t)4294967295U)
#define OPM$MinLRealPatH ((int32_t)4293918719U)
#define OPM$MaxSInt 127
#define OPM$MaxInt 32767
#define OPM$MaxLInt 2147483647
#define OPM$MaxSet 31
#define OPM$MaxRealPat 2139095039
#define OPM$MaxLRealPatL ((int32_t)4294967295U)
#define OPM$MaxLRealPatH 2146435071
#define OPM$MaxIndex 2147483647
#define OPM$MaxHDig 8
#define OPM$MaxRExp 38
#define OPM$MaxLExp 308
#define OPM$MinHaltNr 20
#define OPM$MaxHaltNr 2147483647L
#define OPM$MinRegNr 0
#define OPM$MaxRegNr 31
#define OPM$MaxSysFlag 0
#define OPM$MaxCC (-1)
#define OPM$LANotAlloc (-1)
#define OPM$ConstNotAlloc (-1)
#define OPM$TDAdrUndef (-1)
#define OPM$MaxCases 128
#define OPM$MaxCaseRange 512
#define OPM$NEWusingAdr 0
#define OPM$TDMask 0
#define OPM$OptimizeSelf 1
#define OPM$WarnUnsafe 0
#define OPM$Eot 0
#define OPM$SetLen (31 + 1)
#define OPM$NumErrors (DIV$((912 + (31 + 1)), (31 + 1)) * (31 + 1))
#define OPM$PathChar "/"
#define OPM$inxchk 0
#define OPM$ovflchk 1
#define OPM$typchk 3
#define OPM$ptrinit 5
#define OPM$assert 6
#define OPM$fullstackinit 20
#define OPM$trace 22
#define OPM$exportDefinitions 30
#define OPM$useDefinitions 31
#define OPM$findpc 7
#define OPM$systemchk 8
#define OPM$nofiles 9
#define OPM$newsf 10
#define OPM$extsf 11
#define OPM$warning 12
#define OPM$prefix 18
#define OPM$oberon2 19
#define OPM$oberon1 21
#define OPM$traceprocs 24
#define OPM$DefaultCodeOpt (0 | 1u << 0 | 1u << 3 | 1u << 5 | 1u << 20 | 1u << 6)
#define OPM$DefaultParserOpt (0)
#define OPM$NewFileFormat 0
/* public */ extern float OPM$MinReal;
/* public */ extern float OPM$MaxReal;
/* public */ extern double OPM$MinLReal;
/* public */ extern double OPM$MaxLReal;
/* public */ extern uint8_t OPM$noerr;
/* public */ extern int32_t OPM$curpos;
/* public */ extern int32_t OPM$errpos;
/* public */ extern int32_t OPM$breakpos;
/* public */ extern int32_t OPM$breakpc;
typedef struct OPM$_$0 { int32_t $[DIV$((DIV$((912 + (31 + 1)), (31 + 1)) * (31 + 1)), (31 + 1))]; } OPM$_$0;
extern OPM$_$0 OPM$errors;
typedef struct OPM$_$1 { uint8_t $[32]; } OPM$_$1;
/* public */ extern OPM$_$1 OPM$outputPath;
typedef struct OPM$_$2 { uint8_t $[32]; } OPM$_$2;
/* public */ extern OPM$_$2 OPM$outputPrefix;
/* public */ extern int32_t OPM$codeOptions;
/* public */ extern int32_t OPM$parserOptions;
typedef struct OPM$_$3 { uint8_t $[32]; } OPM$_$3;
/* public */ extern OPM$_$3 OPM$errName;
extern uint8_t OPM$first;
typedef struct OPM$_$4 { uint8_t $[8]; } OPM$_$4;
/* public */ extern OPM$_$4 OPM$extension;
#define OPM$OFtag 187
#define OPM$OFnative 175
#define OPM$OFnew 176
#define OPM$OFportable 136
typedef struct OPM$_$5 {
    struct OPM$_$5$Class$* class$;
    int32_t L;
    int32_t H;
} OPM$_$5;
void OPM$_$5$init$(OPM$_$5* obj, unsigned int n);
struct OPM$_$5$Class$ {
    void* super$;
};
extern struct OPM$_$5$Class$ OPM$_$5$class$;
extern OPM$_$5 OPM$LRealPat;
extern int32_t OPM$lastpos;
extern int32_t OPM$pat;
extern int32_t OPM$refpatch;
extern Texts$Reader OPM$inR;
extern Texts$Text OPM$Log;
extern Texts$Writer OPM$W;
extern Files$Rider OPM$oldSymF;
extern Files$Rider OPM$newSymF;
extern Files$Rider OPM$ObjF;
extern Files$Rider OPM$RefF;
extern Files$Rider OPM$ModF;
extern Files$File OPM$RefFile;
extern Files$File OPM$ObjFile;
extern Files$File OPM$ModFile;
extern Files$File OPM$oldSymFile;
extern Files$File OPM$newSymFile;
/* public */ extern void OPM$Init(int32_t codeOpt, int32_t parserOpt, Texts$Reader source, Texts$Text log);
/* public */ extern void OPM$Close();
/* public */ extern void OPM$Get(uint8_t* ch);
// no typedef for open array OPM$_$6 (uint8_t*)
// no typedef for open array OPM$_$7 (uint8_t*)
extern void OPM$MakeFileName(MIC$AP path, MIC$AP prefix, MIC$AP modName, MIC$AP fileName, MIC$AP ext);
/* public */ extern void OPM$FPrint(int32_t* fp, int32_t val);
/* public */ extern void OPM$FPrintSet(int32_t* fp, int32_t set);
/* public */ extern void OPM$FPrintReal(int32_t* fp, float real);
/* public */ extern void OPM$FPrintLReal(int32_t* fp, double lr);
// no typedef for open array OPM$_$8 (uint8_t*)
extern void OPM$WString(Files$Rider* R, MIC$AP s);
/* public */ extern void OPM$LogW(uint8_t ch);
// no typedef for open array OPM$_$9 (uint8_t*)
/* public */ extern void OPM$LogWStr(MIC$AP s);
/* public */ extern void OPM$LogWNum(int32_t i, int32_t len);
/* public */ extern void OPM$LogWHex(int32_t i);
/* public */ extern void OPM$LogWLn();
// no typedef for open array OPM$_$10 (uint8_t*)
extern void OPM$ErrorText(int16_t n, MIC$AP msg);
extern void OPM$ErrorMsg(int16_t n);
typedef struct OPM$_$11 { uint8_t $[127]; } OPM$_$11;
/* public */ extern void OPM$Mark(int16_t n, int32_t pos);
/* public */ extern void OPM$err(int16_t n);
/* public */ extern void OPM$SymW(uint8_t b);
/* public */ extern void OPM$SymWCh(uint8_t ch);
/* public */ extern void OPM$SymWTag(int16_t k);
/* public */ extern void OPM$SymWInt(int32_t k);
/* public */ extern void OPM$SymWLInt(int32_t k);
/* public */ extern void OPM$SymWNum(int32_t i);
/* public */ extern int32_t OPM$SymWPos();
// no typedef for open array OPM$_$12 (uint8_t*)
/* public */ extern void OPM$SymWMod(MIC$AP name);
/* public */ extern void OPM$SymWSet(int32_t s);
/* public */ extern void OPM$SymWReal(float r);
/* public */ extern void OPM$SymWLReal(double lr);
// no typedef for open array OPM$_$13 (uint8_t*)
/* public */ extern void OPM$SymWString(MIC$AP s);
/* public */ extern void OPM$RefW(uint8_t ch);
/* public */ extern void OPM$RefWNum(int32_t i);
/* public */ extern void OPM$ObjW(uint8_t ch);
/* public */ extern void OPM$ObjWInt(int16_t i);
/* public */ extern void OPM$ObjWLInt(int32_t i);
// no typedef for open array OPM$_$14 (uint8_t*)
/* public */ extern void OPM$ObjWBytes(MIC$AP bytes, int32_t n);
/* public */ extern void OPM$ObjWNum(int32_t i);
// no typedef for open array OPM$_$15 (uint8_t*)
/* public */ extern void OPM$ObjWString(MIC$AP s);
/* public */ extern int32_t OPM$ObjAllocInt();
/* public */ extern void OPM$ObjFillInt(int32_t pos, int16_t int_);
// no typedef for open array OPM$_$16 (uint8_t*)
/* public */ extern void OPM$OpenSym(Files$Rider* R, MIC$AP name, uint8_t self, uint8_t* done);
typedef struct OPM$_$17 { uint8_t $[512]; } OPM$_$17;
typedef struct OPM$_$18 { uint8_t $[1]; } OPM$_$18;
// no typedef for open array OPM$_$19 (uint8_t*)
/* public */ extern void OPM$Begin(MIC$AP modName);
typedef struct OPM$_$20 { uint8_t $[512]; } OPM$_$20;
extern void OPM$Commit(Files$File F);
/* public */ extern void OPM$EndSym();
/* public */ extern void OPM$EndObj();
/* public */ extern void OPM$CloseObj();
extern void OPM$BEGIN$();
extern void OPM$init$(void);

#endif // __OPM_INCLUDED__