// OPO.c
// this file was generated by AoCodeNavigator 0.6.10 on Mo. Feb. 23 23:59:33 2026

#include "OPO.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

/* public */ int32_t OPO$pc;

/* public */ int32_t OPO$dsize;

/* public */ int32_t OPO$csize;

/* public */ int8_t OPO$lastImmSize;

/* public */ uint8_t* OPO$constant = NULL;

/* public */ OPO$_$1 OPO$code;

/* public */ uint8_t OPO$CodeErr;

/* public */ void OPO$PutByte(int16_t b) {
    if( (OPO$pc >= 65000) ) { 
        if( (!OPO$CodeErr) ) { 
            OPM$err(210);
            OPO$CodeErr = 1;
        }
        OPO$pc = 0;
    } else { 
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(b);
        OPO$pc++;
        if( (OPO$pc >= OPM$breakpc) ) { 
            OPM$err(255);
            OPM$breakpc = 2147483647L;
        }
    }
}

void OPO$PutWord(int32_t w) {
    if( (OPO$pc >= (65000 - 2)) ) { 
        if( (!OPO$CodeErr) ) { 
            OPM$err(210);
            OPO$CodeErr = 1;
        }
        OPO$pc = 0;
    } else { 
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$MOD(w, 256));
        OPO$pc++;
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$MOD(OBERON$DIV(w, 256), 256));
        OPO$pc++;
        if( (OPO$pc >= OPM$breakpc) ) { 
            OPM$err(255);
            OPM$breakpc = 2147483647L;
        }
    }
}

/* public */ void OPO$PutDWord(int32_t dw) {
    if( (OPO$pc >= (65000 - 4)) ) { 
        if( (!OPO$CodeErr) ) { 
            OPM$err(210);
            OPO$CodeErr = 1;
        }
        OPO$pc = 0;
    } else { 
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$MOD(dw, 256));
        OPO$pc++;
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$MOD(OBERON$DIV(dw, 256), 256));
        OPO$pc++;
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$MOD(OBERON$DIV(dw, 65536), 256));
        OPO$pc++;
        ((uint8_t*)OPO$code.$)[OPO$pc] = (uint8_t)(OBERON$DIV(dw, 16777216));
        OPO$pc++;
        if( (OPO$pc >= OPM$breakpc) ) { 
            OPM$err(255);
            OPM$breakpc = 2147483647L;
        }
    }
}

/* public */ void OPO$PutByteAt(int32_t pos, int16_t byte) {
    int32_t currentPC;
    currentPC = OPO$pc;
    OPO$pc = pos;
    OPO$PutByte(byte);
    OPO$pc = currentPC;
}

/* public */ void OPO$PutDWordAt(int32_t pos, int32_t dw) {
    int32_t currentPC;
    currentPC = OPO$pc;
    OPO$pc = pos;
    OPO$PutDWord(dw);
    OPO$pc = currentPC;
}

void OPO$GetByte(int32_t pos, int16_t* byte) {
    (*byte) = (int32_t)(uint8_t)(((uint8_t*)OPO$code.$)[pos]);
}

/* public */ void OPO$GetDWord(int32_t pos, int32_t* dw) {
    int16_t byte;
    (*dw) = (((int32_t)(uint8_t)(((uint8_t*)OPO$code.$)[pos]) + ((int32_t)((int32_t)(uint8_t)(((uint8_t*)OPO$code.$)[(pos + 1)])) * 256)) + ((int32_t)((int32_t)(uint8_t)(((uint8_t*)OPO$code.$)[(pos + 2)])) * 65536));
    byte = (int32_t)(uint8_t)(((uint8_t*)OPO$code.$)[(pos + 3)]);
    if( (byte >= 128) ) { 
        byte = (byte - 256);
    }
    (*dw) = (((int32_t)(byte) * 16777216) + (*dw));
}

/* public */ void OPO$PutConsDWord(int32_t pos, int32_t dw) {
    OPO$constant[pos] = (uint8_t)(OBERON$MOD(dw, 256));
    OPO$constant[(pos + 1)] = (uint8_t)(OBERON$MOD(OBERON$DIV(dw, 256), 256));
    OPO$constant[(pos + 2)] = (uint8_t)(OBERON$MOD(OBERON$DIV(dw, 65536), 256));
    OPO$constant[(pos + 3)] = (uint8_t)(OBERON$DIV(dw, 16777216));
}

/* public */ void OPO$GetConsDWord(int32_t pos, int32_t* dw) {
    int16_t byte;
    (*dw) = (((int32_t)(uint8_t)(OPO$constant[pos]) + ((int32_t)((int32_t)(uint8_t)(OPO$constant[(pos + 1)])) * 256)) + ((int32_t)((int32_t)(uint8_t)(OPO$constant[(pos + 2)])) * 65536));
    byte = (int32_t)(uint8_t)(OPO$constant[(pos + 3)]);
    if( (byte >= 128) ) { 
        byte = (byte - 256);
    }
    (*dw) = (((int32_t)(byte) * 16777216) + (*dw));
}

void OPO$PutReg(int16_t reg1, int16_t reg2) {
    reg1 = OBERON$MOD(reg1, 8);
    reg2 = OBERON$MOD(reg2, 8);
    OPO$PutByte((((3 * 64) + (reg1 * 8)) + reg2));
}

void OPO$PutRMInx(int8_t mode, int16_t reg, int16_t base, int16_t inx, int16_t scale, int32_t disp) {
    reg = OBERON$MOD(reg, 8);
    inx = OBERON$MOD(inx, 8);
    if( (mode == 16) ) { 
        OPO$PutByte((((0 * 64) + (reg * 8)) + 4));
        OPO$PutByte((((scale * 64) + (inx * 8)) + 5));
        OPO$PutDWord(disp);
    } else { 
        base = OBERON$MOD(base, 8);
        if( ((disp == 0) && (base != 5)) ) { 
            OPO$PutByte((((0 * 64) + (reg * 8)) + 4));
            OPO$PutByte((((scale * 64) + (inx * 8)) + base));
        } else if( ((disp <= 127) && (disp >= (-128))) ) { 
            OPO$PutByte((((1 * 64) + (reg * 8)) + 4));
            OPO$PutByte((((scale * 64) + (inx * 8)) + base));
            OPO$PutByte((int16_t)(disp));
        } else { 
            OPO$PutByte((((2 * 64) + (reg * 8)) + 4));
            OPO$PutByte((((scale * 64) + (inx * 8)) + base));
            OPO$PutDWord(disp);
        }
    }
}

void OPO$PutRegMem(int8_t mode, int16_t reg, int16_t base, int32_t disp) {
    reg = OBERON$MOD(reg, 8);
    if( (mode == 16) ) { 
        OPO$PutByte((((0 * 64) + (reg * 8)) + 5));
        OPO$PutDWord(disp);
    } else { 
        base = OBERON$MOD(base, 8);
        if( (base == 4) ) { 
            OPO$PutRMInx(mode, reg, base, 4, 0, disp);
        } else if( ((disp == 0) && (base != 5)) ) { 
            OPO$PutByte((((0 * 64) + (reg * 8)) + base));
        } else if( ((disp <= 127) && (disp >= (-128))) ) { 
            OPO$PutByte((((1 * 64) + (reg * 8)) + base));
            OPO$PutByte((int16_t)(disp));
        } else { 
            OPO$PutByte((((2 * 64) + (reg * 8)) + base));
            OPO$PutDWord(disp);
        }
    }
}

void OPO$PutMem(int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( (base == (-1)) ) { 
        if( (inx == (-1)) ) { 
            OPO$PutRegMem(16, reg, (-1), disp);
        } else { 
            OPO$PutRMInx(16, reg, (-1), inx, scale, disp);
        }
    } else if( (inx == (-1)) ) { 
        OPO$PutRegMem(17, reg, base, disp);
    } else { 
        OPO$PutRMInx(17, reg, base, inx, scale, disp);
    }
}

void OPO$PutDisp(int32_t disp, int16_t size) {
    OPO$lastImmSize = (uint8_t)(size);
    if( (size >= 16) ) { 
        OPO$PutByte((int16_t)(disp));
    } else if( (size >= 8) ) { 
        OPO$PutWord(disp);
    } else { 
        OPO$PutDWord(disp);
    }
}

/* public */ void OPO$Prefix(int16_t reg, int8_t* w) {
    if( (((1 << reg) & (0 | (uint32_t)((((uint64_t)1 << (15 - 8 + 1)) - 1) << 8))) != 0) ) { 
        OPO$PutByte(102);
        (*w) = 1;
    } else if( (((1 << reg) & (0 | (uint32_t)((((uint64_t)1 << (7 - 0 + 1)) - 1) << 0))) != 0) ) { 
        (*w) = 1;
    } else { 
        (*w) = 0;
    }
}

/* public */ void OPO$GenMOV(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    int16_t r;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        OPO$PutByte((138 + w));
        OPO$PutReg(reg, base);
        break;
    case 1:
        if( (((((reg == 0) || (reg == 8)) || (reg == 16)) && (inx == (-1))) && (base == (-1))) ) { 
            OPO$PutByte((162 + w));
            OPO$PutDWord(disp);
        } else { 
            OPO$PutByte((136 + w));
            OPO$PutMem(reg, base, inx, scale, disp);
        }
        break;
    case 2:
        if( (((((reg == 0) || (reg == 8)) || (reg == 16)) && (inx == (-1))) && (base == (-1))) ) { 
            OPO$PutByte((160 + w));
            OPO$PutDWord(disp);
        } else { 
            OPO$PutByte((138 + w));
            OPO$PutMem(reg, base, inx, scale, disp);
        }
        break;
    case 3:
        r = reg;
        reg = OBERON$MOD(reg, 8);
        OPO$PutByte(((176 + (w * 8)) + reg));
        OPO$PutDisp(imm, r);
        break;
    case 4:
        OPO$PutByte((198 + w));
        OPO$PutMem(reg, base, inx, scale, disp);
        OPO$PutDisp(imm, reg);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenMOVSX(int8_t mode, int8_t s, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte(15);
    OPO$PutByte((190 + s));
    switch( mode ) { 
    case 0:
        OPO$PutReg(reg, base);
        break;
    case 2:
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenMOVZX(int8_t mode, int8_t s, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte(15);
    OPO$PutByte((182 + s));
    switch( mode ) { 
    case 0:
        OPO$PutReg(reg, base);
        break;
    case 2:
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenIN(int16_t size) {
    switch( size ) { 
    case 0:
        OPO$PutByte(237);
        break;
    case 8:
        OPO$PutWord(60774);
        break;
    case 16:
        OPO$PutByte(236);
        break;
    }
}

/* public */ void OPO$GenOUT(int16_t size) {
    switch( size ) { 
    case 0:
        OPO$PutByte(239);
        break;
    case 8:
        OPO$PutWord(61286);
        break;
    case 16:
        OPO$PutByte(238);
        break;
    }
}

/* public */ void OPO$GenPUSH(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        reg = OBERON$MOD(reg, 8);
        OPO$PutByte((80 + reg));
        break;
    case 2:
        reg = 6;
        OPO$PutByte(255);
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        if( ((imm <= 127) && (imm >= (-128))) ) { 
            OPO$PutByte(106);
            OPO$PutByte((int16_t)(imm));
        } else { 
            OPO$PutByte(104);
            OPO$PutDWord(imm);
        }
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenPOP(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        reg = OBERON$MOD(reg, 8);
        OPO$PutByte((88 + reg));
        break;
    case 2:
        reg = 0;
        OPO$PutByte(143);
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenXCHG(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        if( ((reg == 0) || (reg == 8)) ) { 
            base = OBERON$MOD(base, 8);
            OPO$PutByte((144 + base));
        } else { 
            OPO$PutByte((134 + w));
            OPO$PutReg(reg, base);
        }
        break;
    case 1:
        OPO$PutByte((134 + w));
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenLEA(int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( (((reg == base) && (inx == (-1))) && (disp == 0)) ) { 
    } else { 
        OPO$PutByte(141);
        OPO$PutMem(reg, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenTyp1(int8_t op, int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    int8_t wImm;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        OPO$PutByte(((op + 2) + w));
        OPO$PutReg(reg, base);
        break;
    case 1:
        OPO$PutByte((op + w));
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 2:
        OPO$PutByte(((op + 2) + w));
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        if( (((reg == 0) || (reg == 8)) || (reg == 16)) ) { 
            OPO$PutByte(((op + 4) + w));
            OPO$PutDisp(imm, reg);
        } else { 
            if( (reg >= 16) ) { 
                OPO$PutByte(128);
                wImm = 16;
            } else if( ((imm <= 127) && (imm >= (-128))) ) { 
                OPO$PutByte(131);
                wImm = 16;
            } else { 
                OPO$PutByte(129);
                wImm = (uint8_t)(reg);
            }
            OPO$PutReg(OBERON$DIV(op, 8), reg);
            OPO$PutDisp(imm, wImm);
        }
        break;
    case 4:
        if( (reg >= 16) ) { 
            OPO$PutByte(128);
            wImm = 16;
        } else if( ((imm <= 127) && (imm >= (-128))) ) { 
            OPO$PutByte(131);
            wImm = 16;
        } else { 
            OPO$PutByte(129);
            wImm = (uint8_t)(reg);
        }
        OPO$PutMem(OBERON$DIV(op, 8), base, inx, scale, disp);
        OPO$PutDisp(imm, wImm);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenINC(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    if( (mode == 3) ) { 
        if( (w != 0) ) { 
            reg = OBERON$MOD(reg, 8);
            OPO$PutByte((64 + reg));
        } else { 
            OPO$PutByte((254 + w));
            OPO$PutReg(0, reg);
        }
    } else { 
        OPO$PutByte((254 + w));
        OPO$PutMem(0, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenDEC(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    if( (mode == 3) ) { 
        if( (w != 0) ) { 
            reg = OBERON$MOD(reg, 8);
            OPO$PutByte((72 + reg));
        } else { 
            OPO$PutByte((254 + w));
            OPO$PutReg(1, reg);
        }
    } else { 
        OPO$PutByte((254 + w));
        OPO$PutMem(1, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenNEG(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte((246 + w));
    if( (mode == 0) ) { 
        OPO$PutReg(3, reg);
    } else { 
        OPO$PutMem(3, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenIMUL(int8_t mode, uint8_t shortform, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        if( shortform ) { 
            OPO$PutByte((246 + w));
            OPO$PutReg(5, base);
        } else { 
            OPO$PutByte(15);
            OPO$PutByte(175);
            OPO$PutReg(reg, base);
        }
        break;
    case 2:
        if( shortform ) { 
            OPO$PutByte((246 + w));
            OPO$PutMem(5, base, inx, scale, disp);
        } else { 
            OPO$PutByte(15);
            OPO$PutByte(175);
            OPO$PutMem(reg, base, inx, scale, disp);
        }
        break;
    case 3:
        if( ((imm <= 127) && (imm >= (-128))) ) { 
            OPO$PutByte(107);
            OPO$PutReg(reg, base);
            OPO$PutByte((int16_t)(imm));
        } else { 
            OPO$PutByte(105);
            OPO$PutReg(reg, base);
            OPO$PutDisp(imm, base);
        }
        break;
    case 4:
        if( ((imm <= 127) && (imm >= (-128))) ) { 
            OPO$PutByte(107);
            OPO$PutMem(reg, base, inx, scale, disp);
            OPO$PutByte((int16_t)(imm));
        } else { 
            OPO$PutByte(105);
            OPO$PutMem(reg, base, inx, scale, disp);
            OPO$PutDisp(imm, base);
        }
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenIDIV(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte((246 + w));
    if( (mode == 0) ) { 
        OPO$PutReg(7, reg);
    } else { 
        OPO$PutMem(7, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenShiftRot(int8_t op, int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        OPO$PutByte((210 + w));
        OPO$PutReg(op, reg);
        break;
    case 1:
        OPO$PutByte((210 + w));
        OPO$PutMem(op, base, inx, scale, disp);
        break;
    case 3:
        if( (imm == 1) ) { 
            OPO$PutByte((208 + w));
            OPO$PutReg(op, reg);
        } else { 
            OPO$PutByte((192 + w));
            OPO$PutReg(op, reg);
            OPO$PutByte((int16_t)(imm));
        }
        break;
    case 4:
        if( (imm == 1) ) { 
            OPO$PutByte((208 + w));
            OPO$PutMem(op, base, inx, scale, disp);
        } else { 
            OPO$PutByte((192 + w));
            OPO$PutMem(op, base, inx, scale, disp);
            OPO$PutByte((int16_t)(imm));
        }
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenNOT(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte((246 + w));
    if( (mode == 0) ) { 
        OPO$PutReg(2, reg);
    } else { 
        OPO$PutMem(2, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenString(int16_t op, int16_t size) {
    int8_t w;
    OPO$Prefix(size, &w);
    OPO$PutByte(((op * 2) + w));
}

/* public */ void OPO$GenRepString(int16_t op, int16_t size) {
    int8_t w;
    OPO$Prefix(size, &w);
    OPO$PutByte(243);
    OPO$PutByte(((op * 2) + w));
}

/* public */ void OPO$GenRepCmpsScas(int16_t op, int16_t size) {
    int8_t w;
    OPO$Prefix(size, &w);
    OPO$PutByte(243);
    OPO$PutByte(((op * 2) + w));
}

/* public */ void OPO$GenTEST(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    switch( mode ) { 
    case 0:
        if( (w == 0) ) { 
            OPO$PutByte(132);
        } else { 
            OPO$PutByte(133);
        }
        OPO$PutReg(base, reg);
        break;
    case 1:
        if( (w == 0) ) { 
            OPO$PutByte(132);
        } else { 
            OPO$PutByte(133);
        }
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        if( (((1 << reg) & (0 | 1u << 0 | 1u << 8 | 1u << 16)) != 0) ) { 
            if( (w == 0) ) { 
                OPO$PutByte(168);
            } else { 
                OPO$PutByte(169);
            }
            OPO$PutDisp(imm, (OBERON$DIV(reg, 8) * 8));
        } else { 
            if( (w == 0) ) { 
                OPO$PutByte(246);
            } else { 
                OPO$PutByte(247);
            }
            OPO$PutReg(0, reg);
            OPO$PutDisp(imm, (OBERON$DIV(reg, 8) * 8));
        }
        break;
    case 4:
        if( (w == 0) ) { 
            OPO$PutByte(246);
        } else { 
            OPO$PutByte(247);
        }
        OPO$PutMem(0, base, inx, scale, disp);
        OPO$PutDisp(imm, (OBERON$DIV(reg, 8) * 8));
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenBT(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte(15);
    switch( mode ) { 
    case 0:
        OPO$PutByte(163);
        OPO$PutReg(base, reg);
        break;
    case 1:
        OPO$PutByte(163);
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        OPO$PutByte(186);
        OPO$PutReg(4, reg);
        OPO$PutByte((int16_t)(imm));
        break;
    case 4:
        OPO$PutByte(186);
        OPO$PutMem(4, base, inx, scale, disp);
        OPO$PutByte((int16_t)(imm));
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenBTR(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte(15);
    switch( mode ) { 
    case 0:
        OPO$PutByte(179);
        OPO$PutReg(base, reg);
        break;
    case 1:
        OPO$PutByte(179);
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        OPO$PutByte(186);
        OPO$PutReg(6, reg);
        OPO$PutByte((int16_t)(imm));
        break;
    case 4:
        OPO$PutByte(186);
        OPO$PutMem(6, base, inx, scale, disp);
        OPO$PutByte((int16_t)(imm));
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenBTS(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp, int32_t imm) {
    int8_t w;
    OPO$Prefix(reg, &w);
    OPO$PutByte(15);
    switch( mode ) { 
    case 0:
        OPO$PutByte(171);
        OPO$PutReg(base, reg);
        break;
    case 1:
        OPO$PutByte(171);
        OPO$PutMem(reg, base, inx, scale, disp);
        break;
    case 3:
        OPO$PutByte(186);
        OPO$PutReg(5, reg);
        OPO$PutByte((int16_t)(imm));
        break;
    case 4:
        OPO$PutByte(186);
        OPO$PutMem(5, base, inx, scale, disp);
        OPO$PutByte((int16_t)(imm));
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenCALL(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( (mode == 3) ) { 
        OPO$PutByte(232);
        OPO$PutDWord(disp);
    } else { 
        OPO$PutByte(255);
        if( (mode == 0) ) { 
            OPO$PutReg(2, reg);
        } else { 
            OPO$PutMem(2, base, inx, scale, disp);
        }
    }
}

/* public */ void OPO$GenJMP(int8_t mode, int16_t reg, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( (mode == 3) ) { 
        if( ((disp <= 127) && (disp >= (-128))) ) { 
            OPO$PutByte(235);
            OPO$PutByte((int16_t)(disp));
        } else { 
            OPO$PutByte(233);
            OPO$PutDWord(disp);
        }
    } else { 
        OPO$PutByte(255);
        if( (mode == 0) ) { 
            OPO$PutReg(4, reg);
        } else { 
            OPO$PutMem(4, base, inx, scale, disp);
        }
    }
}

/* public */ void OPO$GenRET(int32_t size) {
    if( (size == 0) ) { 
        OPO$PutByte(195);
    } else if( (size > 65535) ) { 
        OPO$GenPOP(0, 3, (-1), (-1), 0, 0);
        OPO$GenTyp1(0, 3, 4, (-1), (-1), 0, 0, size);
        OPO$GenJMP(0, 3, (-1), (-1), 0, 0);
    } else { 
        OPO$PutByte(194);
        OPO$PutWord(size);
    }
}

/* public */ void OPO$GenJcc(int8_t op, int32_t disp) {
    if( ((disp <= 127) && (disp >= (-128))) ) { 
        OPO$PutByte((112 + op));
        OPO$PutByte((int16_t)(disp));
    } else { 
        OPO$PutByte(15);
        OPO$PutByte((128 + op));
        OPO$PutDWord(disp);
    }
}

/* public */ void OPO$GenSetcc(int8_t op, int8_t mode, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    OPO$PutByte(15);
    OPO$PutByte((144 + op));
    if( (mode == 0) ) { 
        OPO$PutReg(0, base);
    } else { 
        OPO$PutMem(0, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenINT(int16_t intNumber) {
    OPO$PutByte(205);
    OPO$PutByte(intNumber);
}

/* public */ void OPO$InlineCode(MIC$AP code, int16_t parSize) {
    int16_t i;
    int16_t n;
    n = (int32_t)(uint8_t)(((uint8_t*)code.$)[0]);
    i = 1;
    while( (i <= n) ) {
        OPO$PutByte((int32_t)(uint8_t)(((uint8_t*)code.$)[i]));
        i++;
    }
}

/* public */ void OPO$GenFLD(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 0:
        OPO$PutByte(217);
        OPO$PutByte((192 + base));
        break;
    case 2:
        if( (size == 4) ) { 
            OPO$PutByte(219);
            OPO$PutMem(5, base, inx, scale, disp);
        } else { 
            OPO$PutByte((217 + (size * 2)));
            OPO$PutMem(0, base, inx, scale, disp);
        }
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFST(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 0:
        OPO$PutByte(221);
        OPO$PutByte((208 + base));
        break;
    case 1:
        OPO$PutByte((217 + (size * 2)));
        OPO$PutMem(2, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFSTP(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 0:
        OPO$PutByte(221);
        OPO$PutByte((216 + base));
        break;
    case 1:
        if( (size == 4) ) { 
            OPO$PutByte(219);
            OPO$PutMem(7, base, inx, scale, disp);
        } else { 
            OPO$PutByte((217 + (size * 2)));
            OPO$PutMem(3, base, inx, scale, disp);
        }
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFCOM(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 0:
        OPO$PutByte(216);
        OPO$PutByte((208 + base));
        break;
    case 2:
        OPO$PutByte((216 + (size * 2)));
        OPO$PutMem(2, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFCOMP(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 0:
        OPO$PutByte(216);
        OPO$PutByte((216 + base));
        break;
    case 2:
        OPO$PutByte((216 + (size * 2)));
        OPO$PutMem(3, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFtyp1(int8_t op, int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    switch( mode ) { 
    case 5:
        OPO$PutByte(216);
        OPO$PutByte(((192 + ((int16_t)(op) * 8)) + base));
        break;
    case 6:
        OPO$PutByte(220);
        OPO$PutByte(((192 + ((int16_t)(op) * 8)) + base));
        break;
    case 7:
        OPO$PutByte(222);
        OPO$PutByte(((192 + ((int16_t)(op) * 8)) + base));
        break;
    case 8:
        OPO$PutByte((216 + (size * 2)));
        OPO$PutMem(op, base, inx, scale, disp);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFADD(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    OPO$GenFtyp1(0, mode, size, base, inx, scale, disp);
}

/* public */ void OPO$GenFSUB(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( ((mode == 6) || (mode == 7)) ) { 
        OPO$GenFtyp1(5, mode, size, base, inx, scale, disp);
    } else { 
        OPO$GenFtyp1(4, mode, size, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenFSUBR(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( ((mode == 6) || (mode == 7)) ) { 
        OPO$GenFtyp1(4, mode, size, base, inx, scale, disp);
    } else { 
        OPO$GenFtyp1(5, mode, size, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenFMUL(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    OPO$GenFtyp1(1, mode, size, base, inx, scale, disp);
}

/* public */ void OPO$GenFDIV(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( ((mode == 6) || (mode == 7)) ) { 
        OPO$GenFtyp1(7, mode, size, base, inx, scale, disp);
    } else { 
        OPO$GenFtyp1(6, mode, size, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenFDIVR(int8_t mode, int8_t size, int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    if( ((mode == 6) || (mode == 7)) ) { 
        OPO$GenFtyp1(6, mode, size, base, inx, scale, disp);
    } else { 
        OPO$GenFtyp1(7, mode, size, base, inx, scale, disp);
    }
}

/* public */ void OPO$GenFFREE(int16_t freg) {
    OPO$PutByte(221);
    OPO$PutByte((192 + freg));
}

/* public */ void OPO$GenFop1(int16_t op) {
    switch( op ) { 
    case 0:
        OPO$PutByte(222);
        OPO$PutByte(217);
        break;
    case 1:
        OPO$PutByte(217);
        OPO$PutByte(228);
        break;
    case 2:
        OPO$PutByte(217);
        OPO$PutByte(238);
        break;
    case 3:
        OPO$PutByte(217);
        OPO$PutByte(232);
        break;
    case 4:
        OPO$PutByte(217);
        OPO$PutByte(225);
        break;
    case 5:
        OPO$PutByte(217);
        OPO$PutByte(224);
        break;
    case 6:
        OPO$PutByte(223);
        OPO$PutByte(224);
        break;
    case 7:
        OPO$PutByte(217);
        OPO$PutByte(247);
        break;
    case 8:
        OPO$PutByte(217);
        OPO$PutByte(246);
        break;
    default:
        exit(42);
        break;
    }
}

/* public */ void OPO$GenFSTCW(int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    OPO$PutByte(217);
    OPO$PutMem(7, base, inx, scale, disp);
}

/* public */ void OPO$GenFLDCW(int16_t base, int16_t inx, int8_t scale, int32_t disp) {
    OPO$PutByte(217);
    OPO$PutMem(5, base, inx, scale, disp);
}

void OPO$BEGIN$() {
    OPO$constant = (uint8_t*)$allocda(1024, sizeof(uint8_t));
}

static int OPO$initialized = 0;
void OPO$init$(void) {
    if( OPO$initialized ) return;
    OPO$initialized = 1;
    OPT$init$();
    OPM$init$();
    OPO$BEGIN$();
}

