#ifndef __OPP_INCLUDED__
#define __OPP_INCLUDED__

// OPP.h
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include <stdint.h>
#include "OPT.h"
#include "OPS.h"
#include "OPM.h"
#include "OPB.h"
#include "OPA.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPP$char_ 1
#define OPP$integer 2
#define OPP$real 3
#define OPP$longreal 4
#define OPP$null 0
#define OPP$times 1
#define OPP$slash 2
#define OPP$div 3
#define OPP$mod 4
#define OPP$and 5
#define OPP$plus 6
#define OPP$minus 7
#define OPP$or 8
#define OPP$eql 9
#define OPP$neq 10
#define OPP$lss 11
#define OPP$leq 12
#define OPP$gtr 13
#define OPP$geq 14
#define OPP$in 15
#define OPP$is 16
#define OPP$arrow 17
#define OPP$period 18
#define OPP$comma 19
#define OPP$colon 20
#define OPP$upto 21
#define OPP$rparen 22
#define OPP$rbrak 23
#define OPP$rbrace 24
#define OPP$of 25
#define OPP$then 26
#define OPP$do_ 27
#define OPP$to 28
#define OPP$by 29
#define OPP$lparen 30
#define OPP$lbrak 31
#define OPP$lbrace 32
#define OPP$not 33
#define OPP$becomes 34
#define OPP$number 35
#define OPP$nil 36
#define OPP$true 37
#define OPP$false 38
#define OPP$string 39
#define OPP$ident 40
#define OPP$semicolon 41
#define OPP$bar 42
#define OPP$end 43
#define OPP$else_ 44
#define OPP$elsif 45
#define OPP$until 46
#define OPP$if_ 47
#define OPP$case_ 48
#define OPP$while_ 49
#define OPP$repeat 50
#define OPP$for_ 51
#define OPP$loop 52
#define OPP$with 53
#define OPP$exit 54
#define OPP$return_ 55
#define OPP$array 56
#define OPP$object 57
#define OPP$record 58
#define OPP$pointer 59
#define OPP$begin 60
#define OPP$code 61
#define OPP$const_ 62
#define OPP$type 63
#define OPP$var 64
#define OPP$procedure 65
#define OPP$import 66
#define OPP$module 67
#define OPP$eof 68
#define OPP$Var 1
#define OPP$VarPar 2
#define OPP$Con 3
#define OPP$Fld 4
#define OPP$Typ 5
#define OPP$LProc 6
#define OPP$XProc 7
#define OPP$SProc 8
#define OPP$CProc 9
#define OPP$IProc 10
#define OPP$Mod 11
#define OPP$Head 12
#define OPP$TProc 13
#define OPP$Undef 0
#define OPP$Byte 1
#define OPP$Bool 2
#define OPP$Char 3
#define OPP$SInt 4
#define OPP$Int 5
#define OPP$LInt 6
#define OPP$Real 7
#define OPP$LReal 8
#define OPP$Set 9
#define OPP$String 10
#define OPP$NilTyp 11
#define OPP$NoTyp 12
#define OPP$Pointer 13
#define OPP$ProcTyp 14
#define OPP$Comp 15
#define OPP$intSet (0 | (uint32_t)((((uint64_t)1 << (6 - 4 + 1)) - 1) << 4))
#define OPP$Basic 1
#define OPP$StaticArr 2
#define OPP$SDynArr 3
#define OPP$DynArr 4
#define OPP$OpenArr 5
#define OPP$Record 6
#define OPP$ArraySet (0 | 1u << 2 | 1u << 3 | 1u << 4 | 1u << 5)
#define OPP$haltfn 0
#define OPP$newfn 1
#define OPP$sizefn 12
#define OPP$incfn 13
#define OPP$lenfn 17
#define OPP$sysnewfn 30
#define OPP$awaitfn 64
#define OPP$Nvar 0
#define OPP$Nvarpar 1
#define OPP$Nfield 2
#define OPP$Nderef 3
#define OPP$Nindex 4
#define OPP$Nguard 5
#define OPP$Neguard 6
#define OPP$Nconst 7
#define OPP$Ntype 8
#define OPP$Nproc 9
#define OPP$Nupto 10
#define OPP$Nmop 11
#define OPP$Ndop 12
#define OPP$Ncall 13
#define OPP$Ninittd 14
#define OPP$Nif 15
#define OPP$Ncaselse 16
#define OPP$Ncasedo 17
#define OPP$Nenter 18
#define OPP$Nassign 19
#define OPP$Nifelse 20
#define OPP$Ncase 21
#define OPP$Nwhile 22
#define OPP$Nrepeat 23
#define OPP$Nloop 24
#define OPP$Nexit 25
#define OPP$Nreturn 26
#define OPP$Nwith 27
#define OPP$Ntrap 28
#define OPP$Nassembler 29
#define OPP$Ncode 30
#define OPP$super 1
#define OPP$internal 0
#define OPP$external 1
#define OPP$externalR 2
#define OPP$hasBody 1
#define OPP$isRedef 2
#define OPP$slNeeded 3
#define OPP$locked 6
#define OPP$asmProc 7
#define OPP$operatorFlag 8
#define OPP$checkOverwriting 31
#define OPP$protectedObj 4
#define OPP$activeObj 5
#define OPP$safe 8
#define OPP$notag 1
#define OPP$stdcall 2
#define OPP$cdecl 3
#define OPP$untraced 4
#define OPP$delegate 5
#define OPP$systemtype 6
#define OPP$HiddenSelf "@SELF"
typedef struct OPP$_$0 {
    struct OPP$_$0$Class$* class$;
    int32_t low;
    int32_t high;
} OPP$_$0;
void OPP$_$0$init$(OPP$_$0* obj, unsigned int n);
struct OPP$_$0$Class$ {
    void* super$;
};
extern struct OPP$_$0$Class$ OPP$_$0$class$;
typedef struct OPP$CaseTable { OPP$_$0 $[128]; } OPP$CaseTable;
void OPP$CaseTable$init$(OPP$CaseTable* obj, unsigned int n);
#define OPP$FTarget 1
#define OPP$FExpr 2
#define OPP$FAssign 3
#define OPP$FCall 4
#define OPP$FCond 5
#define OPP$FParam 6
#define OPP$FPassExpr 7
#define OPP$FReturn 9
typedef struct OPP$FixDesc* OPP$FixPtr;
typedef struct OPP$FixDesc {
    struct OPP$FixDesc$Class$* class$;
    int32_t mode;
    OPT$Object scope;
    int8_t level;
    OPT$Node node;
    OPS$TokenStream stream;
    OPP$FixPtr next;
} OPP$FixDesc;
void OPP$FixDesc$init$(OPP$FixDesc* obj, unsigned int n);
struct OPP$FixDesc$Class$ {
    void* super$;
};
extern struct OPP$FixDesc$Class$ OPP$FixDesc$class$;
typedef struct OPP$TypeFix {
    struct OPP$TypeFix$Class$* class$;
    int32_t pos;
    OPS$Name name;
    OPT$Object scope;
    int8_t level;
} OPP$TypeFix;
void OPP$TypeFix$init$(OPP$TypeFix* obj, unsigned int n);
struct OPP$TypeFix$Class$ {
    void* super$;
};
extern struct OPP$TypeFix$Class$ OPP$TypeFix$class$;
typedef struct OPP$ObjFixDesc {
    struct OPP$ObjFixDesc$Class$* class$;
    int32_t pos;
    OPS$Name name;
    OPT$Object scope;
    int8_t level;
    OPT$Object obj;
} OPP$ObjFixDesc;
void OPP$ObjFixDesc$init$(OPP$ObjFixDesc* obj, unsigned int n);
struct OPP$ObjFixDesc$Class$ {
    struct OPP$TypeFix$Class$* super$;
};
extern struct OPP$ObjFixDesc$Class$ OPP$ObjFixDesc$class$;
typedef struct OPP$StructFixDesc {
    struct OPP$StructFixDesc$Class$* class$;
    int32_t pos;
    OPS$Name name;
    OPT$Object scope;
    int8_t level;
    OPT$Struct typ;
} OPP$StructFixDesc;
void OPP$StructFixDesc$init$(OPP$StructFixDesc* obj, unsigned int n);
struct OPP$StructFixDesc$Class$ {
    struct OPP$TypeFix$Class$* super$;
};
extern struct OPP$StructFixDesc$Class$ OPP$StructFixDesc$class$;
typedef struct OPP$_$1 { uint8_t $[80]; } OPP$_$1;
/* public */ extern OPP$_$1 OPP$SignOnMessage;
extern int8_t OPP$sym;
extern int8_t OPP$level;
extern int16_t OPP$LoopLevel;
extern OPT$Node OPP$TDinit;
extern OPT$Node OPP$lastTDinit;
extern OPT$Node OPP$RecInit;
extern OPT$Node OPP$lastRecInit;
extern OPT$Node OPP$CondNodes;
extern int8_t OPP$CondCount;
extern uint8_t OPP$UndefFlag;
extern uint8_t OPP$FixPhase;
extern OPT$Object OPP$UndefObj;
extern uint8_t OPP$scopeLock;
extern OPP$FixPtr OPP$FixList;
extern OPP$FixPtr OPP$FixLast;
extern OPT$Object OPP$ExtObj;
extern OPT$Object OPP$inc;
extern OPT$Struct OPP$ptrToRec;
typedef struct OPP$_$2 { OPP$ObjFixDesc $[128]; } OPP$_$2;
void OPP$_$2$init$(OPP$_$2* obj, unsigned int n);
extern OPP$_$2 OPP$ObjFix;
typedef struct OPP$_$4 {
    struct OPP$_$4$Class$* class$;
    OPT$Object obj;
    int8_t level;
} OPP$_$4;
void OPP$_$4$init$(OPP$_$4* obj, unsigned int n);
struct OPP$_$4$Class$ {
    void* super$;
};
extern struct OPP$_$4$Class$ OPP$_$4$class$;
typedef struct OPP$_$3 { OPP$_$4 $[256]; } OPP$_$3;
void OPP$_$3$init$(OPP$_$3* obj, unsigned int n);
extern OPP$_$3 OPP$ObjCheck;
typedef struct OPP$_$5 { OPP$StructFixDesc $[128]; } OPP$_$5;
void OPP$_$5$init$(OPP$_$5* obj, unsigned int n);
extern OPP$_$5 OPP$TypFix;
extern int32_t OPP$nofCheck;
extern int32_t OPP$nofObjFix;
extern int32_t OPP$nofTypFix;
extern void OPP$err(int16_t n);
extern void OPP$CheckSym(int16_t s);
extern uint8_t OPP$IsModuleScope();
extern uint8_t OPP$IsObjectScope();
extern uint8_t OPP$IsRecordScope();
extern void OPP$SetFlags(OPT$Object obj, int32_t flag);
extern int32_t OPP$GetFlags(OPT$Object obj);
extern void OPP$DumpScope(OPT$Object o);
extern OPT$Object OPP$GetSelf();
extern void OPP$InsertFix(int32_t mode, OPS$TokenStream stream, OPT$Node node);
extern void OPP$NewFix(OPP$TypeFix* f, OPS$Name name);
extern void OPP$NewCheck(OPT$Object obj);
extern void OPP$NewType(OPT$Object obj);
extern void OPP$CheckRecord(OPT$Struct typ);
#define OPP$CheckRecord$stamp 4660
extern void OPP$CheckArray(OPT$Struct typ);
extern void OPP$CheckPointer(OPT$Struct typ);
extern void OPP$CheckProcedure(OPT$Struct typ);
extern void OPP$CheckStruct(OPT$Struct str);
extern void OPP$CheckObj(OPT$Object obj);
extern void OPP$qualident(OPT$Object* id);
extern void OPP$ConstExpression(OPT$Node* x);
extern void OPP$CheckMark(int8_t* vis, uint8_t rdonlyAllowed);
extern void OPP$CheckSysFlag(int8_t* sysflag, int8_t default_, int32_t allowed);
extern void OPP$BlockMode(int32_t* flag, uint8_t local, uint8_t* lock);
extern void OPP$RecordType(OPT$Struct* typ, OPT$Struct* banned, OPT$Object owner);
extern void OPP$OwnScope(OPT$Object* obj);
extern void OPP$ArrayType(OPT$Struct* typ, OPT$Struct* banned);
extern void OPP$ObjectType(OPT$Struct* typ, OPT$Struct* banned);
extern void OPP$PointerType(OPT$Struct* typ, OPT$Struct* banned);
extern void OPP$FormalParameters(OPT$Object* firstPar, OPT$Struct* resTyp, int8_t sysflag);
extern void OPP$CheckAndFix(OPT$Struct typ);
extern void OPP$TypeDecl(OPT$Struct* typ, OPT$Struct* banned, OPT$Object owner);
extern void OPP$selector(OPT$Node* x);
extern void OPP$ActualParameters(OPT$Node* aparlist, OPT$Object fpar);
extern void OPP$Await(OPT$Node* x, int16_t* n);
extern void OPP$StandProcCall(OPT$Node* x);
extern void OPP$InlineProc(OPT$Node* x, OPT$Node* apar, OPT$Object fpar);
extern void OPP$Element(OPT$Node* x);
extern void OPP$Sets(OPT$Node* x);
// no typedef for open array OPP$_$7 (uint8_t*)
extern void OPP$Resolve(OPT$Object* obj, MIC$AP name, OPT$Node* x, OPT$Node* y);
extern void OPP$OpCall(OPT$Object* op, OPT$Node* x, OPT$Node y);
extern void OPP$Factor(OPT$Node* x);
extern void OPP$Term(OPT$Node* x);
extern void OPP$SimpleExpression(OPT$Node* x);
extern void OPP$Expression(OPT$Node* x);
extern void OPP$ProcedureDeclaration(OPT$Node* x);
extern void OPP$CaseLabelList(OPT$Node* lab, int16_t LabelForm, int16_t* n, MIC$AP tab);
extern void OPP$CheckBool(OPT$Node* x);
extern void OPP$DoFixes();
extern void OPP$StatSeq(OPT$Node* stat);
extern void OPP$StatBlock(OPT$Node* statseq, uint8_t local);
extern void OPP$AddTraceCode(OPT$Object owner, OPT$Node* statseq);
extern void OPP$Block(OPT$Node* procdec, OPT$Node* statseq);
extern void OPP$CreateHiddenStructs();
extern void OPP$FullName(MIC$AP fullname);
/* public */ extern void OPP$Module(OPT$Node* prog, MIC$AP modName);
extern void OPP$BEGIN$();
extern void OPP$init$(void);

#endif // __OPP_INCLUDED__