// OPS.c
// this file was generated by AoCodeNavigator 0.6.10 on Mo. Feb. 23 23:59:33 2026

#include "OPS.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void OPS$_$0$init$(OPS$_$0* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$0$class$;
    }
}

struct OPS$_$0$Class$ OPS$_$0$class$ = { 
    0,
};

void OPS$_$1$init$(OPS$_$1* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$1$class$;
    }
}

struct OPS$_$1$Class$ OPS$_$1$class$ = { 
    &OPS$_$0$class$,
};

void OPS$_$2$init$(OPS$_$2* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$2$class$;
    }
}

struct OPS$_$2$Class$ OPS$_$2$class$ = { 
    &OPS$_$0$class$,
};

void OPS$_$3$init$(OPS$_$3* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$3$class$;
    }
}

struct OPS$_$3$Class$ OPS$_$3$class$ = { 
    &OPS$_$0$class$,
};

void OPS$_$4$init$(OPS$_$4* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$4$class$;
    }
}

struct OPS$_$4$Class$ OPS$_$4$class$ = { 
    &OPS$_$0$class$,
};

void OPS$_$5$init$(OPS$_$5* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPS$_$5$class$;
    }
}

struct OPS$_$5$Class$ OPS$_$5$class$ = { 
    &OPS$_$0$class$,
};

/* public */ OPS$Name OPS$name;

/* public */ OPS$String OPS$str;

/* public */ int16_t OPS$numtyp;

/* public */ int32_t OPS$intval;

/* public */ float OPS$realval;

/* public */ double OPS$lrlval;

/* public */ OPS$GetProc OPS$Get;

/* public */ uint8_t OPS$ch;

OPS$TokenStream OPS$stream = NULL;

OPS$TokenStream OPS$last = NULL;

void OPS$err(int16_t n) {
    OPM$err(n);
}

void OPS$StreamGet(int8_t* sym) {
    if( ((OPS$stream != NULL) && ((*OPS$stream).next != NULL)) ) { 
        OPS$stream = (*OPS$stream).next;
        (*sym) = (*OPS$stream).sym;
        OPM$errpos = (*OPS$stream).pos;
        if( (OPS$stream ? $isinst(&OPS$_$1$class$, (void*)OPS$stream->class$) : 0) ) { 
            OPS$intval = (*((OPS$IntToken)OPS$stream)).intval;
            OPS$numtyp = (*((OPS$IntToken)OPS$stream)).typ;
        } else if( (OPS$stream ? $isinst(&OPS$_$2$class$, (void*)OPS$stream->class$) : 0) ) { 
            OPS$realval = (*((OPS$RealToken)OPS$stream)).realval;
            OPS$numtyp = 3;
        } else if( (OPS$stream ? $isinst(&OPS$_$3$class$, (void*)OPS$stream->class$) : 0) ) { 
            OPS$lrlval = (*((OPS$LRealToken)OPS$stream)).lrlval;
            OPS$numtyp = 4;
        } else if( (OPS$stream ? $isinst(&OPS$_$4$class$, (void*)OPS$stream->class$) : 0) ) { 
            memcpy(OPS$str.$, (*((OPS$StrToken)OPS$stream)).str.$,256 * sizeof(uint8_t));
            OPS$intval = (*((OPS$StrToken)OPS$stream)).len;
        } else if( (OPS$stream ? $isinst(&OPS$_$5$class$, (void*)OPS$stream->class$) : 0) ) { 
            memcpy(OPS$name.$, (*((OPS$NameToken)OPS$stream)).name.$,32 * sizeof(uint8_t));
        } else if( ((((1 <= (*sym)) && ((*sym) <= 17)) || ((*sym) == 33)) || ((*sym) == 34)) ) { 
            memcpy(OPS$name.$, (*((OPS$NameToken)OPS$stream)).name.$,32 * sizeof(uint8_t));
        }
    } else { 
        (*sym) = 68;
    }
}

void OPS$RecToken(int8_t sym) {
    OPS$Token s = NULL;
    OPS$RealToken r = NULL;
    OPS$LRealToken lr = NULL;
    OPS$IntToken i = NULL;
    OPS$StrToken st = NULL;
    OPS$NameToken nam = NULL;
    if( (sym == 35) ) { 
        if( (OPS$numtyp == 3) ) { 
            r = (OPS$_$2*)GC_MALLOC(sizeof(OPS$_$2)); r->class$ = &OPS$_$2$class$;
            (*r).realval = OPS$realval;
            s = (OPS$Token)r;
        } else if( (OPS$numtyp == 4) ) { 
            lr = (OPS$_$3*)GC_MALLOC(sizeof(OPS$_$3)); lr->class$ = &OPS$_$3$class$;
            (*lr).lrlval = OPS$lrlval;
            s = (OPS$Token)lr;
        } else { 
            i = (OPS$_$1*)GC_MALLOC(sizeof(OPS$_$1)); i->class$ = &OPS$_$1$class$;
            (*i).intval = OPS$intval;
            (*i).typ = OPS$numtyp;
            s = (OPS$Token)i;
        }
    } else if( (sym == 39) ) { 
        st = (OPS$_$4*)GC_MALLOC(sizeof(OPS$_$4)); st->class$ = &OPS$_$4$class$;
        memcpy((*st).str.$, OPS$str.$,256 * sizeof(uint8_t));
        (*st).len = OPS$intval;
        s = (OPS$Token)st;
    } else if( (sym == 40) ) { 
        nam = (OPS$_$5*)GC_MALLOC(sizeof(OPS$_$5)); nam->class$ = &OPS$_$5$class$;
        memcpy((*nam).name.$, OPS$name.$,32 * sizeof(uint8_t));
        s = (OPS$Token)nam;
    } else if( ((((1 <= sym) && (sym <= 17)) || (sym == 33)) || (sym == 34)) ) { 
        nam = (OPS$_$5*)GC_MALLOC(sizeof(OPS$_$5)); nam->class$ = &OPS$_$5$class$;
        memcpy((*nam).name.$, OPS$name.$,32 * sizeof(uint8_t));
        s = (OPS$Token)nam;
    } else { 
        s = (OPS$_$0*)GC_MALLOC(sizeof(OPS$_$0)); s->class$ = &OPS$_$0$class$;
    }
    (*s).pos = OPM$errpos;
    (*s).sym = sym;
    (*s).next = (*OPS$last).next;
    (*OPS$last).next = s;
    OPS$last = s;
}

/* public */ void OPS$StartRecording(int8_t sym) {
    OPS$stream = (OPS$_$0*)GC_MALLOC(sizeof(OPS$_$0)); OPS$stream->class$ = &OPS$_$0$class$;
    OPS$last = OPS$stream;
    OPS$RecToken(sym);
}

/* public */ void OPS$StopRecording(OPS$TokenStream* s) {
    (*s) = OPS$stream;
    OPS$stream = NULL;
    OPS$last = NULL;
}

/* public */ void OPS$StartPlaying(OPS$TokenStream s) {
    OPS$stream = s;
    OPS$Get = OPS$StreamGet;
}

void OPS$Str(int8_t* sym) {
    int16_t i;
    uint8_t och;
    i = 0;
    och = OPS$ch;
    while(1) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == och) ) { 
            goto __133;
        }
        if( (OPS$ch < ' ') ) { 
            OPS$err(3);
            goto __133;
        }
        if( (i == (256 - 1)) ) { 
            OPS$err(241);
            goto __133;
        }
        ((uint8_t*)OPS$str.$)[i] = OPS$ch;
        i++;
    }    __133:

    OPM$Get(&OPS$ch);
    ((uint8_t*)OPS$str.$)[i] = 0;
    OPS$intval = (i + 1);
    if( (OPS$intval == 2) ) { 
        (*sym) = 35;
        OPS$numtyp = 1;
        OPS$intval = (int32_t)(uint8_t)(((uint8_t*)OPS$str.$)[0]);
    } else { 
        (*sym) = 39;
    }
}

void OPS$Identifier(int8_t* sym) {
    int16_t i;
    i = 0;
    do {
        ((uint8_t*)OPS$name.$)[i] = OPS$ch;
        i++;
        OPM$Get(&OPS$ch);
    } while( !((((OPS$ch < '0') || (('9' < OPS$ch) && ((uint8_t)toupper((uint8_t)OPS$ch) < 'A'))) || ('Z' < (uint8_t)toupper((uint8_t)OPS$ch))) || (i == 32)) );
    if( (i == 32) ) { 
        OPS$err(240);
        i--;
    }
    ((uint8_t*)OPS$name.$)[i] = 0;
    (*sym) = 40;
}

/* public */ uint8_t OPS$CheckCardinality(MIC$AP name, int8_t nofp) {
    switch( ((uint8_t*)name.$)[0] ) { 
    case '+':
    case '-':
        return ((nofp == 1) || (nofp == 2));
        break;
    case '~':
        return ((((uint8_t*)name.$)[1] == 0) && (nofp == 1));
        break;
    default:
        return (nofp == 2);
        break;
    }
}

/* public */ void OPS$CheckOperator(int8_t* id) {
    uint8_t ch0;
    uint8_t ch1;
    uint8_t ch2;
    (*id) = 126;
    strcpy((char*)OPS$name.$, (const char*)OPS$str.$);
    ch0 = ((uint8_t*)OPS$str.$)[0];
    ch1 = ((uint8_t*)OPS$str.$)[1];
    ch2 = ((uint8_t*)OPS$str.$)[2];
    switch( ch0 ) { 
    case '=':
    case '#':
    case '&':
        if( (ch1 == 0) ) { 
            return;
        }
        break;
    case '<':
    case '>':
        if( ((ch1 == 0) || ((ch1 == '=') && (ch2 == 0))) ) { 
            return;
        }
        break;
    case 'I':
        if( ((ch1 == 'N') && (ch2 == 0)) ) { 
            return;
        }
        break;
    case 'D':
        if( (strcmp((const char*)OPS$str.$, (const char*)"DIV") == 0) ) { 
            return;
        }
        break;
    case 'M':
        if( (strcmp((const char*)OPS$str.$, (const char*)"MOD") == 0) ) { 
            return;
        }
        break;
    case 'O':
        if( (strcmp((const char*)OPS$str.$, (const char*)"OR") == 0) ) { 
            return;
        }
        break;
    case '+':
    case '-':
    case '*':
    case '/':
        if( ((ch1 == 0) || ((ch2 == 0) && (ch1 == '*'))) ) { 
            return;
        }
        break;
    case '~':
        if( (ch1 == 0) ) { 
            return;
        }
        break;
    case ':':
        if( (strcmp((const char*)OPS$str.$, (const char*)":=") == 0) ) { 
            return;
        }
        break;
    default:
        break;
    }
    (*id) = 0;
}

double OPS$Number$Ten(int16_t e) {
    double x;
    double p;
    x = 1;
    p = 10;
    while( (e > 0) ) {
        if( ((e) & 1) ) { 
            x = (x * p);
        }
        e = OBERON$DIV(e, 2);
        if( (e > 0) ) { 
            p = (p * p);
        }
    }
    return x;
}

int16_t OPS$Number$Ord(uint8_t ch, uint8_t hex) {
    if( (ch <= '9') ) { 
        return ((int32_t)(uint8_t)(ch) - (int32_t)(uint8_t)('0'));
    } else if( hex ) { 
        return (((int32_t)(uint8_t)(ch) - (int32_t)(uint8_t)('A')) + 10);
    } else { 
        OPS$err(2);
        return 0;
    }
}

/* public */ void OPS$Number() {
    int16_t i;
    int16_t m;
    int16_t n;
    int16_t d;
    int16_t e;
    OPS$_$6 dig;
    double f;
    uint8_t expCh;
    uint8_t neg;
    i = 0;
    m = 0;
    n = 0;
    d = 0;
    while(1) {
        if( ((('0' <= OPS$ch) && (OPS$ch <= '9')) || (((d == 0) && ('A' <= OPS$ch)) && (OPS$ch <= 'F'))) ) { 
            if( ((m > 0) || (OPS$ch != '0')) ) { 
                if( (n < 24) ) { 
                    ((uint8_t*)dig.$)[n] = OPS$ch;
                    n++;
                }
                m++;
            }
            OPM$Get(&OPS$ch);
            i++;
        } else if( (OPS$ch == '.') ) { 
            OPM$Get(&OPS$ch);
            if( (OPS$ch == '.') ) { 
                OPS$ch = 127;
                goto __208;
            } else if( (d == 0) ) { 
                d = i;
            } else { 
                OPS$err(2);
            }
        } else { 
            goto __208;
        }
    }    __208:

    if( (d == 0) ) { 
        if( (n == m) ) { 
            OPS$intval = 0;
            i = 0;
            if( (OPS$ch == 'X') ) { 
                OPM$Get(&OPS$ch);
                OPS$numtyp = 1;
                if( (n <= 2) ) { 
                    while( (i < n) ) {
                        OPS$intval = ((OPS$intval * 16) + OPS$Number$Ord(((uint8_t*)dig.$)[i], 1));
                        i++;
                    }
                } else { 
                    OPS$err(203);
                }
            } else if( (OPS$ch == 'H') ) { 
                OPM$Get(&OPS$ch);
                OPS$numtyp = 2;
                if( (n <= 8) ) { 
                    if( ((n == 8) && (((uint8_t*)dig.$)[0] > '7')) ) { 
                        OPS$intval = (-1);
                    }
                    while( (i < n) ) {
                        OPS$intval = ((OPS$intval * 16) + OPS$Number$Ord(((uint8_t*)dig.$)[i], 1));
                        i++;
                    }
                } else { 
                    OPS$err(203);
                }
            } else { 
                OPS$numtyp = 2;
                while( (i < n) ) {
                    d = OPS$Number$Ord(((uint8_t*)dig.$)[i], 0);
                    i++;
                    if( (OPS$intval <= OBERON$DIV((2147483647L - d), 10)) ) { 
                        OPS$intval = ((OPS$intval * 10) + d);
                    } else { 
                        OPS$err(203);
                    }
                }
            }
        } else { 
            OPS$err(203);
        }
    } else { 
        f = 0;
        e = 0;
        expCh = 'E';
        while( (n > 0) ) {
            n--;
            f = ((OPS$Number$Ord(((uint8_t*)dig.$)[n], 0) + f) / 10);
        }
        if( ((OPS$ch == 'E') || (OPS$ch == 'D')) ) { 
            expCh = OPS$ch;
            OPM$Get(&OPS$ch);
            neg = 0;
            if( (OPS$ch == '-') ) { 
                neg = 1;
                OPM$Get(&OPS$ch);
            } else if( (OPS$ch == '+') ) { 
                OPM$Get(&OPS$ch);
            }
            if( (('0' <= OPS$ch) && (OPS$ch <= '9')) ) { 
                do {
                    n = OPS$Number$Ord(OPS$ch, 0);
                    OPM$Get(&OPS$ch);
                    if( (e <= OBERON$DIV((32767 - n), 10)) ) { 
                        e = ((e * 10) + n);
                    } else { 
                        OPS$err(203);
                    }
                } while( !((OPS$ch < '0') || ('9' < OPS$ch)) );
                if( neg ) { 
                    e = (-e);
                }
            } else { 
                OPS$err(2);
            }
        }
        e -= ((i - d) - m);
        if( (expCh == 'E') ) { 
            OPS$numtyp = 3;
            if( (((1 - 38) < e) && (e <= 38)) ) { 
                if( (e < 0) ) { 
                    OPS$realval = (float)((f / OPS$Number$Ten((-e))));
                } else { 
                    OPS$realval = (float)((f * OPS$Number$Ten(e)));
                }
            } else { 
                OPS$err(203);
            }
        } else { 
            OPS$numtyp = 4;
            if( (((1 - 308) < e) && (e <= 308)) ) { 
                if( (e < 0) ) { 
                    OPS$lrlval = (f / OPS$Number$Ten((-e)));
                } else { 
                    OPS$lrlval = (f * OPS$Number$Ten(e));
                }
            } else { 
                OPS$err(203);
            }
        }
    }
}

void OPS$DefaultGet$Comment() {
    uint8_t dump;
    OPM$Get(&OPS$ch);
    if( (OPS$ch == '@') ) { 
        dump = 1;
        OPM$LogWLn();
    }
    while(1) {
        while(1) {
            while( (OPS$ch == '(') ) {
                OPM$Get(&OPS$ch);
                if( (OPS$ch == '*') ) { 
                    OPS$DefaultGet$Comment();
                } else if( dump ) { 
                    OPM$LogW('(');
                }
            }
            if( (OPS$ch == '*') ) { 
                OPM$Get(&OPS$ch);
                goto __289;
            }
            if( (OPS$ch == 0) ) { 
                goto __289;
            }
            if( dump ) { 
                OPM$LogW(OPS$ch);
            }
            OPM$Get(&OPS$ch);
        }        __289:

        if( (OPS$ch == ')') ) { 
            OPM$Get(&OPS$ch);
            goto __288;
        }
        if( dump ) { 
            OPM$LogW('*');
        }
        if( (OPS$ch == 0) ) { 
            OPS$err(5);
            goto __288;
        }
    }    __288:

}

void OPS$DefaultGet(int8_t* sym) {
    int8_t s;
    while( (OPS$ch <= ' ') ) {
        if( (OPS$ch == 0) ) { 
            (*sym) = 68;
            return;
        } else { 
            OPM$Get(&OPS$ch);
        }
    }
    OPM$errpos = (OPM$curpos - 1);
    if( (OPS$ch == '"') || (OPS$ch == 39) ) {
        OPS$Str(&s);
    } else if( (OPS$ch == '#') ) {
        s = 10;
        strcpy((char*)OPS$name.$, "#");
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '&') ) {
        s = 5;
        strcpy((char*)OPS$name.$, "&");
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '(') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '*') ) { 
            OPS$DefaultGet$Comment();
            OPS$Get(&(*sym));
            return;
        } else { 
            s = 30;
        }
    } else if( (OPS$ch == ')') ) {
        s = 22;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '*') ) {
        strcpy((char*)OPS$name.$, "*");
        s = 1;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '+') ) {
        strcpy((char*)OPS$name.$, "+");
        s = 6;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == ',') ) {
        s = 19;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '-') ) {
        strcpy((char*)OPS$name.$, "-");
        s = 7;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '.') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '.') ) { 
            OPM$Get(&OPS$ch);
            s = 21;
        } else { 
            s = 18;
        }
    } else if( (OPS$ch == '/') ) {
        strcpy((char*)OPS$name.$, "/");
        OPM$Get(&OPS$ch);
        s = 2;
    } else if( (OPS$ch >= '0' && OPS$ch <= '9') ) {
        OPS$Number();
        s = 35;
    } else if( (OPS$ch == ':') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '=') ) { 
            OPM$Get(&OPS$ch);
            s = 34;
            strcpy((char*)OPS$name.$, ":=");
        } else { 
            s = 20;
        }
    } else if( (OPS$ch == ';') ) {
        s = 41;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '<') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '=') ) { 
            OPM$Get(&OPS$ch);
            s = 12;
            strcpy((char*)OPS$name.$, "<=");
        } else { 
            s = 11;
            strcpy((char*)OPS$name.$, "<");
        }
    } else if( (OPS$ch == '=') ) {
        s = 9;
        strcpy((char*)OPS$name.$, "=");
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '>') ) {
        OPM$Get(&OPS$ch);
        if( (OPS$ch == '=') ) { 
            OPM$Get(&OPS$ch);
            s = 14;
            strcpy((char*)OPS$name.$, ">=");
        } else { 
            s = 13;
            strcpy((char*)OPS$name.$, ">");
        }
    } else if( (OPS$ch == 'A') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"ARRAY") == 0) ) { 
            s = 56;
        }
    } else if( (OPS$ch == 'B') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"BEGIN") == 0) ) { 
            s = 60;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"BY") == 0) ) { 
            s = 29;
        }
    } else if( (OPS$ch == 'C') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"CASE") == 0) ) { 
            s = 48;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"CODE") == 0) ) { 
            s = 61;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"CONST") == 0) ) { 
            s = 62;
        }
    } else if( (OPS$ch == 'D') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"DO") == 0) ) { 
            s = 27;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"DIV") == 0) ) { 
            s = 3;
        }
    } else if( (OPS$ch == 'E') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"END") == 0) ) { 
            s = 43;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"ELSE") == 0) ) { 
            s = 44;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"ELSIF") == 0) ) { 
            s = 45;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"EXIT") == 0) ) { 
            s = 54;
        }
    } else if( (OPS$ch == 'F') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"FALSE") == 0) ) { 
            s = 38;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"FOR") == 0) ) { 
            s = 51;
        }
    } else if( (OPS$ch == 'I') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"IF") == 0) ) { 
            s = 47;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"IN") == 0) ) { 
            s = 15;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"IS") == 0) ) { 
            s = 16;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"IMPORT") == 0) ) { 
            s = 66;
        }
    } else if( (OPS$ch == 'L') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"LOOP") == 0) ) { 
            s = 52;
        }
    } else if( (OPS$ch == 'M') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"MOD") == 0) ) { 
            s = 4;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"MODULE") == 0) ) { 
            s = 67;
        }
    } else if( (OPS$ch == 'N') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"NIL") == 0) ) { 
            s = 36;
        }
    } else if( (OPS$ch == 'O') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"OR") == 0) ) { 
            s = 8;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"OF") == 0) ) { 
            s = 25;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"OBJECT") == 0) ) { 
            s = 57;
        }
    } else if( (OPS$ch == 'P') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"PROCEDURE") == 0) ) { 
            s = 65;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"POINTER") == 0) ) { 
            s = 59;
        }
    } else if( (OPS$ch == 'R') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"RECORD") == 0) ) { 
            s = 58;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"REPEAT") == 0) ) { 
            s = 50;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"RETURN") == 0) ) { 
            s = 55;
        }
    } else if( (OPS$ch == 'T') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"THEN") == 0) ) { 
            s = 26;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"TO") == 0) ) { 
            s = 28;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"TRUE") == 0) ) { 
            s = 37;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"TYPE") == 0) ) { 
            s = 63;
        }
    } else if( (OPS$ch == 'U') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"UNTIL") == 0) ) { 
            s = 46;
        }
    } else if( (OPS$ch == 'V') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"VAR") == 0) ) { 
            s = 64;
        }
    } else if( (OPS$ch == 'W') ) {
        OPS$Identifier(&s);
        if( (strcmp((const char*)OPS$name.$, (const char*)"WHILE") == 0) ) { 
            s = 49;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)"WITH") == 0) ) { 
            s = 53;
        }
    } else if( (OPS$ch >= 'G' && OPS$ch <= 'H') || (OPS$ch == 'J') || (OPS$ch == 'K') || (OPS$ch == 'Q') || (OPS$ch == 'S') || (OPS$ch >= 'X' && OPS$ch <= 'Z') ) {
        OPS$Identifier(&s);
    } else if( (OPS$ch == '[') ) {
        s = 31;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == ']') ) {
        s = 23;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '^') ) {
        s = 17;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch >= 'a' && OPS$ch <= 'z') ) {
        OPS$Identifier(&s);
    } else if( (OPS$ch == '{') ) {
        s = 32;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '|') ) {
        s = 42;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '}') ) {
        s = 24;
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == '~') ) {
        s = 33;
        strcpy((char*)OPS$name.$, "~");
        OPM$Get(&OPS$ch);
    } else if( (OPS$ch == 127) ) {
        s = 21;
        OPM$Get(&OPS$ch);
    } else {
        s = 0;
        OPM$Get(&OPS$ch);
    }

    if( (OPS$stream != NULL) ) { 
        OPS$RecToken(s);
    }
    (*sym) = s;
}

/* public */ void OPS$Init() {
    OPS$ch = ' ';
    OPS$stream = NULL;
    OPS$last = NULL;
    OPS$Get = OPS$DefaultGet;
}

void OPS$BEGIN$() {
    OPS$Init();
}

static int OPS$initialized = 0;
void OPS$init$(void) {
    if( OPS$initialized ) return;
    OPS$initialized = 1;
    OPM$init$();
    OPS$BEGIN$();
}

