#ifndef __OPS_INCLUDED__
#define __OPS_INCLUDED__

// OPS.h
// this file was generated by AoCodeNavigator 0.6.12 on Mi. März 4 17:25:17 2026

#include <stdint.h>
#include "OPM.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPS$MaxStrLen 256
#define OPS$MaxIdLen 32
/* public */ typedef struct OPS$Name { uint8_t $[32]; } OPS$Name;
/* public */ typedef struct OPS$String { uint8_t $[256]; } OPS$String;
/* public */ typedef void (*OPS$GetProc)(int8_t* sym); 
typedef struct OPS$_$0* OPS$Token;
typedef struct OPS$_$0 {
    struct OPS$_$0$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
} OPS$_$0;
void OPS$_$0$init$(OPS$_$0* obj, unsigned int n);
struct OPS$_$0$Class$ {
    void* super$;
};
extern struct OPS$_$0$Class$ OPS$_$0$class$;
typedef struct OPS$_$1* OPS$IntToken;
typedef struct OPS$_$1 {
    struct OPS$_$1$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
    int32_t intval;
    int16_t typ;
} OPS$_$1;
void OPS$_$1$init$(OPS$_$1* obj, unsigned int n);
struct OPS$_$1$Class$ {
    struct OPS$_$0$Class$* super$;
};
extern struct OPS$_$1$Class$ OPS$_$1$class$;
typedef struct OPS$_$2* OPS$RealToken;
typedef struct OPS$_$2 {
    struct OPS$_$2$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
    float realval;
} OPS$_$2;
void OPS$_$2$init$(OPS$_$2* obj, unsigned int n);
struct OPS$_$2$Class$ {
    struct OPS$_$0$Class$* super$;
};
extern struct OPS$_$2$Class$ OPS$_$2$class$;
typedef struct OPS$_$3* OPS$LRealToken;
typedef struct OPS$_$3 {
    struct OPS$_$3$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
    double lrlval;
} OPS$_$3;
void OPS$_$3$init$(OPS$_$3* obj, unsigned int n);
struct OPS$_$3$Class$ {
    struct OPS$_$0$Class$* super$;
};
extern struct OPS$_$3$Class$ OPS$_$3$class$;
typedef struct OPS$_$4* OPS$StrToken;
typedef struct OPS$_$4 {
    struct OPS$_$4$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
    OPS$String str;
    int32_t len;
} OPS$_$4;
void OPS$_$4$init$(OPS$_$4* obj, unsigned int n);
struct OPS$_$4$Class$ {
    struct OPS$_$0$Class$* super$;
};
extern struct OPS$_$4$Class$ OPS$_$4$class$;
typedef struct OPS$_$5* OPS$NameToken;
typedef struct OPS$_$5 {
    struct OPS$_$5$Class$* class$;
    int32_t pos;
    int8_t sym;
    OPS$Token next;
    OPS$Name name;
} OPS$_$5;
void OPS$_$5$init$(OPS$_$5* obj, unsigned int n);
struct OPS$_$5$Class$ {
    struct OPS$_$0$Class$* super$;
};
extern struct OPS$_$5$Class$ OPS$_$5$class$;
/* public */ typedef OPS$Token OPS$TokenStream;
/* public */ extern OPS$Name OPS$name;
/* public */ extern OPS$String OPS$str;
/* public */ extern int16_t OPS$numtyp;
/* public */ extern int32_t OPS$intval;
/* public */ extern float OPS$realval;
/* public */ extern double OPS$lrlval;
/* public */ extern OPS$GetProc OPS$Get;
/* public */ extern uint8_t OPS$ch;
extern OPS$TokenStream OPS$stream;
extern OPS$TokenStream OPS$last;
#define OPS$char_ 1
#define OPS$integer 2
#define OPS$real 3
#define OPS$longreal 4
#define OPS$null 0
#define OPS$times 1
#define OPS$slash 2
#define OPS$div 3
#define OPS$mod 4
#define OPS$and 5
#define OPS$plus 6
#define OPS$minus 7
#define OPS$or 8
#define OPS$eql 9
#define OPS$neq 10
#define OPS$lss 11
#define OPS$leq 12
#define OPS$gtr 13
#define OPS$geq 14
#define OPS$in 15
#define OPS$is 16
#define OPS$arrow 17
#define OPS$period 18
#define OPS$comma 19
#define OPS$colon 20
#define OPS$upto 21
#define OPS$rparen 22
#define OPS$rbrak 23
#define OPS$rbrace 24
#define OPS$of 25
#define OPS$then 26
#define OPS$do_ 27
#define OPS$to 28
#define OPS$by 29
#define OPS$lparen 30
#define OPS$lbrak 31
#define OPS$lbrace 32
#define OPS$not 33
#define OPS$becomes 34
#define OPS$number 35
#define OPS$nil 36
#define OPS$true 37
#define OPS$false 38
#define OPS$string 39
#define OPS$ident 40
#define OPS$semicolon 41
#define OPS$bar 42
#define OPS$end 43
#define OPS$else_ 44
#define OPS$elsif 45
#define OPS$until 46
#define OPS$if_ 47
#define OPS$case_ 48
#define OPS$while_ 49
#define OPS$repeat 50
#define OPS$for_ 51
#define OPS$loop 52
#define OPS$with 53
#define OPS$exit 54
#define OPS$return_ 55
#define OPS$array 56
#define OPS$object 57
#define OPS$record 58
#define OPS$pointer 59
#define OPS$begin 60
#define OPS$code 61
#define OPS$const_ 62
#define OPS$type 63
#define OPS$var 64
#define OPS$procedure 65
#define OPS$import 66
#define OPS$module 67
#define OPS$eof 68
extern void OPS$err(int16_t n);
extern void OPS$StreamGet(int8_t* sym);
extern void OPS$RecToken(int8_t sym);
/* public */ extern void OPS$StartRecording(int8_t sym);
/* public */ extern void OPS$StopRecording(OPS$TokenStream* s);
/* public */ extern void OPS$StartPlaying(OPS$TokenStream s);
extern void OPS$Str(int8_t* sym);
extern void OPS$Identifier(int8_t* sym);
/* public */ extern uint8_t OPS$CheckCardinality(MIC$AP name, int8_t nofp);
/* public */ extern void OPS$CheckOperator(int8_t* id);
/* public */ extern void OPS$Number();
typedef struct OPS$_$6 { uint8_t $[24]; } OPS$_$6;
extern void OPS$DefaultGet(int8_t* sym);
/* public */ extern void OPS$Init();
extern void OPS$BEGIN$();
extern void OPS$init$(void);

#endif // __OPS_INCLUDED__