#ifndef __OPT_INCLUDED__
#define __OPT_INCLUDED__

// OPT.h
// this file was generated by AoCodeNavigator 0.6.10 on So. Feb. 22 16:24:39 2026

#include <stdint.h>
#include "OPS.h"
#include "OPM.h"
#include "OPTR.h"
#include "Files.h"

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPT$TraceFP 0
#define OPT$MaxConstLen 256
#define OPT$DefMaxImport 64
#define OPT$DefMaxStruct 32
#define OPT$DefMaxReimp 32
#define OPT$HdPtrName "@ptr"
#define OPT$ObjBody "@Body"
#define OPT$Delegate "@delegate"
#define OPT$HdPtrStruct "@pointer"
#define OPT$Var 1
#define OPT$VarPar 2
#define OPT$Con 3
#define OPT$Fld 4
#define OPT$Typ 5
#define OPT$LProc 6
#define OPT$XProc 7
#define OPT$SProc 8
#define OPT$CProc 9
#define OPT$Mod 11
#define OPT$Head 12
#define OPT$TProc 13
#define OPT$Alias 14
#define OPT$Operator 15
#define OPT$Undef 0
#define OPT$Byte 1
#define OPT$Bool 2
#define OPT$Char 3
#define OPT$SInt 4
#define OPT$Int 5
#define OPT$LInt 6
#define OPT$Real 7
#define OPT$LReal 8
#define OPT$Set 9
#define OPT$String 10
#define OPT$NilTyp 11
#define OPT$NoTyp 12
#define OPT$Pointer 13
#define OPT$ProcTyp 14
#define OPT$Comp 15
#define OPT$HInt 16
#define OPT$Basic 1
#define OPT$StaticArr 2
#define OPT$SDynArr 3
#define OPT$DynArr 4
#define OPT$OpenArr 5
#define OPT$Record 6
#define OPT$Nconst 7
#define OPT$Ncall 13
#define OPT$haltfn 0
#define OPT$newfn 1
#define OPT$absfn 2
#define OPT$capfn 3
#define OPT$ordfn 4
#define OPT$entierfn 5
#define OPT$oddfn 6
#define OPT$minfn 7
#define OPT$maxfn 8
#define OPT$chrfn 9
#define OPT$shortfn 10
#define OPT$longfn 11
#define OPT$sizefn 12
#define OPT$incfn 13
#define OPT$decfn 14
#define OPT$inclfn 15
#define OPT$exclfn 16
#define OPT$lenfn 17
#define OPT$copyfn 18
#define OPT$ashfn 19
#define OPT$assertfn 32
#define OPT$awaitfn 64
#define OPT$lockfn 66
#define OPT$adrfn 20
#define OPT$ccfn 21
#define OPT$lshfn 22
#define OPT$rotfn 23
#define OPT$getfn 24
#define OPT$putfn 25
#define OPT$getrfn 26
#define OPT$putrfn 27
#define OPT$bitfn 28
#define OPT$valfn 29
#define OPT$sysnewfn 30
#define OPT$movefn 31
#define OPT$stifn 33
#define OPT$clifn 34
#define OPT$poutfn 35
#define OPT$pinfn 36
#define OPT$shalt 37
#define OPT$get8fn 38
#define OPT$get16fn 39
#define OPT$get32fn 40
#define OPT$put8fn 41
#define OPT$put16fn 42
#define OPT$put32fn 43
#define OPT$typefn 44
#define OPT$internal 0
#define OPT$external 1
#define OPT$externalR 2
#define OPT$hasBody 1
#define OPT$slNeeded 3
#define OPT$protectedObj 4
#define OPT$activeObj 5
#define OPT$locked 6
#define OPT$guarded 7
#define OPT$safe 8
#define OPT$asmProc 7
#define OPT$typeVisible 8
#define OPT$used 1
#define OPT$param 3
#define OPT$SFtypBool 1
#define OPT$SFtypChar 2
#define OPT$SFtypSInt 3
#define OPT$SFtypInt 4
#define OPT$SFtypLInt 5
#define OPT$SFtypHInt 6
#define OPT$SFtypReal 7
#define OPT$SFtypLReal 8
#define OPT$SFtypSet 9
#define OPT$SFtypString 10
#define OPT$SFtypNoTyp 11
#define OPT$SFtypNilTyp 12
#define OPT$SFtypByte 13
#define OPT$SFtypptr 14
#define OPT$SFlastStruct 14
#define OPT$SFmod1 15
#define OPT$SFmod31 44
#define OPT$SFmodOther 45
#define OPT$SFtypOpenArr 46
#define OPT$SFtypDynArr 47
#define OPT$SFtypArray 48
#define OPT$SFtypPointer 49
#define OPT$SFtypRecord 50
#define OPT$SFtypProcTyp 51
#define OPT$SFsysflag 52
#define OPT$SFinvisible 53
#define OPT$SFreadonly 54
#define OPT$SFobjflag 55
#define OPT$SFconst 55
#define OPT$SFvar 56
#define OPT$SFlproc 57
#define OPT$SFxproc 58
#define OPT$SFoperator 59
#define OPT$SFtproc 60
#define OPT$SFcproc 60
#define OPT$SFalias 61
#define OPT$SFtyp 62
#define OPT$SFend 63
#define OPT$inserted 0
#define OPT$same 1
#define OPT$removed 3
#define OPT$modified 4
/* public */ typedef struct OPT$ConstDesc* OPT$Const;
/* public */ typedef struct OPT$ObjDesc* OPT$Object;
/* public */ typedef struct OPT$ModDesc* OPT$Module;
/* public */ typedef struct OPT$StrDesc* OPT$Struct;
/* public */ typedef struct OPT$NodeDesc* OPT$Node;
/* public */ // no typedef for pointer to array OPT$ConstExt (using MIC$DA instead)
/* public */ typedef struct OPT$ConstDesc {
    struct OPT$ConstDesc$Class$* class$;
    uint8_t* ext;
    int32_t intval;
    int32_t intval2;
    int32_t setval;
    double realval;
} OPT$ConstDesc;
void OPT$ConstDesc$init$(OPT$ConstDesc* obj, unsigned int n);
struct OPT$ConstDesc$Class$ {
    void* super$;
};
extern struct OPT$ConstDesc$Class$ OPT$ConstDesc$class$;
/* public */ typedef struct OPT$ObjDesc {
    struct OPT$ObjDesc$Class$* class$;
    OPT$Object left;
    OPT$Object right;
    OPT$Object link;
    OPT$Object scope;
    OPT$Object myscope;
    OPT$Object link2;
    OPT$Object old;
    int8_t prio;
    int8_t sysflag;
    OPT$Node code;
    OPS$Name name;
    uint8_t leaf;
    int8_t mode;
    int8_t mnolev;
    int8_t vis;
    OPT$Struct typ;
    OPT$Const conval;
    int32_t adr;
    int32_t linkadr;
    OPT$Object nxtobj;
    OPT$Object sibling;
    uint8_t par;
    uint8_t inited;
    uint8_t used;
    int32_t fp;
    int8_t history;
    int32_t txtpos;
    int32_t flag;
} OPT$ObjDesc;
void OPT$ObjDesc$init$(OPT$ObjDesc* obj, unsigned int n);
struct OPT$ObjDesc$Class$ {
    void* super$;
};
extern struct OPT$ObjDesc$Class$ OPT$ObjDesc$class$;
// no typedef for pointer to array OPT$StructArr (using MIC$DA instead)
// no typedef for open array OPT$_$0 (OPT$Struct*)
// no typedef for pointer to array OPT$ModArr (using MIC$DA instead)
// no typedef for open array OPT$_$1 (OPT$Module*)
/* public */ typedef struct OPT$ModDesc {
    struct OPT$ModDesc$Class$* class$;
    OPT$Object left;
    OPT$Object right;
    OPT$Object link;
    OPT$Object scope;
    OPT$Object myscope;
    OPT$Object link2;
    OPT$Object old;
    int8_t prio;
    int8_t sysflag;
    OPT$Node code;
    OPS$Name name;
    uint8_t leaf;
    int8_t mode;
    int8_t mnolev;
    int8_t vis;
    OPT$Struct typ;
    OPT$Const conval;
    int32_t adr;
    int32_t linkadr;
    OPT$Object nxtobj;
    OPT$Object sibling;
    uint8_t par;
    uint8_t inited;
    uint8_t used;
    int32_t fp;
    int8_t history;
    int32_t txtpos;
    int32_t flag;
    OPT$Object publics;
    uint8_t directImp;
    int16_t nofimp;
    OPT$Module* import;
    int16_t nofstr;
    OPT$Struct* struct_;
    int16_t nofreimp;
    OPT$Struct* reimp;
} OPT$ModDesc;
void OPT$ModDesc$init$(OPT$ModDesc* obj, unsigned int n);
struct OPT$ModDesc$Class$ {
    struct OPT$ObjDesc$Class$* super$;
};
extern struct OPT$ModDesc$Class$ OPT$ModDesc$class$;
/* public */ typedef struct OPT$StrDesc {
    struct OPT$StrDesc$Class$* class$;
    int8_t form;
    int8_t comp;
    int8_t mno;
    int8_t extlev;
    int16_t ref;
    int8_t align;
    int8_t sysflag;
    int32_t rectest;
    int32_t n;
    int32_t size;
    int32_t tdadr;
    int32_t offset;
    int32_t txtpos;
    int32_t txtpos2;
    OPT$Struct BaseTyp;
    OPT$Object link;
    OPT$Object strobj;
    int16_t fpdone;
    int16_t sref;
    int16_t oref;
    uint8_t pvused;
    uint8_t pbused;
    int32_t fp;
    int32_t pvfp;
    int32_t pbfp;
    uint8_t incomplete;
    OPT$Struct ptr;
} OPT$StrDesc;
void OPT$StrDesc$init$(OPT$StrDesc* obj, unsigned int n);
struct OPT$StrDesc$Class$ {
    void* super$;
};
extern struct OPT$StrDesc$Class$ OPT$StrDesc$class$;
/* public */ typedef struct OPT$NodeDesc {
    struct OPT$NodeDesc$Class$* class$;
    OPT$Node left;
    OPT$Node right;
    OPT$Node link;
    int8_t class;
    int8_t subcl;
    uint8_t readonly;
    OPT$Struct typ;
    OPT$Object obj;
    OPT$Const conval;
    uint8_t global;
    OPT$Node up;
    OPT$Node down;
    int32_t ref;
    int8_t flag;
    int8_t subflg;
} OPT$NodeDesc;
void OPT$NodeDesc$init$(OPT$NodeDesc* obj, unsigned int n);
struct OPT$NodeDesc$Class$ {
    void* super$;
};
extern struct OPT$NodeDesc$Class$ OPT$NodeDesc$class$;
/* public */ extern OPT$Object OPT$topScope;
/* public */ extern OPT$Object OPT$objects;
/* public */ extern OPT$Struct OPT$undftyp;
/* public */ extern OPT$Struct OPT$bytetyp;
/* public */ extern OPT$Struct OPT$booltyp;
/* public */ extern OPT$Struct OPT$chartyp;
/* public */ extern OPT$Struct OPT$sinttyp;
/* public */ extern OPT$Struct OPT$inttyp;
/* public */ extern OPT$Struct OPT$linttyp;
/* public */ extern OPT$Struct OPT$hinttyp;
/* public */ extern OPT$Struct OPT$realtyp;
/* public */ extern OPT$Struct OPT$lrltyp;
/* public */ extern OPT$Struct OPT$settyp;
/* public */ extern OPT$Struct OPT$stringtyp;
/* public */ extern OPT$Struct OPT$niltyp;
/* public */ extern OPT$Struct OPT$notyp;
/* public */ extern OPT$Struct OPT$ptrtyp;
/* public */ extern uint8_t OPT$SYSimported;
/* public */ extern int8_t OPT$nofmod;
/* public */ extern OPT$Module* OPT$modules;
extern int8_t OPT$nofemod;
extern OPT$Module* OPT$emodules;
/* public */ extern int16_t OPT$modNo;
extern OPT$Object OPT$universe;
extern OPT$Object OPT$syslink;
typedef struct OPT$_$2 { int8_t $[(51 + 1)]; } OPT$_$2;
extern OPT$_$2 OPT$strucForm;
typedef struct OPT$_$3 { int8_t $[(51 + 1)]; } OPT$_$3;
extern OPT$_$3 OPT$strucComp;
typedef struct OPT$_$4 { OPT$Struct $[(14 + 1)]; } OPT$_$4;
extern OPT$_$4 OPT$predefStruct;
typedef struct OPT$_$5 { int8_t $[(15 + 1)]; } OPT$_$5;
extern OPT$_$5 OPT$strucFormSF;
typedef struct OPT$_$6 { int8_t $[(15 + 1)]; } OPT$_$6;
extern OPT$_$6 OPT$strucCompSF;
extern uint8_t OPT$export;
typedef struct OPT$_$7 { OPT$Object $[(15 + 1)]; } OPT$_$7;
extern OPT$_$7 OPT$exp;
extern int16_t OPT$nofstruc;
extern uint8_t OPT$newSF;
extern uint8_t OPT$extSF;
extern uint8_t OPT$symNew;
extern uint8_t OPT$symExtended;
extern uint8_t OPT$sfpresent;
extern uint8_t OPT$impSelf;
extern uint8_t OPT$expGlobal;
typedef void (*OPT$_$8)(OPT$Struct typ, uint8_t allocDesc); 
/* public */ extern OPT$_$8 OPT$typSize;
/* public */ extern OPT$Struct OPT$ToBeFixed;
extern void OPT$err(int16_t n);
/* public */ extern void OPT$Close();
extern OPT$Module OPT$NewMod();
/* public */ extern OPT$Const OPT$NewConst();
/* public */ extern OPT$Object OPT$NewObj();
/* public */ extern OPT$Struct OPT$NewStr(int8_t form, int8_t comp);
/* public */ extern OPT$Node OPT$NewNode(int8_t class);
/* public */ extern uint8_t* OPT$NewExt();
extern void OPT$DoubleStructArr(OPT$Struct** x);
extern void OPT$DoubleModArr(OPT$Module** x);
/* public */ extern void OPT$MarkObj(OPT$Object obj);
/* public */ extern void OPT$MarkType(OPT$Struct typ);
/* public */ extern void OPT$TraverseObjects(OPT$Object top);
/* public */ extern void OPT$FindImport(OPT$Object mod, OPT$Object* res);
// no typedef for open array OPT$_$9 (uint8_t*)
/* public */ extern void OPT$FindField(MIC$AP name, OPT$Struct typ, OPT$Object* res, uint8_t mark);
// no typedef for open array OPT$_$10 (uint8_t*)
/* public */ extern void OPT$FindInScope(MIC$AP name, OPT$Object scope, OPT$Object* res);
/* public */ extern void OPT$Find(OPT$Object* res);
// no typedef for open array OPT$_$11 (uint8_t*)
/* public */ extern void OPT$Insert(MIC$AP name, OPT$Object* obj);
extern void OPT$CopyOp(OPT$Object* new, OPT$Object* obj);
extern uint8_t OPT$IsExtern(OPT$Object obj);
/* public */ extern void OPT$Contextualize(OPT$Object* sentinel);
extern void OPT$Distance(OPT$Struct typ, OPT$Struct otyp, int8_t* distance);
/* public */ extern void OPT$QualResolve(OPT$Object* obj, OPT$Node* x, OPT$Node* y, int8_t* distance, uint8_t* wrn);
// no typedef for open array OPT$_$12 (uint8_t*)
/* public */ extern OPT$Object OPT$Resolve(MIC$AP name, OPT$Node* x, OPT$Node* y);
/* public */ extern void OPT$OpenScope(int8_t level, OPT$Object owner);
/* public */ extern void OPT$CloseScope();
/* public */ extern void OPT$Init(MIC$AP name);
// no typedef for open array OPT$_$13 (uint8_t*)
extern void OPT$FPrintName(int32_t* fp, MIC$AP name);
extern void OPT$FPrintSign(int32_t* fp, OPT$Struct result, OPT$Object par);
extern void OPT$FPrintMeth(int32_t* pbfp, int32_t* pvfp, OPT$Object fld);
extern void OPT$FPrintRecord(OPT$Struct typ);
extern void OPT$FPrintTyp0(OPT$Struct typ);
/* public */ extern void OPT$FPrintTyp(OPT$Struct typ);
/* public */ extern void OPT$FPrintObj(OPT$Object obj);
extern void OPT$FPrintErr(OPT$Object obj);
extern OPT$Object OPT$MatchOp(OPT$Object op, OPT$Object list);
extern void OPT$InsertImport(OPT$Object obj, OPT$Object root);
extern int8_t OPT$CompOldTyp(OPT$Struct typ, OPT$Struct oldtyp);
extern void OPT$CompOldSym(OPT$Object obj);
// no typedef for open array OPT$_$14 (uint8_t*)
extern void OPT$ReadString(Files$Rider* R, MIC$AP string);
extern void OPT$Imp(MIC$AP impName, MIC$AP modName, OPT$Module* M);
/* public */ extern void OPT$Import(MIC$AP aliasName, MIC$AP impName, MIC$AP selfName);
/* public */ extern void OPT$OutMod(OPT$Module mod);
extern void OPT$Enumerate(OPT$Object obj);
extern void OPT$OutCProc(OPT$Node n);
extern void OPT$OutParList(OPT$Object par);
extern void OPT$OutFld(OPT$Object fld);
typedef struct OPT$_$15 { uint8_t $[32]; } OPT$_$15;
extern void OPT$OutRecord(OPT$Struct typ);
extern void OPT$OutStruct(OPT$Struct typ);
extern void OPT$OutConst(int8_t form, OPT$Const conval);
extern void OPT$OutObj(OPT$Object obj);
/* public */ extern void OPT$OutScope(OPT$Object scope, uint8_t public);
/* public */ extern void OPT$Export(MIC$AP modName, uint8_t* newsf, uint8_t* extsf);
extern void OPT$InitStruct(OPT$Struct* typ, int8_t form, int8_t sref);
// no typedef for open array OPT$_$16 (uint8_t*)
extern void OPT$EnterIntConst(MIC$AP name, int32_t value);
// no typedef for open array OPT$_$17 (uint8_t*)
extern void OPT$EnterTyp(MIC$AP name, int8_t form, int16_t size, OPT$Struct* res, int8_t sref);
// no typedef for open array OPT$_$18 (uint8_t*)
extern void OPT$EnterTypAlias(MIC$AP name, OPT$Struct typ);
// no typedef for open array OPT$_$19 (uint8_t*)
extern void OPT$EnterProc(MIC$AP name, int16_t num);
// no typedef for open array OPT$_$20 (uint8_t*)
extern void OPT$EnterPtr(MIC$AP name, int32_t num);
extern void OPT$BEGIN$();
extern void OPT$init$(void);

#endif // __OPT_INCLUDED__