// OPT.c
// this file was generated by AoCodeNavigator 0.6.09 on Sa. Feb. 21 01:13:16 2026

#include "OPT.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void OPT$ConstDesc$init$(OPT$ConstDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPT$ConstDesc$class$;
    }
}

struct OPT$ConstDesc$Class$ OPT$ConstDesc$class$ = { 
    0,
};

void OPT$ObjDesc$init$(OPT$ObjDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPT$ObjDesc$class$;
    }
}

struct OPT$ObjDesc$Class$ OPT$ObjDesc$class$ = { 
    0,
};

void OPT$ModDesc$init$(OPT$ModDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPT$ModDesc$class$;
    }
}

struct OPT$ModDesc$Class$ OPT$ModDesc$class$ = { 
    &OPT$ObjDesc$class$,
};

void OPT$StrDesc$init$(OPT$StrDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPT$StrDesc$class$;
    }
}

struct OPT$StrDesc$Class$ OPT$StrDesc$class$ = { 
    0,
};

void OPT$NodeDesc$init$(OPT$NodeDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &OPT$NodeDesc$class$;
    }
}

struct OPT$NodeDesc$Class$ OPT$NodeDesc$class$ = { 
    0,
};

/* public */ OPT$Object OPT$topScope = NULL;

/* public */ OPT$Object OPT$objects = NULL;

/* public */ OPT$Struct OPT$undftyp = NULL;

/* public */ OPT$Struct OPT$bytetyp = NULL;

/* public */ OPT$Struct OPT$booltyp = NULL;

/* public */ OPT$Struct OPT$chartyp = NULL;

/* public */ OPT$Struct OPT$sinttyp = NULL;

/* public */ OPT$Struct OPT$inttyp = NULL;

/* public */ OPT$Struct OPT$linttyp = NULL;

/* public */ OPT$Struct OPT$hinttyp = NULL;

/* public */ OPT$Struct OPT$realtyp = NULL;

/* public */ OPT$Struct OPT$lrltyp = NULL;

/* public */ OPT$Struct OPT$settyp = NULL;

/* public */ OPT$Struct OPT$stringtyp = NULL;

/* public */ OPT$Struct OPT$niltyp = NULL;

/* public */ OPT$Struct OPT$notyp = NULL;

/* public */ OPT$Struct OPT$ptrtyp = NULL;

/* public */ uint8_t OPT$SYSimported;

/* public */ int8_t OPT$nofmod;

/* public */ OPT$Module* OPT$modules = NULL;

int8_t OPT$nofemod;

OPT$Module* OPT$emodules = NULL;

/* public */ int16_t OPT$modNo;

OPT$Object OPT$universe = NULL;

OPT$Object OPT$syslink = NULL;

OPT$_$2 OPT$strucForm;

OPT$_$3 OPT$strucComp;

OPT$_$4 OPT$predefStruct;

OPT$_$5 OPT$strucFormSF;

OPT$_$6 OPT$strucCompSF;

uint8_t OPT$export;

OPT$_$7 OPT$exp;

int16_t OPT$nofstruc;

uint8_t OPT$newSF;

uint8_t OPT$extSF;

uint8_t OPT$symNew;

uint8_t OPT$symExtended;

uint8_t OPT$sfpresent;

uint8_t OPT$impSelf;

uint8_t OPT$expGlobal;

/* public */ OPT$_$8 OPT$typSize;

/* public */ OPT$Struct OPT$ToBeFixed = NULL;

void OPT$err(int16_t n) {
    OPM$err(n);
}

/* public */ void OPT$Close() {
    int16_t i;
    OPT$topScope = NULL;
    OPT$objects = NULL;
    i = 0;
    while( (i < $toda((void**)OPT$modules)->$1) ) {
        OPT$modules[i] = NULL;
        i++;
    }
    i = 0;
    while( (i < $toda((void**)OPT$emodules)->$1) ) {
        OPT$emodules[i] = NULL;
        i++;
    }
    i = 0;
    while( (i < (14 + 1)) ) {
        ((OPT$Object*)OPT$exp.$)[i] = NULL;
        i++;
    }
    OPT$nofmod = 0;
    OPT$nofemod = 0;
}

OPT$Module OPT$NewMod() {
    OPT$Module M = NULL;
    M = (OPT$ModDesc*)GC_MALLOC(sizeof(OPT$ModDesc)); M->class$ = &OPT$ModDesc$class$;
    (*M).struct_ = (OPT$Struct*)$allocda(32, sizeof(OPT$Struct));
    (*M).reimp = (OPT$Struct*)$allocda(32, sizeof(OPT$Struct));
    (*M).import = (OPT$Module*)$allocda(64, sizeof(OPT$Module));
    return M;
}

/* public */ OPT$Const OPT$NewConst() {
    OPT$Const const_ = NULL;
    const_ = (OPT$ConstDesc*)GC_MALLOC(sizeof(OPT$ConstDesc)); const_->class$ = &OPT$ConstDesc$class$;
    return const_;
}

/* public */ OPT$Object OPT$NewObj() {
    OPT$Object obj = NULL;
    obj = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); obj->class$ = &OPT$ObjDesc$class$;
    (*obj).txtpos = OPM$errpos;
    return obj;
}

/* public */ OPT$Struct OPT$NewStr(int8_t form, int8_t comp) {
    OPT$Struct typ = NULL;
    typ = (OPT$StrDesc*)GC_MALLOC(sizeof(OPT$StrDesc)); typ->class$ = &OPT$StrDesc$class$;
    (*typ).form = form;
    (*typ).comp = comp;
    (*typ).tdadr = (-1);
    (*typ).offset = (-1);
    (*typ).txtpos = OPM$errpos;
    (*typ).size = (-1);
    (*typ).BaseTyp = OPT$undftyp;
    return typ;
}

/* public */ OPT$Node OPT$NewNode(int8_t class) {
    OPT$Node node = NULL;
    node = (OPT$NodeDesc*)GC_MALLOC(sizeof(OPT$NodeDesc)); node->class$ = &OPT$NodeDesc$class$;
    (*node).class = class;
    return node;
}

/* public */ uint8_t* OPT$NewExt() {
    uint8_t* ext = NULL;
    ext = (uint8_t*)$allocda(256, sizeof(uint8_t));
    return ext;
}

void OPT$DoubleStructArr(OPT$Struct** x) {
    int32_t i;
    OPT$Struct* h = NULL;
    i = $toda((void**)(*x))->$1;
    h = (*x);
    (*x) = (OPT$Struct*)$allocda((2 * i), sizeof(OPT$Struct));
    if(!((*x) != NULL)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    memcpy((void*)&((*x)[0]), (void*)&(h[0]), (i * sizeof(OPT$Struct)));
}

void OPT$DoubleModArr(OPT$Module** x) {
    int32_t i;
    OPT$Module* h = NULL;
    i = $toda((void**)(*x))->$1;
    h = (*x);
    (*x) = (OPT$Module*)$allocda((2 * i), sizeof(OPT$Module));
    if(!((*x) != NULL)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    memcpy((void*)&((*x)[0]), (void*)&(h[0]), (i * sizeof(OPT$Module)));
}

/* public */ void OPT$MarkObj(OPT$Object obj) {
    if( (obj != NULL) ) { 
        (*obj).used = 1;
        if( ((*obj).mnolev < 0) ) { 
            (*OPT$modules[(-(*obj).mnolev)]).used = 1;
        }
    }
}

/* public */ void OPT$MarkType(OPT$Struct typ) {
    (*typ).pvused = 1;
    OPT$MarkObj((*typ).strobj);
}

/* public */ void OPT$TraverseObjects(OPT$Object top) {
    int32_t flag;
    OPT$Struct type = NULL;
    if( (top != NULL) ) { 
        OPT$TraverseObjects((*top).left);
        if( (((((1 << (*top).mode) & (0 | 1u << 1 | 1u << 2 | 1u << 4 | 1u << 3 | 1u << 5 | 1u << 6 | 1u << 13 | 1u << 9 | 1u << 11)) != 0) && ((*top).vis == 0)) && (strcmp((const char*)(*top).name.$, (const char*)"@SELF") != 0)) ) { 
            flag = ((*top).flag & (0 | 1u << 1 | 1u << 3));
            if( (flag == (0 | 1u << 3)) ) { 
                OPM$Mark((-913), (*top).txtpos);
            } else if( (flag == (0)) ) { 
                OPM$Mark((-900), (*top).txtpos);
            }
        }
        if( (((1 << (*top).mode) & (0 | 1u << 6 | 1u << 7 | 1u << 13)) != 0) ) { 
            OPT$TraverseObjects((*(*top).scope).right);
        }
        type = (*top).typ;
        while( (((*type).form == 13) || ((*type).comp == 2)) ) {
            type = (*type).BaseTyp;
        }
        if( ((((*type).comp == 6) && ((*type).mno == 0)) && ((*type).rectest != 2147483647L)) ) { 
            (*type).rectest = 2147483647L;
            OPT$TraverseObjects((*type).link);
        }
        OPT$TraverseObjects((*top).right);
    }
}

/* public */ void OPT$FindImport(OPT$Object mod, OPT$Object* res) {
    OPT$Object obj = NULL;
    obj = (*mod).scope;
    while(1) {
        if( (obj == NULL) ) { 
            goto __282;
        }
        if( (strcmp((const char*)OPS$name.$, (const char*)(*obj).name.$) < 0) ) { 
            obj = (*obj).left;
        } else if( (strcmp((const char*)OPS$name.$, (const char*)(*obj).name.$) > 0) ) { 
            obj = (*obj).right;
        } else { 
            if( (((*obj).mode == 5) && ((*obj).vis == 0)) ) { 
                obj = NULL;
            } else { 
                OPT$MarkObj(obj);
            }
            goto __282;
        }
    }    __282:

    (*res) = obj;
}

/* public */ void OPT$FindField(MIC$AP name, OPT$Struct typ, OPT$Object* res, uint8_t mark) {
    OPT$Object obj = NULL;
    (*res) = NULL;
    while( ((((typ != NULL) && (typ != OPT$ToBeFixed)) && (typ != OPT$undftyp)) && ((*res) == NULL)) ) {
        obj = (*typ).link;
        while( (obj != NULL) ) {
            if( (strcmp((const char*)name.$, (const char*)(*obj).name.$) < 0) ) { 
                obj = (*obj).left;
            } else if( (strcmp((const char*)name.$, (const char*)(*obj).name.$) > 0) ) { 
                obj = (*obj).right;
            } else { 
                (*obj).flag |= (1u << 1);
                (*res) = obj;
                obj = NULL;
            }
        }
        if( (((((*res) != NULL) && ((*(*res)).mode == 13)) && ((*(*res)).mnolev < 0)) && ((*(*res)).vis == 0)) ) { 
            (*res) = NULL;
        }
        if( ((*res) == NULL) ) { 
            if( (((((*typ).BaseTyp != NULL) && ((*typ).BaseTyp != OPT$ToBeFixed)) && ((*(*(*typ).BaseTyp).strobj).vis == 0)) && mark) ) { 
                OPT$MarkObj((*typ).strobj);
            }
            typ = (*typ).BaseTyp;
        }
    }
    if( ((*res) == NULL) ) { 
        return;
    }
    if( mark ) { 
        (*(*res)).used = 1;
        OPT$MarkObj((*typ).strobj);
        (*typ).pbused = 1;
    }
}

/* public */ void OPT$FindInScope(MIC$AP name, OPT$Object scope, OPT$Object* res) {
    OPT$Object obj = NULL;
    OPT$Object head = NULL;
    uint8_t inRec;
    head = scope;
    inRec = 0;
    while(1) {
        if( (((*head).link != NULL) && ((*(*head).link).mode == 5)) ) { 
            OPT$FindField(name, (*(*head).link).typ, &obj, 1);
            if( ((inRec && (obj != NULL)) && (!(((1 << (*obj).mode) & (0 | 1u << 5 | 1u << 3)) != 0))) ) { 
                OPT$err(200);
            }
            inRec = 1;
            if( ((obj != NULL) || (*(*(*head).link).typ).incomplete) ) { 
                goto __321;
            }
        } else { 
            obj = (*head).right;
            while(1) {
                if( (obj == NULL) ) { 
                    goto __329;
                }
                if( (strcmp((const char*)name.$, (const char*)(*obj).name.$) < 0) ) { 
                    obj = (*obj).left;
                } else if( (strcmp((const char*)name.$, (const char*)(*obj).name.$) > 0) ) { 
                    obj = (*obj).right;
                } else { 
                    if( (((inRec && ((*head).link != NULL)) && ((*(*head).link).mode != 11)) && (!(((1 << (*obj).mode) & (0 | 1u << 5 | 1u << 3)) != 0))) ) { 
                        OPT$err(200);
                    }
                    (*obj).flag |= (1u << 1);
                    goto __329;
                }
            }            __329:

            if( (obj != NULL) ) { 
                goto __321;
            }
        }
        head = (*head).left;
        if( (head == NULL) ) { 
            goto __321;
        }
    }    __321:

    if( ((obj != NULL) && ((*obj).mode < 0)) ) { 
        obj = NULL;
    }
    (*res) = obj;
}

/* public */ void OPT$Find(OPT$Object* res) {
    OPT$FindInScope((MIC$AP){32, OPS$name.$}, OPT$topScope, &(*res));
}

/* public */ void OPT$Insert(MIC$AP name, OPT$Object* obj) {
    OPT$Object ob0 = NULL;
    OPT$Object ob1 = NULL;
    uint8_t left;
    ob0 = OPT$topScope;
    ob1 = (*ob0).right;
    left = 0;
    while(1) {
        if( (ob1 != NULL) ) { 
            if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) < 0) ) { 
                ob0 = ob1;
                ob1 = (*ob0).left;
                left = 1;
            } else if( (strcmp((const char*)name.$, (const char*)(*ob1).name.$) > 0) ) { 
                ob0 = ob1;
                ob1 = (*ob0).right;
                left = 0;
            } else { 
                if( ((*ob1).prio < 126) ) { 
                    OPT$err(1);
                    ob0 = ob1;
                    ob1 = (*ob0).right;
                } else { 
                    goto __355;
                }
            }
        } else { 
            ob1 = OPT$NewObj();
            (*ob1).leaf = 1;
            if( left ) { 
                (*ob0).left = ob1;
            } else { 
                (*ob0).right = ob1;
            }
            (*ob1).left = NULL;
            (*ob1).right = NULL;
            strcpy((char*)(*ob1).name.$, (const char*)name.$);
            (*ob1).mnolev = (*OPT$topScope).mnolev;
            goto __355;
        }
    }    __355:

    (*obj) = ob1;
}

void OPT$CopyOp(OPT$Object* new, OPT$Object* obj) {
    (*(*new)).link = (*(*obj)).link;
    (*(*new)).scope = (*(*obj)).scope;
    (*(*new)).prio = (*(*obj)).prio;
    (*(*new)).code = (*(*obj)).code;
    memcpy((*(*new)).name.$, (*(*obj)).name.$,32 * sizeof(uint8_t));
    (*(*new)).leaf = (*(*obj)).leaf;
    (*(*new)).mode = (*(*obj)).mode;
    (*(*new)).mnolev = (*(*obj)).mnolev;
    (*(*new)).vis = (*(*obj)).vis;
    (*(*new)).typ = (*(*obj)).typ;
    (*(*new)).conval = (*(*obj)).conval;
}

uint8_t OPT$IsExtern(OPT$Object obj) {
    OPT$Object res = NULL;
    if( ((*(*obj).typ).strobj != NULL) ) { 
        OPT$FindInScope((MIC$AP){32, (*(*(*obj).typ).strobj).name.$}, OPT$topScope, &res);
        OPT$FindInScope((MIC$AP){32, (*(*(*obj).typ).strobj).name.$}, OPT$universe, &obj);
    }
    return ((res != NULL) && (res == obj));
}

uint8_t OPT$Contextualize$eqptyp(OPT$Struct t1, OPT$Struct t2) {
    if( (t1 == t2) ) { 
        return 1;
    } else if( (((*t1).comp == 4) && ((*t2).comp == 4)) ) { 
        while( (((*t1).comp == 4) && ((*t2).comp == 4)) ) {
            t1 = (*t1).BaseTyp;
            t2 = (*t2).BaseTyp;
        }
        return (t1 == t2);
    } else { 
        return 0;
    }
}

/* public */ void OPT$Contextualize(OPT$Object* sentinel) {
    OPT$Object new = NULL;
    OPT$Object t1 = NULL;
    OPT$Object t2 = NULL;
    OPT$Object aop = NULL;
    OPT$Object fp = NULL;
    OPT$Object scope = NULL;
    new = OPT$NewObj();
    t1 = (*(*sentinel)).link;
    if( (t1 == NULL) ) { 
        OPT$err(143);
    } else { 
        t2 = (*t1).link;
        if( ((t2 == NULL) && (!OPS$CheckCardinality((MIC$AP){32, (*(*sentinel)).name.$}, 1))) ) { 
            OPT$err(143);
        } else if( (t2 != NULL) ) { 
            if( ((!OPS$CheckCardinality((MIC$AP){32, (*(*sentinel)).name.$}, 2)) || ((*t2).link != NULL)) ) { 
                OPT$err(143);
            } else if( (OPT$IsExtern(t1) && OPT$IsExtern(t2)) ) { 
                OPT$err(146);
            }
        } else if( OPT$IsExtern(t1) ) { 
            OPT$err(146);
        }
    }
    aop = (*(*sentinel)).link2;
    scope = (*(*(*sentinel)).scope).left;
    while( ((scope != NULL) && ((*scope).mnolev >= 0)) ) {
        while( (aop != NULL) ) {
            fp = (*aop).link;
            if( OPT$Contextualize$eqptyp((*t1).typ, (*fp).typ) ) { 
                if( (((t2 != NULL) && ((*fp).link != NULL)) && OPT$Contextualize$eqptyp((*t2).typ, (*(*fp).link).typ)) ) { 
                    OPT$err(139);
                } else if( ((t2 == NULL) && ((*fp).link == NULL)) ) { 
                    OPT$err(139);
                }
            }
            aop = (*aop).left;
        }
        scope = (*scope).left;
        if( (scope != NULL) ) { 
            OPT$FindInScope((MIC$AP){32, (*(*sentinel)).name.$}, scope, &aop);
            if( (aop != NULL) ) { 
                aop = (*aop).link2;
            }
        }
    }
    OPT$CopyOp(&new, &(*sentinel));
    (*new).left = (*(*sentinel)).link2;
    (*(*sentinel)).link2 = new;
    (*(*sentinel)).prio = 127;
    (*sentinel) = new;
}

void OPT$Distance(OPT$Struct typ, OPT$Struct otyp, int8_t* distance) {
    OPT$Struct t = NULL;
    (*distance) = 127;
    if( (((*typ).form == 13) && (((1 << (*otyp).comp) & (0 | 1u << 2 | 1u << 5 | 1u << 3 | 1u << 4)) != 0)) ) { 
        typ = (*typ).BaseTyp;
    }
    if( (typ == otyp) ) { 
        (*distance) = 0;
    } else if( (typ == OPT$sinttyp) ) { 
        if( (otyp == OPT$inttyp) ) { 
            (*distance) = 1;
        } else if( (otyp == OPT$linttyp) ) { 
            (*distance) = 2;
        } else if( (otyp == OPT$realtyp) ) { 
            (*distance) = 3;
        } else if( (otyp == OPT$lrltyp) ) { 
            (*distance) = 4;
        }
    } else if( (typ == OPT$inttyp) ) { 
        if( (otyp == OPT$linttyp) ) { 
            (*distance) = 1;
        } else if( (otyp == OPT$realtyp) ) { 
            (*distance) = 2;
        } else if( (otyp == OPT$lrltyp) ) { 
            (*distance) = 3;
        }
    } else if( (typ == OPT$linttyp) ) { 
        if( (otyp == OPT$realtyp) ) { 
            (*distance) = 1;
        } else if( (otyp == OPT$lrltyp) ) { 
            (*distance) = 2;
        }
    } else if( (typ == OPT$realtyp) ) { 
        if( (otyp == OPT$lrltyp) ) { 
            (*distance) = 1;
        }
    } else if( (((*typ).comp == (*otyp).comp) && ((*typ).comp == 6)) ) { 
        t = typ;
        while( (((t != otyp) && (t != OPT$undftyp)) && (t != NULL)) ) {
            t = (*t).BaseTyp;
        }
        if( (t == otyp) ) { 
            (*distance) = ((*typ).extlev - (*otyp).extlev);
        }
    } else if( ((((*typ).form == 10) && ((*otyp).comp == 5)) && ((*(*otyp).BaseTyp).form == 3)) ) { 
        (*distance) = 1;
    } else if( ((((1 << (*typ).comp) & (0 | 1u << 2 | 1u << 5 | 1u << 3 | 1u << 4)) != 0) && ((*otyp).comp == 5)) ) { 
        while( ((*otyp).comp == 5) ) {
            otyp = (*otyp).BaseTyp;
            typ = (*typ).BaseTyp;
        }
        if( (typ == otyp) ) { 
            (*distance) = 1;
        } else if( (((*typ).form == 13) && ((*otyp).form == 13)) ) { 
            OPT$Distance((*typ).BaseTyp, (*otyp).BaseTyp, &(*distance));
        }
    } else if( (((*typ).form == 13) && ((*otyp).form == 13)) ) { 
        typ = (*typ).BaseTyp;
        otyp = (*otyp).BaseTyp;
        if( (((*typ).comp == 6) && ((*otyp).comp == 6)) ) { 
            t = typ;
            while( (((t != otyp) && (t != NULL)) && (t != OPT$undftyp)) ) {
                t = (*t).BaseTyp;
            }
            if( (t == otyp) ) { 
                (*distance) = ((*typ).extlev - (*otyp).extlev);
            }
        }
    }
}

uint8_t OPT$QualResolve$CheckVarPar(OPT$Node act, OPT$Object form) {
    return ((((*form).mode != 2) || ((*act).class < 7)) || ((*act).class == 13));
}

/* public */ void OPT$QualResolve(OPT$Object* obj, OPT$Node* x, OPT$Node* y, int8_t* distance, uint8_t* wrn) {
    OPT$Object op = NULL;
    OPT$Object yp = NULL;
    int8_t d1;
    int8_t d2;
    op = (*(*obj)).link2;
    (*obj) = NULL;
    (*distance) = 127;
    while( (op != NULL) ) {
        if( OPT$QualResolve$CheckVarPar((*x), (*op).link) ) { 
            OPT$Distance((*(*x)).typ, (*(*op).link).typ, &d1);
            if( (d1 != 127) ) { 
                yp = (*(*op).link).link;
                if( ((*y) != NULL) ) { 
                    if( (yp != NULL) ) { 
                        if( OPT$QualResolve$CheckVarPar((*y), yp) ) { 
                            OPT$Distance((*(*y)).typ, (*yp).typ, &d2);
                            if( (d2 < 127) ) { 
                                d1 = (d1 + d2);
                                if( (d1 < (*distance)) ) { 
                                    (*distance) = d1;
                                    (*obj) = op;
                                    (*wrn) = 0;
                                } else if( (d1 == (*distance)) ) { 
                                    (*wrn) = 1;
                                }
                            }
                        }
                    }
                } else if( (yp == NULL) ) { 
                    if( (d1 < (*distance)) ) { 
                        (*distance) = d1;
                        (*obj) = op;
                        (*wrn) = 0;
                    } else if( (d1 == (*distance)) ) { 
                        (*wrn) = 1;
                    }
                }
            }
        }
        op = (*op).left;
    }
}

/* public */ OPT$Object OPT$Resolve(MIC$AP name, OPT$Node* x, OPT$Node* y) {
    OPT$Object op = NULL;
    OPT$Object res = NULL;
    OPT$Object scope = NULL;
    int8_t i;
    int8_t d;
    int8_t distance;
    uint8_t wrn;
    uint8_t warning;
    res = NULL;
    i = 0;
    distance = 127;
    scope = OPT$topScope;
    wrn = 0;
    warning = 0;
    while( (scope != NULL) ) {
        OPT$FindInScope(name, scope, &op);
        if( ((op != NULL) && ((*op).scope != NULL)) ) { 
            scope = (*(*(*op).scope).left).left;
            OPT$QualResolve(&op, &(*x), &(*y), &d, &wrn);
            if( (d < distance) ) { 
                res = op;
                distance = d;
                warning = wrn;
            } else if( (d == distance) ) { 
                if( (d == 0) ) { 
                    exit(99);
                } else if( (d < 127) ) { 
                    warning = 1;
                }
            }
        } else { 
            scope = NULL;
        }
    }
    i = 1;
    while( (i < OPT$nofmod) ) {
        OPT$FindInScope(name, OPT$modules[i], &op);
        if( (op != NULL) ) { 
            OPT$QualResolve(&op, &(*x), &(*y), &d, &wrn);
            if( (d < distance) ) { 
                res = op;
                distance = d;
                warning = wrn;
            } else if( (d == distance) ) { 
                if( (d == 0) ) { 
                    exit(99);
                } else if( (d < 127) ) { 
                    warning = 1;
                }
            }
        }
        i++;
    }
    if( warning ) { 
        OPT$err((-310));
    }
    return res;
}

/* public */ void OPT$OpenScope(int8_t level, OPT$Object owner) {
    OPT$Object head = NULL;
    head = OPT$NewObj();
    (*head).mode = 12;
    (*head).mnolev = level;
    (*head).link = owner;
    if( (owner != NULL) ) { 
        (*owner).scope = head;
    }
    (*head).left = OPT$topScope;
    (*head).right = NULL;
    (*head).scope = NULL;
    OPT$topScope = head;
}

/* public */ void OPT$CloseScope() {
    if( (OPT$topScope != NULL) ) { 
        OPT$topScope = (*OPT$topScope).left;
    }
}

/* public */ void OPT$Init(MIC$AP name) {
    OPT$topScope = OPT$universe;
    OPT$OpenScope(0, NULL);
    OPT$nofmod = 1;
    OPT$SYSimported = 0;
    OPT$impSelf = 0;
    OPT$sfpresent = 1;
    OPT$newSF = (((1 << 10) & OPM$parserOptions) != 0);
    OPT$extSF = (OPT$newSF || (((1 << 11) & OPM$parserOptions) != 0));
    OPT$modules[0] = OPT$NewMod();
    memcpy((void*)OPT$modules[0], (void*)OPT$topScope, sizeof(OPT$ObjDesc));
    memcpy((*OPT$modules[0]).name.$, name.$,32 * sizeof(uint8_t));
    OPT$topScope = (OPT$Object)OPT$modules[0];
}

void OPT$FPrintName(int32_t* fp, MIC$AP name) {
    int16_t i;
    uint8_t ch;
    i = 0;
    do {
        ch = ((uint8_t*)name.$)[i];
        OPM$FPrint(&(*fp), (int32_t)(uint8_t)(ch));
        i++;
    } while( !(ch == 0) );
}

void OPT$FPrintSign(int32_t* fp, OPT$Struct result, OPT$Object par) {
    OPT$FPrintTyp0(result);
    OPM$FPrint(&(*fp), (*result).fp);
    while( (par != NULL) ) {
        OPM$FPrint(&(*fp), (*par).mode);
        if( ((*par).typ != NULL) ) { 
            OPT$FPrintTyp0((*par).typ);
            OPM$FPrint(&(*fp), (*(*par).typ).fp);
        }
        par = (*par).link;
    }
}

void OPT$FPrintMeth(int32_t* pbfp, int32_t* pvfp, OPT$Object fld) {
    int32_t fp;
    if( (fld != NULL) ) { 
        OPT$FPrintMeth(&(*pbfp), &(*pvfp), (*fld).left);
        if( (((*fld).mode == 13) && ((*fld).vis != 0)) ) { 
            fp = 0;
            OPM$FPrint(&fp, 13);
            OPT$FPrintName(&fp, (MIC$AP){32, (*fld).name.$});
            OPT$FPrintSign(&fp, (*fld).typ, (*fld).link);
            if( (fld == (*(*(*(*fld).link).typ).strobj).link2) ) { 
                OPM$FPrint(&fp, (-1));
            }
            (*fld).fp = fp;
            OPM$FPrint(&fp, OBERON$DIV((*fld).adr, 65536));
            OPM$FPrint(&(*pbfp), fp);
            OPM$FPrint(&(*pvfp), fp);
        }
        OPT$FPrintMeth(&(*pbfp), &(*pvfp), (*fld).right);
    }
}

void OPT$FPrintRecord(OPT$Struct typ) {
    OPT$Object fld = NULL;
    int32_t fp;
    int32_t pbfp;
    int32_t pvfp;
    pvfp = (*typ).fp;
    pbfp = (*typ).fp;
    if( ((*typ).BaseTyp != NULL) ) { 
        OPM$FPrint(&pvfp, (*(*typ).BaseTyp).pvfp);
        OPM$FPrint(&pbfp, (*(*typ).BaseTyp).pbfp);
    }
    if( ((*typ).size < 0) ) { 
        OPT$typSize(typ, 0);
    }
    fld = (*typ).link;
    OPT$FPrintMeth(&pbfp, &pvfp, fld);
    while( ((fld != NULL) && ((*fld).mode == 4)) ) {
        OPT$FPrintTyp((*fld).typ);
        if( ((*fld).vis != 0) ) { 
            fp = 0;
            OPM$FPrint(&fp, (*fld).mode);
            OPT$FPrintName(&fp, (MIC$AP){32, (*fld).name.$});
            OPM$FPrint(&fp, (*fld).vis);
            if( ((*fld).sysflag != 0) ) { 
                OPM$FPrint(&fp, (*fld).sysflag);
            }
            OPM$FPrint(&fp, (*(*fld).typ).fp);
            (*fld).fp = fp;
            OPM$FPrint(&pbfp, (*(*fld).typ).pbfp);
            OPM$FPrint(&pbfp, (*fld).adr);
            OPM$FPrint(&pvfp, (*(*fld).typ).pvfp);
            OPM$FPrint(&pvfp, (*fld).adr);
            OPM$FPrint(&pvfp, fp);
            OPM$FPrint(&pbfp, fp);
            fld = (*fld).link;
        } else { 
            fp = 0;
            if( ((*fld).sysflag != 0) ) { 
                OPM$FPrint(&fp, (*fld).sysflag);
            }
            (*fld).fp = fp;
            OPM$FPrint(&pvfp, (*fld).fp);
            fld = (*fld).link;
        }
    }
    OPM$FPrintSet(&pbfp, ((*(*(*typ).strobj).conval).setval & (0 | 1u << 4 | 1u << 1 | 1u << 5)));
    (*typ).pbfp = pbfp;
    (*typ).pvfp = pvfp;
}

void OPT$FPrintTyp0(OPT$Struct typ) {
    int32_t fp;
    int32_t fp1;
    int32_t fp2;
    int8_t f;
    int8_t c;
    OPT$Struct btyp = NULL;
    if( ((typ != NULL) && ((*typ).fpdone >= 0)) ) { 
        fp = 0;
        f = (*typ).form;
        c = (*typ).comp;
        OPM$FPrint(&fp, f);
        OPM$FPrint(&fp, c);
        fp1 = fp;
        if( ((*typ).sysflag != 0) ) { 
            OPM$FPrint(&fp, (*typ).sysflag);
        }
        if( ((*typ).mno != OPT$modNo) ) { 
            OPT$FPrintName(&fp, (MIC$AP){32, (*OPT$modules[(*typ).mno]).name.$});
            OPT$FPrintName(&fp, (MIC$AP){32, (*(*typ).strobj).name.$});
        }
        fp2 = fp;
        btyp = (*typ).BaseTyp;
        (*typ).fp = fp;
        if( (((c == 6) && (btyp != NULL)) || (f == 13)) ) { 
            OPT$FPrintTyp0(btyp);
            OPM$FPrint(&(*typ).fp, (*btyp).fp);
        } else if( (((1 << c) & (0 | 1u << 2 | 1u << 3 | 1u << 4 | 1u << 5)) != 0) ) { 
            OPT$FPrintTyp0(btyp);
            OPM$FPrint(&(*typ).fp, (*btyp).fp);
            if( (c == 2) ) { 
                OPM$FPrint(&(*typ).fp, (*typ).n);
            }
            (*typ).pbfp = (*typ).fp;
            (*typ).pvfp = (*typ).fp;
        } else if( (f == 14) ) { 
            OPT$FPrintSign(&(*typ).fp, btyp, (*typ).link);
            (*typ).pbfp = (*typ).fp;
            (*typ).pvfp = (*typ).fp;
        } else if( (f == 13) ) { 
            OPM$FPrint(&(*typ).fp, 1);
        }
        if( 0 ) { 
            OPM$LogWLn();
            OPM$LogWStr((MIC$AP){strlen("FPTyp0 - ") + 1,"FPTyp0 - "});
            OPM$LogWHex(fp1);
            OPM$LogWHex(fp2);
            OPM$LogWHex((*typ).fp);
            if( ((*typ).strobj != NULL) ) { 
                OPM$LogWStr((MIC$AP){strlen(" - ") + 1," - "});
                OPM$LogWStr((MIC$AP){32, (*(*typ).strobj).name.$});
            }
        }
    }
}

/* public */ void OPT$FPrintTyp(OPT$Struct typ) {
    if( (((typ != NULL) && ((*typ).fpdone != (OPT$modNo + 1))) && ((*typ).fpdone >= 0)) ) { 
        OPT$FPrintTyp0(typ);
        if( ((*typ).comp != 6) ) { 
            (*typ).fpdone = (OPT$modNo + 1);
        }
        if( ((*typ).BaseTyp != NULL) ) { 
            OPT$FPrintTyp((*typ).BaseTyp);
        }
        if( ((*typ).comp == 6) ) { 
            OPT$FPrintRecord(typ);
        }
        (*typ).fpdone = (OPT$modNo + 1);
        if( 0 ) { 
            OPM$LogWLn();
            OPM$LogWStr((MIC$AP){strlen("FPTyp  - ") + 1,"FPTyp  - "});
            OPM$LogWHex((*typ).fp);
            OPM$LogWHex((*typ).pbfp);
            OPM$LogWHex((*typ).pvfp);
            if( ((*typ).strobj != NULL) ) { 
                OPM$LogWStr((MIC$AP){strlen(" - ") + 1," - "});
                OPM$LogWStr((MIC$AP){32, (*(*typ).strobj).name.$});
            }
        }
    }
}

/* public */ void OPT$FPrintObj(OPT$Object obj) {
    int32_t fp;
    int32_t fp1;
    float rval;
    int16_t f;
    int16_t m;
    uint8_t* ext = NULL;
    OPT$Node n = NULL;
    fp = 0;
    OPM$FPrint(&fp, (*obj).mode);
    OPT$FPrintName(&fp, (MIC$AP){32, (*obj).name.$});
    OPM$FPrint(&fp, (*obj).vis);
    if( 0 ) { 
        fp1 = fp;
    }
    if( ((*obj).mode == 3) ) { 
        f = (*(*obj).typ).form;
        OPM$FPrint(&fp, f);
        OPM$FPrint(&fp, (*(*obj).typ).comp);
        switch( f ) { 
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
            OPM$FPrint(&fp, (*(*obj).conval).intval);
            break;
        case 9:
            OPM$FPrintSet(&fp, (*(*obj).conval).setval);
            break;
        case 7:
            rval = (float)((*(*obj).conval).realval);
            OPM$FPrintReal(&fp, rval);
            break;
        case 8:
            OPM$FPrintLReal(&fp, (*(*obj).conval).realval);
            break;
        case 10:
            OPT$FPrintName(&fp, (MIC$AP){$toda((void**)(*(*obj).conval).ext)->$1,(*(*obj).conval).ext});
            break;
        case 11:
            break;
        }
    } else if( ((*obj).mode == 1) ) { 
        OPT$FPrintTyp((*obj).typ);
        OPM$FPrint(&fp, (*(*obj).typ).fp);
    } else if( ((*obj).mode == 7) ) { 
        OPT$FPrintSign(&fp, (*obj).typ, (*obj).link);
        if( ((*obj).sysflag != 0) ) { 
            OPM$FPrint(&fp, (*obj).sysflag);
        }
    } else if( ((*obj).mode == 9) ) { 
        OPT$FPrintSign(&fp, (*obj).typ, (*obj).link);
        n = (*(*obj).code).left;
        while( (n != NULL) ) {
            ext = (*(*n).conval).ext;
            m = (int32_t)(uint8_t)(ext[0]);
            f = 1;
            OPM$FPrint(&fp, m);
            while( (f <= m) ) {
                OPM$FPrint(&fp, (int32_t)(uint8_t)(ext[f]));
                f++;
            }
            n = (*n).link;
        }
    } else if( ((*obj).mode == 5) ) { 
        OPT$FPrintTyp((*obj).typ);
        OPM$FPrint(&fp, (*(*obj).typ).fp);
    }
    (*obj).fp = fp;
    if( 0 ) { 
        OPM$LogWLn();
        OPM$LogWStr((MIC$AP){strlen("FPObj  - ") + 1,"FPObj  - "});
        OPM$LogWHex(fp1);
        OPM$LogWHex(fp);
        OPM$LogWStr((MIC$AP){strlen(" - ") + 1," - "});
        OPM$LogWStr((MIC$AP){32, (*obj).name.$});
    }
}

void OPT$FPrintErr(OPT$Object obj) {
    int16_t errNo;
    if( OPT$expGlobal ) { 
        if( ((*obj).history == 3) ) { 
            errNo = 450;
        } else if( ((*obj).history == 0) ) { 
            errNo = 451;
        } else if( ((*obj).history == 4) ) { 
            errNo = 452;
        } else { 
            return;
        }
        strcpy((char*)OPM$errName.$, (const char*)(*obj).name.$);
        if( (errNo == 451) ) { 
            if( (!OPT$extSF) ) { 
                OPT$err(errNo);
            }
            OPT$symExtended = 1;
        } else { 
            if( (!OPT$newSF) ) { 
                OPT$err(errNo);
            }
            OPT$symNew = 1;
        }
        if( (errNo == 450) ) { 
            (*obj).vis = 0;
        }
    }
}

OPT$Object OPT$MatchOp(OPT$Object op, OPT$Object list) {
    OPT$FPrintObj(op);
    list = (*list).link2;
    while( ((list != NULL) && ((*list).old == NULL)) ) {
        if( ((*list).fp == 0) ) { 
            OPT$FPrintObj(list);
        }
        if( ((*op).fp == (*list).fp) ) { 
            return list;
        }
        list = (*list).left;
    }
    return NULL;
}

void OPT$InsertImport(OPT$Object obj, OPT$Object root) {
    OPT$Object ob0 = NULL;
    OPT$Object ob1 = NULL;
    uint8_t left;
    ob0 = root;
    ob1 = (*ob0).right;
    left = 0;
    while(1) {
        if( (ob1 != NULL) ) { 
            if( (strcmp((const char*)(*obj).name.$, (const char*)(*ob1).name.$) < 0) ) { 
                ob0 = ob1;
                ob1 = (*ob1).left;
                left = 1;
            } else if( (strcmp((const char*)(*obj).name.$, (const char*)(*ob1).name.$) > 0) ) { 
                ob0 = ob1;
                ob1 = (*ob1).right;
                left = 0;
            } else if( (strcmp((const char*)(*obj).name.$, (const char*)"") == 0) ) { 
                (*obj).scope = NULL;
                return;
            } else { 
                (*obj).old = ob1;
                if( (((*ob1).prio == 127) && ((*root).mnolev != 0)) ) { 
                    (*obj).right = NULL;
                    (*obj).left = (*ob1).link2;
                    (*ob1).link2 = obj;
                    (*obj).mnolev = (*root).mnolev;
                }
                goto __763;
            }
        } else { 
            if( ((*obj).prio == 126) ) { 
                (*obj).left = NULL;
                ob1 = obj;
                obj = OPT$NewObj();
                OPT$CopyOp(&obj, &ob1);
                (*obj).prio = 127;
                (*obj).link2 = ob1;
                (*ob1).old = NULL;
                (*ob1).mnolev = (*root).mnolev;
            }
            if( left ) { 
                (*ob0).left = obj;
            } else { 
                (*ob0).right = obj;
            }
            (*obj).left = NULL;
            (*obj).right = NULL;
            (*obj).old = NULL;
            (*obj).mnolev = (*root).mnolev;
            return;
        }
    }    __763:

}

int8_t OPT$CompOldTyp(OPT$Struct typ, OPT$Struct oldtyp) {
    if( ((((*typ).form == 15) && ((*typ).comp != 6)) || ((*typ).form == 13)) ) { 
        return OPT$CompOldTyp((*typ).BaseTyp, (*oldtyp).BaseTyp);
    } else if( (((*typ).form == 15) && ((*typ).comp == 6)) ) { 
        if( (((*typ).pvfp != (*oldtyp).pvfp) || ((*typ).pbfp != (*oldtyp).pbfp)) ) { 
            return 4;
        } else { 
            return 1;
        }
    } else { 
        return 1;
    }
}

void OPT$CompOldSym(OPT$Object obj) {
    OPT$Object old = NULL;
    while( (obj != NULL) ) {
        old = (*obj).old;
        if( ((old != NULL) && ((*old).prio == 127)) ) { 
            old = OPT$MatchOp(obj, old);
            (*obj).old = old;
        }
        if( (old != NULL) ) { 
            if( ((*obj).prio != 126) ) { 
                OPT$FPrintObj(obj);
                OPT$FPrintObj(old);
            }
            if( ((*obj).fp != (*old).fp) ) { 
                if( (((*obj).vis != (*old).vis) && ((*old).vis == 0)) ) { 
                    (*obj).history = 3;
                    OPT$FPrintErr(obj);
                } else { 
                    (*old).history = 4;
                }
            } else if( (((*obj).mode == 5) || ((((*(*obj).typ).form == 15) && ((*(*obj).typ).comp == 6)) && (strcmp((const char*)(*(*(*obj).typ).strobj).name.$, (const char*)"") == 0))) ) { 
                (*old).history = OPT$CompOldTyp((*obj).typ, (*old).typ);
            } else { 
                (*old).history = 1;
            }
        } else { 
            (*obj).history = 3;
        }
        obj = (*obj).nxtobj;
    }
}

void OPT$ReadString(Files$Rider* R, MIC$AP string) {
    int16_t i;
    uint8_t ch;
    i = 0;
    while(1) {
        Files$Read(&(*R), &ch);
        if( (ch == 0) ) { 
            ((uint8_t*)string.$)[i] = 0;
            return;
        } else if( (ch < 127) ) { 
            ((uint8_t*)string.$)[i] = ch;
            i++;
        } else if( (ch > 127) ) { 
            ((uint8_t*)string.$)[i] = (uint8_t)(((int32_t)(uint8_t)(ch) - 128));
            ((uint8_t*)string.$)[(i + 1)] = 0;
            return;
        } else { 
            goto __825;
        }
    }    __825:

    while(1) {
        Files$Read(&(*R), &ch);
        if( (ch == 0) ) { 
            ((uint8_t*)string.$)[i] = 0;
            return;
        } else { 
            ((uint8_t*)string.$)[i] = ch;
            i++;
        }
    }    __831:

}

void OPT$Imp$GetImports(OPT$Module*M, Files$Rider* R, OPS$Name*modName) {
    // added params: M R modName 
    OPS$Name name;
    OPT$Module TM = NULL;
    OPT$ReadString(&(*R), (MIC$AP){32, name.$});
    while( (strcmp((const char*)name.$, (const char*)"") != 0) ) {
        OPT$Imp((MIC$AP){32, name.$}, (MIC$AP){32, (*modName).$}, &TM);
        (*(*M)).import[(*(*M)).nofimp] = TM;
        (*(*M)).nofimp++;
        if( ((*(*M)).nofimp >= $toda((void**)(*(*M)).import)->$1) ) { 
            OPT$DoubleModArr(&(*(*M)).import);
        }
        (*(*M)).nofreimp = 0;
        OPT$ReadString(&(*R), (MIC$AP){32, name.$});
    }
}

void OPT$Imp$InParList(OPT$Object* first, OPT$Module*M, Files$Rider* R, OPT$Object* last_1, int32_t* tag) {
    // added params: M R last_1 (last) tag 
    OPT$Object last = NULL;
    OPT$Object par = NULL;
    (*first) = NULL;
    last = NULL;
    Files$ReadNum(&(*R), &(*tag));
    while( ((*tag) != 63) ) {
        par = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); par->class$ = &OPT$ObjDesc$class$;
        if( (last == NULL) ) { 
            (*first) = par;
        } else { 
            (*last).link = par;
        }
        last = par;
        if( ((*tag) == 56) ) { 
            (*par).mode = 2;
            Files$ReadNum(&(*R), &(*tag));
        } else { 
            (*par).mode = 1;
        }
        OPT$Imp$InStruct(&(*par).typ, 1, M, R, last_1, tag);
        OPT$ReadString(&(*R), (MIC$AP){32, (*par).name.$});
        Files$ReadNum(&(*R), &(*tag));
    }
}

void OPT$Imp$SetTypFlags(OPT$Struct typ) {
    if( (((*typ).extlev == (-1)) || ((*typ).n < 0)) ) { 
        if( ((*typ).BaseTyp != NULL) ) { 
            OPT$Imp$SetTypFlags((*typ).BaseTyp);
            (*typ).extlev = ((*(*typ).BaseTyp).extlev + 1);
            (*typ).n = (*(*typ).BaseTyp).n;
            (*(*(*typ).strobj).conval).setval = ((*(*(*typ).strobj).conval).setval | ((*(*(*(*typ).BaseTyp).strobj).conval).setval & (0 | 1u << 4)));
        } else { 
            (*typ).extlev = 0;
            (*typ).n = 0;
            (*(*(*typ).strobj).scope).left = OPT$topScope;
        }
    }
}

void OPT$Imp$InRecord(OPT$Struct typ, OPT$Module*M, Files$Rider* R, OPT$Object* last_1, int32_t* tag) {
    // added params: M R last_1 (last) tag 
    OPT$Object scope = NULL;
    OPT$Object last = NULL;
    OPT$Object fld = NULL;
    OPT$Struct btyp = NULL;
    int32_t n;
    int32_t flags;
    OPT$Const conval = NULL;
    scope = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); scope->class$ = &OPT$ObjDesc$class$;
    (*scope).mode = 12;
    (*scope).mnolev = (-(*typ).mno);
    last = NULL;
    btyp = (*typ).BaseTyp;
    conval = OPT$NewConst();
    (*(*typ).strobj).conval = conval;
    Files$ReadNum(&(*R), &flags);
    if( (((1 << 0) & flags) != 0) ) { 
        (*conval).setval |= (1u << 4);
    }
    if( (((1 << 1) & flags) != 0) ) { 
        (*conval).setval |= (1u << 5);
    }
    if( (((1 << 2) & flags) != 0) ) { 
        (*conval).setval |= (1u << 8);
    }
    Files$Read(&(*R), &(*(*typ).strobj).prio);
    Files$ReadNum(&(*R), &(*tag));
    while( ((*tag) < 60) ) {
        fld = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); fld->class$ = &OPT$ObjDesc$class$;
        if( (last != NULL) ) { 
            (*last).link = fld;
        }
        last = fld;
        if( ((*tag) == 55) ) { 
            Files$Read(&(*R), &(*fld).sysflag);
            Files$ReadNum(&(*R), &(*tag));
        }
        if( ((*tag) == 54) ) { 
            Files$ReadNum(&(*R), &(*tag));
            (*fld).vis = 2;
        } else { 
            (*fld).vis = 1;
        }
        (*fld).mode = 4;
        OPT$Imp$InStruct(&(*fld).typ, 0, M, R, last_1, tag);
        OPT$ReadString(&(*R), (MIC$AP){32, (*fld).name.$});
        if( (strcmp((const char*)(*fld).name.$, (const char*)"") == 0) ) { 
            (*fld).vis = 0;
        }
        OPT$InsertImport(fld, scope);
        Files$ReadNum(&(*R), &(*tag));
    }
    if( ((*tag) == 60) ) { 
        Files$ReadNum(&(*R), &(*tag));
        while( ((*tag) != 63) ) {
            fld = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); fld->class$ = &OPT$ObjDesc$class$;
            (*fld).mode = 13;
            (*fld).vis = 1;
            (*fld).conval = OPT$NewConst();
            (*fld).linkadr = (-1);
            (*(*fld).conval).setval = (0 | 1u << 1);
            OPT$Imp$InStruct(&(*fld).typ, 0, M, R, last_1, tag);
            OPT$ReadString(&(*R), (MIC$AP){32, (*fld).name.$});
            if( (strcmp((const char*)(*fld).name.$, (const char*)"") == 0) ) { 
                (*fld).vis = 0;
                OPT$ReadString(&(*R), (MIC$AP){32, (*fld).name.$});
            }
            OPT$Imp$InParList(&(*fld).link, M, R, last_1, tag);
            if( (strcmp((const char*)(*fld).name.$, (const char*)"@Body") == 0) ) { 
                (*(*typ).strobj).link = (*fld).link;
                fld = (*typ).strobj;
                (*conval).setval |= (1u << 1);
            } else { 
                if( (((uint8_t*)(*fld).name.$)[0] == '&') ) { 
                    n = 0;
                    do {
                        ((uint8_t*)(*fld).name.$)[n] = ((uint8_t*)(*fld).name.$)[(n + 1)];
                        n++;
                    } while( !(((uint8_t*)(*fld).name.$)[n] == 0) );
                    (*(*typ).strobj).link2 = fld;
                }
                OPT$InsertImport(fld, scope);
            }
            Files$ReadNum(&(*R), &(*tag));
        }
    }
    if(!((!(((1 << 5) & (*conval).setval) != 0)) || (((1 << 1) & (*conval).setval) != 0))){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
    (*(*typ).strobj).scope = scope;
    (*typ).link = (*scope).right;
}

void OPT$Imp$InStruct(OPT$Struct* typ, uint8_t par, OPT$Module*M, Files$Rider* R, OPT$Object* last, int32_t* tag) {
    // added params: M R last tag 
    int32_t typtag;
    int32_t typadr;
    int8_t vis;
    OPT$Object tobj = NULL;
    OPT$Struct btyp = NULL;
    OPS$Name typname;
    OPT$Module mod = NULL;
    int16_t i;
    if( ((*tag) <= 0) ) { 
        (*tag)--;
        if(!((*tag) > (-$toda((void**)(*(*M)).struct_)->$1))){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
        (*typ) = (*(*M)).struct_[(-(*tag))];
    } else if( ((*tag) <= 14) ) { 
        (*typ) = ((OPT$Struct*)OPT$predefStruct.$)[(*tag)];
    } else if( ((*tag) <= 45) ) { 
        if( ((*tag) == 45) ) { 
            Files$ReadNum(&(*R), &(*tag));
        } else { 
            (*tag) = ((*tag) - 15);
        }
        mod = (*(*M)).import[(*tag)];
        OPT$ReadString(&(*R), (MIC$AP){32, typname.$});
        if( (((uint8_t*)typname.$)[0] != 0) ) { 
            i = 1;
            while( ((i < (*mod).nofstr) && (strcmp((const char*)(*(*(*mod).struct_[i]).strobj).name.$, (const char*)typname.$) != 0)) ) {
                i++;
            }
            if( (i < (*mod).nofstr) ) { 
                (*typ) = (*mod).struct_[i];
            } else { 
                (*typ) = OPT$niltyp;
                if( (!OPT$impSelf) ) { 
                    OPT$err(150);
                }
            }
            (*mod).nofreimp++;
            if( ((*mod).nofreimp >= $toda((void**)(*mod).reimp)->$1) ) { 
                OPT$DoubleStructArr(&(*mod).reimp);
            }
            (*mod).reimp[(*mod).nofreimp] = (*typ);
        } else { 
            Files$ReadNum(&(*R), &typadr);
            typadr++;
            if(!(typadr < $toda((void**)(*mod).reimp)->$1)){fprintf(stderr,"assertion FAILED in %s:%d\n", __FILE__, __LINE__);fflush(stderr);};
            (*typ) = (*mod).reimp[typadr];
        }
    } else { 
        (*typ) = (OPT$StrDesc*)GC_MALLOC(sizeof(OPT$StrDesc)); (*typ)->class$ = &OPT$StrDesc$class$;
        (*(*M)).struct_[(*(*M)).nofstr] = (*typ);
        (*(*typ)).tdadr = (-1);
        (*(*typ)).offset = (-1);
        (*(*typ)).sref = (-(*(*M)).nofstr);
        (*(*M)).nofstr++;
        if( ((*(*M)).nofstr >= $toda((void**)(*(*M)).struct_)->$1) ) { 
            OPT$DoubleStructArr(&(*(*M)).struct_);
        }
        if( ((*tag) == 53) ) { 
            vis = 0;
            Files$ReadNum(&(*R), &(*tag));
        } else { 
            vis = 1;
        }
        if( ((*tag) == 52) ) { 
            Files$ReadNum(&(*R), &(*tag));
            (*(*typ)).sysflag = (uint8_t)((int16_t)((*tag)));
            Files$ReadNum(&(*R), &(*tag));
        }
        (*(*typ)).form = ((int8_t*)OPT$strucForm.$)[(*tag)];
        (*(*typ)).comp = ((int8_t*)OPT$strucComp.$)[(*tag)];
        (*(*typ)).mno = (-(*(*M)).mnolev);
        (*(*typ)).size = (-1);
        typtag = (*tag);
        Files$ReadNum(&(*R), &(*tag));
        (*(*typ)).extlev = (-1);
        OPT$Imp$InStruct(&(*(*typ)).BaseTyp, par, M, R, last, tag);
        btyp = (*(*typ)).BaseTyp;
        if( (((*(*typ)).comp == 6) && ((btyp == OPT$notyp) || (btyp == OPT$niltyp))) ) { 
            (*(*typ)).BaseTyp = NULL;
        } else if( ((((*(*typ)).comp == 6) && (btyp != NULL)) && ((*btyp).form == 13)) ) { 
            (*(*typ)).BaseTyp = (*btyp).BaseTyp;
        } else if( ((((*(*typ)).form == 13) && ((*btyp).comp == 6)) && (strcmp((const char*)(*(*btyp).strobj).name.$, (const char*)"") == 0)) ) { 
            (*btyp).ptr = (*typ);
        }
        tobj = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); tobj->class$ = &OPT$ObjDesc$class$;
        (*tobj).mode = 5;
        (*tobj).nxtobj = (*last);
        (*last) = tobj;
        (*tobj).typ = (*typ);
        OPT$ReadString(&(*R), (MIC$AP){32, (*tobj).name.$});
        (*(*typ)).strobj = tobj;
        if( (strcmp((const char*)(*tobj).name.$, (const char*)"") != 0) ) { 
            (*tobj).vis = vis;
            (*tobj).typ = (*typ);
            OPT$InsertImport(tobj, (*M));
        }
        switch( typtag ) { 
        case 47:
        case 46:
            if( (((1 << (*btyp).comp) & (0 | 1u << 4 | 1u << 5)) != 0) ) { 
                (*(*typ)).n = ((*btyp).n + 1);
            } else { 
                (*(*typ)).n = 0;
            }
            break;
        case 48:
            Files$ReadNum(&(*R), &(*(*typ)).n);
            break;
        case 49:
            break;
        case 50:
            OPT$Imp$InRecord((*typ), M, R, last, tag);
            (*(*typ)).n = (-1);
            break;
        case 51:
            OPT$Imp$InParList(&(*(*typ)).link, M, R, last, tag);
            break;
        }
        if( ((OPT$impSelf && (strcmp((const char*)(*tobj).name.$, (const char*)"") != 0)) && ((*tobj).vis != 0)) ) { 
            (*(*typ)).sref = 0;
        }
    }
}

void OPT$Imp$InObj(OPT$Module*M, Files$Rider* R, OPT$Object* last, int8_t* mode, OPT$Object* obj, uint8_t* operator, int32_t* tag) {
    // added params: M R last mode obj operator tag 
    (*obj) = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); (*obj)->class$ = &OPT$ObjDesc$class$;
    (*(*obj)).mode = (*mode);
    (*(*obj)).nxtobj = (*last);
    (*last) = (*obj);
    if( ((*tag) == 55) ) { 
        Files$Read(&(*R), &(*(*obj)).sysflag);
        Files$ReadNum(&(*R), &(*tag));
    }
    if( ((*tag) == 54) ) { 
        Files$ReadNum(&(*R), &(*tag));
        (*(*obj)).vis = 2;
    } else { 
        (*(*obj)).vis = 1;
    }
    OPT$Imp$InStruct(&(*(*obj)).typ, 0, M, R, last, tag);
    OPT$ReadString(&(*R), (MIC$AP){32, (*(*obj)).name.$});
    if( (*operator) ) { 
        (*(*obj)).prio = 126;
    }
    OPT$InsertImport((*obj), (*M));
}

void OPT$Imp$InCProc(Files$Rider* R, OPT$Object* obj) {
    // added params: R obj 
    OPT$Node n = NULL;
    OPT$Node last = NULL;
    uint8_t* ext = NULL;
    uint8_t ch;
    int32_t i;
    int32_t len;
    (*(*obj)).code = (OPT$NodeDesc*)GC_MALLOC(sizeof(OPT$NodeDesc)); (*(*obj)).code->class$ = &OPT$NodeDesc$class$;
    (*(*(*obj)).code).class = 29;
    (*(*(*obj)).code).conval = OPT$NewConst();
    (*(*(*obj)).code).obj = (*obj);
    Files$Read(&(*R), &ch);
    do {
        n = (OPT$NodeDesc*)GC_MALLOC(sizeof(OPT$NodeDesc)); n->class$ = &OPT$NodeDesc$class$;
        (*n).conval = OPT$NewConst();
        ext = OPT$NewExt();
        (*(*n).conval).ext = ext;
        if( ((*(*(*obj)).code).left == NULL) ) { 
            (*(*(*obj)).code).left = n;
        } else { 
            (*last).link = n;
        }
        last = n;
        len = (int32_t)(uint8_t)(ch);
        ext[0] = ch;
        i = 1;
        while( (i <= len) ) {
            Files$Read(&(*R), &ext[i]);
            i++;
        }
        Files$Read(&(*R), &ch);
    } while( !(ch == 0) );
}

void OPT$Imp$InConst(Files$Rider* R, OPT$Object* obj, int32_t* tag) {
    // added params: R obj tag 
    OPT$Const conval = NULL;
    int16_t s;
    float r;
    conval = (OPT$ConstDesc*)GC_MALLOC(sizeof(OPT$ConstDesc)); conval->class$ = &OPT$ConstDesc$class$;
    (*(*obj)).conval = conval;
    if( ((*tag) == 1) || ((*tag) == 2) || ((*tag) >= 3 && (*tag) <= 5) ) {
        Files$ReadNum(&(*R), &(*conval).intval);
    } else if( ((*tag) == 9) ) {
        Files$ReadNum(&(*R), &(*conval).setval);
    } else if( ((*tag) == 7) ) {
        Files$ReadReal(&(*R), &r);
        (*conval).realval = r;
        (*conval).intval = (-1);
    } else if( ((*tag) == 8) ) {
        Files$ReadLReal(&(*R), &(*conval).realval);
        (*conval).intval = (-1);
    } else if( ((*tag) == 10) ) {
        (*conval).ext = (uint8_t*)$allocda(256, sizeof(uint8_t));
        OPT$ReadString(&(*R), (MIC$AP){$toda((void**)(*conval).ext)->$1,(*conval).ext});
        s = 0;
        while( ((*conval).ext[s] != 0) ) {
            s++;
        }
        (*conval).intval = (-1);
        (*conval).intval2 = (s + 1);
    } else if( ((*tag) == 12) ) {
    }
}

void OPT$Imp(MIC$AP impName, MIC$AP modName, OPT$Module* M) {
    Files$Rider R;
    int16_t i;
    int32_t tag;
    uint8_t done;
    int8_t mode;
    OPT$Object obj = NULL;
    OPT$Object last = NULL;
    OPT$Struct tdum = NULL;
    uint8_t new;
    uint8_t operator;
    i = 0;
    while( ((i < OPT$nofmod) && (strcmp((const char*)impName.$, (const char*)(*OPT$modules[i]).name.$) != 0)) ) {
        i++;
    }
    if( (i < OPT$nofmod) ) { 
        (*M) = OPT$modules[i];
        new = 0;
    } else { 
        (*M) = OPT$NewMod();
        strcpy((char*)(*(*M)).name.$, (const char*)impName.$);
        (*(*M)).mnolev = (-OPT$nofmod);
        OPT$modules[OPT$nofmod] = (*M);
        OPT$nofmod++;
        if( (OPT$nofmod >= $toda((void**)OPT$modules)->$1) ) { 
            OPT$DoubleModArr(&OPT$modules);
        }
        new = 1;
    }
    (*(*M)).nofreimp = 0;
    if( (new || (OPT$impSelf && (i == 0))) ) { 
        (*(*M)).nofimp = 0;
        (*(*M)).struct_[0] = NULL;
        (*(*M)).nofstr = 1;
        operator = 0;
        OPM$OpenSym(&R, impName, OPT$impSelf, &done);
        if( done ) { 
            OPT$Imp$GetImports(M, &R, (uint8_t*)modName.$);
            if( OPM$noerr ) { 
                i = 0;
                while( (i < OPT$nofmod) ) {
                    (*OPT$modules[i]).nofreimp = 0;
                    i++;
                }
                last = NULL;
                Files$ReadNum(&R, &tag);
                if( (tag == 55) ) { 
                    mode = 3;
                    Files$ReadNum(&R, &tag);
                    while( (tag < 56) ) {
                        OPT$Imp$InObj(M, &R, &last, &mode, &obj, &operator, &tag);
                        OPT$Imp$InConst(&R, &obj, &tag);
                        Files$ReadNum(&R, &tag);
                    }
                }
                if( (tag == 56) ) { 
                    mode = 1;
                    Files$ReadNum(&R, &tag);
                    while( (tag < 58) ) {
                        OPT$Imp$InObj(M, &R, &last, &mode, &obj, &operator, &tag);
                        Files$ReadNum(&R, &tag);
                    }
                }
                if( (tag == 58) ) { 
                    mode = 7;
                    Files$ReadNum(&R, &tag);
                    while( (tag < 59) ) {
                        OPT$Imp$InObj(M, &R, &last, &mode, &obj, &operator, &tag);
                        OPT$Imp$InParList(&(*obj).link, M, &R, &last, &tag);
                        Files$ReadNum(&R, &tag);
                        (*obj).conval = OPT$NewConst();
                        (*(*obj).conval).setval = (0);
                    }
                }
                if( (tag == 59) ) { 
                    mode = 7;
                    operator = 1;
                    Files$ReadNum(&R, &tag);
                    while( (tag < 60) ) {
                        OPT$Imp$InObj(M, &R, &last, &mode, &obj, &operator, &tag);
                        OPT$Imp$InParList(&(*obj).link, M, &R, &last, &tag);
                        (*obj).conval = OPT$NewConst();
                        (*(*obj).conval).setval = (0);
                        Files$ReadNum(&R, &tag);
                    }
                    operator = 0;
                }
                if( (tag == 60) ) { 
                    mode = 9;
                    Files$ReadNum(&R, &tag);
                    while( (tag < 61) ) {
                        OPT$Imp$InObj(M, &R, &last, &mode, &obj, &operator, &tag);
                        OPT$Imp$InParList(&(*obj).link, M, &R, &last, &tag);
                        (*obj).conval = OPT$NewConst();
                        (*(*obj).conval).setval = (0 | 1u << 1 | 1u << 7);
                        OPT$Imp$InCProc(&R, &obj);
                        Files$ReadNum(&R, &tag);
                    }
                }
                if( (tag == 61) ) { 
                    Files$ReadNum(&R, &tag);
                    while( (tag < 62) ) {
                        obj = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); obj->class$ = &OPT$ObjDesc$class$;
                        (*obj).vis = 1;
                        (*obj).mode = 5;
                        OPT$Imp$InStruct(&(*obj).typ, 0, M, &R, &last, &tag);
                        OPT$ReadString(&R, (MIC$AP){32, (*obj).name.$});
                        if( ((*(*(*obj).typ).strobj).vis == 0) ) { 
                            (*(*(*obj).typ).strobj).flag |= (1u << 8);
                        }
                        OPT$InsertImport(obj, (*M));
                        OPT$CompOldSym(obj);
                        Files$ReadNum(&R, &tag);
                    }
                }
                if( (tag == 62) ) { 
                    Files$ReadNum(&R, &tag);
                    while( (tag < 63) ) {
                        OPT$Imp$InStruct(&tdum, 0, M, &R, &last, &tag);
                        Files$ReadNum(&R, &tag);
                    }
                }
                (*(*M)).publics = last;
                while( (last != NULL) ) {
                    if( ((((*last).mode == 5) && ((*(*last).typ).form == 15)) && ((*(*last).typ).comp == 6)) ) { 
                        OPT$Imp$SetTypFlags((*last).typ);
                    }
                    last = (*last).nxtobj;
                }
                Files$Close(Files$Base(&R));
            }
        } else { 
            if( OPT$impSelf ) { 
                OPT$newSF = 1;
                OPT$extSF = 1;
                OPT$sfpresent = 0;
            } else { 
                OPT$err(152);
            }
        }
    } else if( ((i == 0) && (!OPT$impSelf)) ) { 
        OPT$err(154);
    }
}

/* public */ void OPT$Import(MIC$AP aliasName, MIC$AP impName, MIC$AP selfName) {
    OPT$Object ali = NULL;
    OPT$Module M = NULL;
    OPT$Insert(aliasName, &ali);
    (*ali).mode = 11;
    (*ali).typ = OPT$notyp;
    if( (strcmp((const char*)impName.$, (const char*)"SYSTEM") == 0) ) { 
        OPT$SYSimported = 1;
        (*ali).mnolev = 0;
        (*ali).scope = OPT$syslink;
        (*ali).adr = 0;
    } else { 
        if( ((strcmp((const char*)impName.$, (const char*)selfName.$) == 0) && (strcmp((const char*)aliasName.$, (const char*)"@self") != 0)) ) { 
            M = OPT$NewMod();
            OPT$err(49);
        }
        OPT$impSelf = (strcmp((const char*)impName.$, (const char*)(*OPT$modules[0]).name.$) == 0);
        OPT$Imp(impName, selfName, &M);
        (*M).directImp = 1;
        (*ali).scope = (*M).right;
        (*ali).mnolev = (*M).mnolev;
    }
}

/* public */ void OPT$OutMod(OPT$Module mod) {
    if( ((*mod).mode == 0) ) { 
        OPM$SymWMod((MIC$AP){32, (*mod).name.$});
        OPT$nofemod++;
        if( (OPT$nofemod >= $toda((void**)OPT$emodules)->$1) ) { 
            OPT$DoubleModArr(&OPT$emodules);
        }
        OPT$emodules[OPT$nofemod] = mod;
        (*mod).mode = OPT$nofemod;
    }
}

void OPT$Enumerate(OPT$Object obj) {
    OPT$Object p = NULL;
    if( (obj != NULL) ) { 
        if( ((*obj).prio == 127) ) { 
            p = (*obj).link2;
            while( (p != NULL) ) {
                (*p).sibling = ((OPT$Object*)OPT$exp.$)[15];
                ((OPT$Object*)OPT$exp.$)[15] = p;
                p = (*p).left;
            }
            OPT$Enumerate((*obj).left);
            OPT$Enumerate((*obj).right);
        } else { 
            OPT$Enumerate((*obj).left);
            if( (((*obj).vis > 0) == OPT$export) ) { 
                if( (OPT$expGlobal && ((*obj).history == 3)) ) { 
                    OPT$FPrintErr(obj);
                    (*obj).mode = 0;
                } else { 
                    if( (((*obj).mode != 5) || ((*(*obj).typ).strobj != obj)) ) { 
                        OPT$FPrintErr(obj);
                    }
                    if( (((*obj).mode == 5) && ((*(*obj).typ).strobj != obj)) ) { 
                        (*obj).sibling = ((OPT$Object*)OPT$exp.$)[14];
                        ((OPT$Object*)OPT$exp.$)[14] = obj;
                    } else if( (((*obj).mode != 1) || (!(*obj).par)) ) { 
                        (*obj).sibling = ((OPT$Object*)OPT$exp.$)[(*obj).mode];
                        ((OPT$Object*)OPT$exp.$)[(*obj).mode] = obj;
                    }
                }
            }
            OPT$Enumerate((*obj).right);
        }
    }
}

void OPT$OutCProc(OPT$Node n) {
    uint8_t* ext = NULL;
    int32_t i;
    int32_t len;
    do {
        ext = (*(*n).conval).ext;
        len = (int32_t)(uint8_t)(ext[0]);
        i = 0;
        while( (i <= len) ) {
            OPM$SymW(ext[i]);
            i++;
        }
        n = (*n).link;
    } while( !(n == NULL) );
    OPM$SymW(0);
}

void OPT$OutParList(OPT$Object par) {
    while( (par != NULL) ) {
        if( ((*par).mode == 2) ) { 
            OPM$SymW((uint8_t)(56));
        }
        OPT$OutStruct((*par).typ);
        OPM$SymWString((MIC$AP){32, (*par).name.$});
        (*par).par = 1;
        (*par).nxtobj = (*par).link;
        par = (*par).link;
    }
    OPM$SymWNum(63);
}

void OPT$OutFld(OPT$Object fld) {
    while( (fld != NULL) ) {
        if( ((*fld).sysflag != 0) ) { 
            OPM$SymW((uint8_t)(55));
            OPM$SymW((uint8_t)((*fld).sysflag));
        }
        if( ((*fld).vis == 2) ) { 
            OPM$SymW((uint8_t)(54));
        }
        OPT$OutStruct((*fld).typ);
        if( ((*fld).vis > 0) ) { 
            OPM$SymWString((MIC$AP){32, (*fld).name.$});
        } else { 
            OPM$SymW(0);
        }
        fld = (*fld).link;
    }
}

void OPT$OutRecord$TraverseBody(OPT$Object fld, int32_t* count) {
    // added params: count 
    OPT$_$15 str;
    if( ((fld != NULL) && (((1 << 1) & (*(*fld).conval).setval) != 0)) ) { 
        OPM$SymW((uint8_t)(60));
        strcpy((char*)str.$, (const char*)"@Body");
        (*count)++;
        OPT$OutStruct(OPT$notyp);
        OPM$SymWString((MIC$AP){32, str.$});
        OPT$OutParList((*fld).link);
    }
}

void OPT$OutRecord$TraverseT(OPT$Object fld, int32_t* count, OPT$Struct* typ) {
    // added params: count typ 
    if( (fld != NULL) ) { 
        OPT$OutRecord$TraverseT((*fld).left, count, typ);
        if( ((*fld).mode == 13) ) { 
            if( ((*count) == 0) ) { 
                OPM$SymW((uint8_t)(60));
            }
            (*count)++;
            OPT$OutStruct((*fld).typ);
            if( ((*fld).vis == 0) ) { 
                OPM$SymW(0);
            }
            if( (fld == (*(*(*typ)).strobj).link2) ) { 
                OPM$SymW('&');
            }
            OPM$SymWString((MIC$AP){32, (*fld).name.$});
            OPT$OutParList((*fld).link);
        }
        OPT$OutRecord$TraverseT((*fld).right, count, typ);
    }
}

void OPT$OutRecord(OPT$Struct typ) {
    OPT$Struct btyp = NULL;
    int32_t count;
    int32_t flag;
    btyp = (*typ).BaseTyp;
    flag = (0);
    if( (((1 << 4) & (*(*(*typ).strobj).conval).setval) != 0) ) { 
        flag |= (1u << 0);
    }
    if( (((1 << 5) & (*(*(*typ).strobj).conval).setval) != 0) ) { 
        flag |= (1u << 1);
    }
    if( (((1 << 8) & (*(*(*typ).strobj).conval).setval) != 0) ) { 
        flag |= (1u << 2);
    }
    OPM$SymWSet(flag);
    OPM$SymWCh((uint8_t)((*(*typ).strobj).prio));
    if( (((*typ).link != NULL) && ((*(*typ).link).mode == 4)) ) { 
        OPT$OutFld((*typ).link);
    }
    count = 0;
    OPT$OutRecord$TraverseBody((*typ).strobj, &count);
    OPT$OutRecord$TraverseT((*typ).link, &count, &typ);
    OPM$SymWNum(63);
}

void OPT$OutStruct(OPT$Struct typ) {
    int8_t tag;
    OPT$Module mod = NULL;
    OPT$Object tobj = NULL;
    if( (typ == NULL) ) { 
        OPM$SymW(0);
    } else if( ((*typ).mno != 0) ) { 
        mod = OPT$modules[(*typ).mno];
        OPT$OutMod(mod);
        if( ((*mod).nofstr > 0) ) { 
            (*mod).nofstr = 0;
        }
        if( ((*mod).mode > 31) ) { 
            OPM$SymW((uint8_t)(45));
            OPM$SymWNum(((*mod).mode - 1));
        } else { 
            OPM$SymW((uint8_t)(((15 - 1) + (*mod).mode)));
        }
        if( ((*typ).sref < 0) ) { 
            (*mod).nofstr--;
            (*typ).sref = (-(*mod).nofstr);
            OPM$SymWString((MIC$AP){32, (*(*typ).strobj).name.$});
        } else { 
            OPM$SymW(0);
            OPM$SymWNum(((*typ).sref - 1));
        }
    } else if( ((*typ).sref > 0) ) { 
        OPM$SymWNum((*typ).sref);
    } else if( ((*typ).sref != 0) ) { 
        OPM$SymWNum(((*typ).sref + 1));
    } else { 
        OPT$nofstruc--;
        (*typ).sref = OPT$nofstruc;
        tag = (((int8_t*)OPT$strucFormSF.$)[(*typ).form] + ((int8_t*)OPT$strucCompSF.$)[(*typ).comp]);
        if( ((OPT$export && ((*typ).strobj != NULL)) && ((*(*typ).strobj).vis == 0)) ) { 
            OPM$SymW((uint8_t)(53));
        }
        if( ((*typ).sysflag != 0) ) { 
            OPM$SymW((uint8_t)(52));
            OPM$SymW((uint8_t)((*typ).sysflag));
        }
        OPM$SymW((uint8_t)(tag));
        if( ((((*typ).comp == 6) && ((*typ).BaseTyp != NULL)) && ((*(*typ).BaseTyp).ptr != NULL)) ) { 
            OPT$OutStruct((*(*typ).BaseTyp).ptr);
        } else if( (((*typ).comp == 6) && ((*typ).BaseTyp == NULL)) ) { 
            OPT$OutStruct(OPT$notyp);
        } else { 
            OPT$OutStruct((*typ).BaseTyp);
        }
        tobj = (OPT$ObjDesc*)GC_MALLOC(sizeof(OPT$ObjDesc)); tobj->class$ = &OPT$ObjDesc$class$;
        (*tobj).mode = 5;
        (*tobj).nxtobj = OPT$objects;
        OPT$objects = tobj;
        (*tobj).typ = typ;
        if( (((*typ).strobj == NULL) || (strcmp((const char*)(*(*typ).strobj).name.$, (const char*)"") == 0)) ) { 
            OPM$SymW(0);
        } else { 
            OPT$FPrintErr((*typ).strobj);
            OPM$SymWString((MIC$AP){32, (*(*typ).strobj).name.$});
            strcpy((char*)(*tobj).name.$, (const char*)(*(*typ).strobj).name.$);
        }
        switch( tag ) { 
        case 47:
        case 46:
            break;
        case 48:
            OPM$SymWNum((*typ).n);
            break;
        case 49:
            break;
        case 50:
            OPT$OutRecord(typ);
            break;
        case 51:
            OPT$OutParList((*typ).link);
            break;
        }
    }
}

void OPT$OutConst(int8_t form, OPT$Const conval) {
    if( (form == 2) || (form == 3) || (form >= 4 && form <= 6) ) {
        OPM$SymWNum((*conval).intval);
    } else if( (form == 9) ) {
        OPM$SymWSet((*conval).setval);
    } else if( (form == 7) ) {
        OPM$SymWReal((float)((*conval).realval));
    } else if( (form == 8) ) {
        OPM$SymWLReal((*conval).realval);
    } else if( (form == 10) ) {
        OPM$SymWString((MIC$AP){$toda((void**)(*conval).ext)->$1,(*conval).ext});
    } else if( (form == 11) ) {
    }
}

void OPT$OutObj(OPT$Object obj) {
    (*obj).nxtobj = OPT$objects;
    OPT$objects = obj;
    OPT$OutStruct((*obj).typ);
    if( (obj == (*(*OPT$topScope).link).link2) ) { 
        OPM$SymW('&');
    }
    OPM$SymWString((MIC$AP){32, (*obj).name.$});
}

/* public */ void OPT$OutScope(OPT$Object scope, uint8_t public) {
    OPT$Object obj = NULL;
    uint8_t first;
    int32_t i;
    OPT$export = public;
    ((OPT$Object*)OPT$exp.$)[3] = NULL;
    ((OPT$Object*)OPT$exp.$)[1] = NULL;
    ((OPT$Object*)OPT$exp.$)[6] = NULL;
    ((OPT$Object*)OPT$exp.$)[7] = NULL;
    ((OPT$Object*)OPT$exp.$)[14] = NULL;
    ((OPT$Object*)OPT$exp.$)[5] = NULL;
    ((OPT$Object*)OPT$exp.$)[15] = NULL;
    OPT$Enumerate(scope);
    i = 1;
    while( ((i < $toda((void**)OPT$modules)->$1) && (OPT$modules[i] != NULL)) ) {
        if( (*OPT$modules[i]).directImp ) { 
            OPT$OutMod(OPT$modules[i]);
        }
        i++;
    }
    if( (((OPT$Object*)OPT$exp.$)[3] != NULL) ) { 
        OPM$SymW((uint8_t)(55));
        obj = ((OPT$Object*)OPT$exp.$)[3];
        while( (obj != NULL) ) {
            OPT$OutObj(obj);
            OPT$OutConst((*(*obj).typ).form, (*obj).conval);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[1] != NULL) ) { 
        OPM$SymW((uint8_t)(56));
        obj = ((OPT$Object*)OPT$exp.$)[1];
        while( (obj != NULL) ) {
            if( ((*obj).vis == 2) ) { 
                OPM$SymW((uint8_t)(54));
            }
            OPT$OutObj(obj);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[6] != NULL) ) { 
        OPM$SymW((uint8_t)(57));
        obj = ((OPT$Object*)OPT$exp.$)[6];
        while( (obj != NULL) ) {
            OPT$OutObj(obj);
            OPT$OutParList((*obj).link);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[7] != NULL) ) { 
        OPM$SymW((uint8_t)(58));
        obj = ((OPT$Object*)OPT$exp.$)[7];
        while( (obj != NULL) ) {
            if( ((*obj).sysflag != 0) ) { 
                OPM$SymW((uint8_t)(55));
                OPM$SymW((uint8_t)((*obj).sysflag));
            }
            OPT$OutObj(obj);
            OPT$OutParList((*obj).link);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[15] != NULL) ) { 
        OPM$SymW((uint8_t)(59));
        obj = ((OPT$Object*)OPT$exp.$)[15];
        while( (obj != NULL) ) {
            OPT$OutObj(obj);
            OPT$OutParList((*obj).link);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[9] != NULL) ) { 
        OPM$SymW((uint8_t)(60));
        obj = ((OPT$Object*)OPT$exp.$)[9];
        while( (obj != NULL) ) {
            OPT$OutObj(obj);
            OPT$OutParList((*obj).link);
            OPT$OutCProc((*(*obj).code).left);
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[14] != NULL) ) { 
        OPM$SymW((uint8_t)(61));
        obj = ((OPT$Object*)OPT$exp.$)[14];
        while( (obj != NULL) ) {
            OPT$OutStruct((*obj).typ);
            OPM$SymWString((MIC$AP){32, (*obj).name.$});
            obj = (*obj).sibling;
        }
    }
    if( (((OPT$Object*)OPT$exp.$)[5] != NULL) ) { 
        obj = ((OPT$Object*)OPT$exp.$)[5];
        first = 1;
        while( (obj != NULL) ) {
            if( ((*(*obj).typ).sref == 0) ) { 
                if( first ) { 
                    OPM$SymW((uint8_t)(62));
                    first = 0;
                }
                if( ((!OPT$export) || (((*(*obj).typ).strobj != NULL) && ((*(*(*obj).typ).strobj).vis != 0))) ) { 
                    OPT$OutStruct((*obj).typ);
                }
            }
            obj = (*obj).sibling;
        }
    }
    OPM$SymWNum(63);
}

/* public */ void OPT$Export(MIC$AP modName, uint8_t* newsf, uint8_t* extsf) {
    int8_t mods;
    OPS$Name aliasName;
    OPT$symExtended = 0;
    OPT$symNew = 0;
    OPT$nofstruc = 0;
    OPT$nofemod = 0;
    OPT$objects = NULL;
    OPT$modNo = 0;
    strcpy((char*)aliasName.$, (const char*)"@self");
    mods = OPT$nofmod;
    OPT$Import((MIC$AP){32, aliasName.$}, modName, modName);
    OPT$nofmod = mods;
    if( OPM$noerr ) { 
        OPT$expGlobal = 1;
        OPT$CompOldSym((*OPT$modules[0]).publics);
        OPT$OutScope((*OPT$topScope).right, 1);
        OPT$expGlobal = 0;
        (*extsf) = (OPT$sfpresent && OPT$symExtended);
        (*newsf) = ((!OPT$sfpresent) || OPT$symNew);
        OPM$EndSym();
        if( (!OPM$noerr) ) { 
            OPT$err(155);
            (*newsf) = 0;
            (*extsf) = 0;
        }
    } else { 
        OPT$newSF = 0;
        OPT$extSF = 0;
    }
}

void OPT$InitStruct(OPT$Struct* typ, int8_t form, int8_t sref) {
    (*typ) = OPT$NewStr(form, 1);
    (*(*typ)).ref = form;
    (*(*typ)).size = 1;
    (*(*typ)).sref = sref;
    ((OPT$Struct*)OPT$predefStruct.$)[sref] = (*typ);
    (*(*typ)).tdadr = 0;
    (*(*typ)).offset = 0;
    (*(*typ)).strobj = OPT$NewObj();
    (*(*typ)).fpdone = (-1);
    (*(*typ)).pvfp = form;
    (*(*typ)).pbfp = form;
    (*(*typ)).fp = form;
}

void OPT$EnterIntConst(MIC$AP name, int32_t value) {
    OPT$Object obj = NULL;
    OPT$Insert(name, &obj);
    (*obj).conval = OPT$NewConst();
    (*obj).mode = 3;
    (*obj).typ = OPT$sinttyp;
    (*(*obj).conval).intval = value;
}

void OPT$EnterTyp(MIC$AP name, int8_t form, int16_t size, OPT$Struct* res, int8_t sref) {
    OPT$Object obj = NULL;
    OPT$Struct typ = NULL;
    OPT$Insert(name, &obj);
    typ = OPT$NewStr(form, 1);
    (*obj).mode = 5;
    (*obj).typ = typ;
    (*obj).vis = 1;
    (*typ).sref = sref;
    ((OPT$Struct*)OPT$predefStruct.$)[sref] = typ;
    (*typ).strobj = obj;
    (*typ).size = size;
    (*typ).tdadr = 0;
    (*typ).offset = 0;
    (*typ).ref = form;
    (*res) = typ;
    (*typ).fpdone = (-1);
    (*typ).pvfp = size;
    (*typ).pbfp = form;
    (*typ).fp = form;
}

void OPT$EnterTypAlias(MIC$AP name, OPT$Struct typ) {
    OPT$Object obj = NULL;
    OPT$Insert(name, &obj);
    (*obj).mode = 5;
    (*obj).typ = typ;
    (*obj).vis = 1;
}

void OPT$EnterProc(MIC$AP name, int16_t num) {
    OPT$Object obj = NULL;
    OPT$Insert(name, &obj);
    (*obj).mode = 8;
    (*obj).typ = OPT$notyp;
    (*obj).adr = num;
}

void OPT$EnterPtr(MIC$AP name, int32_t num) {
    OPT$Object obj = NULL;
    OPT$Insert(name, &obj);
    (*obj).mode = 1;
    (*obj).typ = OPT$ptrtyp;
    (*obj).adr = num;
    (*obj).linkadr = num;
    (*obj).mnolev = 0;
}

void OPT$BEGIN$() {
    OPT$topScope = NULL;
    OPT$modules = (OPT$Module*)$allocda(64, sizeof(OPT$Module));
    OPT$emodules = (OPT$Module*)$allocda(64, sizeof(OPT$Module));
    OPT$OpenScope(0, NULL);
    OPM$errpos = 0;
    OPT$InitStruct(&OPT$undftyp, 0, 0);
    OPT$InitStruct(&OPT$notyp, 12, 11);
    OPT$InitStruct(&OPT$stringtyp, 10, 10);
    OPT$InitStruct(&OPT$niltyp, 11, 12);
    (*OPT$undftyp).BaseTyp = OPT$undftyp;
    OPT$EnterTyp((MIC$AP){strlen("BYTE") + 1,"BYTE"}, 1, 1, &OPT$bytetyp, 13);
    OPT$EnterTyp((MIC$AP){strlen("PTR") + 1,"PTR"}, 13, 4, &OPT$ptrtyp, 14);
    OPT$EnterProc((MIC$AP){strlen("ADR") + 1,"ADR"}, 20);
    OPT$EnterProc((MIC$AP){strlen("CC") + 1,"CC"}, 21);
    OPT$EnterProc((MIC$AP){strlen("LSH") + 1,"LSH"}, 22);
    OPT$EnterProc((MIC$AP){strlen("ROT") + 1,"ROT"}, 23);
    OPT$EnterProc((MIC$AP){strlen("GET") + 1,"GET"}, 24);
    OPT$EnterProc((MIC$AP){strlen("PUT") + 1,"PUT"}, 25);
    OPT$EnterProc((MIC$AP){strlen("GETREG") + 1,"GETREG"}, 26);
    OPT$EnterProc((MIC$AP){strlen("PUTREG") + 1,"PUTREG"}, 27);
    OPT$EnterProc((MIC$AP){strlen("BIT") + 1,"BIT"}, 28);
    OPT$EnterProc((MIC$AP){strlen("VAL") + 1,"VAL"}, 29);
    OPT$EnterProc((MIC$AP){strlen("NEW") + 1,"NEW"}, 30);
    OPT$EnterProc((MIC$AP){strlen("MOVE") + 1,"MOVE"}, 31);
    OPT$EnterProc((MIC$AP){strlen("PORTOUT") + 1,"PORTOUT"}, 35);
    OPT$EnterProc((MIC$AP){strlen("PORTIN") + 1,"PORTIN"}, 36);
    OPT$EnterProc((MIC$AP){strlen("STI") + 1,"STI"}, 33);
    OPT$EnterProc((MIC$AP){strlen("CLI") + 1,"CLI"}, 34);
    OPT$EnterProc((MIC$AP){strlen("HALT") + 1,"HALT"}, 37);
    OPT$EnterProc((MIC$AP){strlen("GET8") + 1,"GET8"}, 38);
    OPT$EnterProc((MIC$AP){strlen("GET16") + 1,"GET16"}, 39);
    OPT$EnterProc((MIC$AP){strlen("GET32") + 1,"GET32"}, 40);
    OPT$EnterProc((MIC$AP){strlen("PUT8") + 1,"PUT8"}, 41);
    OPT$EnterProc((MIC$AP){strlen("PUT16") + 1,"PUT16"}, 42);
    OPT$EnterProc((MIC$AP){strlen("PUT32") + 1,"PUT32"}, 43);
    OPT$EnterProc((MIC$AP){strlen("TYPECODE") + 1,"TYPECODE"}, 44);
    OPT$syslink = (*OPT$topScope).right;
    OPT$universe = OPT$topScope;
    (*OPT$topScope).right = NULL;
    OPT$EnterTyp((MIC$AP){strlen("CHAR") + 1,"CHAR"}, 3, 1, &OPT$chartyp, 2);
    OPT$EnterTyp((MIC$AP){strlen("SET") + 1,"SET"}, 9, 4, &OPT$settyp, 9);
    OPT$EnterTyp((MIC$AP){strlen("REAL") + 1,"REAL"}, 7, 4, &OPT$realtyp, 7);
    OPT$EnterTyp((MIC$AP){strlen("INTEGER") + 1,"INTEGER"}, 5, 2, &OPT$inttyp, 4);
    OPT$EnterTyp((MIC$AP){strlen("LONGINT") + 1,"LONGINT"}, 6, 4, &OPT$linttyp, 5);
    OPT$EnterTyp((MIC$AP){strlen("HUGEINT") + 1,"HUGEINT"}, 16, 8, &OPT$hinttyp, 6);
    OPT$EnterTyp((MIC$AP){strlen("LONGREAL") + 1,"LONGREAL"}, 8, 8, &OPT$lrltyp, 8);
    OPT$EnterTyp((MIC$AP){strlen("SHORTINT") + 1,"SHORTINT"}, 4, 1, &OPT$sinttyp, 3);
    OPT$EnterTyp((MIC$AP){strlen("BOOLEAN") + 1,"BOOLEAN"}, 2, 1, &OPT$booltyp, 1);
    OPT$EnterTypAlias((MIC$AP){strlen("PTR") + 1,"PTR"}, OPT$ptrtyp);
    OPT$universe = (*OPT$topScope).right;
    (*OPT$topScope).right = OPT$syslink;
    OPT$EnterIntConst((MIC$AP){strlen("EAX") + 1,"EAX"}, 8);
    OPT$EnterIntConst((MIC$AP){strlen("ECX") + 1,"ECX"}, 9);
    OPT$EnterIntConst((MIC$AP){strlen("EDX") + 1,"EDX"}, 10);
    OPT$EnterIntConst((MIC$AP){strlen("EBX") + 1,"EBX"}, 11);
    OPT$EnterIntConst((MIC$AP){strlen("ESP") + 1,"ESP"}, 12);
    OPT$EnterIntConst((MIC$AP){strlen("EBP") + 1,"EBP"}, 13);
    OPT$EnterIntConst((MIC$AP){strlen("ESI") + 1,"ESI"}, 14);
    OPT$EnterIntConst((MIC$AP){strlen("EDI") + 1,"EDI"}, 15);
    OPT$EnterIntConst((MIC$AP){strlen("AX") + 1,"AX"}, 16);
    OPT$EnterIntConst((MIC$AP){strlen("CX") + 1,"CX"}, 17);
    OPT$EnterIntConst((MIC$AP){strlen("DX") + 1,"DX"}, 18);
    OPT$EnterIntConst((MIC$AP){strlen("BX") + 1,"BX"}, 19);
    OPT$EnterIntConst((MIC$AP){strlen("SP") + 1,"SP"}, 20);
    OPT$EnterIntConst((MIC$AP){strlen("BP") + 1,"BP"}, 21);
    OPT$EnterIntConst((MIC$AP){strlen("SI") + 1,"SI"}, 22);
    OPT$EnterIntConst((MIC$AP){strlen("DI") + 1,"DI"}, 23);
    OPT$EnterIntConst((MIC$AP){strlen("AL") + 1,"AL"}, 24);
    OPT$EnterIntConst((MIC$AP){strlen("CL") + 1,"CL"}, 25);
    OPT$EnterIntConst((MIC$AP){strlen("DL") + 1,"DL"}, 26);
    OPT$EnterIntConst((MIC$AP){strlen("BL") + 1,"BL"}, 27);
    OPT$EnterIntConst((MIC$AP){strlen("AH") + 1,"AH"}, 28);
    OPT$EnterIntConst((MIC$AP){strlen("CH") + 1,"CH"}, 29);
    OPT$EnterIntConst((MIC$AP){strlen("DH") + 1,"DH"}, 30);
    OPT$EnterIntConst((MIC$AP){strlen("BH") + 1,"BH"}, 31);
    (*OPT$topScope).right = OPT$universe;
    OPT$universe = OPT$topScope;
    OPT$EnterProc((MIC$AP){strlen("HALT") + 1,"HALT"}, 0);
    OPT$EnterProc((MIC$AP){strlen("NEW") + 1,"NEW"}, 1);
    OPT$EnterProc((MIC$AP){strlen("ABS") + 1,"ABS"}, 2);
    OPT$EnterProc((MIC$AP){strlen("CAP") + 1,"CAP"}, 3);
    OPT$EnterProc((MIC$AP){strlen("ORD") + 1,"ORD"}, 4);
    OPT$EnterProc((MIC$AP){strlen("ENTIER") + 1,"ENTIER"}, 5);
    OPT$EnterProc((MIC$AP){strlen("ODD") + 1,"ODD"}, 6);
    OPT$EnterProc((MIC$AP){strlen("MIN") + 1,"MIN"}, 7);
    OPT$EnterProc((MIC$AP){strlen("MAX") + 1,"MAX"}, 8);
    OPT$EnterProc((MIC$AP){strlen("CHR") + 1,"CHR"}, 9);
    OPT$EnterProc((MIC$AP){strlen("SHORT") + 1,"SHORT"}, 10);
    OPT$EnterProc((MIC$AP){strlen("LONG") + 1,"LONG"}, 11);
    OPT$EnterProc((MIC$AP){strlen("SIZE") + 1,"SIZE"}, 12);
    OPT$EnterProc((MIC$AP){strlen("INC") + 1,"INC"}, 13);
    OPT$EnterProc((MIC$AP){strlen("DEC") + 1,"DEC"}, 14);
    OPT$EnterProc((MIC$AP){strlen("INCL") + 1,"INCL"}, 15);
    OPT$EnterProc((MIC$AP){strlen("EXCL") + 1,"EXCL"}, 16);
    OPT$EnterProc((MIC$AP){strlen("LEN") + 1,"LEN"}, 17);
    OPT$EnterProc((MIC$AP){strlen("COPY") + 1,"COPY"}, 18);
    OPT$EnterProc((MIC$AP){strlen("ASH") + 1,"ASH"}, 19);
    OPT$EnterProc((MIC$AP){strlen("ASSERT") + 1,"ASSERT"}, 32);
    OPT$EnterProc((MIC$AP){strlen("AWAIT") + 1,"AWAIT"}, 64);
    OPT$EnterPtr((MIC$AP){strlen("@SELF") + 1,"@SELF"}, 0);
    OPT$EnterPtr((MIC$AP){strlen("SELF") + 1,"SELF"}, 0);
    ((int8_t*)OPT$strucForm.$)[49] = 13;
    ((int8_t*)OPT$strucForm.$)[50] = 15;
    ((int8_t*)OPT$strucForm.$)[51] = 14;
    ((int8_t*)OPT$strucForm.$)[47] = 15;
    ((int8_t*)OPT$strucForm.$)[48] = 15;
    ((int8_t*)OPT$strucForm.$)[46] = 15;
    ((int8_t*)OPT$strucComp.$)[49] = 1;
    ((int8_t*)OPT$strucComp.$)[50] = 6;
    ((int8_t*)OPT$strucComp.$)[51] = 1;
    ((int8_t*)OPT$strucComp.$)[47] = 4;
    ((int8_t*)OPT$strucComp.$)[48] = 2;
    ((int8_t*)OPT$strucComp.$)[46] = 5;
    ((int8_t*)OPT$strucFormSF.$)[13] = 49;
    ((int8_t*)OPT$strucFormSF.$)[14] = 51;
    ((int8_t*)OPT$strucCompSF.$)[2] = 48;
    ((int8_t*)OPT$strucCompSF.$)[4] = 47;
    ((int8_t*)OPT$strucCompSF.$)[6] = 50;
    ((int8_t*)OPT$strucCompSF.$)[5] = 46;
    OPT$ToBeFixed = (OPT$StrDesc*)GC_MALLOC(sizeof(OPT$StrDesc)); OPT$ToBeFixed->class$ = &OPT$StrDesc$class$;
    (*OPT$ToBeFixed).incomplete = 1;
}

static int OPT$initialized = 0;
void OPT$init$(void) {
    if( OPT$initialized ) return;
    OPT$initialized = 1;
    OPS$init$();
    OPM$init$();
    Files$init$();
    OPT$BEGIN$();
}

