#ifndef __OPTR_INCLUDED__
#define __OPTR_INCLUDED__

// OPTR.h
// this file was generated by AoCodeNavigator 0.6.10 on Do. Feb. 26 22:14:37 2026

#include <stdint.h>

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
#define OPTR$Undef 0
#define OPTR$Byte 1
#define OPTR$Bool 2
#define OPTR$Char 3
#define OPTR$SInt 4
#define OPTR$Int 5
#define OPTR$LInt 6
#define OPTR$Real 7
#define OPTR$Set 9
#define OPTR$NilTyp 11
#define OPTR$Pointer 13
#define OPTR$ProcTyp 14
/* public */ typedef void (*OPTR$EnterConstProc)(MIC$AP name, int32_t value); 
/* public */ extern int32_t OPTR$MinRegNr;
/* public */ extern int32_t OPTR$MaxRegNr;
/* public */ extern uint8_t OPTR$ValidRegType(int32_t regNr, int8_t typeForm);
/* public */ extern int32_t OPTR$RegIndex(int32_t regNr);
/* public */ extern uint8_t OPTR$IsLegacyReg(int32_t regNr);
/* public */ extern void OPTR$EnterRegisters(OPTR$EnterConstProc enter);
extern void OPTR$BEGIN$();
extern void OPTR$init$(void);

#endif // __OPTR_INCLUDED__