// OPTR.c
// this file was generated by AoCodeNavigator 0.6.10 on Mo. Feb. 23 23:59:33 2026

#include "OPTR.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

/* public */ int32_t OPTR$MinRegNr;

/* public */ int32_t OPTR$MaxRegNr;

/* public */ uint8_t OPTR$ValidRegType(int32_t regNr, int8_t typeForm) {
    if( ((0 <= regNr) && (regNr < 8)) ) { 
        return (((1 << typeForm) & (0 | (uint32_t)((((uint64_t)1 << (7 - 0 + 1)) - 1) << 0) | 1u << 9 | 1u << 11 | 1u << 13 | 1u << 14)) != 0);
    } else if( ((8 <= regNr) && (regNr < 16)) ) { 
        return (((1 << typeForm) & (0 | 1u << 6 | 1u << 7 | 1u << 9 | 1u << 13 | 1u << 14)) != 0);
    } else if( ((16 <= regNr) && (regNr < 24)) ) { 
        return (((1 << typeForm) & (0 | 1u << 5)) != 0);
    } else if( ((24 <= regNr) && (regNr < 32)) ) { 
        return (((1 << typeForm) & (0 | 1u << 1 | 1u << 2 | 1u << 3 | 1u << 4)) != 0);
    } else { 
        return 0;
    }
}

/* public */ int32_t OPTR$RegIndex(int32_t regNr) {
    return OBERON$MOD(regNr, 8);
}

/* public */ uint8_t OPTR$IsLegacyReg(int32_t regNr) {
    return ((0 <= regNr) && (regNr < 8));
}

/* public */ void OPTR$EnterRegisters(OPTR$EnterConstProc enter) {
    enter((MIC$AP){strlen("EAX") + 1,"EAX"}, 8);
    enter((MIC$AP){strlen("ECX") + 1,"ECX"}, 9);
    enter((MIC$AP){strlen("EDX") + 1,"EDX"}, 10);
    enter((MIC$AP){strlen("EBX") + 1,"EBX"}, 11);
    enter((MIC$AP){strlen("ESP") + 1,"ESP"}, 12);
    enter((MIC$AP){strlen("EBP") + 1,"EBP"}, 13);
    enter((MIC$AP){strlen("ESI") + 1,"ESI"}, 14);
    enter((MIC$AP){strlen("EDI") + 1,"EDI"}, 15);
    enter((MIC$AP){strlen("AX") + 1,"AX"}, 16);
    enter((MIC$AP){strlen("CX") + 1,"CX"}, 17);
    enter((MIC$AP){strlen("DX") + 1,"DX"}, 18);
    enter((MIC$AP){strlen("BX") + 1,"BX"}, 19);
    enter((MIC$AP){strlen("SP") + 1,"SP"}, 20);
    enter((MIC$AP){strlen("BP") + 1,"BP"}, 21);
    enter((MIC$AP){strlen("SI") + 1,"SI"}, 22);
    enter((MIC$AP){strlen("DI") + 1,"DI"}, 23);
    enter((MIC$AP){strlen("AL") + 1,"AL"}, 24);
    enter((MIC$AP){strlen("CL") + 1,"CL"}, 25);
    enter((MIC$AP){strlen("DL") + 1,"DL"}, 26);
    enter((MIC$AP){strlen("BL") + 1,"BL"}, 27);
    enter((MIC$AP){strlen("AH") + 1,"AH"}, 28);
    enter((MIC$AP){strlen("CH") + 1,"CH"}, 29);
    enter((MIC$AP){strlen("DH") + 1,"DH"}, 30);
    enter((MIC$AP){strlen("BH") + 1,"BH"}, 31);
}

void OPTR$BEGIN$() {
    OPTR$MinRegNr = 0;
    OPTR$MaxRegNr = 31;
}

static int OPTR$initialized = 0;
void OPTR$init$(void) {
    if( OPTR$initialized ) return;
    OPTR$initialized = 1;
    OPTR$BEGIN$();
}

