#ifndef __OUT_INCLUDED__
#define __OUT_INCLUDED__

// Out.h
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:11:23 2026

#include <stdint.h>

#define ASH$(x, n) (((n) >= 0) ? ((x) << ((n) >= 0 ? (n) : 0)) : ((x) >> ((n) < 0  ? -(n) : 0)))
#define MOD$(x, y) (((x) % (y) < 0) ? ((x) % (y) + (y)) : ((x) % (y)))
#define DIV$(x, y) ((((x) % (y) != 0) && (((x) < 0) != ((y) < 0))) ? ((x) / (y) - 1) : ((x) / (y)))
#ifndef __MIC_DEFINE__
#define __MIC_DEFINE__
static inline int64_t OBERON$MOD(int64_t x, int64_t y) { int64_t r = x % y; return r < 0 ? r + y : r; }
static inline int64_t OBERON$DIV(int64_t x, int64_t y) { int64_t q = x / y; int64_t r = x % y; return (r != 0 && ((x < 0) != (y < 0))) ? q - 1 : q; }
typedef struct MIC$AP { uint32_t $1; void* $; } MIC$AP;
typedef struct MIC$DA { uint32_t $1; void* $[]; } MIC$DA;
#endif
/* public */ extern void Out$Open();
/* public */ extern void Out$Char(uint8_t ch);
// no typedef for open array Out$_$0 (uint8_t*)
/* public */ extern void Out$String(MIC$AP str);
/* public */ extern void Out$Int(int32_t i, int16_t n);
/* public */ extern void Out$Real(float x, int16_t n);
/* public */ extern void Out$LongReal(double x, int16_t n);
/* public */ extern void Out$Ln();

#endif // __OUT_INCLUDED__