// Texts.c
// this file was generated by ActiveOberon IDE 0.1.6 on Mo. März 9 20:11:23 2026

#include "Texts.h"
#include <gc.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <ctype.h>
#include <stddef.h>

typedef struct $Class { struct $Class* super; } $Class;
static int $isinst(void* super, void* sub) {
    $Class* cls = ($Class*)sub;
    while(cls) {
        if( cls == super ) return 1;
        cls = cls->super;
    }
    return 0;
}
static MIC$DA* $toda(void** ptr) {
    return (MIC$DA*)((char*)ptr - offsetof(MIC$DA, $));
}
static void** $allocda(uint32_t count, int elemSize) {
    MIC$DA* ptr = (MIC$DA*)GC_MALLOC(sizeof(MIC$DA) + count * elemSize);
    if( ptr == 0 ) return 0;
    ptr->$1 = count;
    return ptr->$;
}

void Texts$_$0$init$(Texts$_$0* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Texts$_$0$class$;
    }
}

struct Texts$_$0$Class$ Texts$_$0$class$ = { 
    0,
};

void Texts$BufDesc$init$(Texts$BufDesc* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Texts$BufDesc$class$;
    }
}

struct Texts$BufDesc$Class$ Texts$BufDesc$class$ = { 
    0,
};

void Texts$Writer$init$(Texts$Writer* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Texts$Writer$class$;
    }
}

struct Texts$Writer$Class$ Texts$Writer$class$ = { 
    0,
};

void Texts$Reader$init$(Texts$Reader* obj, unsigned int n) {
    int i;
    for( i = 0; i < n; i++ ) {
        obj[i].class$ = &Texts$Reader$class$;
    }
}

struct Texts$Reader$Class$ Texts$Reader$class$ = { 
    0,
};

/* public */ void Texts$WriteString(Texts$Writer* W, MIC$AP s) {
    int16_t i = 0;
    i = 0;
    while( (((uint8_t*)s.$)[i] != 0) ) {
        Texts$Write(&(*W), ((uint8_t*)s.$)[i]);
        i++;
    }
}

/* public */ void Texts$WriteLn(Texts$Writer* W) {
    Texts$Write(&(*W), 13);
}

static int Texts$initialized = 0;
void Texts$init$(void) {
    if( Texts$initialized ) return;
    Texts$initialized = 1;
    Fonts$init$();
}

